### PR TITLE
Update Samsung Internet Data

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
Sorry for the huge PR

This updates several versions of data for Samsung Internet.

The majority of the data is inferred from Chrome for Android. 

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by Elchi3** [comment]
Thank you @AdaRoseCannon! :smile: 

We usually split up at least by folder to avoid gigantic PRs but I will give this a try :relaxed:

**Comment by vinyldarkscratch** [comment]
Dang, that's a lot of files that have been changed!  ~~My browser's actually lagging a little, haha~~

I noticed some of the tags that the compat data helper applied, and I'm thinking that we should at least cherry-pick the addition of Samsung Internet 10.0 / 10.2 into its own PR, since that can be confirmed and merged much quicker.  I also noticed there was an update to `package-lock.json`, which I believe we should omit from this, focusing it as much on the Samsung Internet data as possible.  (It would definitely help to separate this by folder!)  Does that sound reasonable?

**Comment by AdaRoseCannon** [comment]
No problem :)

I'll make some more PRs tomorrow cherrypicking individual folders.

Ada

**Comment by vinyldarkscratch** [comment]
Thank you very much, it’s a big help!  😄

- Vinyl Darkscratch-Kazotetsu, Founder of Gooborg Studios
(Sent from my Nightinfection, my iPhone)

--
If you believe you have received this email in error, please contact me at vinyldarkscratch@gmail.com, Twitter @vdscratchy, or Telegram @vinyldarkscratch

**Comment by vinyldarkscratch** [comment]
Oh and it looks like Travis actually **did** successfully complete a build for this, apparently they forgot to tell GitHub.  So, other than potential inconsistency issues lurking around, this data should be good!

**Comment by AdaRoseCannon** [comment]
I'll leave this PR up but it should hopefully disappear on it's own.

**Comment by vinyldarkscratch** [comment]
Thanks for the cherry-picked PRs!  I'd say that we can safely close this now and focus on the smaller ones.

**Pull request closed without merging**
