### PR TITLE
Add Philip Jägenstedt as a BCD Peer

### PR DESCRIPTION
**Pull request by ddbeck**
I'm pleased to invite @foolip to join [the list of Peers](https://github.com/mdn/browser-compat-data/blob/master/GOVERNANCE.md#list-of-current-peers). I've reached out to the active Owners, who have approved this nomination.

@foolip has already accepted the Mozilla Commit Access Requirements (see https://github.com/mdn/mdn/issues/101).

Please join me in welcoming Philip to the team. 🎉

### CODE REVIEW

**Comment by foolip** [comment]
Oh wow, such a kind welcome! Thank you @ddbeck!

I'm looking forward to contributing both in a personal capacity but also advocating for more projects of the sort that @vinyldarkscratch and I are now working on. With the right funding/staffing, I believe BCD can provide even more value to web developers than it already is :)

**Review by Elchi3 — APPROVED** [review]
Thanks for all your investment, @foolip :heart:

**Comment by jpmedley** [comment]
Welcome, Philip.

**Comment by foolip** [comment]
I have accepted the invite and have write access now. Thank you, everyone!

**Pull request merged**
