### PR TITLE
Note Firefox 63 support for report-sample [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by a2sheppy**
Previously, Firefox always included this info. Now the
expression is required.

### CODE REVIEW

**Comment by Elchi3** [comment]
Thanks for your PR, I need a bug to review this change.

**Comment by a2sheppy** [comment]
Please hold off on reviewing this. I need to update this PR once I sort out how to handle some corrections properly.

**Comment by a2sheppy** [comment]
This is holding for PR #1799 to land, so we can use feature imports to repeat the report-sample feature across the various directives.

**Comment by Elchi3** [comment]
Bulk data updates through external sources and scripts are our preferred approach to better compat data right now and we're not currently considering de-duplicating version data. Therefore I have closed PRs and issues related to https://github.com/mdn/browser-compat-data/pull/1799.

Please open a new PR that doesn't depend on ideas or features not yet implemented in BCD.

**Pull request closed without merging**
