### PR TITLE
Add release information for Chrome 74 (now stable)

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by Elchi3** [comment]
Looks good to me. Want to update webview_android as well?

**Comment by jpmedley** [comment]
LGTM. Please sit on this until May 2, when we actually ship beta.

**Comment by foolip** [comment]
> Want to update webview_android as well?

@Elchi3 done

> Please sit on this until May 2, when we actually ship beta

Is there an alternative way to edit that would allow PRs like this to be released on the same day as the stable promotion? I'd like to start using these release dates as the source of truth for Confluence, but sometimes have a week's required delay would mean I have to add a mechanism for patching the data.

**Comment by Elchi3** [comment]
I'm sure I understand why we would need to sit on this for one week. To whom would it matter to not already have beta in there?

There is also https://github.com/mdn/browser-compat-data/issues/1664 which proposes to add automation for this. With something like that in place, you could probably have exact time-based updates to these files when stable, beta or any products ship. I'm just not aware of anyone who would need that, so the issue wasn't prioritized so far.

**Comment by foolip** [comment]
Could we resolve this by just not having future releases? What do people use them for?

**Comment by vinyldarkscratch** [comment]
Not really sure why we'd have to await May 2nd either, especially since Chrome 74 is already released.  Personally, I think we should go ahead and merge this, worry about anything like the beta and nightly later on.

**Comment by Elchi3** [comment]
>  Could we resolve this by just not having future releases? What do people use them for?

I don't think removing future releases is useful as documentation is almost always (and ideally) written prior to a release. That's at least how we do this for Firefox.

Our linter uses the files in `browsers/` to the validate the versions, so without future releases there, you can't submit compat data containing such a version.

In the `browsers/` files, you also have the `status` property. For releases that happened, it is either "retired" or "current". For all releases with that status, you can be sure that they've happened. For the ones with "beta", "nightly", or "planned", this isn't the case. So, I think the `status` property would make this filterable, if you don't want future releases, depending on your use case for the data. Does that make sense?

**Comment by jpmedley** [comment]
I frequently forget that stable versions of Chrome ship about a week before the next version goes to beta. I should not have held this up. 

In general my concern with publishing dates ahead of time is that any dates we may have published externally are approximations, not commitments.

**Comment by vinyldarkscratch** [comment]
From what I see, there wasn't any dates set for the beta or nightly version, just the date of the existing release.  I think there was some confusion in what exactly this PR was doing -- based upon the discussion, I'm thinking it may have been interpreted as primarily affecting the beta version, not the new stable release.

So, @jpmedley, are we clear to merge this and add the data for Chrome 74?

**Comment by jpmedley** [comment]
Yes.

**Comment by foolip** [comment]
I assumed the problem was saying that 75 was beta when the beta channel was still on 74. Anyway, I'll do the next thing next time if I send the PR :)

**Comment by jpmedley** [comment]
Correct.

**Pull request merged**
