### PR TITLE
Updates for Chrome 121 beta

### PR DESCRIPTION
**Pull request by Elchi3**
The Open Web Docs BCD collector found new features shipping in Chrome 121 beta. Currently, the collector covers about 82% of BCD, so the following list might not be exhaustive. Certain APIs that use enrollment etc. might not have been found either. For comparison, the Chromestatus list for Chrome 121 is here: https://chromestatus.com/features#milestone%3D121.

<hr>

With this PR, BCD marks the following features as shipping in Chrome 121: cc @chrisdavidmills 

- api.CSSImportRule.supportsText
- api.CharacterBoundsUpdateEvent
- api.CharacterBoundsUpdateEvent.CharacterBoundsUpdateEvent
- api.CharacterBoundsUpdateEvent.rangeEnd
- api.CharacterBoundsUpdateEvent.rangeStart
- api.ClipboardItem.supports_static
- api.EditContext
- api.EditContext.EditContext
- api.EditContext.attachedElements
- api.EditContext.characterBounds
- api.EditContext.characterBoundsRangeStart
- api.EditContext.characterboundsupdate_event
- api.EditContext.compositionend_event
- api.EditContext.compositionstart_event
- api.EditContext.selectionEnd
- api.EditContext.selectionStart
- api.EditContext.text
- api.EditContext.textformatupdate_event
- api.EditContext.textupdate_event
- api.EditContext.updateCharacterBounds
- api.EditContext.updateControlBounds
- api.EditContext.updateSelection
- api.EditContext.updateSelectionBounds
- api.EditContext.updateText
- api.HTMLElement.editContext
- api.HTMLSelectElement.showPicker
- api.TextFormat
- api.TextFormat.TextFormat
- api.TextFormat.rangeEnd
- api.TextFormat.rangeStart
- api.TextFormat.underlineStyle
- api.TextFormat.underlineThickness
- api.TextFormatUpdateEvent
- api.TextFormatUpdateEvent.TextFormatUpdateEvent
- api.TextFormatUpdateEvent.getTextFormats
- api.TextUpdateEvent
- api.TextUpdateEvent.TextUpdateEvent
- api.TextUpdateEvent.selectionEnd
- api.TextUpdateEvent.selectionStart
- api.TextUpdateEvent.text
- api.TextUpdateEvent.updateRangeEnd
- api.TextUpdateEvent.updateRangeStart
- css.properties.scrollbar-color
- css.properties.scrollbar-width
- css.selectors.grammar-error
- css.selectors.spelling-error
- javascript.builtins.Array.fromAsync

<hr>

Some new features have been tagged to be part of the `"web-features:edit-context"` group. cc @ddbeck 

- api.CharacterBoundsUpdateEvent
- api.CharacterBoundsUpdateEvent.CharacterBoundsUpdateEvent
- api.CharacterBoundsUpdateEvent.rangeEnd
- api.CharacterBoundsUpdateEvent.rangeStart
- api.EditContext
- api.EditContext.EditContext
- api.EditContext.attachedElements
- api.EditContext.characterBounds
- api.EditContext.characterBoundsRangeStart
- api.EditContext.characterboundsupdate_event
- api.EditContext.compositionend_event
- api.EditContext.compositionstart_event
- api.EditContext.selectionEnd
- api.EditContext.selectionStart
- api.EditContext.text
- api.EditContext.textformatupdate_event
- api.EditContext.textupdate_event
- api.EditContext.updateCharacterBounds
- api.EditContext.updateControlBounds
- api.EditContext.updateSelection
- api.EditContext.updateSelectionBounds
- api.EditContext.updateText
- api.HTMLElement.editContext
- api.TextFormat
- api.TextFormat.TextFormat
- api.TextFormat.rangeEnd
- api.TextFormat.rangeStart
- api.TextFormat.underlineStyle
- api.TextFormat.underlineThickness
- api.TextFormatUpdateEvent
- api.TextFormatUpdateEvent.TextFormatUpdateEvent
- api.TextFormatUpdateEvent.getTextFormats
- api.TextUpdateEvent
- api.TextUpdateEvent.TextUpdateEvent
- api.TextUpdateEvent.selectionEnd
- api.TextUpdateEvent.selectionStart
- api.TextUpdateEvent.text
- api.TextUpdateEvent.updateRangeEnd
- api.TextUpdateEvent.updateRangeStart

### CODE REVIEW

**Comment by ddbeck** [comment]
Cool! I will spot check the tagged features a little later and if everything looks good create a corresponding `text-edit` YAML on web-features.

And if @captainbrosset wants to comment on creating a new `text-edit` group (since I saw https://github.com/mdn/mdn/issues/493) that'd be nice too, but probably not a blocker.

**Comment by Elchi3** [comment]
Thanks @ddbeck! I called the group `edit-context` here but happy to change to `text-edit` if that's a better name.

**Comment by ddbeck** [comment]
> Thanks @ddbeck! I called the group `edit-context` here but happy to change to `text-edit` if that's a better name.

No that was just me misreading 🤦. I've edited my earlier comment to make it more obvious what the heck I was talking about.

**Comment by ddbeck** [comment]
OK, reviewing only the tagging part here: I've now compared the spec to tagged features. I'm happy with this list. I've opened a companion feature PR on web-features: https://github.com/web-platform-dx/web-features/pull/496.

Again, it'd be nice to get someone who knows anything at all about this API to check to see if I've missed anything (or if there's a likely reason to hold this back—e.g., it might not actually land in 121). But I'd be OK without it too.

**Comment by captainbrosset** [comment]
> And if @captainbrosset wants to comment on creating a new `edit-context` group (since I saw [mdn/mdn#493](https://github.com/mdn/mdn/issues/493)) that'd be nice too, but probably not a blocker.

Creating a new `edit-context` group sounds perfect!

**Review by captainbrosset — APPROVED** [review]
I spot checked the EditContext-related stuff and the `edit-context` web-features group, and all seems fine to me.
I don't think there's a lot of risks for mistakes here. This is a self-contained API (i.e. not like Clipboard 😉) that shipped all in one release.
That said, I'm also very new to it myself (probably like everyone but the spec authors at this point). 
I'll be documenting this on MDN soon, so might have more feedback after that.

**Comment by chrisdavidmills** [comment]
@Elchi3 I went through all the Chrome 121 beta entries with a fine toothcomb and compiled the following lists to represent items that the collector picked up, versus ones it didn't. This time I opted for a simplified format that was quicker to compile and possibly a bit easier to go through. Does this work for you?

## Features listed in Chrome 121 beta release

### Found by the collector

- api.CSSImportRule.supportsText: I'm not really sure where this one fits in
- Feature detection for supported clipboard formats: https://chromestatus.com/feature/5176417696612352
  - api.ClipboardItem.supports_static
- EditContext API: https://chromestatus.com/feature/5041440373604352
  - api.CharacterBoundsUpdateEvent
  - api.CharacterBoundsUpdateEvent.CharacterBoundsUpdateEvent
  - api.CharacterBoundsUpdateEvent.rangeEnd
  - api.CharacterBoundsUpdateEvent.rangeStart
  - api.EditContext
  - api.EditContext.EditContext
  - api.EditContext.attachedElements
  - api.EditContext.characterBounds
  - api.EditContext.characterBoundsRangeStart
  - api.EditContext.characterboundsupdate_event
  - api.EditContext.compositionend_event
  - api.EditContext.compositionstart_event
  - api.EditContext.selectionEnd
  - api.EditContext.selectionStart
  - api.EditContext.text
  - api.EditContext.textformatupdate_event
  - api.EditContext.textupdate_event
  - api.EditContext.updateCharacterBounds
  - api.EditContext.updateControlBounds
  - api.EditContext.updateSelection
  - api.EditContext.updateSelectionBounds
  - api.EditContext.updateText
  - api.HTMLElement.editContext
  - api.TextFormat
  - api.TextFormat.TextFormat
  - api.TextFormat.rangeEnd
  - api.TextFormat.rangeStart
  - api.TextFormat.underlineStyle
  - api.TextFormat.underlineThickness
  - api.TextFormatUpdateEvent
  - api.TextFormatUpdateEvent.TextFormatUpdateEvent
  - api.TextFormatUpdateEvent.getTextFormats
  - api.TextUpdateEvent
  - api.TextUpdateEvent.TextUpdateEvent
  - api.TextUpdateEvent.selectionEnd
  - api.TextUpdateEvent.selectionStart
  - api.TextUpdateEvent.text
  - api.TextUpdateEvent.updateRangeEnd
  - api.TextUpdateEvent.updateRangeStart
- HTMLSelectElement showPicker(): https://chromestatus.com/feature/5111537299881984
  - api.HTMLSelectElement.showPicker
- CSS Scrollbars: scrollbar-color, scrollbar-width: https://chromestatus.com/feature/5665308343795712
  - css.properties.scrollbar-color
  - css.properties.scrollbar-width
- CSS spelling and grammar features: https://chromestatus.com/feature/4811776539492352
  - css.selectors.grammar-error
  - css.selectors.spelling-error
- Array.fromAsync: https://chromestatus.com/feature/5069575759069184
  - javascript.builtins.Array.fromAsync

### Not found by the collector

- Discard Input Events To Recently Moved Cross-Origin Iframes: https://chromestatus.com/feature/5079376387637248 (more of a browser behavior thing)
- Attribution Reporting Feature Bundle: Reduced Aggregate Delays, Event-Level Report Epsilon Field, Reserved Keys: https://chromestatus.com/feature/5181611197071360 (hidden behind enrollment?)
- CSS font-palette property animation: https://chromestatus.com/feature/5177171439517696 (behavior change rather than a new property)
- CSS Highlight Inheritance: https://chromestatus.com/feature/5090853643354112 (behavior change rather than a new property)
- CSS supports() condition for @import: https://chromestatus.com/feature/5899007704694784 (addition to @import syntax)
- Document picture-in-picture: require user gesture for resize APIs: https://chromestatus.com/feature/5398995019235328 (Window returned by DocumentPictureInPicture.requestWindow() can now use resizeBy() and resizeTo() with user gesture)
- Improved CSS masking for SVG: https://chromestatus.com/feature/5138520058626048 (CSS masking stuff)
- MediaCapabilities: Query HDR support with decodingInfo(): https://chromestatus.com/feature/6640863931269120 (HdrMetadataType option added to MediaCapabilities.encodingInfo dictionary parameter)
- No-Vary-Search Hint for Prefetch Speculation Rules: https://chromestatus.com/feature/4887338302308352 (new field for speculation rule JSON structure)
- No-Vary-Search support in navigation prefetch cache: https://chromestatus.com/feature/5071247189213184 (new HTTP header)
- Private Aggregation API: aggregation coordinator selection: https://chromestatus.com/feature/5140711678935040 (hidden behind enrollment?)
- Protected Audience Ad slot size in real-time bidding signals fetch and update more interest group fields: https://chromestatus.com/feature/5090856430469120
- Remote Playback API: https://chromestatus.com/feature/5778318691401728 (surprised this one wasn't found)
- Ruby-specific display values: https://chromestatus.com/feature/6416726833233920 (new display property values, default display values for `<ruby>` and `<rt>` elements)
- Speculation rules: delivery via Speculation-Rules header: https://chromestatus.com/feature/5069400512659456 (new HTTP header)
- Speculation rules: document-sourced rules: https://chromestatus.com/feature/5112150536749056 (new field for speculation rule JSON structure; predicate?)
- Speculation rules: eagerness field: https://chromestatus.com/feature/5091678266851328 (new field for speculation rule JSON structure)
- Expose SpeechSynthesis and SpeechSynthesisVoice interface objects: https://chromestatus.com/feature/4818803819020288 (not even sure if there is anything to do here)
- Storage Buckets API: https://chromestatus.com/feature/5739224579964928 (surprised this one wasn't found)
- URLPattern: Inherit left, wildcard right: https://chromestatus.com/feature/6076647526891520 (changes to inheritance behavior of URLPattern)
- URLPattern: RegExp v flag instead of u: https://chromestatus.com/feature/5122651463090176 (internal behavior change to enable unicode sets in URLPatterns)
- WebGPU default entry points to shader modules: https://chromestatus.com/feature/5102870756327424 (GPUProgrammableStage)
- WebGPU timestamp queries: https://chromestatus.com/feature/5136606877188096 (GPUComputePassTimestampWrites)
- X25519Kyber768 key encapsulation for TLS: https://chromestatus.com/feature/5257822742249472 (not really sure how we'd document this)
Multiple Readers and Writers in File System Access API: https://chromestatus.com/feature/5172892632875008 (new locking modes for FileSystemSyncAccessHandle and FileSystemWritableFileStream)
- Set IndexedDB transaction durability to `relaxed` by default: https://chromestatus.com/feature/5084460341264384 (IDBDatabase.transaction durability option now defaults to relaxed)

**Comment by Elchi3** [comment]
Thanks once again Chris for your detailed analysis. It will help us to detect more things automatically in the future. ❤️ 

Some comments on items not found:
- As said previously, features that are "behavior things" aren't really subject to our automatic collection. So thanks for listing them, but right now we can't do anything about them automatically.
- Same for features that are new parameters and other sub features: not always subject to automatic collection right now.
- Enrollment. We have to see how to support enrollment in the collector and how to have a note on BCD features that are only available when enrolled. This is a to-do for BCD and the collector. Right now it is very tricky to tell if they are supported.
- HTTP features aren't automatically collected currently. I don't know how we could feature detect these. Something to think about. I think we should add the new HTTP header in a separate PR manually.

Two things that seem like we should have detected them with our current infrastructure:

>  Remote Playback API: https://chromestatus.com/feature/5778318691401728 (surprised this one wasn't found). 

Yes, I am surprised too. We have https://github.com/mdn/browser-compat-data/pull/21486 to investigate the situation. Seems like the API was exposed for a long time already and so we feature detected it when it shipped to Android already.

> Storage Buckets API: https://chromestatus.com/feature/5739224579964928 (surprised this one wasn't found).

Yes, strange. I wonder if this slipped to 122? See https://wpt.fyi/results/storage/buckets?label=master&product=chrome-121.0.6167.8%20beta&product=chrome%5Bexperimental%5D&aligned where the WPT fail for 121 and pass for 122. Maybe Chromestatus is wrong?

**Comment by Elchi3** [comment]
@chrisdavidmills I'm not planning to add more to this PR. If what this PR changes, looks good to you, I'd appreciate an approval and merge. :) I left some comments for the rest, but that should probably be sorted in other PRs.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I'm not planning to add more to this PR. If what this PR changes, looks good to you, I'd appreciate an approval and merge. :) I left some comments for the rest, but that should probably be sorted in other PRs.

@Elchi3. Sure thing; merging!

**Pull request merged**
