### PR TITLE
Correct Safari support for Worklet.addModule

### PR DESCRIPTION
**Pull request by MrBrain295**
#### Summary
Fix safari support.

#### Related issues
This fixes: #17550

### CODE REVIEW

**Comment by queengooborg** [comment]
Thanks @MrBrain295!  Did this data come from the issue, or have you also performed your own testing to confirm the data?

**Comment by MrBrain295** [comment]
This data came from the issue.

**Comment by queengooborg** [comment]
Gotcha -- would you mind researching this further and double-checking the information?  I don't trust the accuracy of the data from the issue!

**Comment by MrBrain295** [comment]
I found the [safari 14.1 release notes](https://developer.apple.com/documentation/safari-release-notes/safari-14_1-release-notes) and it does say it added more audio Worklet support.

**Review by queengooborg — APPROVED** [review]
I double-checked this in Safari 14.1 on BrowserStack, and since worklet support in general was added then, this looks good to me, thanks!

**Pull request merged**
