### PR TITLE
Add UC (international and Chinese) for Android as a browsers

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Per https://github.com/GoogleChromeLabs/confluence/pull/247 some versions are duplicated for UC China, and I didn't check if that was the case for English as well. I've asked UC folks to review this and it would be good to verify that the version history looks correct.

**Comment by Elchi3** [comment]
Thanks, this looks good to me. I will wait with merging until UC folks gave this a review.

**Comment by toxic-johann** [comment]
Hi @Elchi3 , I am Johann from UC Browser.

Both [http://wap.uc.cn/verlist/chinese_999/ucbrowser/145](http://wap.uc.cn/verlist/chinese_999/ucbrowser/145) and  [http://wap.uc.cn/verlist/english_354/ucbrowser/145](http://wap.uc.cn/verlist/english_354/ucbrowser/145) are our official page. So the data is correct.

As for the duplicated versions, We recommend to take the latest one.  And @foolip just do so. 

We think this pr is ok.

**Comment by foolip** [comment]
Thanks @toxic-johann!

@Elchi3, can you go ahead and merge this? Please don't squash into a single commit, or if you do so make sure to keep the script in the commit message.

**Pull request merged**
