### PR TITLE
Chrome and firefox support chrome_url_overrides.newtab

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by wbamberg** [comment]
I'm not sure what the best thing to do here is. In the previous version, I'd implicitly included newtab support in `basic_support`. 

`basic_support` is a mandatory subfeature, and represents the "lowest common denominator". What exactly that includes is kind of implicit, AIUI: things that aren't called out in separate subfeatures are considered part of `basic_support`.

I agree that explicitly calling out `newtab` support is better, and clearer, than leaving it implicit. But if we do include it, what does `basic_support` mean in this case? It conveys no extra information. And we can't omit it, because it's mandatory.

@Elchi3 , what do you think about this one?

**Comment by Elchi3** [comment]
This is indeed a tricky question. I also like to see `newtab` explicitly, I think it makes the table easier to read.

I would come back to "lowest common denominator" here. So, `basic_support` means that `chrome_url_overrides` is supported in whatever way without looking at its properties at all.

If many browsers supported `newtab` first then that's their `basic_support` at the same time. If, in theory, Edge implements this and supports `history` first, Edge's `basic_support` would be the same as their `history` support. So `basic_support` gives you back when `chrome_url_overrides` was made available regardless of which functionality exactly.

Does that make _some_ sense?

**Comment by wbamberg** [comment]
So in cases like this, `basic_support` is true for a browser if the browser supports any of the subfeatures. To be pedantic, that means it's not a "lowest common denominator" since as you say it's not necessarily common between browsers.

I guess this is OK: it's redundant, since it doesn't add anything over the subfeatures. The alternative would be to make `basic_support` optional in the schema.

The thing about manifest keys (at least ones like this) is, they don't really have any functionality over the properties they contain. It doesn't make sense for a browser to support `chrome_url_overrides` but not support any of its properties. So if you break out all the properties into subfeatures, there's nothing left.

**Comment by domoritz** [comment]
For what it's worth, I was trying to make sense of the documentation and had no idea what `basic_support` means. I think as a reader, I can easily see if a browser supports any property in the short table. Thus, I think a table with only `newtab`, `history`, and `bookmarks` is sufficient but I don't know how consistent that is with other properties.

**Comment by wbamberg** [comment]
@domoritz , I agree with you that it's a problem that the meaning of `basic_support` isn't very clear. For now though, let's just add the `newtab` subfeature.

Since the notes attached to `basic_support` refer to `newtab', would you mind moving them into the `newtab` subfeature? Then I'll merge this.

**Comment by domoritz** [comment]
@wbamberg, I coped the whole block from basic_support into newtab.

**Comment by wbamberg** [comment]
Please remove the notes from `basic_support` too, or they'll be duplicated. Sorry to be a pain and thanks for your persistence :).

**Comment by domoritz** [comment]
Done. @wbamberg, I think you can edit my pr. 

screen shot 2017-06-15 at 13 27 57

**Comment by domoritz** [comment]
Thanks for doing all this awesome work on MDN!

**Pull request merged**
