### PR TITLE
Remove XPath and XSLT data

### LINKED ISSUE #2027: Migrate XSLT compat data
XSLT compat data migration is being started and set up in #2026.

## Changes that need to be made as part of this:
- [x] Move all XSLT elements under the [XSLT elements reference](https://developer.mozilla.org/docs/Web/XSLT/Element)
- [x] Rename `/docs/Web/XSLT/Elements/*` to <code>[/docs/Web/XSLT/Element/*](https://developer.mozilla.org/docs/Web/XSLT/Element)</code>
- [ ] Modernise XSLT macros (mdn/kumascript#734)

## Pages which need conveting:
- [ ] [XSLT/Element/apply-imports](https://developer.mozilla.org/docs/Web/XSLT/Element/apply-imports)
- [ ] [XSLT/Element/apply-templates](https://developer.mozilla.org/docs/Web/XSLT/Element/apply-templates)
- [ ] [XSLT/Element/attribute](https://developer.mozilla.org/docs/Web/XSLT/Element/attribute)
- [ ] [XSLT/Element/attribute-set](https://developer.mozilla.org/docs/Web/XSLT/Element/attribute-set)
- [ ] [XSLT/Element/call-template](https://developer.mozilla.org/docs/Web/XSLT/Element/call-template)
- [ ] [XSLT/Element/choose](https://developer.mozilla.org/docs/Web/XSLT/Element/choose)
- [ ] [XSLT/Element/comment](https://developer.mozilla.org/docs/Web/XSLT/Element/comment)
- [ ] [XSLT/Element/copy](https://developer.mozilla.org/docs/Web/XSLT/Element/copy)
- [ ] [XSLT/Element/copy-of](https://developer.mozilla.org/docs/Web/XSLT/Element/copy-of)
- [ ] [XSLT/Element/decimal-format](https://developer.mozilla.org/docs/Web/XSLT/Element/decimal-format)
- [ ] [XSLT/Element/element](https://developer.mozilla.org/docs/Web/XSLT/Element/element)
- [ ] [XSLT/Element/fallback](https://developer.mozilla.org/docs/Web/XSLT/Element/fallback)
- [ ] [XSLT/Element/for-each](https://developer.mozilla.org/docs/Web/XSLT/Element/for-each)
- [ ] [XSLT/Element/if](https://developer.mozilla.org/docs/Web/XSLT/Element/if)
- [ ] [XSLT/Element/import](https://developer.mozilla.org/docs/Web/XSLT/Element/import)
- [ ] [XSLT/Element/include](https://developer.mozilla.org/docs/Web/XSLT/Element/include)
- [ ] [XSLT/Element/key](https://developer.mozilla.org/docs/Web/XSLT/Element/key)
- [ ] [XSLT/Element/message](https://developer.mozilla.org/docs/Web/XSLT/Element/message)
- [ ] [XSLT/Element/namespace-alias](https://developer.mozilla.org/docs/Web/XSLT/Element/namespace-alias)
- [ ] [XSLT/Element/number](https://developer.mozilla.org/docs/Web/XSLT/Element/number)
- [ ] [XSLT/Element/otherwise](https://developer.mozilla.org/docs/Web/XSLT/Element/otherwise)
- [ ] [XSLT/Element/output](https://developer.mozilla.org/docs/Web/XSLT/Element/output)
- [ ] [XSLT/Element/param](https://developer.mozilla.org/docs/Web/XSLT/Element/param)
- [ ] [XSLT/Element/preserve-space](https://developer.mozilla.org/docs/Web/XSLT/Element/preserve-space)
- [ ] [XSLT/Element/processing-instruction](https://developer.mozilla.org/docs/Web/XSLT/Element/processing-instruction)
- [ ] [XSLT/Element/sort](https://developer.mozilla.org/docs/Web/XSLT/Element/sort)
- [ ] [XSLT/Element/strip-space](https://developer.mozilla.org/docs/Web/XSLT/Element/strip-space)
- [x] [XSLT/Element/stylesheet](https://developer.mozilla.org/docs/Web/XSLT/Element/stylesheet) (#2026)
- [ ] [XSLT/Element/template](https://developer.mozilla.org/docs/Web/XSLT/Element/template)
- [ ] [XSLT/Element/text](https://developer.mozilla.org/docs/Web/XSLT/Element/text)
- [ ] [XSLT/Element/transform](https://developer.mozilla.org/docs/Web/XSLT/Element/transform)
- [ ] [XSLT/Element/value-of](https://developer.mozilla.org/docs/Web/XSLT/Element/value-of)
- [ ] [XSLT/Element/variable](https://developer.mozilla.org/docs/Web/XSLT/Element/variable)
- [ ] [XSLT/Element/when](https://developer.mozilla.org/docs/Web/XSLT/Element/when)
- [ ] [XSLT/Element/with-param](https://developer.mozilla.org/docs/Web/XSLT/Element/with-param)

### LINKED ISSUE #9589: Remove xpath feature/directory from the repo?
For XPath, we actually have only a single feature in BCD, and the entire content of its MDN article is literally a single sentence:

> The `self` axis indicates the context node itself. It can be abbreviated as a single period `(.)`.

Does that solitary feature — not really even documented in MDN — merit continuing to have its own top-level directory in BCD?

### LINKED ISSUE #9826: Remove xslt feature/directory from the repo (the data for which is mostly null)
For reasons similar to #9589, the data (or lack of data…) in the `xslt` directory doesn’t seem to merit continuing to have its own top-level directory in BCD.

As with the `xpath` directory, there is only one actual standard XSLT feature for which we have data in that directory. The rest of the features in there are for non-standard EXSLT stuff.

And in both cases the bulk of the `xslt` data is `null` values, and nobody seems to care — certainly nobody cares enough to do the work of replacing it with actual data.

So if we are going to the trouble of removing the `xpath` directory, it would seem prudent to also remove the `xslt` directory.

### PR DESCRIPTION
**Pull request by ddbeck**
cc: @Elchi3, @sideshowbarker 

This PR is in draft status, until there's another set of breaking changes we can roll this up with.

This PR drops XPath and XSLT data, as well as associated schema, linting, docs, etc. This data is very incomplete. We're not foreclosing on this data returning at some point, but if it comes back, it needs to be in the context of an intentional effort.

<details>
<summary>Potentially affected MDN URLs</summary>

- [`xslt.elements.stylesheet`](https://developer.mozilla.org/docs/Web/XSLT/Element/stylesheet)
- [`xslt.elements.stylesheet.exclude-result-prefixes`](https://developer.mozilla.org/docs/Web/XSLT/Element/stylesheet#attr-exclude-result-prefixes)
- [`xslt.elements.stylesheet.extension-element-prefixes`](https://developer.mozilla.org/docs/Web/XSLT/Element/stylesheet#attr-extension-element-prefixes)
- [`xslt.elements.stylesheet.id`](https://developer.mozilla.org/docs/Web/XSLT/Element/stylesheet#attr-id)
- [`xslt.elements.stylesheet.version`](https://developer.mozilla.org/docs/Web/XSLT/Element/stylesheet#attr-version)
- [`xslt.exslt.exsl.node-set`](https://developer.mozilla.org/docs/Web/EXSLT/exsl/node-set)
- [`xslt.exslt.exsl.object-type`](https://developer.mozilla.org/docs/Web/EXSLT/exsl/object-type)
- [`xslt.exslt.math.highest`](https://developer.mozilla.org/docs/Web/EXSLT/math/highest)
- [`xslt.exslt.math.lowest`](https://developer.mozilla.org/docs/Web/EXSLT/math/lowest)
- [`xslt.exslt.math.max`](https://developer.mozilla.org/docs/Web/EXSLT/math/max)
- [`xslt.exslt.math.min`](https://developer.mozilla.org/docs/Web/EXSLT/math/min)
- [`xslt.exslt.regexp.match`](https://developer.mozilla.org/docs/Web/EXSLT/regexp/match)
- [`xslt.exslt.regexp.replace`](https://developer.mozilla.org/docs/Web/EXSLT/regexp/replace)
- [`xslt.exslt.regexp.test`](https://developer.mozilla.org/docs/Web/EXSLT/regexp/test)
- [`xslt.exslt.set.difference`](https://developer.mozilla.org/docs/Web/EXSLT/set/difference)
- [`xslt.exslt.set.distinct`](https://developer.mozilla.org/docs/Web/EXSLT/set/distinct)
- [`xslt.exslt.set.has-same-node`](https://developer.mozilla.org/docs/Web/EXSLT/set/has-same-node)
- [`xslt.exslt.set.intersection`](https://developer.mozilla.org/docs/Web/EXSLT/set/intersection)
- [`xslt.exslt.set.leading`](https://developer.mozilla.org/docs/Web/EXSLT/set/leading)
- [`xslt.exslt.set.trailing`](https://developer.mozilla.org/docs/Web/EXSLT/set/trailing)
- [`xslt.exslt.str.concat`](https://developer.mozilla.org/docs/Web/EXSLT/str/concat)
- [`xslt.exslt.str.split`](https://developer.mozilla.org/docs/Web/EXSLT/str/split)
- [`xslt.exslt.str.tokenize`](https://developer.mozilla.org/docs/Web/EXSLT/str/tokenize)
- [`xpath.axes.self`](https://developer.mozilla.org/docs/Web/XPath/Axes/self)

</details

Fixes #9589 and fixes #9826 and fixes #2027.

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by bershanskiy** [comment]
Speaking of breaking changes, I remember there were a few incorrectly named features. Since feature renaming might break dependents, we might want to rename them all at once.

- `DOMHighResTimestamp` to `DOMHighResTimeStamp` (#9892)
- (looking for more)

**Comment by ddbeck** [comment]
@bershanskiy thanks for flagging that. I do record renames like that in the release notes (and add the _needs-release-note_ label to applicable PRs). That said, we're not using all feature name-changes trigger a semver major release (we tried to document this at https://github.com/mdn/browser-compat-data#semantic-versioning-policy).

**Review by sideshowbarker — APPROVED** [review]

**Review by sideshowbarker — APPROVED** [review]

**Review by Elchi3 — APPROVED** [review]
No more 🛤️ and 🚜 !!! 😄

**Comment by Elchi3** [comment]
(You should remove the 🛤️ and 🚜 labels from BCD)

**Review by BertsLifee — COMMENTED** [review]
Remove spec exception for XSLT

**Pull request merged**
