### PR TITLE
Remove PhotoCapabilities API from BCD

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes `PhotoCapabilities` from BCD.  This feature is a dictionary, enum, or WebIDL typedef and should not be included in BCD.

### CODE REVIEW

**Comment by foolip** [comment]
@queengooborg this PR is also adding stuff. Can you split out the additions into a separate PR?

**Comment by queengooborg** [comment]
It isn't adding new features; I'm folding the features of the `PhotoCapabilities` dictionary into the member that returns it.

**Comment by queengooborg** [comment]
Though actually, since the subfeatures and the parent feature have the same versions and there's no inconsistencies, I'll just remove the new subfeatures!

**Comment by foolip** [comment]
This is blocked on https://github.com/mdn/content/pull/10471 now.

**Comment by queengooborg** [comment]
Content PR merged!

**Review by foolip — APPROVED** [review]

**Pull request merged**
