### PR TITLE
Add data for CSS ellipse() method

### PR DESCRIPTION
**Pull request by Blakelist7**
Add data for`ellipse()`.
Fixes: #11208

### CODE REVIEW

**Comment by Blakelist7** [comment]
@teoli2003 please review this PR.

**Comment by teoli2003** [comment]
Hi! @Blakelist7 Thanks a lot! Can you tell us how you determined the values?

**Comment by Blakelist7** [comment]
Sure! I checked if the example was working on a specific version using https://caniuse.com/

**Comment by teoli2003** [comment]
Thanks! You found Edge 80, this is strange as all the other entries on this file have Edge 79. Can you double-check?

**Comment by Blakelist7** [comment]
Actually, in the mentioned site edge version's starts from 80 so I was not able to check for 79.

**Comment by teoli2003** [comment]
@foolip and @vinyldarkscratch, any hint about how to test for Edge 79? (I would be surprised it doesn't work there)

**Comment by vinyldarkscratch** [comment]
Can you share the exact CanIUse entry you obtained your data from?  You can get a permalink by clicking the "#" icon on the entry!

I'm also guessing you went to BrowserStack to test the support, which yes, doesn't have Edge 79.  However, I highly doubt that a feature like this would have been excluded in Edge 79 considering its established support in Chrome.  Have you also tested support in Edge 18 or older?

**Comment by Blakelist7** [comment]
This is my first time using CanIUse, so firstly I searched for `basic-shape` and from there I used BrowserSlack to test.
Yes, I tested for Edge 18 and it is not compatible.

**Comment by foolip** [comment]
> @foolip and @vinyldarkscratch, any hint about how to test for Edge 79? (I would be surprised it doesn't work there)

If testing on BrowserStack I just test Edge 80 and assume 79 will be the same unless the feature was introduced in Chromium 80.

Or one can use Sauce Labs which also has Edge 79.

**Comment by Blakelist7** [comment]
> > @foolip and @vinyldarkscratch, any hint about how to test for Edge 79? (I would be surprised it doesn't work there)
> 
> If testing on BrowserStack I just test Edge 80 and assume 79 will be the same unless the feature was introduced in Chromium 80.
> 
> Or one can use Sauce Labs which also has Edge 79.

Thank you for the resource and I just checked using Sauce Labs, yes it works on Edge 79. :)

**Comment by teoli2003** [comment]
Cool. Thanks. LGTM (I can't formally approve, though)

**Review by vinyldarkscratch — APPROVED** [review]
Thanks for the PR!  I just confirmed the version numbers real quick, and this is looking good to me!

**Comment by teoli2003** [comment]
@Blakelist7 Congrats for your first bcd commit!

**Comment by Blakelist7** [comment]
@teoli2003 
Also as I can check for `circle()`, `polygon()` and `inset()` their examples are not supported in FF 54, so should I create an issue here in BCD or content?

**Comment by vinyldarkscratch** [comment]
Since it involves browser compatibility, let's open the issue here?

**Comment by Blakelist7** [comment]
> Since it involves browser compatibility, let's open the issue here?

Cool

**Pull request merged**
