### PR TITLE
Correct details of UIEvent.detail for Internet Explorer

### PR DESCRIPTION
**Pull request by craigkovatch**
The `UIEvent.detail` compat data for IE indicates full compatibility from IE9+, but the implementation is wildly out-of-spec. Documented the real behavior based on inspection. (Also confirmed that Edge works as expected.)

### CODE REVIEW

**Comment by craigkovatch** [comment]
Help me @vinyldarkscratch you're my only hope.obiwan.gif

**Comment by vinyldarkscratch** [comment]
~~[The force will be with you, always](https://gfycat.com/necessaryhandybobwhite-monstercat-release-female-beat-saber)~~

Hmm...  Using the example from the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event#Examples), I can't seem to replicate the behavior you're mentioning in IE 9 (it behaves just like my test in Chrome).  What version of IE did you test with?  Also, if you have it around, what was your test code?

**Comment by vinyldarkscratch** [comment]
Hey @craigkovatch, do you plan to return to this PR?

**Comment by craigkovatch** [comment]
@vinyldarkscratch that MDN example uses arrow-function syntax which fails to do anything at all in any version of IE :)

Try saving this as an HTML file locally and loading it in IE. You'll see every call to console.log is with `0`:

```<html>
<head>
<title>Event.detail</title>
</head>
<body>
  <button onclick="console.log(event.detail)">test</button>
</body>
</html>
```

**Comment by vinyldarkscratch** [comment]
I see what you mean now.  Thanks for the follow-up!  

It seems that, in this case, the behavior does not match standard behavior when placed on `onXXX` attributes, but works just fine when event listeners are added via JavaScript like in the example on MDN (I modified it to use standard `function` notation before testing by the way).  As such, the wording of the note should probably be updated...  Not sure how to word it, though -- I'm open to ideas!

**Comment by craigkovatch** [comment]
@vinyldarkscratch I'm afraid I still can't repro the behavior you're seeing. I tried binding via both React and using `addEventListener` in native JS as you suggested, and I still observe IE11 to always report `0`: https://jsfiddle.net/vjrt8kbs/

**Pull request merged**
