### PR TITLE
Delete anchor HTML attribute

### PR DESCRIPTION
**Pull request by foolip**
It is not shipping in Chrome 125:
https://groups.google.com/a/chromium.org/g/blink-dev/c/jGTYNuidPRs/m/qm7Z5qsrAQAJ

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Thank you! 👍

**Comment by chrisdavidmills** [comment]
It works in Canary already, so I would've preferred to keep it in but marked as preview support, as we did with the `anchorElement`. Would that be OK? Either way, we should probably be consistent across the two of them.

**Comment by foolip** [comment]
Oh, sorry, since I didn't see `anchorElement` in https://github.com/mdn/browser-compat-data/pull/22903 I assumed that wasn't in BCD, but it was included in https://github.com/mdn/browser-compat-data/pull/22813. These two go together, so I'll restore this with "preview".

**Comment by mfreed7** [comment]
So neither `anchor` nor `anchorElement` should be working in 125 (Beta) or 126 (Canary). Make sure to turn off Experimental Web Platform Features. If you still see either of those functioning, please file a bug, but I just checked and don't see support.

**Comment by foolip** [comment]
The guidelines for the use of "preview" are here:
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#choosing-preview-values

It's used relatively little in BCD and experimental flags are used a lot more, but an upside of using "preview" is that you don't have to pick a version number, so there's no risk of the flags being removed and the originally guessed version number turning into the official version number.

**Comment by chrisdavidmills** [comment]
> So neither `anchor` nor `anchorElement` should be working in 125 (Beta) or 126 (Canary). Make sure to turn off Experimental Web Platform Features. If you still see either of those functioning, please file a bug, but I just checked and don't see support.

My bad — I did have this flag active. Sorry for the confusion.

**Comment by chrisdavidmills** [comment]
> The guidelines for the use of "preview" are here: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#choosing-preview-values
> 
> It's used relatively little in BCD and experimental flags are used a lot more, but an upside of using "preview" is that you don't have to pick a version number, so there's no risk of the flags being removed and the originally guessed version number turning into the official version number.

Now that I realize these features are behind a flag, I think it would good to report the flag data in their BCD. Is it appropriate to report the flag data and use the "preview" value at the same time?

**Comment by foolip** [comment]
@chrisdavidmills I've never seen that done, but if no lint complains about the combination or flags and "preview", that seems fine.

**Pull request merged**
