### PR TITLE
docs: update Intl.Locale support in Safari

### PR DESCRIPTION
**Pull request by wopian**
Safari 14 Technology Preview 107 added support for Intl.Locale and was enabled by default in Safari 14 TP 110.

Safari 14 is currently only in a beta phase and I do not use an Apple product/Safari myself, so I don't know how the Technology Previews map to actual Safari versions so they may need changing?

### Browser Support Verification

1. Intl.Locale added in Safari 14 TP 107 behind a flag on May 28 2020
   - https://webkit.org/blog/10585/release-notes-for-safari-technology-preview-107/
   - https://trac.webkit.org/changeset/261215/webkit/
   - https://bugs.webkit.org/show_bug.cgi?id=209772
2. Intl.Locale enabled by default in Safari 14 TP 110 (WebKit `263,214`-`263,988`) on July 16 2020
   - https://webkit.org/blog/10929/release-notes-for-safari-technology-preview-110/
   - https://trac.webkit.org/changeset/263227/webkit/
3. `minimize()` and `maximise()` implementation corrected in WebKit `264,275` on July 12 2020 (missed TP 110 window)
   - https://trac.webkit.org/changeset/264275/webkit
   - https://bugs.webkit.org/show_bug.cgi?id=214223
   - https://bugs.webkit.org/show_bug.cgi?id=214231

### Tested

The implementation was tested on iOS 14 Dev build 2 by someone else for me using https://6f6bm.csb.app. This revealed the implementation error on the Locale methods `maximise()` and `minimise()` which I reported and was promptly fixed. It missed the latest 14 TP 110 release by a couple of weeks and will likely land in 14 TP 111.

<details>
<summary>Screenshot of 6f6bm.csb.app on iOS 14 Dev build 2</summary>

</details>

### CODE REVIEW

**Comment by sideshowbarker** [comment]
Beautiful — welcome to BCD, @wopian 🎉

**Comment by wopian** [comment]
Thank you 😊

**Comment by wopian** [comment]
I thought it just missed the TP 110 cutoff window by a few days, turns out it missed the TP 111 release by just a handful of revisions.

TP 111 released yesterday on July 29 containing revisions upto 264,208 (220 changes). The patch landed in the trunk on revision 264,275.

**Comment by sideshowbarker** [comment]
> TP 111 released yesterday on July 29 containing revisions upto 264,208 (220 changes). The patch landed in the trunk on revision 264,275.

wow yeah that’s about as close as it gets

**Pull request merged**
