### PR TITLE
updates compatibility chart for Navigator api

### PR DESCRIPTION
**Pull request by jay-deshmukh**

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hey there, thanks for the PR!  Can you provide more sources as to why you think Firefox's support is `false`?

**Comment by jay-deshmukh** [comment]
Hi , I was trying to test Navigator.connection on firefox and it returned `undefined`

Screenshot 2019-11-06 at 10 35 55 AM

**Comment by vinyldarkscratch** [comment]
Gotcha -- thanks for the quick follow-up!  After some further research, first off it seems that you're typing it out with a capital N (which is the API itself), rather than a lowercase one (which is the generated object).  Second, it appears that support **is** there in Firefox, although it's hidden behind a flag, `dom.netinfo.enabled`.

Screen Shot 2019-11-06 at 04 15 41

Can we update this PR accordingly?  I noticed this is your first PR, so let me know if need assistance in learning how the schema works for flags!  (You can also check out the [schema docs](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#compat-data-in-support-statements).)

**Comment by jay-deshmukh** [comment]
Screenshot 2019-11-06 at 5 49 47 PM

**Comment by jay-deshmukh** [comment]
my browser version is `70.0.1` what's your's ?

**Comment by vinyldarkscratch** [comment]
Like I just said, the feature's actually behind a flag in Firefox, so support is not enabled by default.  A user will need to set `dom.netinfo.enabled` to `true` to get support.

**Comment by jay-deshmukh** [comment]
> Like I just said, the feature's actually behind a flag in Firefox, so support is not enabled by default. A user will need to set dom.netinfo.enabled to true to get support.

gotcha ! ... read it later thanks :)

**Comment by jay-deshmukh** [comment]
updated PR accordingly.

**Comment by vinyldarkscratch** [comment]
We actually have a machine-readable way to mark support under flags!  Rather than writing up a note, we'll add the following:

```json
"flags": [
  {
    "type": "preference",
    "name": "dom.netinfo.enabled",
    "value_to_set": "true"
  }
]
```

**Comment by vinyldarkscratch** [comment]
Hey @jay-deshmukh, do you plan to return to this PR?

**Comment by jay-deshmukh** [comment]
hi @vinyldarkscratch . Yup will update the PR by EOD

**Comment by vinyldarkscratch** [comment]
To get the ball rolling again, I went ahead and superseded this in #5150.  Thanks for raising the issue!

**Pull request closed without merging**
