### PR TITLE
Drop the “MediaQueryListListener” feature

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change drops the “MediaQueryListListener” feature. It’s not the name of an actual API but instead apparently was just a kind of shorthand for something that’s no longer part of any spec anyway. See https://wiki.developer.mozilla.org/docs/Web/API/MediaQueryListListener

### CODE REVIEW

**Comment by foolip** [comment]
@ddbeck can you redirect https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaQueryListListener before we merge this?

**Comment by sideshowbarker** [comment]
> @ddbeck can you redirect https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaQueryListListener before we merge this?

I can redirect it — so can you actually, I think: In the top editing bar of the MDN editing UI, you should see that the furthest-right button is a curved-arrow icon with **Create a Redirect** tooltip text. When you push push that it pops up a dialog that lets you choose the article name to redirect to.

**Comment by foolip** [comment]
Aha, I thought special powers were needed. I've redirected it now, but https://developer.mozilla.org/docs/Web/API/MediaQueryListListener hasn't updated yet.

**Comment by foolip** [comment]
Going through some of the docs for this, I think the interesting thing to communicate to web developers is whether `MediaQueryList` supports `addListener`, `addEventListener`, or both. How the callback function for `addListener` was specified is not in itself observable to web developers.

What gives me doubt is what to do with these notes still left in MDN:
https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#Syntax
https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/removeListener#Syntax

Is there anything about those that should be preserved?

**Comment by sideshowbarker** [comment]
> Going through some of the docs for this, I think the interesting thing to communicate to web developers is whether `MediaQueryList` supports `addListener`, `addEventListener`, or both.

Yeah, agreed

> How the callback function for `addListener` was specified is not in itself observable to web developers.
> 
> What gives me doubt is what to do with these notes still left in MDN:
> https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#Syntax
> https://wiki.developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/removeListener#Syntax
> 
> Is there anything about those that should be preserved?

No, I think — nothing there that needs to be preserved (given as you noted that how the callback function is specified isn’t observable).

**Comment by ddbeck** [comment]
So what needs to happen here? Remove the mentions of `MediaQueryListListener` on MDN and merge this?

**Comment by sideshowbarker** [comment]
> So what needs to happen here? Remove the mentions of `MediaQueryListListener` on MDN and merge this?

I think so — but I guess we need confirmation from @foolip

**Comment by vinyldarkscratch** [comment]
Foolip's been away from BCD for a while -- reading through this thread, I'd say that this is ready to go.  If those notes don't need to be preserved, then we can push go and remove this!

**Comment by sideshowbarker** [comment]
> I'd say that this is ready to go. If those notes don't need to be preserved, then we can push go and remove this!

OK, thanks — then I’m happy if you (or anybody other than me, since I’m the author for the patch) can go ahead and push the button to merge this

**Comment by sideshowbarker** [comment]
Thanks for the merge!

**Comment by ddbeck** [comment]
So it's not exactly explicit from the process [we discussed previously](https://github.com/mdn/browser-compat-data/pull/6929#issuecomment-717981716), but I'd like to make sure that we clean up any content messes that follow from our feature removals before merging. By redirecting the `MediaQueryListListener` page back to `MediaQueryList`, we created oddities on the pages for `MediaQueryList.addListener()` and `.removeListener()`. I'll fix those pages now, but, in the future, I'd like open questions about content problems to be answered (with content changes or issues against mdn/sprints) before merging.

**Pull request merged**
