### PR TITLE
Add latest samsung internet android releases

### PR DESCRIPTION
**Pull request by mfranzke**
#### Summary

it's really hard to find information on Samsung Internet browser, but version 26 is the current version according to http://www.samsungapps.com/appquery/appDetail.as?appId=com.sec.android.app.sbrowser

- Samsung Internet 26: taken the earliest apk version date from https://www.apkmirror.com/uploads/?appcategory=samsung-internet-for-android, https://samsung-internet.en.aptoide.com/versions and https://play.google.com/store/apps/details/Samsung+Internet+Browser?id=com.sec.android.app.sbrowser&hl=en_US&pli=1
- Samsung Internet 27: zloirock/core-js@3dec7dd

#### Test results and supporting details

no available release notes that I could find.
update (2024-09-04): just double checked it on an Samsung Galaxy A04s smartphone, and added two screenshots that even also mention the user agents.

##### version 26.0.3.7 screenshot

it's being called "Samsung Internet 122", which is actually not the "Samsung Internet" release version but the Chromium version.

Screenshot_20240904_180507_Samsung Internet

##### version 27.0.039 Beta screenshot

it's being called "Samsung Internet 125", which is actually not the "Samsung Internet" release version but the Chromium version.

Screenshot_20240904_180436_Samsung Internet Beta

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
I tried adding Samsung Internet 26.0 in https://github.com/mdn/browser-compat-data/pull/23924 as well but we were similarly unsure about its release.

Trying a ping to @matatk again :) Matthew, can you help us? Was there a Samsung Internet 26.0 release in July?

**Comment by Elsensee** [comment]
I didn't find this PR because i foolishly only looked under Issues. 😅

I would second the data. I verified the Blink engine versions.

Also this Reddit post hints at a late June release of the second 26.0 release: https://old.reddit.com/r/samsunggalaxy/comments/1ds3c8a/samsung_internet_browser_260052_recent_update/

Meaning, the first version probably appeared before that date and definitely not in July.

**Comment by mfranzke** [comment]
> I didn't find this PR because i foolishly only looked under Issues. 😅
> 
> I would second the data. I verified the Blink engine versions.
> 
> Also this Reddit post hints at a late June release of the second 26.0 release: https://old.reddit.com/r/samsunggalaxy/comments/1ds3c8a/samsung_internet_browser_260052_recent_update/
> 
> Meaning, the first version probably appeared before that date and definitely not in July.

Moin and thanks a lot !

**Review by Elchi3 — APPROVED** [review]
Thank you for all the additional evidence, @mfranzke! 👍 
Let's merge this!

**Pull request merged**
