### PR TITLE
css.types.angle-percentage: delete child elements

### PR DESCRIPTION
**Pull request by bershanskiy**
## Summary

Fix mdn_url for css.types.angle-percentage

## Related issues
This is one of the issues found by #5201 

A checklist to help your pull request get merged faster:
- [ ] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by Elchi3** [comment]
Hm well, there is no documentation under https://developer.mozilla.org/en-US/docs/Web/CSS/angle-percentage#deg but there is under https://developer.mozilla.org/en-US/docs/Web/CSS/angle#deg.
So, the URLs are correct, I guess?

**Comment by bershanskiy** [comment]
> Hm well, there is no documentation under https://developer.mozilla.org/en-US/docs/Web/CSS/angle-percentage#deg but there is under https://developer.mozilla.org/en-US/docs/Web/CSS/angle#deg.

That can be easily fixed, if desired (I could update English locale and add stubs to all other locales). As is, the docs URLs are a bit misleading and kinda defeat having `<angle-percentage>` page at all.

**Comment by Elchi3** [comment]
Thank you so much for volunteering to fix this! 
I don't really know why things are set up the way they are. Maybe @rachelandrew has thoughts on the matter?

**Comment by rachelandrew** [comment]
I think it just hasn't been added there yet so if you want to add it that would be great!

**Comment by bershanskiy** [comment]
@Elchi3 @rachelandrew 

Actually, now that I had more time to think about it I don't understand the need for `<angle>` types under `<angle-percentage>` data type. Specifically, since `<angle-percentage>` is equivalent to `[ <angle> | <percentage> ]`, then all degree units/types children of `css.types.angle-percentage` have to be exactly the same as under `css.types.angle`; the percentage type/unit is just that -- a percentage.

So it would make more sense to me if we just deleted the redundant data:
 - `css.types.angle-percentage.deg` (already stored as `css.types.angle.deg`),
 - `css.types.angle-percentage.grad` (already stored as `css.types.angle.grad`),
 - `css.types.angle-percentage.rad` (already stored as `css.types.angle.rad`), and
 - `css.types.angle-percentage.turn` (already stored as `css.types.angle.turn`).
That would shrink `angle-percentage.json` to only contain `css.types.angle-percentage.__compat`.

Is there something I'm missing like `angle-percentage` interaction with other stuff?

**Comment by Elchi3** [comment]
This seems like the right call to me, but @rachelandrew might know more here.

**Comment by rachelandrew** [comment]
LGTM

**Pull request merged**
