### PR TITLE
Set Chrome 91 as stable chrome.

### PR DESCRIPTION
**Pull request by lukewarlow**
#### Summary

Chrome 91 was just launched to stable channel.

#### Test results and supporting details

https://chromereleases.googleblog.com/2021/05/stable-channel-update-for-desktop_25.html

https://chromereleases.googleblog.com/2021/05/chrome-for-android-update_01607414128.html

### CODE REVIEW

**Review by lucalves — CHANGES_REQUESTED** [review]
I think it would be interesting to also update the files `browsers/chrome_android.json` and `browsers/webview_android.json`.

**Comment by lukewarlow** [comment]
> I think it would be interesting to also update the files `browsers/chrome_android.json` and `browsers/webview_android.json`.

But Chrome Android hasn't been updated yet?

**Review by lucalves — APPROVED** [review]
I believe it's ok now, thanks! Let's wait for a review from the mdn team.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
Thanks @lukewarlow!

**Pull request merged**
