### PR TITLE
Adding support for Request.destination in Chrome, Opera and Edge

### PR DESCRIPTION
**Pull request by nhoizey**
Source: https://www.chromestatus.com/feature/5629697845100544

### CODE REVIEW

**Comment by Elchi3** [comment]
Looks good to me, thanks for contributing to mdn-browser-compat-data!

May I ask you to also update https://github.com/mdn/browser-compat-data/blob/master/api/Request.json#L722 accordingly as part of this?

**Comment by nhoizey** [comment]
@Elchi3 just added the second file, sorry, I didn't know there are two locations to update.

**Comment by nhoizey** [comment]
@Elchi3 also, @aarongustafson [told me it was added in Edge 14342](https://twitter.com/AaronGustafson/status/1026607533203451904), but I'm not sure how you deal with such version numbers for Edge. Would it be "14"?

**Comment by Elchi3** [comment]
Yes, the Edge team only wants to have versions like 13, 14, 15, 16, etc. represented here and not the more granular build numbers. See https://github.com/mdn/kumascript/pull/131#issuecomment-291992318.

14 sounds right to me. Thanks for asking around to get this info! :+1:

**Comment by nhoizey** [comment]
I added version 14 for Edge.

I didn't add Edge Mobile, because it seems it is based on Chromium on Android and webkit on iOS, so these are actually two different browsers.

**Pull request merged**
