### PR TITLE
IE11 doesn't support PageTransitionEvent.persisted

### PR DESCRIPTION
**Pull request by victor-homyakov**
Related StackOverflow question: https://stackoverflow.com/q/17432899/1235394

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by victor-homyakov** [comment]
The app I'm working on had a bug when user navigated back-forward and browsers used their back-forward cache. Initial fix for Safari was based on `pageshow` event and `PageTransitionEvent.persisted` property. But the fix didn't work for IE11 - it supports `pageshow` event, but doesn't support `persisted` property of the event.

**Comment by vinyldarkscratch** [comment]
Hey there, thanks for your PR!  From what I'm seeing here, `PageTransitionEvent` _does_ have the `persisted` property, but it's unreliable.  As such, I would recommend that we set the compatibility to `true`, with a note mentioning the workaround:

`The <code>persisted</code> property is known to be buggy in Internet Explorer.  It is advised to check if <code>window.performance.navigation.type == 2</code> as well.`

**Comment by victor-homyakov** [comment]
Maybe it's better to specify exact browser version? I've found corresponding MSDN page https://msdn.microsoft.com/en-us/windows/desktop/dn255067, it indicates that `persisted` is supported since IE11, if I deciphered the page properly.

```
"ie": {
  "version_added": "11",
  "notes": [
    "The <code>persisted</code> property is known to be buggy in Internet Explorer 11.",
    "It is advised to check if <code>window.performance.navigation.type == 2</code> as well."
  ]
}
```

is it OK?

**Comment by vinyldarkscratch** [comment]
I'd say that if it's only supported in IE 11, we can omit the version number from the notes, but yeah, looking good!  I'd also say, let's keep them as one note together, since it's the same topic?

**Comment by vinyldarkscratch** [comment]
Hey @victor-homyakov, do you plan to return to this PR?

**Comment by vinyldarkscratch** [comment]
Since there's been no response, I went ahead and superseded this PR.  Thanks for raising the issue!

**Comment by victor-homyakov** [comment]
Oops, sorry. I've completely forgotten about this PR and somehow missed notifications. Thank you!

**Pull request closed without merging**
