### PR TITLE
Web APIs: add DragEvent

### PR DESCRIPTION
**Pull request by caugner**
[DragEvent](https://developer.mozilla.org/docs/Web/API/DragEvent)

### CODE REVIEW

**Comment by caugner** [comment]
I have added `dataTransfer` with Chrome/Firefox compat data derived from source code, so this is ready to merge from my side.

**Comment by ddbeck** [comment]
Thanks for this PR, @caugner. Looks good, though it seems there's some data in [the MDN table for `dataTransfer`](https://developer.mozilla.org/en-US/docs/Web/API/DragEvent/dataTransfer#Browser_compatibility). Is there some reason not to include that data too?

**Comment by caugner** [comment]
Good catch, @ddbeck. I have just added the data in 5209e06f777139266a5f912b356b5d632f892859.

**Comment by ddbeck** [comment]
Great, thank you @caugner! 🎉

**Pull request merged**
