### PR TITLE
Intl.supportedValuesOf was added to node.js v18

### PR DESCRIPTION
**Pull request by gugu**
#### Summary

Intl.supportedValuesOf was added to node.js v18

### CODE REVIEW

**Review by gugu — COMMENTED** [review]
Correct node.js version

**Comment by queengooborg** [comment]
Hi @gugu, thank you for your PR, and welcome to BCD!

Could you provide supporting materials to validate your claim in this PR, such as test code and results, blog posts, documentation, etc.?

**Comment by gugu** [comment]
This method was added in v8 version 9.9: https://v8.dev/blog/v8-release-99#intl-enumeration
And node.js uses v8 10.1: https://nodejs.org/de/blog/announcements/v18-release-announce/#v8-10-1
Example:
```
Welcome to Node.js v18.12.0.
Type ".help" for more information.
> Intl.supportedValuesOf("timeZone").slice(0,2)
[ 'Africa/Abidjan', 'Africa/Accra' ]
```

**Review by queengooborg — APPROVED** [review]
Thank you, the Node.js article is a great help -- LGTM!

**Pull request merged**
