### PR TITLE
Chrome 69 added support for env()

### PR DESCRIPTION
**Pull request by freaktechnik**
https://developers.google.com/web/updates/2018/09/nic69#notch

### CODE REVIEW

**Comment by connorshea** [comment]
It’s not quite that simple, I don’t think. Only chrome for android supports it as far as I can tell?

**Comment by freaktechnik** [comment]
Desktop chrome doesn't mark `env()` as invalid, but I also don't think these env variables are particularly useful on desktop...

**Comment by jpmedley** [comment]
@Elchi3  Don't merge this yet. I'm getting clarification how this impacts desktop and webview.

**Comment by jpmedley** [comment]
Here's the scoop. This should be marked Android only for now. There eventually will be features that make env() useful on desktop. I know desktop doesn't mark it as invalid, but we're just trying to keep the noise down.

**Comment by freaktechnik** [comment]
Should it then also be disabled for desktop safari?

**Comment by jpmedley** [comment]
I don't know. That's no my company's product.

**Comment by jpmedley** [comment]
It looks like missing browser names report as null (rendered as '?'). (Am I interpreting the macro code correctly, @Elchi3 ?) The `chrome_android` and `webview_android` fields should be set to `false`, not removed completely. Please change.

**Comment by freaktechnik** [comment]
Why should they be set to false? From what I understand this is supported on android only? Do you mean to set chrome to false?

**Comment by Elchi3** [comment]
> It looks like missing browser names report as null (rendered as '?'). (Am I interpreting the macro code correctly, @Elchi3 ?) 

That's correct.

So, if I understand the conversation here correctly, we need to add "chrome: false", and this should be good to go.

**Comment by freaktechnik** [comment]
Thanks!

**Pull request merged**
