### PR TITLE
Changing Firefox support information to include Mac OSX support

### PR DESCRIPTION
**Pull request by chrisdavidmills**
I've included all of this in one PR, as it is a simple change — every bit of firefox support information has been included to include separate entries for Windows support, and Mac OSX support.

### CODE REVIEW

**Comment by teoli2003** [comment]
Support for a platform only is a case we have not addressed in the current schema, but we will have too. cc/ @Elchi3 

We have an issue opened for it: issue #474

**Comment by ddbeck** [comment]
Regardless of how this data is ultimately structured, I think it would be nice to see a move toward the "macOS" naming (at least for non-historical cases) as that's what more and more people will actually see on their systems.

**Comment by chrisdavidmills** [comment]
This is a good point, @ddbeck — I've not thought about this for years, and always used Mac OSX out of habit. I'll use macOS going forward.

**Comment by Elchi3** [comment]
I agree that an enhanced data structure for operating systems would be good. We don't have such a structure yet and #474 tracks that. For now and to land this, I think the proposed structure makes sense, we can later transform the multiple versions into something that deals with operating systems.

So, should we rename Mac OSX to macOS here? Looks good to me otherwise.

**Comment by chrisdavidmills** [comment]
Yup, sounds good to me. Updates made.

**Pull request merged**
