### PR TITLE
API: add SVGUnknownElement

### PR DESCRIPTION
**Pull request by caugner**
Sources:
1. Scalable Vector Graphics 2 specification:
   https://svgwg.org/svg2-draft/struct.html#InterfaceSVGUnknownElement
2. Chromium repository:
   https://github.com/chromium/chromium/blob/f18e79d901f56154f80eea1e2218544285e62623/third_party/WebKit/LayoutTests/external/wpt/svg/struct/UnknownElement/interface-expected.txt
3. Firefox bug tracker:
   https://bugzil.la/589640
   https://bugzil.la/840417
   https://bugzil.la/1239218
4. Firefox repository:
   https://github.com/mozilla/gecko-dev/blob/faeb9b7dddf16e5d3dc18c22f16b1106e4eed1b2/testing/web-platform/meta/svg/interfaces.html.ini#L122

### CODE REVIEW

**Comment by caugner** [comment]
I would argue that it doesn't hurt to add `<unknown>` to the BCD database:

* because it is still part of the current SVG 2 Draft (as of 12 June 2018),
* because it was temporarily implemented in Firefox (see above),
* because we can still remove it again later.

The general question I see here is how to handle deprecated features that are not / no longer implemented in any current browser version, with this being the special case of a feature that will always have been experimental, not (finally) standardized and not (intentionally) implemented either (provided that it is actually going to be removed) .

As stated above, I don't think it does any harm to keep that information. Moreover, I would even tend to not remove it later: If anybody ever comes across a feature like this in legacy or example code, the user may be happy to find a solid clue in BCD on where it comes from.

This user value might be further enhanced by actually recording spec data:

```json
{
  "status": {
    "spec": {
      "name": "svg",
      "version_added": "2",
      "version_removed": "2",
      "notes": "Was part of Editor's Draft, but removed in final version, see <a href='https://github.com/w3c/svgwg/issues/122'>GitHub w3c/svgwg issue 122</a>."
    }
}
```

**Comment by JeremiePat** [comment]
@caugner Okay, all very good points and I finally spotted what is really puzzling me:

`<unknown>` in itself hasn't been implemented in Firefox, only the `SVGUnknownElement` DOM API. So I would suggest to actually change the PR to add info under [`/api`](https://github.com/mdn/browser-compat-data/tree/master/api) for `SVGUnknownElement` which makes more sens.

For the `<unknown>` element itself I would suggest to at minimum wait for the next SVG2 CR that should be published this summer.

**Comment by caugner** [comment]
@JeremiePat Alright, I have now rewritten this PR to add `SVGUnknownElement` rather than `<unknown>`.

**Comment by JeremiePat** [comment]
Ok, LGTM :)

It can be merged as it is however I think it's safe to assume that support for Edge, IE and Safari (all platform) could be marked as `false`

**Comment by caugner** [comment]
Ok, I marked support for those as `false` now.

**Comment by Elchi3** [comment]
Thanks Claas and Jeremie :)

**Pull request merged**
