### PR TITLE
Update WebVR API compatibility

### PR DESCRIPTION
**Pull request by bershanskiy**
## Summary
 - Chrome 80 (desktop, Android, WebView) removed WebVR API:
   - [Chrome status](https://chromestatus.com/feature/4532810371039232)
   - `navigator.getVRDisplays` is `undefined` in Chrome 80
 - Edge 80 is based on Chrome 80, so it removed WebVR API too
   - `navigator.getVRDisplays` is `undefined` too
 - Safari never supported WebVR API, according to the BCD `navigator.getVRDisplays`

Note: Linter complains about Edge version `"80"` being invalid -- I'll add it in a follow-up PR (to be merged before this PR).

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Thanks for the PR!  We actually don’t have Edge 80 in our data yet, can we revert the changes to the Edge data?

**Comment by bershanskiy** [comment]
>  We actually don’t have Edge 80 in our data yet, can we revert the changes to the Edge data?

Yes, I know (I mentioned it in the comment). Edge 80 was *already* released (I have "Version 80.0.361.48 (Official build) (64-bit)") so I'd prefer to just add it to `browsers.json`, if possible. Weirdly enough, I see a lot of press coverage ([The Verge](https://www.theverge.com/2020/2/7/21127711/microsoft-new-edge-browser-arm64-release-surface-pro-x-download-features), [Windows Central](https://www.windowscentral.com/new-microsoft-edge-now-available-windows-10-arm-devices), [Engadget](https://www.engadget.com/2020/02/07/edge-chrome-80-arm64/), [Softpedia](https://news.softpedia.com/news/microsoft-edge-80-now-available-for-download-on-windows-and-mac-529134.shtml), and many others)) and an [official article about DevTools](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2019/12/devtools), but no official release notes or a blog post.

However, I'll remove Edge 80 data if you prefer so.

**Comment by vinyldarkscratch** [comment]
Sorry, I didn't realize Chrome/Edge 80 were released!  I'll get a PR going to update the browser data, then.  :wink:  (I'll mark this as "not ready" until the browser PR is merged!)

**Comment by bershanskiy** [comment]
Note to self: Chrome/Edge data added in #5680.

**Comment by vinyldarkscratch** [comment]
#5680 has now been merged, so this needs a quick rebase!

**Comment by bershanskiy** [comment]
@vinyldarkscratch 
>so this needs a quick rebase!

Done!

**Pull request merged**
