### PR TITLE
Adapt Document fullscreen events to new structure

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates the `fullscreenchange` and `fullscreenerror` events of the Document API to conform to the new style.  Part of work for #14578.

Content PR: https://github.com/mdn/content/pull/12926

### CODE REVIEW

**Comment by sideshowbarker** [comment]
So I see this entirely deletes `onfullscreenerror` and `onfullscreenchange` and doesn’t add anything. That’s intended, right?

**Comment by queengooborg** [comment]
> So I see this entirely deletes `onfullscreenerror` and `onfullscreenchange` and doesn’t add anything. That’s intended, right?

Yes, this intended as the existing `_event` properties cover all the data already!

**Comment by Elchi3** [comment]
> > So I see this entirely deletes `onfullscreenerror` and `onfullscreenchange` and doesn’t add anything. That’s intended, right?
> 
> Yes, this intended as the existing `_event` properties cover all the data already!

That's correct. However, we usually also add the spec_urls from the `on`-entries to the `_event` entries making it clear it's now the entry for both. See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#dom-events-eventname_event for the full guideline.

**Comment by queengooborg** [comment]
@Elchi3 The reason I hadn't updated the spec_url is because it is the same URL for both members!

**Comment by Elchi3** [comment]
Thanks @queengooborg, that makes sense then :)

**Pull request merged**
