### PR TITLE
Update Firefox versions for AnimationEvent API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects the real values for Firefox and Firefox Android for the `AnimationEvent` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/AnimationEvent

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

### CODE REVIEW

**Comment by foolip** [comment]
What are the events that use this interface? Should their data also be updated?

**Comment by queengooborg** [comment]
I'm not 100% positive what events are returning as `AnimationEvent`, but I'm pretty sure it's the `onanimation*` events.  Unfortunately though, I can't find any support for them prior to Firefox 54, prefixed or not.  I'll have to look into this more.

It appears that the original "6" came from the wiki migration, but looking through, Firefox 5 seems to match up with the data for the CSS `@keyframes` rule.

**Comment by foolip** [comment]
I guess this is more likely correct. Other entries that are marked Firefox 5:
```
css.properties.animation-delay (-moz- prefix)
css.properties.animation-direction (-moz- prefix)
css.properties.animation-duration (-moz- prefix)
css.properties.animation-fill-mode (-moz- prefix)
css.properties.animation-iteration-count (-moz- prefix)
css.properties.animation-name (-moz- prefix)
css.properties.animation-play-state (-moz- prefix)
css.properties.animation-timing-function (-moz- prefix)
css.properties.animation (-moz- prefix)
svg.attributes.style.class.animation_support
```

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/15262 as a consistency fix.

**Pull request merged**
