### PR TITLE
Drop the HTMLInputElement.p.moz* methods

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change drops the `mozGetFileNameArray()`, `mozSetFileNameArray()`, and `mozSetFileArray()` methods of `HTMLInputElement.` They’re not exposed to web content in any UAs — not even Gecko. See https://github.com/mdn/browser-compat-data/pull/6982#issuecomment-715895179

### CODE REVIEW

**Comment by evilpie** [comment]
These methods are marked as `[ChromeOnly]` so they should probably be marked as removed for Firefox as well.  https://searchfox.org/mozilla-central/source/dom/webidl/HTMLInputElement.webidl#157

**Comment by foolip** [comment]
@saschanaz should these be removed in https://github.com/mdn/browser-compat-data/pull/6931? Is the reason they're not because BCD says it's supported?

**Comment by saschanaz** [comment]
> @saschanaz should these be removed in #6931? Is the reason they're not because BCD says it's supported?

#6931 only covers things that only filled with explicit `false`. In this case there is a support from Firefox and there are some `null`s, so these are not covered there.

**Comment by foolip** [comment]
I see, thanks @saschanaz!

**Comment by foolip** [comment]
@sideshowbarker do you want to just remove these entries instead?

**Comment by sideshowbarker** [comment]
> @sideshowbarker do you want to just remove these entries instead?

Yes — I’ve now amended the commit here to do that

**Comment by foolip** [comment]
Passing this along to @chrisdavidmills. These two pages need to be redirected to the parent page:
https://developer.mozilla.org/docs/Web/API/HTMLInputElement/mozSetFileNameArray
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/mozSetFileNameArray

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/mozSetFileArray didn't exist.

**Comment by chrisdavidmills** [comment]
@foolip redirects put in place.

**Review by foolip — APPROVED** [review]

**Pull request merged**
