### PR TITLE
Update readme for 1.0.0

### PR DESCRIPTION
**Pull request by Elchi3**
We're planning to release 1.0.0 tomorrow. It is a soft launch and comes with no breaking changes.
The idea of having 1.0.0 now is that we actually start to guarantee the stability of the data format and communicate breaking changes using semantic versioning going forward. There are also no legacy compat data tables in the MDN wiki anymore, so to celebrate that it is time for a 1.0, too. :)

This PR updates the readme to remove outdated statements.

Do we need to prepare anything else for 1.0.0? Please let me know if you can think of anything.

### CODE REVIEW

**Comment by ddbeck** [comment]
The [publishing](https://github.com/mdn/browser-compat-data/blob/master/docs/publishing.md) doc may need updating too, though I imagine it might be easier to write after the release is done.

Also, in the release notes, I'd like there to be a note that mentions the 1.0 release is a non-breaking (for reasons unrelated to this project, I've learned that SemVer is not as widely understood as I had previously guessed).

Otherwise, I'm very pleased with this development. Congrats!

**Comment by jpmedley** [comment]
>we actually start to guarantee the stability of the data format and communicate breaking changes using semantic versioning

Will the weekly updates be 1.0.1, 1.0.2, etc.?

**Comment by Elchi3** [comment]
> Will the weekly updates be 1.0.1, 1.0.2, etc.?

Yes, that is correct. Patch versions will continue as long as we only update data and not the data structures.

**Comment by vinyldarkscratch** [comment]
> The [publishing](https://github.com/mdn/browser-compat-data/blob/master/docs/publishing.md) doc may need updating too, though I imagine it might be easier to write after the release is done.

I agree with this -- since we're now going to be dealing with major/minor versions as well, we should certainly update the publishing guide to reflect this.

This has also got me thinking: would a breaking change just be any change to the schema or the way the data is loaded (such as changes to `index.js`)?  I ask because I'm wondering if linter/script changes would also qualify as a change requiring a new major or minor bump.

**Comment by Elchi3** [comment]
I'll update the publishing guide later.

> would we want to bump major/minor versions based upon only changes to the schema or the way the data is loaded (such as changes to index.js)? 

Yes, this is the idea. Basically whenever data consumers are affected (in terms of the data structure/schema) we need to bump the minor (for non-breaking changes) or major (for breaking changes) version.

> I ask because I'm wondering if linter/script changes would also qualify as a change requiring a new major or minor bump.

No, usually these are helping to update data (en masse or not), but they are not breaking our external interface to consumers and thus I think we would continue to use patch versions like we've done before when such things happened.

**Pull request merged**
