### PR TITLE
Add spec URLs for BluetoothRemoteGattCharacteristic methods

### PR DESCRIPTION
**Pull request by cdgarren**
#### Summary

Add spec URLs for the writeValueWithResponse and writeValueWithoutResponse methods that were added to MDN [here](https://github.com/mdn/content/pull/6436)

### CODE REVIEW

**Review by sideshowbarker — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Deployment of commits to the MDN production site has unfortunately been stalled since June 23rd, so the https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValueWithResponse and https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic/writeValueWithoutResponse are going to be 404 until the https://github.com/mdn/content/pull/6436 change makes it way to production.

So I’ve approved this for merging to main, but marked it as Draft so that we can hold off on merging it until the MDN URLs aren’t 404s any longer.

**Comment by cdgarren** [comment]
Thanks for the heads up.

**Comment by cdgarren** [comment]
@sideshowbarker It looks like the related commit in MDN has been deployed, so is this ready to merge?

**Comment by sideshowbarker** [comment]
> @sideshowbarker It looks like the related commit in MDN has been deployed, so is this ready to merge?

Yup — now merged

And congrats on landing your first BCD change — welcome aboard here 🎉

**Pull request merged**
