### PR TITLE
Mark offsetX and offsetY as not experimental

### PR DESCRIPTION
**Pull request by Timmmm**
#### Summary
Mark offsetX and offsetY as not experimental.

#### Test results and supporting details
These are almost universally supported.

#### Related issues
https://github.com/mdn/content/issues/10120

### CODE REVIEW

**Comment by hamishwillee** [comment]
@ddbeck Can you please look at this one? It seems obviously correct to me.

**Comment by Timmmm** [comment]
I think there's pageX/Y too that I missed but I'll leave someone else to do that.

**Review by ddbeck — APPROVED** [review]
Yes, this definitely clears the bar to be non-experimental. Also, I see it's your first PR to the project—welcome and thank you! 🎉

**Comment by ddbeck** [comment]
@hamishwillee merged! I'd welcome a PR making the changes to content too.

**Pull request merged**
