### PR TITLE
lint: add consistency check

### PR DESCRIPTION
**Pull request by caugner**
This check verifies that if a feature is declared not supported by a browser, all sub-features must also be  declared not supported by that browser.

This currently affects several files, hence the failing check:
https://gist.github.com/caugner/9d562048122552865312e374e63e8f5a#file-yarn-run-lint-log-L678

# Examples

## Example 1: [AudioBufferSourceNode](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode):

Checker says:
image

image

IE has no "Basic support", so `onended` + `stop` cannot be supported either (but are set to `null` here).

## Example 2: [Crypto](https://developer.mozilla.org/en-US/docs/Web/API/Crypto)

Checker says:
image

image

Safari for iOS has no "Basic support", but `getRandomValues` is supported? That must be a mistake.

### CODE REVIEW

**Comment by connorshea** [comment]
The main problem I see with this is the following case:

- Feature 1 has Subfeature A, B, C
- Subfeatures A, B, and C are all supported in Safari
- Because all the subfeatures are supported, feature 1 is marked as supported in Safari.
- The spec gets an update a few years later, now there's Subfeature D. Subfeature D is not supported in Safari yet, so adding it would cause this check to fail. Should Feature 1 be marked as unsupported again?

I'm not sure if this is a valid enough issue to block the lint check, but I wanted to bring it up.

**Comment by caugner** [comment]
> The main problem I see with this is the following case:

In your case the (parent) feature is supported, whereas a (child) subfeature is not supported. That's totally fine and the checker won't reject that.

The checker rejects if the (parent) feature is not supported (i.e. no "basic support), but a (child) subfeature is not marked as "not supported" (e.g. either `null` or even `true`).

**Comment by ExE-Boss** [comment]
I’m fixing the `Crypto` case in #1840.

**Comment by caugner** [comment]
I have added a fixer now that sets `version_added: false` for a browser in a sub-feature if (and only if) the parent feature is not supported by the browser and the sub-feature currently has `version_added: null` or no entry for this browser.

This reduces the number of files with problems from 128 to 40:

```
Problems in 40 files:
  Found 1 inconsistent feature(s) in api/CanvasRenderingContext2D.json:
  → 1 × isPointInStroke [api.CanvasRenderingContext2D.isPointInStroke]:
    → No support in edge, but this is not declared for sub-feature(s): Path_parameter
  Found 1 inconsistent feature(s) in api/Console.json:
  → 1 × exception [api.Console.exception]:
    → No support in chrome, but this is not declared for sub-feature(s): substitution_strings
  Found 1 inconsistent feature(s) in api/ConstantSourceNode.json:
  → 3 × ConstantSourceNode [api.ConstantSourceNode]:
    → No support in chrome, but this is not declared for sub-feature(s): offset, onended, start, stop
    → No support in webview_android, but this is not declared for sub-feature(s): onended, start, stop
    → No support in chrome_android, but this is not declared for sub-feature(s): onended, start, stop
  Found 1 inconsistent feature(s) in api/Crypto.json:
  → 1 × Crypto [api.Crypto]:
    → No support in safari_ios, but this is not declared for sub-feature(s): getRandomValues
  Found 1 inconsistent feature(s) in api/DOMTokenList.json:
  → 1 × replace [api.DOMTokenList.replace]:
    → No support in samsunginternet_android, but this is not declared for sub-feature(s): boolean_value
  Found 1 inconsistent feature(s) in api/DocumentTimeline.json:
  → 2 × DocumentTimeline [api.DocumentTimeline]:
    → No support in firefox, but this is not declared for sub-feature(s): DocumentTimeline
    → No support in firefox_android, but this is not declared for sub-feature(s): DocumentTimeline
  Found 1 inconsistent feature(s) in api/GamepadHapticActuator.json:
  → 1 × GamepadHapticActuator [api.GamepadHapticActuator]:
    → No support in edge, but this is not declared for sub-feature(s): pulse, type
  Found 1 inconsistent feature(s) in api/GamepadPose.json:
  → 1 × GamepadPose [api.GamepadPose]:
    → No support in edge, but this is not declared for sub-feature(s): angularAcceleration, angularVelocity, hasOrientation, hasPosition, linearAcceleration, linearVelocity, orientation, position
  Found 1 inconsistent feature(s) in api/ImageBitmap.json:
  → 1 × ImageBitmap [api.ImageBitmap]:
    → No support in webview_android, but this is not declared for sub-feature(s): close
  Found 1 inconsistent feature(s) in api/MediaDevices.json:
  → 2 × MediaDevices [api.MediaDevices]:
    → No support in safari, but this is not declared for sub-feature(s): getSupportedConstraints, getUserMedia
    → No support in safari_ios, but this is not declared for sub-feature(s): getSupportedConstraints, getUserMedia
  Found 1 inconsistent feature(s) in api/MediaStream.json:
  → 1 × MediaStream [api.MediaStream]:
    → No support in opera, but this is not declared for sub-feature(s): MediaStream, getAudioTracks, getTracks, getVideoTracks, removeTrack
  Found 1 inconsistent feature(s) in api/OffscreenCanvas.json:
  → 1 × OffscreenCanvas [api.OffscreenCanvas]:
    → No support in samsunginternet_android, but this is not declared for sub-feature(s): OffscreenCanvas
  Found 1 inconsistent feature(s) in api/Path2D.json:
  → 1 × Path2D [api.Path2D]:
    → No support in safari_ios, but this is not declared for sub-feature(s): addPath
  Found 1 inconsistent feature(s) in api/PerformanceObserver.json:
  → 1 × PerformanceObserver [api.PerformanceObserver]:
    → No support in webview_android, but this is not declared for sub-feature(s): worker_support
  Found 1 inconsistent feature(s) in api/PictureInPicture.json:
  → 3 × PictureInPicture [api.PictureInPicture]:
    → No support in webview_android, but this is not declared for sub-feature(s): height, onresize, width
    → No support in chrome_android, but this is not declared for sub-feature(s): height, onresize, width
    → No support in opera_android, but this is not declared for sub-feature(s): height, onresize, width
  Found 1 inconsistent feature(s) in api/RTCRtpReceiver.json:
  → 2 × RTCRtpReceiver [api.RTCRtpReceiver]:
    → No support in opera, but this is not declared for sub-feature(s): getStats
    → No support in opera_android, but this is not declared for sub-feature(s): getStats
  Found 2 inconsistent feature(s) in api/Request.json:
  → 2 × Request [api.Request]:
    → No support in safari, but this is not declared for sub-feature(s): Request, cache
    → No support in safari_ios, but this is not declared for sub-feature(s): Request
  → 1 × cache [api.Request.cache]:
    → No support in webview_android, but this is not declared for sub-feature(s): only_if_cached
  Found 1 inconsistent feature(s) in api/SourceBuffer.json:
  → 1 × SourceBuffer [api.SourceBuffer]:
    → No support in firefox_android, but this is not declared for sub-feature(s): appendBufferAsync, removeAsync
  Found 1 inconsistent feature(s) in api/TextMetrics.json:
  → 1 × TextMetrics [api.TextMetrics]:
    → No support in safari_ios, but this is not declared for sub-feature(s): width
  Found 1 inconsistent feature(s) in api/URL.json:
  → 1 × URL [api.URL]:
    → No support in ie, but this is not declared for sub-feature(s): createObjectURL, revokeObjectURL
  Found 1 inconsistent feature(s) in css/at-rules/viewport.json:
  → 2 × viewport [css.at-rules.viewport]:
    → No support in safari, but this is not declared for sub-feature(s): viewport-fit
    → No support in safari_ios, but this is not declared for sub-feature(s): viewport-fit
  Found 1 inconsistent feature(s) in css/properties/all.json:
  → 2 × all [css.properties.all]:
    → No support in safari, but this is not declared for sub-feature(s): revert
    → No support in safari_ios, but this is not declared for sub-feature(s): revert
  Found 1 inconsistent feature(s) in css/properties/clip-path.json:
  → 3 × clip-path [css.properties.clip-path]:
    → No support in edge, but this is not declared for sub-feature(s): svg
    → No support in edge_mobile, but this is not declared for sub-feature(s): svg
    → No support in ie, but this is not declared for sub-feature(s): svg
  Found 1 inconsistent feature(s) in css/properties/touch-action.json:
  → 1 × touch-action [css.properties.touch-action]:
    → No support in safari_ios, but this is not declared for sub-feature(s): manipulation
  Found 1 inconsistent feature(s) in css/properties/word-break.json:
  → 1 × word-break [css.properties.word-break]:
    → No support in opera_android, but this is not declared for sub-feature(s): break-word
  Found 1 inconsistent feature(s) in css/properties/word-spacing.json:
  → 1 × word-spacing [css.properties.word-spacing]:
    → No support in firefox_android, but this is not declared for sub-feature(s): percentages
  Found 1 inconsistent feature(s) in css/selectors/scope.json:
  → 2 × scope [css.selectors.scope]:
    → No support in webview_android, but this is not declared for sub-feature(s): dom_api
    → No support in chrome, but this is not declared for sub-feature(s): dom_api
  Found 1 inconsistent feature(s) in html/elements/menuitem.json:
  → 1 × menuitem [html.elements.menuitem]:
    → No support in opera, but this is not declared for sub-feature(s): disabled
  Found 1 inconsistent feature(s) in http/headers/referrer-policy.json:
  → 2 × Referrer-Policy [http.headers.Referrer-Policy]:
    → No support in opera, but this is not declared for sub-feature(s): same-origin, strict-origin, strict-origin-when-cross-origin
    → No support in opera_android, but this is not declared for sub-feature(s): same-origin, strict-origin, strict-origin-when-cross-origin
  Found 1 inconsistent feature(s) in javascript/builtins/Atomics.json:
  → 1 × Atomics [javascript.builtins.Atomics]:
    → No support in edge, but this is not declared for sub-feature(s): add, and, compareExchange, exchange, isLockFree, load, or, store, sub, wait, wake, xor
  Found 3 inconsistent feature(s) in javascript/builtins/Intl.json:
  → 1 × Intl [javascript.builtins.Intl]:
    → No support in webview_android, but this is not declared for sub-feature(s): NumberFormat, PluralRules
  → 1 × Collator [javascript.builtins.Intl.Collator]:
    → No support in webview_android, but this is not declared for sub-feature(s): caseFirst
  → 1 × DateTimeFormat [javascript.builtins.Intl.DateTimeFormat]:
    → No support in webview_android, but this is not declared for sub-feature(s): formatToParts
  Found 1 inconsistent feature(s) in javascript/builtins/SharedArrayBuffer.json:
  → 1 × SharedArrayBuffer [javascript.builtins.SharedArrayBuffer]:
    → No support in edge, but this is not declared for sub-feature(s): byteLength, slice
  Found 1 inconsistent feature(s) in javascript/statements.json:
  → 1 × import [javascript.statements.import]:
    → No support in webview_android, but this is not declared for sub-feature(s): dynamic_import
  Found 1 inconsistent feature(s) in mathml/elements/maction.json:
  → 1 × maction [mathml.elements.maction]:
    → No support in safari, but this is not declared for sub-feature(s): actiontype, href, mathbackground, mathcolor
  Found 1 inconsistent feature(s) in mathml/elements/mo.json:
  → 1 × mo [mathml.elements.mo]:
    → No support in safari_ios, but this is not declared for sub-feature(s): stretchy
  Found 1 inconsistent feature(s) in mathml/elements/mphantom.json:
  → 1 × mphantom [mathml.elements.mphantom]:
    → No support in safari_ios, but this is not declared for sub-feature(s): mathbackground
  Found 1 inconsistent feature(s) in mathml/elements/mroot.json:
  → 1 × mroot [mathml.elements.mroot]:
    → No support in safari_ios, but this is not declared for sub-feature(s): mathbackground, mathcolor
  Found 1 inconsistent feature(s) in mathml/elements/mrow.json:
  → 1 × mrow [mathml.elements.mrow]:
    → No support in safari_ios, but this is not declared for sub-feature(s): mathbackground, mathcolor
  Found 1 inconsistent feature(s) in mathml/elements/msqrt.json:
  → 1 × msqrt [mathml.elements.msqrt]:
    → No support in safari, but this is not declared for sub-feature(s): mathbackground, mathcolor
  Found 1 inconsistent feature(s) in webextensions/manifest/incognito.json:
  → 1 × incognito [webextensions.manifest.incognito]:
    → No support in edge, but this is not declared for sub-feature(s): split, not_allowed
```

**Comment by vinyldarkscratch** [comment]
Playing around with a fork of this branch, I pulled changes from `master` and fixed the conflicting file of `api/PaymentRequest.json`.  When running `npm run test` on the updated version, it looks like there's some more files that face problems, but there's also some that are now fixed:

# api

>   Found 1 inconsistent feature(s) in api/**KeyboardLayoutMap.json**:
>   → 1 × **KeyboardLayoutMap** [api.KeyboardLayoutMap]: 
>     → No support in opera_android, but this is not declared for sub-feature(s): entries, forEach, get, has, keys, values

➡️ ❌ KeyboardLayoutMap is declared as unsupported on Opera Android, but all of its sub-features (except "size") are supported since version 56?

>  Found 1 inconsistent feature(s) in api/**PaymentRequest.json**:
>   → 4 × **PaymentRequest** [api.PaymentRequest]: 
>     → No support in ie, but this is not declared for sub-feature(s): id
>     → No support in opera, but this is not declared for sub-feature(s): id
>     → No support in opera_android, but this is not declared for sub-feature(s): id
>     → No support in webview_android, but this is not declared for sub-feature(s): id

➡️ 🕐 Easy fix.  😛

> api/**URL.json**

➡️ ✅ File is now fixed.

# mathml

> mathml/elements/**maction.json**

➡️ ✅ File is now fixed.

> mathml/elements/**msqrt.json**

➡️ ✅ File is now fixed.

I'm working on appropriate changes and will send a PR to your fork when complete, @caugner, or if prefered open a new PR on this repo.  :wink:

**Comment by ExE-Boss** [comment]
(In reply to @vinyldarkscratch from https://github.com/mdn/browser-compat-data/pull/2463#issuecomment-424255012)
> I'm working on appropriate changes and will send a PR to your fork when complete, @caugner, or if prefered open a new PR on this repo. 😉

Or you know, just rebase this on master once the above issues are fixed.

**Comment by vinyldarkscratch** [comment]
Something just came to mind.  As this consistency check is determining, browsers must have basic support for a feature before they can support any sub-features.  Wouldn't that also imply that the `version_added` for a sub-feature should be >= the `version_added` for a basic feature?  Otherwise, we'd be implying that a sub-feature had been implemented before a basic feature.

**Comment by caugner** [comment]
> Wouldn't that also imply that the version_added for a sub-feature should be >= the version_added for a basic feature?

@vinyldarkscratch That makes sense to me.

**Comment by caugner** [comment]
Closing in favor of #2875.

**Pull request closed without merging**
