### PR TITLE
Samsung Internet doesn't support Contact Picker API

### PR DESCRIPTION
**Pull request by Elchi3**
Fix https://github.com/mdn/browser-compat-data/issues/19998

### CODE REVIEW

**Comment by queengooborg** [comment]
Unfortunately, in Samsung Internet, the APIs and properties (ex. `navigator.contacts`) are exposed.  When attempting to use the contact picker using the [demo linked in the issue](https://contact-picker.glitch.me/), however, I get a TypeError that reads "Unable to open a contact selector".  This seems like a case of "exposed but has no effect".

**Comment by Elchi3** [comment]
So, do I need to add "exposed but has no effect" as a note? I think `version_added: false` still seems appropriate here as the feature isn't usable.

**Comment by queengooborg** [comment]
Setting Samsung Internet to `false` seems good to me in this case, yeah!  But we should definitely add the note to make sure that consumers don't assume our data is false and it's actually supported.

**Comment by bam** [comment]
Recently version 22 of Samsung Internet has been released and there is no support at all, they removed it!

**Comment by Elchi3** [comment]
> Recently version 22 of Samsung Internet has been released and there is no support at all, they removed it!

Thanks, this PR depends on https://github.com/mdn/browser-compat-data/pull/20405 (it adds Samsung version 22).

**Comment by Elchi3** [comment]
Updated to say that support was removed in version 22.0 :)

**Comment by queengooborg** [comment]
Should we also add a note stating that it was exposed but had no effect due to the bug?

**Comment by Elchi3** [comment]
> Should we also add a note stating that it was exposed but had no effect due to the bug?

Added.

**Review by queengooborg — APPROVED** [review]

**Pull request merged**
