### PR TITLE
SubmitEvent added to Firefox 75

### PR DESCRIPTION
**Pull request by a2sheppy**
Add `SubmitEvent` to Firefox 75
This interface is part of the HTML DOM, and is used to represent
form submit events. It has been added in Firefox 75.

Sources:
* https://html.spec.whatwg.org/#submitevent
* https://bugzilla.mozilla.org/show_bug.cgi?id=1588715
* https://chromestatus.com/features#submitevent
* https://bugs.webkit.org/show_bug.cgi?id=202978

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hey @a2sheppy, do you plan on coming back to this PR?

**Comment by a2sheppy** [comment]
Well.. how the hell did I do that? :) Let me look at it, thanks...

**Comment by Elchi3** [comment]
This has now been added in https://github.com/mdn/browser-compat-data/pull/5998 but that PR didn't know about Firefox 75. Can you open a new PR @a2sheppy ?

**Comment by Elchi3** [comment]
No answer here in weeks, I've opened a new PR https://github.com/mdn/browser-compat-data/pull/6195

**Comment by a2sheppy** [comment]
Hm, sorry about that. Thought I had done that already. :(

**Pull request closed without merging**
