### PR TITLE
Update spec URL for ArrayBuffer: transfer

### PR DESCRIPTION
**Pull request by sideshowbarker**

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
It appears that the actual link **is** what's already there -- both link to the same location, but if you click the chainlinks, it links back to the old URL.  So, I think this is fine as it is?

**Comment by sideshowbarker** [comment]
The problem with that `https://github.com/domenic/proposal-arraybuffer-transfer/#arraybufferprototypetransfer` URL is that if you inspect the DOM of https://github.com/domenic/proposal-arraybuffer-transfer/ — or use `document.querySelector('#arraybufferprototypetransfer')` to check it — you’ll find there’s not actually any `arraybufferprototypetransfer` ID value in that document. Instead, there’s a `user-content-arraybufferprototypetransfer` ID value.

(That seems to be the case for all such headings/IDs in GitHub README files — GitHub generates the actual IDs with that `user-content-` prefix and then has some magic for scrolling you to the right place for that anchor even with the `user-content-` prefix omitted.)

Anyway, the context for this change is, without that `user-content-` prefix part included, if you try to do automated/programmatic checking/confirmation of the existence of that anchor/ID in the document, that checking will fail.

And the further context is that I’ve been writing a tool for doing exactly that kind of check, across the entirety of MDN — it can check all spec URLs in all MDN articles to confirm whether they’re broken; that is, is checks all the IDs from the fragment parts of the spec URLs to confirm whether the cited spec documents actually contain the given ID value. (And it does it not be checking the markup source of the document, but instead by actually parsing and loading the document and running its scripts — which is necessary because in some (many) spec documents, the anchors/IDs are dynamically generated rather than being hardcoded into the static source of the document.)

**Comment by vinyldarkscratch** [comment]
I was talking about this with Chris in person earlier, and in the end, it wouldn’t really make a difference to the end user which one is used — it’s just the machine/script end where it matters.  However, I’m wondering if maybe this would be classified as something that needs to be updated in the script rather than BCD.  From what it looks like, any anchor in GitHub rendered Markdown has the `user-content-` prefix in the ID, although its `href` attribute is accurate.

I’m still leaning towards keeping the URL the way it is (it’s the official URL generated by GitHub, and as such has less of a chance of breaking if GitHub changes the `user-content-` prefix in the ID), and suggesting that the script to check the MDN URLs automatically adds the prefix (or checks the `href` attribute).  However, I’m not strong on this, so maybe @Elchi3 would like to comment on this?

**Comment by sideshowbarker** [comment]
> I’m still leaning towards keeping the URL the way it is (it’s the official URL generated by GitHub, and as such has less of a chance of breaking if GitHub changes the `user-content-` prefix in the ID), and suggesting that the script to check the MDN URLs automatically adds the prefix (or checks the `href` attribute).

That makes sense. I’m happy to just update the script to do it that way. I’ve anyway only run into two cases where an MDN article needs to cite a URL for a document that’s served from GitHub this way. So it’s very much a corner case.

>  However, I’m not strong on this, so maybe @Elchi3 would like to comment on this?

OK, I’ll wait to see what @Elchi3 thinks

**Comment by Elchi3** [comment]
I think the link works, and so there is no need to update this. 

(aside: it seems that checking for ID presence will be a thing of the past anyway once https://chromestatus.com/feature/4733392803332096 is reality / a de-facto standard.)

**Comment by sideshowbarker** [comment]
> I think the link works, and so there is no need to update this.
> 
> (aside: it seems that checking for ID presence will be a thing of the past anyway once https://chromestatus.com/feature/4733392803332096 is reality / a de-facto standard.)

It seems that spec might have quite a long way to go yet before it has a chance of ever getting cross-platform support. https://github.com/mozilla/standards-positions/issues/194#issuecomment-568581041 itemizes some of the significant issues that it has.

**Pull request closed without merging**
