### PR TITLE
removing mozbrowser API features from HTMLIFrameElement

### PR DESCRIPTION
**Pull request by chrisdavidmills**
As per

https://bugzilla.mozilla.org/show_bug.cgi?id=1503070

### CODE REVIEW

**Comment by Elchi3** [comment]
The data update looks fine to me, thanks Chris. I wonder, though, if we shouldn't rip out this Browser API stuff altogether.

I think our iframe docs are quite clumsy due to the browser API features (this isn't even a web API, right?). Should we move the Browser API stuff elsewhere? It looks rather confusing to me as a web developer.

**Comment by chrisdavidmills** [comment]
So, remove all the BCD entries, then on the actual pages just put in a really simple compat notice along the lines of "Supported since Firefox 47, only in privileged code."

And the move all the proprietary method pages belowhttps://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Chrome/API/Browser_API so they don't interfere with the main HTMLIFrameElement pages?

**Comment by Elchi3** [comment]
Yes, exactly. Out of the way from the Web/ docs and no compat table. Maybe a banner or something for the Firefox versions (this isn't supported anywhere else and very likely will never be).

**Comment by chrisdavidmills** [comment]
OK, data updated — moz browser features removed

**Comment by ExE-Boss** [comment]
[Bug&nbsp;1318532](https://bugzilla.mozilla.org/show_bug.cgi?id=1318532) intends to expose this to WebExtensions.

**Comment by chrisdavidmills** [comment]
> Bug 1318532 intends to expose this to WebExtensions.

Yup, but that bug is stalled, and doesn't look like it's going anywhere anytime soon. Plus the bug I referenced at the start gets rid of a load of the functionality from Gecko.

If this was exposed as a proper web extension API, then we'd probably put it in there, and set the BCD up differently.

**Pull request merged**
