### PR TITLE
Add spec_url to html attributes

### PR DESCRIPTION
**Pull request by teoli2003**
Most html attributes haven't yet the spec_url.

This fix some of them (those that I need ;-) ) – there is a lot of work left.

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
I think we need @Elchi3 to also weigh in on this. In general, for any feature that doesn’t have an mdn_url, it’s not clear to me what the concrete benefits are to adding a spec_url for it relative to the costs.

The maintenance costs for spec_url values are not insignificant. Specs can and do change IDs, and when that happens, the spec_url values can break.

When a feature has an mdn_url, the benefit of having a spec_url is clear: The MDN article needs the spec_url in order to populate the Specifications section of the article.

But when a feature doesn’t have an mdn_url, it’s not clear to me what concrete use cases there are for adding a spec_url for it.

Certainly I can say that the BCD-consuming tools I maintain don’t do anything for feature with spec_url values unless the features also have mdn_url values.

**Comment by sideshowbarker** [comment]
Another cost of adding spec_url values that I should have mentioned is the cost of reviewing them. I’m  personally super enthusiastic about reviewing spec_url values for the cases of features that also have mdn_url values. But I can’t say the same at all about reviewing spec_url values for features that don’t have mdn_url values.

caniuse is the one place I can think of that might do something with spec_url values even if they don’t have mdn_url values. And even in that case, I don’t think caniuse has started exposing spec URLs for anything yet. And even if/when it does, I’m not sure that on its own would have compelling enough value to merit the costs of putting spec_url values for anything for which MDN isn’t also exposing a spec URL,

**Comment by Elchi3** [comment]
@teoli2003 can you explain your motivation for adding these?

It certainly isn't disallowed to add them. There is no lint that requires spec_url and mdn_url to appear together only and I think that's okay. For some things we haven't written docs and so no mdn_url is present yet.

I guess a good question is whether html attributes would deserve their own pages under their HTML element which would then give you mdn_urls :)

**Comment by teoli2003** [comment]
The reason why I opened this PR is mdn/content#6333 where I am replacing _existing_ compat table in _existing_ HTML attributes pages.

I agree that the real question is do we want to have HTML/attributes/xyz pages. I've started to study this and will open a conversation about these in mdn/content. I plan to be able to start it later this week. 

Meanwhile, I think we can just keep both this PR and mdn/content#6333 open. (Or we can close them, and I eventually reopen them if the result of the conversation leads to both PR to become valid)

**Comment by ddbeck** [comment]
Setting this as not ready. I know people are taking a lot of holiday right now, so if there's no further news on this by, say, August, we can close this and reopen when it's relevant again.

**Comment by Elchi3** [comment]
Closing this for now.

**Pull request closed without merging**
