### PR TITLE
Add WebGL2 Compat Status to Certain Functions.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by Elchi3** [comment]
So this updates the tables on [WebGLRenderingContext.uniformMatrix](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/uniformMatrix) but there is also [WebGL2RenderingContext.uniformMatrix](https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/uniformMatrix) for WebGL2.

I guess this change belongs in the WebGL2RenderingContext compat file.

**Comment by jpmedley** [comment]
Yes. This is so I can be consistent [pages like this](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData). There are already close to 30 properties done like this.

**Comment by Elchi3** [comment]
> Yes. This is so I can be consistent pages like this. There are already close to 30 properties done like this.

Okay that makes sense to me.

I just noticed that you are adding empty strings. In the current schema, `null` is used if compat is unknown. Looking at the other entries, we have added `false` for WebGL2 status in other browsers. Please change the empty strings to `false`.

**Comment by jpmedley** [comment]
Are you sure? `false` implies I know for sure that those browsers aren't supported. `null` is more appropriate because I really don't know.

**Comment by Elchi3** [comment]
Generally I would have recommended to go with `null`. 
However, in this case, I'm pretty sure and it would also be consistent with the other "WebGL2" entries.

Actually, this is the what we have elsewhere: 
 ```
   "WebGL2": {
      "Android": {
        "support": false
      },
      "Chrome": {
        "support": "56"
      },
      "Chrome for Android": {
        "support": false
      },
      "Edge": {
        "support": false
      },
      "Edge Mobile": {
        "support": true
      },
      "Firefox": {
        "support": "51.0"
      },
      "Firefox for Android": {
        "support": "51.0"
      },
      "Internet Explorer": {
        "support": false
      },
      "IE Mobile": {
        "support": false
      },
      "Opera": {
        "support": "43"
      },
      "Opera Mobile": {
        "support": false
      },
      "Safari": {
        "support": false
      },
      "Safari Mobile": {
        "support": false
      },
      "Servo": {
        "support": false
      },
      "status": {
        "experimental": true,
        "standardized": true,
        "stable": true,
        "obsolete": false
      }
    }
},
```
I think I would expect yours to be this: (Firefox 51, Opera 43, Chrome 56, mobile Chromes 58, rest false)

```
"WebGL2": {
      "Android Webview": {
        "support": "58"
      },
      "Chrome": {
        "support": "56"
      },
      "Chrome for Android": {
        "support": "58"
      },
      "Edge": {
        "support": false
      },
      "Edge Mobile": {
        "support": false
      },
      "Firefox": {
        "support": "51.0"
      },
      "Firefox for Android": {
        "support": "51.0"
      },
      "Internet Explorer": {
        "support": false
      },
      "IE Mobile": {
        "support": false
      },
      "Opera": {
        "support": "43"
      },
      "Opera Mobile": {
        "support": false
      },
      "Safari": {
        "support": false
      },
      "Safari Mobile": {
        "support": false
      },
      "Servo": {
        "support": false
},
```

**Comment by jpmedley** [comment]
It's still a guess, though.

**Comment by Elchi3** [comment]
I think caniuse backs that guess, but I have no strong feeling. Just not empty string and 51 for the Firefoxes.

**Comment by jpmedley** [comment]
Change made. PTAL

**Pull request merged**
