### PR TITLE
Fixes test/lint.js for Windows

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by Elchi3** [comment]
Can someone with a Windows OS review this? Maybe @SebastianZ?

**Comment by SebastianZ** [comment]
> Can someone with a Windows OS review this? Maybe @SebastianZ?

I don't have much time lately to test, but I'll try. How to run the tests?

Sebastian

**Comment by yfdyh000** [comment]
@SebastianZ `npm run lint`

**Comment by SebastianZ** [comment]
Getting an error "Cannot find module 'ajv'". Installing it via `npm install -g ajv` didn't help. Any ideas?

Sebastian

**Comment by yfdyh000** [comment]
Has run `npm install`? `ajv` in `devDependencies`.

**Comment by SebastianZ** [comment]
Sorry for the long delay! I've managed to install ajv, just installed it locally instead of globally, i.e. left out the `-g` parameter on install.

I have to say, on my Windows 10 it doesn't make a difference with or without the patch, all tests pass for me and I see 'OK' on the command line.

Sebastian

**Comment by Elchi3** [comment]
Thanks a lot for testing Sebastian!
I'm also not seeing any difference with Ubuntu here. Our .editorconfig says "end_of_line = lf" btw. 
I think we could merge this, so that @yfdyh000's problems are fixed.

**Pull request merged**
