### PR TITLE
Add consistent copyright notice + use strict to all JS+TS files

### LINKED ISSUE #5879: Remove copyright notices from source files
Some (but not all) of the project source files contain a notice [like this](https://github.com/mdn/browser-compat-data/blob/master/scripts/migrations/001-sort-features.js#L2):

```javascript
/* Any copyright is dedicated to the Public Domain.
 * http://creativecommons.org/publicdomain/zero/1.0/ */
```

I propose that we remove this comment from our source files. The main issue is that we can't consistently apply this notice to every source file. The bulk of BCD's source is in JSON files that do not permit comments. By inconsistently marking files with a copyright notice, I worry that we may create confusion about what terms apply. Similarly, we have a `LICENSE` file that the notice does not mention, further creating the possibility of confusion.

Also, I personally dislike the wording of the notice: the _work_ is dedicated to the public domain and, besides, CC0 is rather more broad (it dedicates a work to the public domain where possible and waives copy and other rights where it is not).

### PR DESCRIPTION
**Pull request by queengooborg**
This PR is a cherry-pick of #5890 that makes the top of our files consistent by performing the following:

- Removing `#!` lines from all the files (they were added to non-executable files as well and don't help since the files aren't marked executable anyways)
- Add `'use strict'` to all files
- Add attribution to all files (and remove improperly-worded copyright notice)

Fixes #5879.

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Looks good to me, but I'd like someone from Mozilla to review, since this changes copyright notices and there might be considerations I'm not aware of. @Rumyra can you review?

**Comment by queengooborg** [comment]
@schalkneethling Would you mind reviewing this PR?

**Comment by schalkneethling** [comment]
> @schalkneethling Would you mind reviewing this PR?

Funny you should ask 😸  - I just learned about this new "standard"/tool from the Free software foundation https://reuse.software - Not saying we should immediately adopt it here, but surely something to consider.

**Review by caugner — APPROVED** [review]
LGTM

**Review by schalkneethling — APPROVED** [review]

**Pull request merged**
