### PR TITLE
Update background-attachment.json

### PR DESCRIPTION
**Pull request by rickdoesburg**
Removed mention of background-attachment: local bug. Fixes https://github.com/mdn/browser-compat-data/issues/18821

#### Summary

I've removed the mention of background-attachment: local not working on iOS. According to the [bug report](https://bugs.webkit.org/show_bug.cgi?id=219324) it has been fixed and merged. However I'm not exactly sure in which Safari version.

#### Test results and supporting details

I've tested this on an iPhone 12 Pro iOS16.2 and using BrowserStack iPhone 12 Pro iOS14. 
Using these examples: 
https://codepen.io/smashingmag/pen/ExRNxpd
https://codepen.io/bramus/pen/ExxgNrV

#### Related
[This is another bug](https://bugs.webkit.org/show_bug.cgi?id=181048) that has been fixed by the same fix.

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey there, thank you for your PR and welcome to BCD!

Because this was a big enough bug to qualify for `partial_implementation`, we should not just remove the note from our data.  Instead, we should do some digging into when exactly the bug was fixed, and add a third support statement to represent this.

**Comment by rickdoesburg** [comment]
> 

I totally agree! Removing the mention might not have been the best solution. How would you suggest we proceed? Is there something I can do?

**Comment by Elchi3** [comment]
> Instead, we should do some digging into when exactly the bug was fixed, and add a third support statement to represent this.

https://github.com/WebKit/WebKit/commit/b6af623293be604b2cda1b7789258fa230aaa8cd is tagged with releases/Apple/Safari-15.4-iOS-15.4. So I think the version we should use is 15.4

**Review by Elchi3 — APPROVED** [review]
I've added a range for 15.4. Thanks @rickdoesburg 👍

**Pull request merged**
