### PR TITLE
Add compat data for MediaQueryList api

### PR DESCRIPTION
**Pull request by lucian95**

### CODE REVIEW

**Comment by Elchi3** [comment]
Looks good so far! 

"New spec update" looks mysterious to me. I have no idea what it means. I think the relevant bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1354441. We should either be more specific about what has changed in the updated spec or remove this note / row completely.
@chrisdavidmills can you help clarifying ?

**Comment by chrisdavidmills** [comment]
This is my fault — @lucian95 copied it from the pages I wrote. I do apologise for such an awful obscure bit of documentation.

The reason I did this is because the changes themselves are all quite minor and obscure. Looking at the webidl changes you can see in https://bug1354441.bmoattachments.org/attachment.cgi?id=8855810:

* MediaQueryList now inherits from EventTarget (it didn't used to inherit at all)
* MediaQueryList's addListener() and removeListener() methods now take EventListener objects as methods, not MediaQueryListListener objects like they used to.
* MediaQueryList has had an onchange event handler added.

So I guess each one of these needs its own entry, separated out from the general information?

**Comment by Elchi3** [comment]
Yes, I think that would be better. Can you update the documentation and add more meaningful rows to the legacy compat tables? Then migrating these might be easier here. Your breakdown sounds reasonable to me and could be better rows in the compat tables of the MediaQueryList pages / sub pages.

**Comment by chrisdavidmills** [comment]
Done! See

https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList

**Comment by Elchi3** [comment]
Awesome, I moved some of it to the sub pages.

@lucian95 we've sorted out the old tables a bit and added some more meaningful sub features. Can you update this PR based on that?

**Comment by lucian95** [comment]
Understood, will use this method from now on for special characteristics of features

**Comment by cheeZery** [comment]
@Elchi3 @chrisdavidmills I know this is a pretty old PR and I'm happy to file a new issue, just wanted to check with you guys first:
According to https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList and https://github.com/mdn/browser-compat-data/blob/master/api/MediaQueryList.json the prototype of ``MediaQueryList`` is inherited from ``EventTarget`` on most modern devices, i.e. all browsers but IE. But it seems that on Safari and Safaria on iOS (or even Chrome on iOS) this doesn't seem to be the case. It just inherits from ``Object`` so that you can't use the ``EventTarget`` API. Did I do something wrong or might there be an error in the data?
Thanks in advance for your help!

**Comment by chrisdavidmills** [comment]
@cheeZery I think we were mainly just going on what it says in the spec. Hacve you got a test case you can point to, so we can do some quick testing of this?

**Comment by cheeZery** [comment]
@chrisdavidmills just execute the following lines:
```javascript
 // Should work in all browser
window.matchMedia("foo").addListener(() => null);

// Should throw TypeError on iOS/macOS, complaing that window.matchMedia(...).addEventListener is not a function
window.matchMedia("foo").addEventListener("change", () => null);
```

**Comment by chrisdavidmills** [comment]
Looks like you are on to something here. Can you file a developer documentation bug at https://bugzilla.mozilla.org/enter_bug.cgi, and we'll get it put into our backlog?

**Comment by cheeZery** [comment]
@chrisdavidmills sorry for the delay. Finally filed that issue. The page you send me told me to "Report issues about the MDN content under 'Developer Documentation'.". Since I couldn't find that I tried Google, which brought me [here](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Report_a_problem#Site_bugs_or_feature_requests), and from there to https://github.com/mdn/sprints/issues/858, hope that was the right place 🙆

**Comment by chrisdavidmills** [comment]
Thanks @cheeZery , that's perfect. We'll follow-up on this issue over there.

**Pull request merged**
