### PR TITLE
Update MDN URLs with standard ids

### PR DESCRIPTION
**Pull request by bershanskiy**
## Summary

Change attribute MDN URLs to better align with naming convention on MDN.

A checklist to help your pull request get merged faster:
- [ ] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by bershanskiy** [comment]
I looked a bit further into the `id` conventions used on pages and found [htmlattrdef](https://github.com/mdn/kumascript/blob/master/macros/htmlattrdef.ejs) macro using `id="attr-<%=$0%>"`. Does this id convention extend anywhere beyond the three HTML attributes on [Web/HTML/Element/html](https://wiki.developer.mozilla.org/docs/Web/HTML/Element/html)?

**Comment by vinyldarkscratch** [comment]
Based upon what we've seen from your previous PRs, I don't think this convention really carries over to the other features.  Maybe we should update the convention?

**Comment by ExE-Boss** [comment]
I&nbsp;think we&nbsp;should keep&nbsp;the&nbsp;`attr-`&nbsp;prefix.

**Comment by bershanskiy** [comment]
@vinyldarkscratch @ExE-Boss I don't really what the convention is, as long as it is consistently followed by all pages so that URLs are predictable.
It does make sense to add `attr-` to denote an attribute section id just in case there is an attribute called similarly to an id used elsewhere on the page.

**Comment by ddbeck** [comment]
@Elchi3, you may have some thoughts on this

**Comment by Elchi3** [comment]
I'm not sure if using `attr-foo` IDs for attributes is a convention in MDN content. Maybe @chrisdavidmills or @a2sheppy know if it is.

**Comment by chrisdavidmills** [comment]
Aren't they used by the htmlattrxref macro to generate links to specific attributes? I reckon don't get rid of them in case it breaks something somewhere.

**Comment by a2sheppy** [comment]
That is exactly right. They're used by {{htmlattrxref}} and possibly by
other things as well.

Chris Mills wrote on 1/14/20 7:12 AM:
>
> Aren't they used by the htmlattrxref macro to generate links to
> specific attributes? I reckon don't get rid of them in case it breaks
> something somewhere.
>

-- 
Eric Shepherd <https://www.bitstampede.com/>
Senior Technical Writer @ Mozilla
MDN Web Docs <https://developer.mozilla.org/>

**Comment by Elchi3** [comment]
I think we want to keep this then.

**Pull request closed without merging**
