### PR TITLE
adding -moz-window-dragging property

### PR DESCRIPTION
**Pull request by chrisdavidmills**

### CODE REVIEW

**Comment by teoli2003** [comment]
I don't think we should add it. This is not part of the open web (even not standard), it is part of XUL extensions/Firefox development.

See the comment in the page: "It only works in Chrome code.:

@Elchi3 : what do you think?

**Comment by chrisdavidmills** [comment]
Awww, shucks.

And I thought I was being conscientious ;-)

**Comment by teoli2003** [comment]
No worry, I thought about these on Tuesday, so I immediately checked. BCD shows lots of cases.

**Comment by chrisdavidmills** [comment]
Let's wait for Florian to chime in. I'd personally be more than happy to not add non-standard stuff into BCD. I guess that just leaves adding it into the data repo so the syntax values show up.

**Comment by teoli2003** [comment]
I would add non-standard stuff, if they are web-facing. This one is chrome-only.

**Comment by teoli2003** [comment]
(and yes for the data repo for the moment).
We will want to move this out with the product documentation (in the future).

**Comment by Elchi3** [comment]
Non-standard is not necessarily a criteria. Whether something is on the web (or cross-browser), is the criteria I think.

So, internal Firefox APIs (whether DOM APIs, CSS properties, or other APIs exposed for internal purposes only, should either not be on MDN at all or be in a special place / document tree. If our audience (web developers and webextension developers) can't use this at all, it is a good sign we shouldn't document it along with the other "normal" Web features and I also not put in our data sets, like BCD or mdn/data.

**Comment by teoli2003** [comment]
Closing, we all agree.

**Pull request closed without merging**
