### PR TITLE
Add Markdownlint

### PR DESCRIPTION
**Pull request by nschonni**
#### Summary

Prettier is already running on the repo to do the basic formatting, but this can catch additional unintended formatting issues.

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey @nschonni!  I'm not sure if I/we want to add Markdownlint to this particular project, but if we do, there are some changes being made that I don't like.  Can we revert the file changes and just keep the linter addition for now?  (I understand it will cause test failures, but that's alright: it helps show the linter is working!)

**Comment by nschonni** [comment]
I pulled out the changes, but I didn't add the problem matcher here, since like you said, there is less markdown in this repo than than mdn/content

**Comment by queengooborg** [comment]
Hey again!  So after disabling rules MD026, MD034 and MD036, the only tweaks that are left are the ones I just covered in #17612 and some missing alt. text for images in a document we're looking to rewrite anyways.  With this in mind, I don't think that we should introduce a brand new dependency for what will only catch a few minor problems.  I'll be asking the rest of the BCD owners what they think during the meeting tomorrow, and will let you know what we decide!

**Comment by queengooborg** [comment]
I talked about this PR during the BCD meeting earlier today, and we decided that adding Markdownlint isn't really important to us in BCD's current stage.  We have very little Markdown in the repository, so just sticking with Prettier is sufficient enough for our needs.

We've been considering converting all of our notes from HTML to Markdown, see https://github.com/mdn/browser-compat-data/issues/16163.  If we decide to go for it, then I think introducing some Markdown linters would be great, but for now, it seems like little benefit for introducing a new dependency.  Thank you anyways!

**Pull request closed without merging**
