### PR TITLE
Updated compatibility for Performance.toJSON()

### PR DESCRIPTION
**Pull request by irenesmith**
This is based on GitHub Issue #[3065](https://github.com/mdn/browser-compat-data/issues/3065)

I have confirmed that desktop Chrome does support this method and updated the BCD data to include Chrome.

### CODE REVIEW

**Comment by jpmedley** [comment]
@irenesmith What version of Chrome are you using?

**Comment by irenesmith** [comment]
@jpmedley I am using 70.0.3538.77
Because I couldn't find any evidence showing when the method was first supported, I put `true` rather than a release number.

**Comment by jpmedley** [comment]
I can't either. Do you have sample code you can send me? I typed `Performance.` in my console and got nothing.

**Comment by Elchi3** [comment]
This was added in Chrome 56: http://web-confluence.appspot.com/#!/catalog?releases=%5B%22Chrome_55.0.2883.75_OSX_10.11.6%22,%22Chrome_56.0.2924.76_OSX_10.11.6%22%5D&q=%22Performance%23toJSON%22

**Pull request merged**
