### PR TITLE
Complete Pointer Events data for Safari (and add `pointerrawupdate`)

### LINKED ISSUE #8709: Safari supports pointer events since version 13
#### What information was incorrect, unhelpful, or incomplete?
Safari supports pointer events.  

#### What did you expect to see?
https://caniuse.com/?search=pointerevent

#### Did you test this? If so, how?
No

<details>
<summary>MDN page report details</summary>

* Query: `api.HTMLElement.pointerenter_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointerenter_event
* Report started: 2021-01-12T07:37:56.350Z

</details>

### PR DESCRIPTION
**Pull request by ddbeck**
This fixes #8709.

This PR does three main things:

- Add Safari version numbers for the `pointercancel` event
- Add Safari version numbers for the `pointerdown` event
- Add features for the `pointerrawupdate` event. [Except Chrome](https://chromestatus.com/feature/6041426311774208), no browser supports this event.

This completes the Pointer Events data for Safari and ensures we have the complete set of event features needed for [the Pointer Events spec](https://w3c.github.io/pointerevents/#pointer-event-types).

### CODE REVIEW

**Comment by ddbeck** [comment]
@Elchi3 is it possible you could review this? I've closed at least 5 duplicates of #8709. This data is a tough spot: interesting enough for people to notice it's wrong, but not interesting enough for anyone to review it. 😬

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Looks good to me, Daniel! Could you try to add spec_urls, though? :)

**Comment by ddbeck** [comment]
@Elchi3 Good idea. This caused me to run into an interesting question (to me, at least). I didn't realize that most of these already had URLs added until I got a merge conflict. 🤦 But it revealed that I picked a different URL fragment (see diff for a bunch of examples). I was using the permalink popover widget from the spec to get those fragments. How do I know which fragment is preferred, if they link to the same place?

**Comment by Elchi3** [comment]
Thanks for going the extra miles!

We don't have guidelines documented yet (https://github.com/mdn/browser-compat-data/issues/10106) but the idea is that we would prefer headings (#the-) instead of definitions (#dfn-) because the UX for the reader is better when you land at a heading (the definition can be buried somewhere in a paragraph). However, @sideshowbarker is still normalizing things, so I'll tag him here, too.

**Comment by ddbeck** [comment]
@Elchi3 Thanks, that's helpful info! I've re-done my merge from main to use the heading fragments, instead of the `#dfn` fragments.

Though I've retained the previous state of the branch, in case @sideshowbarker weighs in differently. You can see the pre-rebase diff here: https://github.com/mdn/browser-compat-data/compare/main...ddbeck:8709-complete-safari-pointers-dfn-spec_urls

**Review by sideshowbarker — APPROVED** [review]
Looks great to me (and will try to get the spec URL data guidelines written up asap)

**Review by Elchi3 — APPROVED** [review]

**Pull request merged**
