### PR TITLE
Move rel=noopener out of <link>, into <area> & <a>

### PR DESCRIPTION
**Pull request by sideshowbarker**
https://html.spec.whatwg.org/multipage/#link-type-noopener

### CODE REVIEW

**Comment by ddbeck** [comment]
@sideshowbarker do you want me to delete your branches when they've been merged? (I'm in the habit of deleting top-level branches, but I'm happy to leave prefixed branches alone.)

**Comment by sideshowbarker** [comment]
> @sideshowbarker do you want me to delete your branches when they've been merged? (I'm in the habit of deleting top-level branches, but I'm happy to leave prefixed branches alone.)

Yes, please do go ahead and delete them. I usually try to delete them myself, but sometimes I forget…

By the way, there is some GitHub setting that will cause PR branches to be auto-deleted when the PR is merged. I think we use it for the web-platform-tests repo and maybe for WHATWG repos. (The branch changes are still retained even after the branch is auto-deleted, so the branch can always be restored later if needed.)

**Comment by ddbeck** [comment]
Ah yeah, it looks like there is a feature to do this: https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

@Elchi3 Interested in turning that setting on? Or should I open an issue for it?

**Comment by Elchi3** [comment]
Today I learned! 

Enabled this just now. Thanks @sideshowbarker and @ddbeck :+1:

**Comment by sideshowbarker** [comment]
Cheers 😁

**Pull request merged**
