### PR TITLE
Add Firefox versions for api.Document.exitPointerEvent

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR adds real values for Firefox and Firefox Android for the `exitPointerEvent` member of the `Document` API, based upon manual testing.

Test Code Used: `document.mozExitPointerEvent`

### CODE REVIEW

**Comment by foolip** [comment]
@vinyldarkscratch do you want to go ahead and tackle all of the entries that have https://w3c.github.io/pointerlock/ as `spec_url`? That would make it easy to tell if everything seems to add up.

**Comment by foolip** [comment]
@vinyldarkscratch just so there's no misunderstanding, there's more stuff (in other files) with https://w3c.github.io/pointerlock/ as the spec URL.

**Comment by foolip** [comment]
But maybe fold this into https://github.com/mdn/browser-compat-data/pull/11457 to have a single PR with everything moz-prefixed for this API?

**Comment by vinyldarkscratch** [comment]
Merged the two PRs together now!

**Pull request closed without merging**
