### PR TITLE
Makes the lint output less verbose

### PR DESCRIPTION
**Pull request by caugner**
* Uses ora to display a spinner with succeed/fail feedback.
* Removes `console.log` calls for succeeding checks.

### CODE REVIEW

**Comment by caugner** [comment]
**Before**:
image

**After**:
image

**Comment by ddbeck** [comment]
This is neat looking, @caugner! That said, it seems to break the behavior of the `show-errors` command.

Finally, I feel kinda unequipped to review adding a dependency, so this may need to wait for Florian's return.

**Comment by caugner** [comment]
@ddbeck Good catch! I wasn't aware of `show-errors`, but have fixed it now (db53b34):

image

Alright, I totally understand (and with `show-errors` it's less urgent already). Let's wait for Florian's return.

**Comment by caugner** [comment]
Note that I have meanwhile fixed the problem (which existed before and you can see in the last screenshot I posted) that `show-errors` didn't output the filenames in the summary below `Problems in <n> files`.

**Comment by caugner** [comment]
@Elchi3 Is there anything I can do to push this towards the release train?

**Pull request merged**
