### PR TITLE
Update CompressionStream.json to include specific constructor arguments

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
Adds the individual values "gzip", "deflate", and "deflate-raw", as requested in https://github.com/mdn/content/pull/17322.

#### Test results and supporting details
Untested. (We don't have tests for these)

* https://github.com/denoland/deno/pull/14863
* https://chromestatus.com/feature/5172771293233152

Unknown as to whether Google shipped the first two values in their initial support.
Unknown as to whether Node.js supports "deflate-raw".

(I lack a device necessary to test these; may someone else confirm or gather extra data regarding this?)

---

These APIs are all incomplete* and not standardized (yet), may and should I mark everything in that file with `"experimental" : true`?

\* See that this proposal still appears to be an early draft: https://wicg.github.io/compression

### CODE REVIEW

**Comment by aslilac** [comment]
Sorry, just now saw this!

**Comment by queengooborg** [comment]
Hey @Phosra, thank you for your PR and welcome to BCD!  I just have a couple of requests:

- The CI is failing due to incorrect feature sorting.  Could run `npm run fix` to fix the sorting?
- Could you provide a source for the version numbers used for `gzip` and `deflate`?

**Comment by aslilac** [comment]
> Unknown as to whether Node.js supports "deflate-raw".

It does not.

**Comment by aslilac** [comment]
You're also going to need to make similar edits to DecompressionStream.json

**Review by queengooborg — APPROVED** [review]
Thank you for providing sources -- this is LGTM!

**Pull request merged**
