### PR TITLE
Correct CSS: prefers-color-scheme data for Firefox for Android - Fixes #5798

### LINKED ISSUE #5798: CSS: prefers-color-scheme Firefox for Android data is incorrect
This feature requires Android integration work that was not done until Android Components 0.50.0 this was first released as Firefox Preview 1.0

https://github.com/mozilla-mobile/android-components/pull/2646/

### PR DESCRIPTION
**Pull request by kbrosnan**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes

Fix an error with prefers-color-scheme for Firefox for Android

- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)

See issue #5798

- [x] Data: if you tested something, describe how you tested with details like browser and version

https://davidwalsh.name/demo/prefers-color-scheme.php
Firefox for Android 68.5.0 ❌
Firefox Preview 1.0 ✔

- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by kbrosnan** [comment]
Hm can't list version 69. Maybe best to just mark it as incompatible for now with a note.

**Comment by vinyldarkscratch** [comment]
Hey @kbrosnan, do you plan to return to this PR?

**Comment by vinyldarkscratch** [comment]
Since we haven't heard back from you and the PR has some merge issues, I went ahead and created a new PR to supersede this one.  Thanks for getting the ball rolling on this!

**Comment by florence443** [comment]
Iam getting no were please what to do

**Comment by florence443** [comment]
Again pull requested I dont know if I doing ok

**Comment by florence443** [comment]
Were iam getting now

**Comment by florence443** [comment]
Still canot get what iam doing

**Comment by florence443** [comment]
What to do the simple  way

**Comment by florence443** [comment]
How may pull request

**Comment by florence443** [comment]
How I'm going to end

**Comment by florence443** [comment]
Dont know  what comment

**Comment by florence443** [comment]
Ok now?

**Comment by florence443** [comment]
Are we finished now?

**Comment by florence443** [comment]
Is it ok

**Comment by florence443** [comment]
Jow do I know I'm  doing things  ok??

**Comment by florence443** [comment]
What to do now?

**Pull request closed without merging**
