### PR TITLE
Fix the data structure for hz and khz units

### PR DESCRIPTION
**Pull request by foolip**
The support data was duplicated in two files frequency.json and frequency-percentage.json.

Keep it in frequency.json only and nest it under the main feature as with other CSS types.

### CODE REVIEW

**Comment by ddbeck** [comment]
@rachelandrew, since you recently worked on the frequency-percentage type, I'd appreciate your take on this. Thank you!

**Comment by rachelandrew** [comment]
@ddbeck @chrisdavidmills and I discussed this and decided to split it out (see: https://github.com/mdn/sprints/issues/778#issuecomment-458487468). I'm not sure I have a strong opinion either way other than that.

**Comment by chrisdavidmills** [comment]
I think we wanted to be as flexible as possible in case the support data ended up being different for those units under frequency and frequency-percentage (it is possible, surely?)

**Comment by foolip** [comment]
@chrisdavidmills I don't think that is possible, because https://drafts.csswg.org/css-values-4/#mixed-percentages is a convenience for the CSS grammar, so `<frequency-percentage>` is literally `<frequency>` or `<percentage>`. It seems a bit similar to Web IDL mixins&mdash;a convenience for spec editors which is invisible to web developers.

It's still possible that support for the unit depends on the property of course, but I'm guessing that would have to be represented in some other way?

**Comment by chrisdavidmills** [comment]
OK, so we could just list the support data for percentage, and frequency, when talking about frequency-percentage (and do similar in other cases). And when we are able to make composite tables out of multiple features, this will just look a bit neater.

@rachelandrew does this proposal work for you?

**Comment by rachelandrew** [comment]
@chrisdavidmills yes I'm happy with that

**Comment by foolip** [comment]
@chrisdavidmills I think that means no changes required in this PR, is that right?

**Comment by chrisdavidmills** [comment]
Yeah, that looks OK to me now. I guess we should still keep the basic composite types and list that support data on their pages, but then also list the support for each of the basic type features that those composite types include, as it were.

**Comment by foolip** [comment]
Any volunteers to review/merge this? I keep having to work around it with every change to css.* I'm making based on scripts discussed in https://github.com/mdn/browser-compat-data/issues/3617.

**Comment by foolip** [comment]
Thanks @ddbeck!

**Pull request merged**
