### PR TITLE
Update Chromium support for api.RTCIceCandidate (and add address)

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
Cherry picked from https://github.com/mdn/browser-compat-data/pull/3826/files/8256f08e7da5e8bc40ffde494aaa3aba6686bc29#r298342645.

### CODE REVIEW

**Comment by Elchi3** [comment]
That deep link doesn't work for me. Can you give this more context/proofs?

**Comment by vinyldarkscratch** [comment]
Sure thing!  @jpmedley had reviewed #3826 and mentioned that members RTCIceCandidate were changed to `false` for Chrome Android, [when they actually landed in 74](https://github.com/mdn/browser-compat-data/pull/3826#discussion_r298342645).  Hence, this pull request.

**Comment by Elchi3** [comment]
Ah okay thanks! In this case, it sounds like @jpmedley is most qualified to review this PR :)

**Comment by vinyldarkscratch** [comment]
I already added `port` and `protocol` in this PR.  The others, though, I'm now pushing a new commit to add them!

**Comment by vinyldarkscratch** [comment]
Thanks @jpmedley!

**Pull request merged**
