### PR TITLE
Updating logical width and height property data

### PR DESCRIPTION
**Pull request by rachelandrew**
Support is in Chrome and Opera https://www.chromestatus.com/feature/6325742262550528

Also added the missing max-block-size.

### CODE REVIEW

**Comment by Elchi3** [comment]
> Also added the missing max-block-size.

That's already dealt with in https://github.com/mdn/browser-compat-data/pull/2928

**Comment by Elchi3** [comment]
Needs a rebase now, sorry about that.

**Comment by rachelandrew** [comment]
Have done, hopefully without making a horrible mess. Let me know.

**Comment by Elchi3** [comment]
> Have done, hopefully without making a horrible mess. Let me know.

Unfortunately I think this has become exactly that. I think easiest would be to get to this in a new PR. Sorry about that!

**Comment by rachelandrew** [comment]
The new PR is here https://github.com/mdn/browser-compat-data/pull/3027

**Pull request closed without merging**
