### PR TITLE
Add tabs removeCSS

### PR DESCRIPTION
**Pull request by a2sheppy**
Add compatibility information for tabs.removeCSS(), per bug 1247455.

### CODE REVIEW

**Comment by wbamberg** [comment]
This PR has the commits from your other PR in it. Can you resubmit from a clean version of master?

**Comment by a2sheppy** [comment]
Gah. I don't even know how to do that. I don't even know how it's
possible to have that other stuff in it. I'll try to figure it out. I
really desperately hate git.


> This PR has the commits from your other PR in it. Can you resubmit
> from a clean version of master?
>

-- 

Sheppy

**Comment by a2sheppy** [comment]
That should do it. Thanks to John Whitlock for helping me fix it.

**Comment by wbamberg** [comment]
Thanks @a2sheppy !

**Pull request merged**
