### PR TITLE
docs(details): added `name` attribute entry

### PR DESCRIPTION
**Pull request by mfranzke**
#### Summary

Added new `name`-attribute to `details` elements, which enable an exclusive `details` element in a grouped list to be open (also known as _accordion_).

#### Related issues

- <https://github.com/whatwg/html/pull/9400>
- <https://chromestatus.com/feature/6710427028815872>

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Thanks and sorry for being slow. 
Do you want to add https://bugzil.la/1856460 for Firefox?

**Comment by mfranzke** [comment]
> Thanks and sorry for being slow. Do you want to add https://bugzil.la/1856460 for Firefox?

loving it, missed that one (seems to me that it has been opened after I opened this issue); thank you !

**Review by Elchi3 — APPROVED** [review]
Thanks for the quick follow-up!
(And Hi! I think we met some years ago at Write The Docs Prague!?)

**Comment by mfranzke** [comment]
> Thanks for the quick follow-up! (And Hi! I think we met some years ago at Write The Docs Prague!?)

Sadly not, but I'll be at w-jax, FOSDEM, beyond tellerrand and probably WeAreDevelopers again, so there might be the chance for the future to meet at some of those in or around Germany.

**Pull request merged**
