### PR TITLE
(TouchList) Add Safari Desktop to supporting browsers; add version for Safari Mobile

### PR DESCRIPTION
**Pull request by strarsis**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

iOS Desktop browser now supports TouchList according to the Apple official documentation for TouchList: https://developer.apple.com/documentation/webkitjs/touchlist (version 10.1+).
The documentation also states the minimum version of Safari iOS (Mobile) for TouchList: version 2.0+.

### CODE REVIEW

**Comment by strarsis** [comment]
OK, ready to merge. 👍

**Review by ddbeck — CHANGES_REQUESTED** [review]
Hi @strarsis and thanks for this PR. I see that it's your first to the project—welcome!

This change looks fine as-is, but I have a suggestion to expand this: can you apply the versions to the `item` and `length` subfeatures too? The linked docs report the same versions for those too, so it looks like we can get three corrections for the price of one here.

Thank you again!

**Comment by strarsis** [comment]
@ddbeck: https://github.com/mdn/browser-compat-data/pull/8848/commits/34d67f48e2d1d874812f5f97279098e598163f28

**Review by ddbeck — APPROVED** [review]
Thank you! 🎉

**Comment by strarsis** [comment]
@ddbeck: And after merging the docs will be rebuilt (and deployed)? https://developer.mozilla.org/en-US/docs/Web/API/TouchList

**Comment by ddbeck** [comment]
@strarsis Changes merged go into the next release of `@mdn/browser-compat-data` (planned for tomorrow and most Thursdays) and MDN usually picks up those changes the next day. I'd expect the page to be regenerated with the new compat data on Friday, January 29.

**Pull request merged**
