### PR TITLE
Modify PerformanceEventTiming table to show it is enabled on FF 89

### PR DESCRIPTION
**Pull request by mirunacurtean**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes

- removed experimental status
- Updated FF and FF for Android columns to show that feature has been enabled in 89th version.  

- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)

[We have PerformanceEventTiming enabled in Nightly for over a month now...](https://bugzilla.mozilla.org/show_bug.cgi?id=1701029#c0)

- [x] Link to related issues or pull requests, if any
Fixes https://github.com/mdn/content/issues/4309

### CODE REVIEW

**Comment by ddbeck** [comment]
Hey @mirunacurtean, you've updated the main interface here, but none of its members. Is that right? Or is there additional work to be done on the subfeatures here?

**Comment by mirunacurtean** [comment]
> Hey @mirunacurtean, you've updated the main interface here, but none of its members. Is that right? Or is there additional work to be done on the subfeatures here?

@ddbeck  Yes, I think so; if you're referring to only the PerformanceEventTiming being affected by these changes and yes it was only what was in the UI that should've been modified.  If I misunderstand something, we can chat over it on slack.

**Comment by mirunacurtean** [comment]
@ddbeck This is now ready for another review. I've updated all the other subfeature rows and deleted the yarn file. 
So that the consistency is maintained I've also added an MDN URL to the .target attribute, even if there is no page created for it yet.

**Review by ddbeck — APPROVED** [review]
Looks great, @mirunacurtean. Thank you! 🎉

**Pull request merged**
