### PR TITLE
Don't combine statements in mirroring

### PR DESCRIPTION
**Pull request by queengooborg**
This PR replaces the `combineStatements` function in the mirroring script with a simplified `flattenStatements`.  Combining statements is not needed in mirroring since mirroring from multiple sources had been abandoned.

### CODE REVIEW

**Comment by foolip** [comment]
These are the changes in `build/data.json` that resulted from this change:

```diff
@@ -18380,10 +18380,15 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": "Default values supported",
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "Default values supported",
+                                "version_added": "5.0"
+                            },
+                            {
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": {
                             "version_added": "17"
                         },
@@ -48494,14 +48499,23 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": [
-                                "URLs may open inside an existing browsing context provided by a standalone web app",
-                                "Can open any URL. ",
-                                "Can only open URLs on the same origin."
-                            ],
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "URLs may open inside an existing browsing context provided by a standalone web app",
+                                "version_added": "5.0"
+                            },
+                            {
+                                "notes": "Can open any URL. ",
+                                "version_added": "5.0"
+                            },
+                            {
+                                "notes": "Can only open URLs on the same origin.",
+                                "version_added": "5.0"
+                            },
+                            {
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": {
                             "version_added": "38"
                         },
@@ -48691,15 +48705,23 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": [
-                                "From version 86, the <code>text/html</code> MIME type is supported.",
-                                "From version 84, the <code>image/png</code> MIME type is supported.",
-                                "Images are not supported."
-                            ],
-                            "partial_implementation": true,
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "From version 86, the <code>text/html</code> MIME type is supported.",
+                                "partial_implementation": true,
+                                "version_added": "12.0"
+                            },
+                            {
+                                "notes": "From version 84, the <code>image/png</code> MIME type is supported.",
+                                "partial_implementation": true,
+                                "version_added": "11.0"
+                            },
+                            {
+                                "notes": "Images are not supported.",
+                                "partial_implementation": true,
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": {
                             "version_added": "63"
                         },
@@ -54453,13 +54475,16 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": [
-                                "Support for 'Customized built-in elements' as well.",
-                                "Support for 'Autonomous custom elements' only."
-                            ],
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "Support for 'Customized built-in elements' as well.",
+                                "version_added": "6.0"
+                            },
+                            {
+                                "notes": "Support for 'Autonomous custom elements' only.",
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": [
                             {
                                 "notes": "Support for 'Customized built-in elements' as well.",
@@ -54561,13 +54586,16 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": [
-                                "Support for 'Customized built-in elements' as well.",
-                                "Support for 'Autonomous custom elements' only."
-                            ],
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "Support for 'Customized built-in elements' as well.",
+                                "version_added": "6.0"
+                            },
+                            {
+                                "notes": "Support for 'Autonomous custom elements' only.",
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": [
                             {
                                 "notes": "Support for 'Customized built-in elements' as well.",
@@ -54722,13 +54750,16 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": [
-                                "Support for 'Customized built-in elements' as well.",
-                                "Support for 'Autonomous custom elements' only."
-                            ],
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "Support for 'Customized built-in elements' as well.",
+                                "version_added": "6.0"
+                            },
+                            {
+                                "notes": "Support for 'Autonomous custom elements' only.",
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": [
                             {
                                 "notes": "Support for 'Customized built-in elements' as well.",
@@ -72403,6 +72434,10 @@
                                 "alternative_name": "charset",
                                 "notes": "<code>charset</code> alias was made read-only in Chrome 45.",
                                 "version_added": "5.0"
+                            },
+                            {
+                                "alternative_name": "inputEncoding",
+                                "version_added": "5.0"
                             }
                         ],
                         "opera": [
@@ -497502,6 +497537,10 @@
                             {
                                 "alternative_name": "offset-rotation",
                                 "version_added": "5.0"
+                            },
+                            {
+                                "alternative_name": "motion-rotation",
+                                "version_added": "5.0"
                             }
                         ],
                         "opera": [
@@ -518971,10 +519010,15 @@
                         "ie": {
                             "version_added": "3"
                         },
-                        "oculus": {
-                            "notes": "<code>&gt;&gt;&gt;</code> is aliased to this selector <a href='https://developers.google.com/web/updates/2017/06/chrome-60-deprecations#make_shadow-piercing_descendant_combinator_behave_like_descendent_combinator'>since its use as the 'shadow-piercing descendant combinator' was deprecated</a>.",
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": "<code>&gt;&gt;&gt;</code> is aliased to this selector <a href='https://developers.google.com/web/updates/2017/06/chrome-60-deprecations#make_shadow-piercing_descendant_combinator_behave_like_descendent_combinator'>since its use as the 'shadow-piercing descendant combinator' was deprecated</a>.",
+                                "version_added": "5.0"
+                            },
+                            {
+                                "version_added": "5.0"
+                            }
+                        ],
                         "opera": {
                             "version_added": "3.5"
                         },
@@ -570782,14 +570826,22 @@
                         "ie": {
                             "version_added": false
                         },
-                        "oculus": {
-                            "notes": [
-                                "Support added for <code>autocomplete</code> on the <code>&lt;textarea&gt;</code> and <code>&lt;select&gt;</code> elements.",
-                                "Chrome does not accept <code>off</code> as a value. See <a href='https://crbug.com/587466'>bug 587466</a>.",
-                                "Originally only supported on the <code>&lt;input&gt;</code> element."
-                            ],
-                            "version_added": "5.0"
-                        },
+                        "oculus": [
+                            {
+                                "notes": [
+                                    "Support added for <code>autocomplete</code> on the <code>&lt;textarea&gt;</code> and <code>&lt;select&gt;</code> elements.",
+                                    "Chrome does not accept <code>off</code> as a value. See <a href='https://crbug.com/587466'>bug 587466</a>."
+                                ],
+                                "version_added": "5.0"
+                            },
+                            {
+                                "notes": [
+                                    "Originally only supported on the <code>&lt;input&gt;</code> element.",
+                                    "Chrome does not accept <code>off</code> as a value. See <a href='https://crbug.com/587466'>bug 587466</a>."
+                                ],
+                                "version_added": true
+                            }
+                        ],
                         "opera": {
                             "version_added": true
                         },
```

**Comment by foolip** [comment]
@queengooborg some of the changes in that diff are regressions. The first one is a clear example, where the statements should be merged. See https://github.com/mdn/browser-compat-data/pull/16968 for another approach.

**Comment by foolip** [comment]
I'm not comfortable with just fixing the data we can see in this diff. Can you either make the mirror script fail hard in case like this, lint for it, or something else?

Here's a situation I think will be problematic without merging statements: say a feature has problem one problem from version X and another added problem from version Y, both still present, so just represented as notes, no `version_removed`. If X and Y map to the same version, shouldn't these be merged?

**Comment by queengooborg** [comment]
I plan to add a linter soon to prevent multiple statements that just have a `version_added` and `version_removed`, `notes` and/or `impl_url` altogether, so that there can only be multiple statements with differences in `partial_implementation` or `prefix`/`alternative_name`.  It would also be nice to enforce a `version_removed` on `partial_implementation` statements if there's a matching statement without it with a higher version, so that the mirroring script will know to remove them should the target's version numbers match.  I don't think that there should ever be multiple statements with just notes if what the notes are describing isn't a significant enough issue where `partial_implementation` or a subfeature should be used.

**Pull request merged**
