### PR TITLE
data for list-item and display: run-in

### PR DESCRIPTION
**Pull request by rachelandrew**
This is for the things discussed in https://github.com/mdn/sprints/issues/523

I'm not sure if the data for run-in makes sense. Let me know!

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
This looks good to me, @rachelandrew .

**Comment by chrisdavidmills** [comment]
Are you OK to merge this, or have you more work you want to do?

**Comment by rachelandrew** [comment]
If you don't think I've made any sort of mess then please do!

**Comment by chrisdavidmills** [comment]
Done!

**Pull request merged**
