### PR TITLE
API: Update Edge versioning information...

### PR DESCRIPTION
**Pull request by mdittmer**
... according to [Web API Confluence Dashboard](https://web-confluence.appspot.com/) dataset

### CODE REVIEW

**Comment by Elchi3** [comment]
Looks alright to me!

Maybe @erikadoyle or someone from Microsoft can review, too? :) Greetings from Paris!

**Comment by erikadoyle** [comment]
Oh wow--fantastic! @libbymc can help review

**Comment by libbymc** [comment]
Yep! Verifying against the diffs I pulled from our IDL (published here: [EdgeHTML.json](https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/blob/master/EdgeHTML/EdgeHTML.json))

**Comment by libbymc** [comment]
Hey @mdittmer! I spot checked a few things and a lot of this looks correct, but there I noticed a few discrepancies:  AudioContext, Gamepad, and PerformanceResourceTiming have been around since the beginning of Edge (and even IE). So these should be the earliest version of Edge (12).

**Comment by teoli2003** [comment]
- For AudioContext, only close() and suspend() are been marked as Edge 14.  They seem to be recent additions (by looking at other browser support.
- For Gamepad APIs, it looks like the ones marked as Edge 15 are also recent additions as Chrome don't support them yet.
- For PerformanceResourceTiming: the Edge16 is only for workerStart.

@libbymc, can you check that these methods weren't in Edge 12 alread, and have been added as Mark has noticed?

**Comment by teoli2003** [comment]
I'm really excited here, as this show that the combination of tools and humans can lead to an amazing quality of the data.

**Comment by libbymc** [comment]
@teoli2003 - yep, you're correct. These methods were added after EdgeHTML 12. Thanks!

**Comment by mdittmer** [comment]
@libbymc PTAL. It just resolved a bunch of merge conflicts. The only potentially questionable ones were a removal in 16 and some things on `URL` that the current data claimed to ship in `13`, but Confluence didn't see shipped until `14`.

**Comment by libbymc** [comment]
@mdittmer we are looking into this on our side. Our current IDL diff process isn't infallible, as there's significant churn in our schema (to be webidl compliant) from version to version.

**Comment by libbymc** [comment]
@mdittmer - initAnimationEvent() was removed in 16, that is correct.  As far as the URL properties - it's possible these were added in 13 but no-op until 14.  Let's go with 14 for those.

**Comment by Elchi3** [comment]
This needs a rebase now, there is an outstanding comment still, and a syntax error that makes travis.
@mdittmer Are you still interested in fixing this one up?

**Pull request closed without merging**
