### PR TITLE
WebVR is enabled in Firefox 61 on macOS, not 60

### PR DESCRIPTION
**Pull request by a2sheppy**
This accidentally picked up a change from a previous PR I submitted, and I can't figure out how to get that file out of here. If anyone can help, I'd appreciate that.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
To remove a commit, you use [`git rebase -i HEAD~2`](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), and [delete the first line](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_reordering_commits). Then you do `git push -f` to push the rewritten history.

P.S.: If you’re on Windows, then you can use [TortoiseGit](https://tortoisegit.org/) to get a GUI based rebase tool which is much easier to understand in my opinion:
1. Use TortoiseGit’s “Git Show log…” context menu option
2. In the Show log… view, right click the `master` branch
3. Select the rebase context menu option and skip the unwanted commit in the Rebase view.

**Comment by Elchi3** [comment]
Where is the info from that this is enabled in Firefox 61? I don't think it is actually.
See e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1454204#c14

**Comment by a2sheppy** [comment]
The info that it was enabled in 61 came from a content coordination meeting but I now think that it is no longer correct. I am looking in to it.

**Comment by a2sheppy** [comment]
Looks like actually it's not enabled by default in 61 after all. At least, I've pulled beta, and in a fresh install, `dom.vr.enabled` is `false`.

**Comment by a2sheppy** [comment]
This should be updated to 62.

**Comment by a2sheppy** [comment]
OK, sorry for that mess. Ran into some trouble here with my mediocre git-fu. The final result should be right though, and ready for review. Except I can't change the review requested indicator. :(

**Comment by Elchi3** [comment]
> This should be updated to 62. I'm on it.

Can you please point to a reference where it says that this is indeed in 62? I can't review myself, because I don't have macOS.

**Comment by a2sheppy** [comment]
@Elchi3 - So, I determined this by installing 61 and 62 both and looking at the default value of the preference on a fresh profile, because I have not found anything written anywhere that gives a definitive answer, and have not succeeded in getting an answer from the VR team. I will try to contact them again.

**Comment by a2sheppy** [comment]
Just got [written confirmation](https://bugzilla.mozilla.org/show_bug.cgi?id=1459362#c19) from Kearwood Gilbert that WebVR on Mac will not be in 61 but is expected in either 62 or 63. I am checking to find out if they have a bug explicitly for throwing the switch.

**Comment by Elchi3** [comment]
hm, given the current docs say "macOS support was enabled in Firefox 60." should we wait this out or get the current status (unimplemented on macOS) reflected in BCD and MDN? @a2sheppy

**Pull request merged**
