### PR TITLE
Organize sandbox attribute values; add missing sandbox values

### LINKED ISSUE #1208: List all sandbox attribute values
This is more of a question than an issue perhaps - 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Browser_compatibility

In the browser compatibility table, there are some sandbox attributes listed, but there are a whole lot more that are not, such as allow-scripts, allow-same-origin, allow-forms, etc. Am I supposed to read this table as any attribute not specifically called out should be included in the "sandbox" row?

### PR DESCRIPTION
**Pull request by queengooborg**
This PR organizes the `sandbox` attribute values of the `iframe` HTML element, as well as adds the missing attribute values.  Fixes #1208.

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Great, thanks for fixing this really old request! 
Can you add spec_urls to all of them? I think it would be useful

**Comment by queengooborg** [comment]
Spec URLs added!

I also found that `allow-downloads-without-user-activation` isn't defined in the spec.  I'm assuming that it was originally in the spec but then removed, so I've marked it as deprecated as well.

**Comment by Elchi3** [comment]
> I also found that `allow-downloads-without-user-activation` isn't defined in the spec. I'm assuming that it was originally in the spec but then removed, so I've marked it as deprecated as well.

Yeah, I couldn't find what's the story here. There is https://github.com/w3c/webappsec-permissions-policy/blob/main/sandbox.md but I don't see it in a specification.

**Review by Elchi3 — APPROVED** [review]

**Comment by Sjord** [comment]
I am thinking about removing `allow-downloads-without-user-activation`, since it is not in the spec anymore and isn't implemented by any browser. I want to [remove it from the MDN docs](https://github.com/mdn/content/pull/33409), and apparently it also needs to be removed from the compatibility table. Does this make sense?

**Comment by Elchi3** [comment]
Yes, I think that makes sense. I found https://chromestatus.com/feature/5706745674465280 which says it was removed in Chromium 83. Do you want to create a PR that removes the data?

**Comment by Sjord** [comment]
[Remove allow-downloads-without-user-activation by Sjord · Pull Request #23253 · mdn/browser-compat-data](https://github.com/mdn/browser-compat-data/pull/23253)

**Pull request merged**
