### PR TITLE
Remove never-supported Budget APIs

### PR DESCRIPTION
**Pull request by saschanaz**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any: #6854, #6768

### CODE REVIEW

**Review by foolip — APPROVED** [review]
I can confirm this with the commit message I wrote for https://github.com/mdn/browser-compat-data/pull/6535:

> Only the reserve() method was shipped, and later removed:
> https://groups.google.com/a/chromium.org/d/msg/blink-dev/yBtmc-4xl_o/GE0vneAVDQAJ
> https://groups.google.com/a/chromium.org/d/msg/blink-dev/18r3whCBv0I/b8qrtFTsDAAJ
>
> https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8362 was
> tested on Chrome and Opera on Windows to verify the ranges. Android
> WebView was never supported per the blink-dev intent, and the other data
> was mirrored.

**Comment by ddbeck** [comment]
@chrisdavidmills We did this removal before we discussed how to handle the disposition of pages. Would you mind deleting the https://wiki.developer.mozilla.org/docs/Web/API/BudgetState tree?

**Comment by ddbeck** [comment]
@chrisdavidmills actually, on second thought, there a couple of others to consider. I'll open an issue on mdn/sprints with a list of all of them instead. Sorry for the nosie.

**Comment by chrisdavidmills** [comment]
It's all good. I just deleted the BudgetState tree.

**Comment by ddbeck** [comment]
@chrisdavidmills Oh, good news: that was all of them after all. Thank you!

**Pull request merged**
