### PR TITLE
Add a note to Firefox about default Accept value change

### PR DESCRIPTION
**Pull request by chrisdavidmills**
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1417463

### CODE REVIEW

**Comment by Elchi3** [comment]
I think a note for Firefox would be enough here. Do you think this is a spec change that other browsers will follow or have followed and so we should record the versions for the other browsers in the future, too? You've set them all to `null`, so I guess there is no info about other browsers available?

**Comment by chrisdavidmills** [comment]
This is a good point. I actually don't know if this is a spec change that all browsers are following, or if it is specced behavior Firefox wasn't following that we've fixed.

So shall we close this for now, and perhaps reopen if we find out we need it?

**Comment by Elchi3** [comment]
You could add a `note` field for this to `firefox`.

**Comment by chrisdavidmills** [comment]
Done!

**Pull request merged**
