### PR TITLE
Set IE/pre-Blink Edge to supported for old CSS property values

### PR DESCRIPTION
**Pull request by queengooborg**
This PR sets IE and pre-Blink Edge to supported for CSS property values that were introduced since all browsers first had support for them.  This is performed with a simple regex find-and-replace:

```regex
(\s+)"chrome": {
\s+  "version_added": "(1|2|3|4|5)"
\s+},
\s+"chrome_android": "mirror",
\s+"edge": "mirror",
\s+"firefox": {
\s+  "version_added": "(1|2|3(?:\.\d)?|4)"
\s+},
\s+"firefox_android": "mirror",
\s+"ie": {
\s+  "version_added": false
\s+},
\s+"oculus": "mirror",
\s+"opera": "mirror",
\s+"opera_android": "mirror",
\s+"safari": {
\s+  "version_added": "(1(?:\.\d)?|2|3)"
\s+},
\s+"safari_ios": "mirror",
\s+"samsunginternet_android": "mirror",
\s+"webview_android": "mirror"
```

-->

```regex
$1"chrome": {
$1  "version_added": "$2"
$1},
$1"chrome_android": "mirror",
$1"edge": {
$1  "version_added": "12"
$1},
$1"firefox": {
$1  "version_added": "$3"
$1},
$1"firefox_android": "mirror",
$1"ie": {
$1  "version_added": "≤11"
$1},
$1"oculus": "mirror",
$1"opera": "mirror",
$1"opera_android": "mirror",
$1"safari": {
$1  "version_added": "$4"
$1},
$1"safari_ios": "mirror",
$1"samsunginternet_android": "mirror",
$1"webview_android": "mirror"
```

### CODE REVIEW

**Comment by queengooborg** [comment]
@Elchi3 This _should_ be all the instances as far as I can tell at the moment?

**Comment by Elchi3** [comment]
Hm, not sure how to test. I could play with `npm run traverse -- css  -b ie -f false` and see how many features are affected:

If I checkout a commit before all the merges yesterday: 1300
If I checkout main: 1729
If I checkout this PR: 1649

This tells me we added 429 features in unreviewed PRs marked all of them as false. And now this PR reduces that to 349 as false and 80 as supported. Could that be? I guess a list of all added features would help to get a sense.

**Comment by queengooborg** [comment]
Hmm, I'm not really sure how to confirm if this is all of the instances either.  The best I've got is probably to check the diff between now and yesterday?

**Comment by queengooborg** [comment]
Okay, I just went through the commits one by one and updated the IE data accordingly!  Most of the property values that we do add _were_ actually not that old, it turns out!

**Review by Elchi3 — APPROVED** [review]
I don't know either. More research would have been helpful here. I'm merging this because I think this data is better than what was merged to main yesterday.

**Comment by queengooborg** [comment]
> More research would have been helpful here.

This is true, however...I think it's important to re-mention that IE is a browser that hasn't gotten a new release in over ten years, and has been out of support for almost two.  We have stated that we would not be maintaining IE data any longer, and in my opinion, this is maintaining IE data.  In a little over three months, the doors will be open for the discussion of possibly _removing_ IE data from BCD altogether.

**Pull request merged**
