### PR TITLE
CSS BackdropFilter Update

### PR DESCRIPTION
**Pull request by vsn4ik**

### CODE REVIEW

**Comment by vsn4ik** [comment]
@AdaRoseCannon confirm, please 🙏

**Comment by AdaRoseCannon** [comment]
Looks correct. I can test when I am back at work tomorrow.

**Comment by ddbeck** [comment]
@AdaRoseCannon do you still want to test this before merging?

This looks plausible to me (based on the Blink version mapping).

**Comment by AdaRoseCannon** [comment]
Sorry I've been super busy if it matches the blink version it's probably fine.

**Review by ddbeck — APPROVED** [review]
Thank you @vsn4ik (and @AdaRoseCannon)! 🎉

**Pull request merged**
