### PR TITLE
fix(css): rename 'Genearal sibling' to 'Subsequent-sibling'

### PR DESCRIPTION
**Pull request by OnkarRuikar**
- related to https://github.com/mdn/content/pull/29394

### CODE REVIEW

**Comment by teoli2003** [comment]
👍

**Comment by teoli2003** [comment]
@queengooborg or @Elchi3, I'm not sure if this needs a semver bump or not (or just an entry in the relnotes). It is a renaming of an existing feature.

**Comment by Elchi3** [comment]
I think this would not result in a semver bump given it is a lower-level namespace, see https://github.com/mdn/browser-compat-data#semantic-versioning-policy

**Comment by teoli2003** [comment]
Thank you!

**Pull request merged**
