### PR TITLE
Fix Firefox versions for `browser.action`

### PR DESCRIPTION
**Pull request by willdurand**
#### Summary

All `browser.action` methods have been added in Firefox 101.

### CODE REVIEW

**Comment by willdurand** [comment]
cc @rebloor

**Comment by rebloor** [comment]
@willdurand I don't follow, do you have a reference for this change?

**Comment by willdurand** [comment]
`action` was necessarily introduced in 101. It's a MV3 namespace.

**Comment by rebloor** [comment]
@willdurand I'm with you now, bemused how I made this mistake in the first place, it got past the linter, and review!

**Review by rebloor — APPROVED** [review]

**Pull request merged**
