### PR TITLE
Make note about return value of prompt()

### PR DESCRIPTION
**Pull request by jpmedley**
This pairs with [this content update](https://github.com/mdn/content/pull/19927). Here's [where the mistake was corrected](https://storage.googleapis.com/chromium-find-releases-static/69e.html#69eeb5b901d805ec2411212d52f1e8d935d58092).

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
I think this should use a range so it appears as "green" / good to use now. The bug is long time fixed.

Also, with mirroring, shouldn't we avoid browser names in notes? Otherwise "Chrome" will be mirrored into Edge, Opera, etc.

```
"chrome": [
              {
                "version_added": "76"
              },
              {
                "version_added": "44",
                "version_removed": "76",
                "partial_implementation": true,
                "notes": "Did not comply with the spec and resolved with an empty promise."
              }
```

**Comment by jpmedley** [comment]
I made that change. (I haven't made a BCD contribution in a while, so I hadn't thought through the implications of 'mirror'.)

Before we merge this, there's another issue I need your advice on. I've also discovered that the implementation released in 76 doesn't match the spec either. The object passed in the promise resolution should have one member called `userChoice`. In Chrome it's called `outcome`. How should this be handled.

**Comment by queengooborg** [comment]
> Also, with mirroring, shouldn't we avoid browser names in notes? Otherwise "Chrome" will be mirrored into Edge, Opera, etc.

This is no longer the case!  When mirroring, "Chrome" becomes the appropriate browser name now!

**Comment by Elchi3** [comment]
> Before we merge this, there's another issue I need your advice on. I've also discovered that the implementation released in 76 doesn't match the spec either. The object passed in the promise resolution should have one member called `userChoice`. In Chrome it's called `outcome`. How should this be handled.

I would say, it should be like this:

 ```
"chrome": [
               {
                 "version_added": "76",
                 "notes": "The object returned by the promise returns a property called <code>outcome</code> instead of <code>userChoice</code>."
                 "partial_implementation": true,
               },
               {
                 "version_added": "44",
                 "version_removed": "76",
                 "partial_implementation": true,
                 "notes": "Did not comply with the spec and resolved with an empty promise."
               }
             ],
```

**Comment by jpmedley** [comment]
Changes made. PTAL

**Review by Elchi3 — APPROVED** [review]

**Pull request merged**
