### PR TITLE
Update for Samsung Internet 14.0 (and one at 14.2)

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
This updates the data for Samsung Internet, it uses the mirror script to generate the changes.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Thanks @AdaRoseCannon!  Giving this PR a quick skim, there's some interesting changes coming from the mirror script that should be looked at a little more carefully.  While the first changes, which set `true` to `10.0`, are fine, I'm also noticing instances where the original version number is changed (i.e. `11.0` to `12.0`).

Can we revert changes to data that isn't `false` -> `14.0` (or the browser file, of course) so we can get this PR merged quicker?

**Comment by AdaRoseCannon** [comment]
Sorry for the slow response i've had a work blocker. Getting back to it now.

**Comment by AdaRoseCannon** [comment]
I fixed the 11.0 to 12.0 error, nice spot.

The ones which are changing to 14.2 are because it was a mistake we had decided to not support the prefers color scheme whilst we worked on our own implementation.

I also updated the browser data again since 14.0 just became stable

**Review by vinyldarkscratch — APPROVED** [review]
Alright, thanks for the updates!  I trust the data, and will merge this right away!

**Pull request merged**
