### PR TITLE
fix: rm notes on Intl.Locale, it does not require per-locale CLDR data, thus 12.0.0 Intl.Locale works just fine

### PR DESCRIPTION
**Pull request by longlho**

### CODE REVIEW

**Comment by Elchi3** [comment]
Hey @longlho, thanks for your PR! Did you see the discussion in https://github.com/mdn/browser-compat-data/pull/5068 that added these notes? Can you elaborate a bit more why the notes should be removed now?

**Comment by longlho** [comment]
Yup I was in that discussion :P

**Comment by Elchi3** [comment]
Looks good to me for `Intl.Locale`. This PR also removes the note from the main `Intl` feature. I guess it was added there for broader visibility? Are we okay removing it there?

**Comment by longlho** [comment]
I think it was just fat fingered. Back then all Intl APIs need that note except for Intl.getCanonicalLocales. However that's changing with Intl.Locale and the new Intl.Enumeration.

**Review by Elchi3 — APPROVED** [review]
Fair enough. It is just a note anyways (and not a note plus partial support). Let's do this, LGTM!

**Pull request merged**
