### PR TITLE
Add MathML spec URLs

### PR DESCRIPTION
**Pull request by sideshowbarker**

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Is it MathML 4 https://mathml-refresh.github.io/mathml/ or MathML Core https://mathml-refresh.github.io/mathml-core/ that we should be using here?

**Comment by sideshowbarker** [comment]
> Is it MathML 4 [mathml-refresh.github.io/mathml](https://mathml-refresh.github.io/mathml/) or MathML Core [mathml-refresh.github.io/mathml-core](https://mathml-refresh.github.io/mathml-core/) that we should be using here?

The existing MDN articles all cite mathml-core; e.g., https://developer.mozilla.org/docs/Web/MathML/Element/mn#specifications

So I think we should proceed for now at least with using the mathml-core URLs — because when we get to the point where we have the Specifications sections in MDN being generated from the BCD spec_url data, we’ll end up with the same URLs the existing MDN articles now have (basically), rather than something different.

**Comment by Elchi3** [comment]
Makes sense Mike but I will try my luck and ping Frédéric about this.

@fred-wang should MDN reference the MathML-4 or the MathML-core specification?

**Comment by fred-wang** [comment]
Hi. Personally, I think only MathML Core is relevant for native browser implementation.

**Review by Elchi3 — APPROVED** [review]
Thanks @fred-wang 👍 
LGTM @sideshowbarker 🎉

**Pull request merged**
