### PR TITLE
HTML Sanitizer API

### PR DESCRIPTION
**Pull request by Rumyra**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes

Adding data for the HTML Sanitizer API

- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)

https://bugzilla.mozilla.org/show_bug.cgi?id=1673309

- [x] Data: if you tested something, describe how you tested with details like browser and version

Code samples in docs run with flag enabled in FF84 https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer

- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)

Everything is passing locally 😅

- [x] Link to related issues or pull requests, if any

https://github.com/mdn/sprints/issues/3902

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@Elchi3 can we get a review on this one please mate? Thanks!

**Review by Elchi3 — APPROVED** [review]
Looks all good to me, nice work @Rumyra 👍 

The only question I would have is around the Firefox version. In the bug you reference, the tracking flags say "firefox83 | fixed", so maybe this is even available behind a pref in 83 already. Something you may be able to clear with the Mozilla engineer ;)

**Comment by Rumyra** [comment]
Thank you @Elchi3 !

From what I could tell from the thread Sanitizer was available in 82/83(?) but only put behind the correct pref in 84... https://phabricator.services.mozilla.com/D94704

I have asked for clarification on this and I am also unsure how this affects BCD 🤷🏻‍♀️ I went with my gut, but I'll see what the verdict is and can go back and change/note etc... 👍

**Review by Elchi3 — APPROVED** [review]
Awesome, then my intention about the tracking flags was right and 83 it is. (these flags are not very obvious to see in Bugzilla unfortunately)

**Pull request merged**
