### PR TITLE
Mark OffscreenCanvas support as partial in Firefox

### PR DESCRIPTION
**Pull request by jdashg**
Firefox's implementation is partial, and has known flaws, and should not
be considered "Full support behind a preference".

OffscreenCanvas support is likely something we (Firefox Graphics team) will be working on in 2020, but we shouldn't give the appearance it's right around the corner.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hey there, first of all, welcome to BCD!  Unfortunately this PR works against our 2019 goal to provide "real" values.  It is also invalid due to the fact that we know that there is support in Firefox, no matter how partial it may be.  If partial support is what you're looking for, BCD provides a `"partial_implementation": true` statement that lets consumers know that the API or feature is incomplete as per the spec design.

It would help to know your sources for this data as well so we can verify it!

**Comment by chrisdavidmills** [comment]
@vinyldarkscratch Jeff is a Firefox engineer on the graphics team; he knows ;-)

The partial implementation setting, IMO, does indicate some kind of usability of the feature (you can see an example rendering here: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto#Browser_compatibility)

In this situation it sounds like the feature is pretty broken, and behind a preference, in which case wouldn't it be better for users to mark it as false, with a note to explain that we do have something but it is not usable currently?

**Comment by jdashg** [comment]
I'm ok with either 'partial behind a flag' or 'none yet'. I've updated it to 'partial' for now, and we do intend for it to work eventually.

**Comment by vinyldarkscratch** [comment]
Thanks for confirmation, @chrisdavidmills, and thanks for the update, @jdashg!  I'm in favor of "partial support" personally, but I'm not strong on my opinion.  😛

Now that we have partial support set, do we also want to add the note suggested above?

**Comment by ddbeck** [comment]
For the record, partial with a note is the correct call here, now that we're writing down [guidelines for this sort of thing](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#non-functional-defined-names-imply-partial_implementation).

**Comment by jdashg** [comment]
I don't have anything useful to mention in the note, besides "support is partial".

PTAL?

**Comment by ddbeck** [comment]
@jdashg Is it possible there's a tracking bug or something to link for a reader to learn more about the implementation status on their own? I don't think we need a comprehensive explanation of what the API does or doesn't do (especially because it's not on by default), but it'd be nice to give a hint about the significance of the partial implementation flag.

**Comment by vinyldarkscratch** [comment]
Hey @jdashg, do you plan on returning to this PR sometime soon?

**Comment by ddbeck** [comment]
To keep things moving along here, I pushed changes to add a Bugzilla link for the partial implementation. I'd appreciate a review, @vinyldarkscratch.

**Pull request merged**
