### PR TITLE
Demix SVGAnimatedPoints to SVGPolygonElement and SVGPolylineElement

### PR DESCRIPTION
**Pull request by foolip**
Tests:
http://mdn-bcd-collector.appspot.com/tests/api/SVGPolygonElement
http://mdn-bcd-collector.appspot.com/tests/api/SVGPolylineElement

Since this is so old, mdn-bcd-collector can't be used to fill in the
exact versions. Instead, the data for &lt;polygon> and &lt;polyline> was
assumed to be largely correct:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polyline#browser_compatibility

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Looks good to me. It would be good to add spec_urls, though. Thank you! :)

**Comment by foolip** [comment]
`spec_url`s added!

**Review by Elchi3 — APPROVED** [review]
tack 👍

**Comment by foolip** [comment]
https://github.com/mdn/content/pull/5181 is the MDN side of this.

**Comment by ddbeck** [comment]
Sorry, I missed this one in last week's release notes. I opened https://github.com/mdn/browser-compat-data/pull/10893 to go back and add it.

**Pull request merged**
