### PR TITLE
Deno and Node support for non-registered symbols in `Weak{Map,Set,Ref}` and `FinalizationRegistry`

### PR DESCRIPTION
**Pull request by lionel-rowe**
#### Summary

Updated info about Deno and Node support for non-registered symbols as `Weak{Map,Set}` keys and as `WeakRef`/`FinalizationRegistry` targets.

I tested with the specified versions, but may well be supported by lower versions than these — not sure how important it is that the version specified is strictly the minimum requirement?

#### Test results and supporting details

```js
function assert(cond) {
    if (!cond) throw '!'
}

const tests = {
    WeakMap() {
        const wm = new WeakMap()
        const key = Symbol()
        const val = { data: 1 }
        wm.set(key, val)
        assert(wm.get(key) === val)
    },
    WeakSet() {
        const ws = new WeakSet()
        const key = Symbol()
        ws.add(key)
        assert(ws.has(key))
    },
    WeakRef() {
        new WeakRef(Symbol())
    },
    FinalizationRegistry() {
        new FinalizationRegistry(() => {}).register(Symbol())
    },
}

for (const [name, test] of Object.entries(tests)) {
    try {
        test()
        console.info(`✅ ${name} supported`)
    } catch(e) {
        console.error(`❌ ${name} unsupported`, e.message)
    }
}
```

#### Related issues

N/A

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey there, thank you for digging into this!

This is something that could definitely be added to the [`mdn-bcd-collector`](https://mdn-bcd-collector.gooborg.com/).  Would you be down to turn your test code into custom tests and submit a PR to the collector?  (Happy to help if needed!)

> I tested with the specified versions, but may well be supported by lower versions than these — not sure how important it is that the version specified is strictly the minimum requirement?

The `version_added` field should always be the earliest version the feature was supported in, rather than just the earliest version tested.  We do, however, have "range syntax" -- in other words, prepending a `≤` character to state the feature may have been supported earlier -- which is allowed for releases older than two years!

**Comment by lionel-rowe** [comment]
> This is something that could definitely be added to the [`mdn-bcd-collector`](https://mdn-bcd-collector.gooborg.com/). Would you be down to turn your test code into custom tests and submit a PR to the collector? (Happy to help if needed!)

Done - PR here: https://github.com/openwebdocs/mdn-bcd-collector/pull/1445

**Comment by lionel-rowe** [comment]
> The `version_added` field should always be the earliest version the feature was supported in, rather than just the earliest version tested. We do, however, have "range syntax" -- in other words, prepending a `≤` character to state the feature may have been supported earlier -- which is allowed for releases older than two years!

I've updated these too now.

**Review by queengooborg — APPROVED** [review]
Thank you, this is looking good to me!

**Pull request merged**
