### PR TITLE
Remove ConstrainLong and LongRange entries

### PR DESCRIPTION
**Pull request by foolip**
These are gone from the spec and MDN:
https://github.com/w3c/mediacapture-main/pull/515
https://github.com/mdn/content/pull/2995

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]

**Comment by ddbeck** [comment]
@foolip @Elchi3 can you explain this in a little more detail? Was this never actually supported or was it dropped and now being removed as irrelevant? Something else?

I ask because I don't know what to write in the release notes for this one.

**Comment by Elchi3** [comment]
My understanding of this PR is that these were renamed to
https://developer.mozilla.org/en-US/docs/Web/API/ConstrainULong
https://developer.mozilla.org/en-US/docs/Web/API/ULongRange

and the old names were dropped and now are now being removed as irrelevant here.

**Comment by ddbeck** [comment]
Very helpful, thank you!

**Comment by foolip** [comment]
It actually doesn't matter whether these types were ever used in implementations or not, because it amount to changing a signed integer to an unsigned one. This has happened a lot (I've done a lot of such spec matching) but it's almost always the case that the values that are actually returned are unchanged. In JS there are only numbers, so a change like this is usually impossible to observe, unless some place that could return a negative number is also updated at the same time.

**Pull request merged**
