### PR TITLE
id in history.onTitleChanged

### PR DESCRIPTION
**Pull request by rebloor**
#### Summary
Adds the `id` parameter to the `history.onTitleChanged` event. Provides the BCD data requested in [Bug 1756663](https://bugzilla.mozilla.org/show_bug.cgi?id=1756663).

#### Test results and supporting details
Test not yet completed, see https://github.com/mdn/browser-compat-data/issues/16716

### CODE REVIEW

**Comment by bershanskiy** [comment]
@rebloor I checked this commit out and ran test and got this:
```
Style - 1 problem (1 error, 0 warnings):
 ✖ webextensions\api\history.json - Error → → Error on line #312:
      → Actual:                    "firefox": {
      → Expected:                 "firefox": {
```
CI produces the same error.

A bit of general troubleshooting: could you run locally `npm run gentypes` and then `npm test`?

**Comment by bershanskiy** [comment]
@rebloor FYI, I created [this commit](https://github.com/bershanskiy/browser-compat-data/commit/1f949b64fcb28b8b645abab6227f46dc2986fbe1) with `npm run fix` and with it, the CI is passing.

**Comment by queengooborg** [comment]
I went ahead and applied the styling fix so that the CI now passes!

**Comment by bershanskiy** [comment]
Since CI passes, can we merge it now? I feel #16716 is an entirely separate issue.

**Comment by rebloor** [comment]
@bershanskiy running `npm run gentypes` didn't make any difference to the local test.

**Comment by bershanskiy** [comment]
Well, since CI passes, this change is probably safe to merge as is.
@rebloor If you would like to, I can try to reproduce #16716 and help you resolve it on Monday. I have a few theories which basically boil down to a different version of TS compiler or some other library being used here. If you want to, we can chat on Matrix.

**Review by queengooborg — APPROVED** [review]

**Pull request merged**
