### PR TITLE
Update Samsung Internet Data, Updating folder css/

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
This is part of #5028 to update the CSS data for Samsung Internet.

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
Is it possible to trigger a rebuild now #5034 has merged?

**Comment by Elchi3** [comment]
Could rebase against latest master, so that #5034 is actually included here? Then this would be rebuilt also.

**Comment by vinyldarkscratch** [comment]
Hey @AdaRoseCannon, I noticed you've been force-pushing -- in this repository, we actually strictly perform squash merging, so you can keep however many commits you desire on your end!  :wink:

**Comment by vinyldarkscratch** [comment]
Just a thought: since this PR still has so many files being modified, I'm thinking that maybe we should split it up by subfolder (so `at-rules`, `properties`, etc.)?  It'll probably make review go much faster!

**Comment by AdaRoseCannon** [comment]
Sure i'll open some more PRs.

**Pull request closed without merging**
