### PR TITLE
Update Chrome versions for stretch value

### PR DESCRIPTION
**Pull request by saschanaz**
Following #2842.

### CODE REVIEW

**Comment by jpmedley** [comment]
@Elchi3 Can you please back this out? Among the problems I've found so far:
* I can find no evidence that `-webkit-fill-available` is still supported. (If it's supported, it's supposed to be listed [in this file](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/virtual/stable/webexposed/css-property-listing-expected.txt?q=css-property-listing-expected.txt&sq=package:chromium&g=0&l=1). )
* The other prefixed properties are supported, but I haven't found a number yet.

**Comment by saschanaz** [comment]
Not sure what happened to that file but I can confirm that it works on the latest Chrome.

**Comment by jpmedley** [comment]
Are you referring to `-webkit-fill-available`?

**Comment by saschanaz** [comment]
Yes, try this short example (although it's only for `max-height`): https://codepen.io/SaschaNaz/pen/XxgGgL

**Comment by Elchi3** [comment]
> @Elchi3 Can you please back this out? Among the problems I've found so far:

Rather than backing this out, would it be possible that either one of you opens a PR with the corrections for this? Otherwise please click on "Revert" on this PR and I will review the revert.
Thank you!

**Pull request merged**
