### PR TITLE
Move getSelection to Document and ShadowRoot; Mark ShadowRoot.getSelection as non-standard.

### PR DESCRIPTION
**Pull request by Elchi3**
Fixes https://github.com/mdn/browser-compat-data/issues/7891
Spec: https://w3c.github.io/selection-api/#extensions-to-document-interface

Delete getSelection from DocumentOrShadowRoot files and add it to Document. On Window, it already exists.

MDN content PR: https://github.com/mdn/content/pull/3037

### CODE REVIEW

**Comment by foolip** [comment]
Chromium does have ShadowRoot#getSelection because it's in the `DocumentOrShadowRoot` mixin here:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/dom/document_or_shadow_root.idl;l=12?q=shadow_root.idl

Also confirmed with https://mdn-bcd-collector.appspot.com/tests/api/ShadowRoot/getSelection 

However, that entry isn't on the same footing as the one on `Document`. It should be marked as non-standard and supported only in Chromium browsers, presumably.

**Comment by foolip** [comment]
https://github.com/w3c/selection-api/issues/114 is the spec issue for this situation.

**Comment by foolip** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/9434. With that merged it should be a simple matter of moving the entries around.

**Comment by Elchi3** [comment]
Thanks @foolip! Now this PR looks a bit more silly than before, but I guess it is still correct given the chromium implementation could remain non-standard.

**Review by foolip — COMMENTED** [review]
Shouldn't the other one also be moved and have its `mdn_url` either updated or removed?

**Comment by Elchi3** [comment]
Moved It and removed the mdn_url.

We will see long-term if all this moving around makes sense. It doesn't change what BCD exposes after all.

**Review by foolip — APPROVED** [review]
I'll leave merging to you, since the description needs updating.

**Pull request merged**
