### PR TITLE
Introduce Mocha to test test/utils.js

### PR DESCRIPTION
**Pull request by foolip**
Also enable colors in GitHub Actions for nicer logs.

Fixes https://github.com/mdn/browser-compat-data/issues/6855.

### CODE REVIEW

**Comment by ddbeck** [comment]
Blocked by #5931 or, more concretely, merging `master-scoped-package` into `master`. See also #6640.

**Comment by foolip** [comment]
This is now ready for review.

**Comment by ddbeck** [comment]
@foolip I'm done wrecking `package-lock.json` for the day. I suspect this will be a quick merge, after a rebase.

**Comment by foolip** [comment]
@ddbeck this is rebased an passing on GitHub Actions now.

**Review by ddbeck — APPROVED** [review]
Thank you—excited to do more with this! 🎉

**Pull request merged**
