### PR TITLE
Add impl_url entries for safari and firefox's field-sizing property

### PR DESCRIPTION
**Pull request by captainbrosset**
#### Summary

This PR adds links to the Safari and Firefox bug trackers where the implementation of the `field-sizing` CSS property is being tracked.

#### Test results and supporting details

N/A

#### Related issues

Firefox: https://bugzil.la/1832409

Safari: https://webkit.org/b/269125

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
The webkit bug is closed. Is https://bugs.webkit.org/show_bug.cgi?id=264720 the better bug to reference?

**Comment by captainbrosset** [comment]
@Elchi3 I'm not sure, the one I referenced _is_ the parent bug that, in theory, covers the entire feature. See the dependency tree:

image

Also, this [WebKit commit](https://github.com/WebKit/WebKit/commit/bcca5fc0fa1715d7da3e05cac22fb460a12539f0) seems to confirm that [269125](https://webkit.org/b/269125) is the right bug.

I'm surprised that it got closed without its children bugs getting closed.

Maybe this means the feature is only partially implemented, but in that case, I don't know which other parent/umbrella bug to point to.

**Comment by captainbrosset** [comment]
Maybe @lukewarlow can help us find the right bug that BCD should point to here?

**Comment by lukewarlow** [comment]
Ah actually your screenshot shows the right thing. They have a tree for what it blocks so that bug blocked the main one and others. It's a slightly confusing view tbh.

**Comment by captainbrosset** [comment]
Oh perfect! Thanks for commenting so quickly. I totally misread that view, indeed. Updating the bug.

**Review by Elchi3 — APPROVED** [review]
Thanks @captainbrosset and @lukewarlow 👍

**Pull request merged**
