### PR TITLE
Fold api.FullscreenOptions into api.Element.requestFullscreen

### PR DESCRIPTION
**Pull request by foolip**
The options_parameter entry by itself doesn't represent anything useful,
and navigationUI is the only dictionary member, so let the entry
represent that.

### CODE REVIEW

**Comment by foolip** [comment]
I am not planning to send the mdn/content PR myself right now. If this gets reviewed and is blocked by that I will, but sometimes someone volunteers to do it, so holding out hope for that :)

**Comment by Elchi3** [comment]
I enjoy being that volunteer: https://github.com/mdn/content/pull/6852

**Comment by foolip** [comment]
Thanks @Elchi3!

**Review by Elchi3 — APPROVED** [review]
Content PR was merged

**Pull request merged**
