### PR TITLE
Add irrelevant flag data removal data guideline

### PR DESCRIPTION
**Pull request by ddbeck**
This PR proposes a limited flag data removal policy, inspired by the [_Removal of irrelevant features_](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md#removal-of-irrelevant-features) policy.

The intent here is to allow judicious removals of valid but historic flag data. This should make it easier for contributors to improve data, such as in #6658. Also, please see https://github.com/mdn/browser-compat-data/issues/3318#issuecomment-691034407 for more about the issue of flag data in general.

### CODE REVIEW

**Comment by ddbeck** [comment]
@foolip would a policy like this satisfy for data removals such as those in #6658? I tried to tailor it narrowly, but like your impressions as someone who's been dealing with this directly.

**Comment by jpmedley** [comment]
@foolip Chrome 70 was released in stable on September 4, 2018. It looks like anything older than that could be removed.

**Comment by foolip** [comment]
Thanks for looking that up @jpmedley! That means this would allow removing the flags I was just dealing with, which is great!

@ddbeck is there a process for getting this guideline adopted? Just wait for feedback for a while?

**Comment by Elchi3** [comment]
I like this (conservative) approach to remove flag data. With the two conditions you are introducing, it seems to me that data will still make sense and useful to web developers (which is what BCD drives ultimately). 

> other considerations may result in flag data continuing to be relevant, even after the guideline conditions are met.

I think this is great to mention as well. I think if someone proposes a scripted update to BCD to apply this new rule broadly, they should probably check any situation where the support data contains extra data such as notes. (maybe we want to specifically mention notes in this sentence).

The following isn't even MDN data, but I leave it here for illustration for the impact I think it has on the caniuse rendering.

https://caniuse.com/?search=streams

| Now | Proposed | 
|:-:|-|
| streams-1  |  streams-2  |

On MDN, as you've discussed, the impact _should_ be even more minor given the current rendering displays historic flags only after you've clicked the drop down. I say _should_, because we haven't solved #1596 yet. So, another gotcha when mass updating historic flag data, is to look into the ordering of our support array. The ordering is unfortunately relevant to the current MDN rendering. caniuse has the better (guaranteed chronological) rendering.

I share all the arguments from the data maintainer's point of view that have been shared in the mentioned issues and I hope this will make things a bit easier. Thanks for thinking this through in a more nuanced way than just dropping all flag data like it was talked about before. r+ from my side.

**Comment by ddbeck** [comment]
> @ddbeck is there a process for getting this guideline adopted? Just wait for feedback for a while?

I didn't really have a plan before. Since it sounds like this guideline is well-received, I don't expect to revise it. But just in case, I'll leave the PR open until at least the end of my work day tomorrow. If there are no objections, I'll merge it then.

**Comment by foolip** [comment]
*Thank you* @ddbeck for getting this done. I'll be happily removing old flag data now when it gets in the way of fixing a problem with the rest of the data.

**Pull request merged**
