### PR TITLE
Some updates for URL.json based on MDN-Confluence.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by Mouvedia** [comment]
This is incorrect. These properties were supported before version 10.

**Comment by jpmedley** [comment]
@foolip @mdittmer I would only add Safari values that came from Confluence. Philip and Mark, is this a false positive?

**Comment by Mouvedia** [comment]
One thing to be aware of if you are doing test, you gotta test that properties do return something.

e.g. Safari on iOS7 produces
```js
Object.prototype.toString.call(instance) === '[object URL]'; // true
instance.href; // undefined
```

**Comment by mdittmer** [comment]
@jpmedley I'm not sure whether or not this is a problem with Confluence. You could poke around with URL objects in BrowserStack to find out.

I spot checked [URL.hostname](https://web-confluence.appspot.com/#!/catalog?releases=%5B%22Safari_9.1.3_OSX_10.11.6%22,%22Safari_10.1.2_OSX_10.12.6%22,%22Safari_11.0.3_OSX_10.13.3%22,%22Safari_11.1_OSX_10.13.4%22%5D&q=%22url%23hostname%22) and the fact that Confluence found `webkitHostname` but not `hostname` in Safari 9 seems like a pretty strong signal that only the webkit-prefixed version existed before Safari 10.

**Comment by jpmedley** [comment]
Is not being able to see prefixed versions of APIs a general limitation of
confluence, or is this something more specific?
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by mdittmer** [comment]
It doesn't treat prefixed APIs specially. They are seen as their own API
with the prefix as part of the name.

**Comment by foolip** [comment]
Indeed, the underlying data probably has webkitURL going back a long time. However, I presume that the mdn-confluence tool doesn't try to consolidate prefixed and unprefixed APIs to be able to say that an API was prefixed-only before some point. @mdittmer is that right?

**Comment by mdittmer** [comment]
@foolip that's correct

**Pull request merged**
