### PR TITLE
Bug 1479935 - Add/enable Clipboard read/write methods

### PR DESCRIPTION
**Pull request by a2sheppy**
Firefox 63 implements the read/write async methods on
the Clipboard API.

### CODE REVIEW

**Comment by a2sheppy** [comment]
Added notes about limitations on availability in Firefox.

@Elchi3 As for the other changes suggested, I was planning to do those in a follow-up PR since they're not on the Clipboard interface itself. That PR will come later this morning.

**Comment by Elchi3** [comment]
> Added notes about limitations on availability in Firefox.

I don't know where this info is from, so it's hard to review. Is there a reason you used two kinds of notes and not all the same for everything?

**Comment by a2sheppy** [comment]
@Elchi3 The information comes from an IRC conversation with annyG, who did the work. Quote:

> sheppy: currently clipboard.writeText is available to secure contexts and web extensions (without the need to require permissions) - it is available under the same conditions as document.execCommand("copy"), and clipboard.readText is available to web extensions only. currently there is no way to expose clipboard.readText to web content. I am also cc'ing nika: for help with this question and perhaps elaboration of future plans

As to this question:

> I don't know where this info is from, so it's hard to review. Is there a reason you used two kinds of notes and not all the same for everything?

I'm not exactly sure what you're asking -- but if you mean why is the text different between the readX() and writeX() methods, it's because availability is not the same. Writing is available from extensions and other secure contexts, while reading is only available to extensions.

I did just realize I don't mention the lack of need to get permission before using this API, though. That needs to be noted, so I'll add another fix to this PR as soon as I get one bit of info from annyG or nika -- it seems unlikely that writing doesn't need permission but reading does, so I want to confirm that.

**Comment by Elchi3** [comment]
> if you mean why is the text different between the readX() and writeX() methods, it's because availability is not the same. Writing is available from extensions and other secure contexts, while reading is only available to extensions.

Thanks, for the explanation. It was not clear to me from just reading the notes here.

**Comment by a2sheppy** [comment]
This is followed up by PR #2676 to set support flags to false for Firefox (the permissions aren't supported even though the API's functions are).

**Comment by a2sheppy** [comment]
More changes coming in; just discovered that the non-text versions of these methods are not enabled in 63 by default.

**Comment by Elchi3** [comment]
Thanks for the updates. I'm still not sure I have all the information sources to review this in detail, but I'm assuming you got this right now. To summarize what this PR changes in case anyone with more clipboard API Firefox implementation knowledge reviews this:

- `navigator.clipboard`: 
  - Enabled by default in Firefox 63
  - No pref
  - No restrictions
- `Clipboard interface`: 
  - Enabled by default in Firefox 63
  - No pref
  - No restrictions
- `Clipboard.read`: 
  - In Firefox 63
  - Behind dom.events.asyncClipboard.dataTransfer pref, 
  - Web: not available
  - Browser extensions: only when using the "clipboardRead" extension permission.
- `Clipboard.readText`: 
  - Enabled by default in Firefox 63
  - No pref
  - Web: not available
  - Browser extensions: only when using the "clipboardRead" extension permission.
- `Clipboard.write`: 
  - In Firefox 63
  - Behind dom.events.asyncClipboard.dataTransfer pref,
  - Web: available without permission in secure contexts from user-initiated event callback
  - Browser extensions: available with the clipboardWrite" permission
- `Clipboard.writeText`: 
  - In Firefox 63
  - No pref
  - Web: available without permission in secure contexts from user-initiated event callback
  - Browser extensions: available with the clipboardWrite" permission

**Comment by a2sheppy** [comment]
@Elchi3 You have it exactly right.

**Pull request merged**
