### PR TITLE
Add fix script to sort browsers and features

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR is a subset of #3427 that introduces strictly the fix script that sorts features and browsers.  Browsers are sorted completely alphabetically, while the features are sorted based upon the following order:

1. `__compat`
2. Alphanumerical features (no symbols other than - or _)
3. Features with symbols other than - or _

Browsers and features can be sorted at any time by running `npm run fix`.

### CODE REVIEW

**Comment by ddbeck** [comment]
Hey @vinyldarkscratch this is a really good start. One thing I'd like to see added here is a couple tests:

* a unit test of `compareFeatures` (e.g., given an unsorted array of strings, use `compareFeatures` to sort that array to the expected sort) — this will help illustrate the sort itself, as an example, in addition to validating that it works as expected
* a test of the whole fix script against a test file, with an expected output (e.g., something that demonstrates that the keys get sorted and no other data is changed) — this will help build confidence that when we run the script against the entire data set, no data will be mangled in the process

**Comment by vinyldarkscratch** [comment]
Happy to add the unit tests, yeah!  Where should said tests belong?  My biggest thought would be some sort of `test-fix.js` file, does that seem reasonable?

**Comment by ddbeck** [comment]
Yeah, that does seem reasonable. Though maybe the fix files themselves should be in `/scripts` and the tests for the fix files should be in `/test`—thought that's a pretty trivial thing, really. Add the tests where you like now and we can rethink organization organization if it seems off.

**Comment by vinyldarkscratch** [comment]
Sure thing!  I’ll add it into the specified file first thing after I get some well-needed sleep.  😉

**Comment by vinyldarkscratch** [comment]
I just added the unit test for the function, as well as separated the sort function into its own file.  I decided to leave everything in `/test` for now to assist with imports, however `/scripts` **is** probably a better place for the fix scripts, something to think about in the future?

How does this PR look, though?

**Comment by Elchi3** [comment]
Oh and yes, the sorting order as proposed is the one that makes sense to me.

**Comment by ddbeck** [comment]
>  Yeah, I think a sub folder like scripts/migrations/ would be cool. These are things we would probably run once ideally. I think in real db migrations like in the Django world, you also number them to indicate on which order they have been run. So, maybe we sort features first, so you have 001-sort-features.js and then 002-sort-browsers.js. Not a requirement, just an idea :)

We've got a little bit of a special case here in that the fix script is going to be both a one-time event (running against the whole repo) and a reusable utility (e.g., you've added a new feature to the end of a file, then run the fix script to sort the features). But you raise an important point here about there being two significant bulk changes.

Here's a revised structure:

1. Move the `fix` scripts to to `/scripts`.
1. Modify `fix-browser-order.js` and `fix-feature-order.js` to be independently runnable (e.g., add a `if (require.main === module)` block to each).
1. For the migration bookkeeping, add `/scripts/migrations/001-sort-features.js` and `/scripts/migrations/002-sort-browsers.js` as wrappers on their respective fix scripts.

Then we'll do two migration PRs. Tidy!

And, yeah, no more tests are needed on this.

**Comment by vinyldarkscratch** [comment]
(Apologies for the delays, I've been on two back to back business trips!)

Sure thing!  I will admit that this is where my lack of NodeJS knowledge starts to get a little more visible (I'll be violating the don't-repeat-yourself rule a tiny bit), but I'm applying changes now.  :wink:

**Comment by Elchi3** [comment]
I've given this another look and I think this is ready. Great work!

Do we merge this now and then think about when to best run the migrations? I guess when to run it depends on how many open PRs the migrations would affect?

**Comment by ddbeck** [comment]
That sounds right to me. The next steps are probably:

1. Merge this PR.
1. In the relevant issues/PRs (I don't think there's one for the browser sort—we'll need a new issue for that), list the PRs expected to be impacted by running a migration script.
1. Decide which, if any, of those PRs are considered blocking.
1. When the migration is unblocked, @vinyldarkscratch and I schedule a time to open, review, and merge the migration.

Does that make sense @Elchi3 and @vinyldarkscratch?

**Comment by Elchi3** [comment]
Sounds great to me! Looking forward to seeing this happen :)

**Comment by vinyldarkscratch** [comment]
Sounds like a plan to me!  It appears that there's three data categories with open PRs: API, CSS, and HTML.  (Also, right off the bat, I'd assume that the other bulk updates would be considered blocking, primarily due to their nature.)

I will give the script a test run now and prepare a list of potentially blocking PRs!  :wink:

**Comment by vinyldarkscratch** [comment]
Looks like the script (both browsers and features) affects four folders: API, CSS, JavaScript, and WebExtensions.  All other folders pass the linter (probably from changes performed before formalizing the bulk update process).  The good news is that there doesn't seem to be that many non-bulk PRs that are potentially blocking changes!

From what I can see, all the other PRs with the `bulk_update` label are blocking changes.  The first three that set true/false values, however, I would say can be dismissed (they set true/false based upon implementation in the browser's IDE files, which we have found has discrepancies, and thus the PRs are just there for keepsake).  All the other ones are basically just mirroring Chrome, Firefox, and Safari forks/mobile counterparts.  Aside from that, it appears that #3946, #4049, #4378, #4578, and #4606 all have changes that would conflict with the fix script's.

**Comment by ddbeck** [comment]
@vinyldarkscratch the impacted PRs here, are they impacted by both the browser sort and the feature sort, or just one or the other?

**Comment by vinyldarkscratch** [comment]
The browser sort doesn't actually have any changes to make, so it's all the feature sort.  Both the feature sort and the mentioned PRs affect the same files (but to be honest, I haven't tested for conflicting diffs specifically -- mostly since this PR will be creating a LOT of them).

**Comment by ddbeck** [comment]
OK, I'm going refrain from having issues to track both fixes then. Seems pointless and noisy when there's only one true migration to make. Here's what I think should happen instead:

## Browser sorting:

Assuming that `001-sort-browsers` is a no-op,

- [ ] Drop the `001-sort-browsers` migration from this PR
- [ ] Open a new PR to enforce browser sorting (since it sounds like we can proceed with this immediately, without waiting on anything else)

## Feature sorting

- [ ] Renumber the `002-sort-features` migration in this PR
- [ ] Wait for #4606 to merge or close (all of the other blocking PRs mentioned have been merged)
- [ ] Schedule our first migration
- [ ] Merge this PR (the merge itself can happen as soon as the migration is scheduled)

**Comment by vinyldarkscratch** [comment]
#4665 has now been created which enforces browser sorting!  (Don't mind the ugly-looking Git history on that -- it's a branch from the feature sorting.  :P)

**Comment by ddbeck** [comment]
Hooray! I am very hopefully we're on the final stretch of this. Thank you for helping on this new process!

Also, all pretty Git histories are lies.

**Comment by vinyldarkscratch** [comment]
Good news: as of this writing, all blocking PRs have now been merged, so we can schedule the migration!

**Comment by ddbeck** [comment]
Great! I sent you an email to pick out at time.

**Comment by ddbeck** [comment]
OK, we've scheduled the migration for Tuesday, August 27. Going to merge this now.

**Pull request merged**
