### PR TITLE
Remove Feature-Policy HTTP header from BCD

### LINKED ISSUE #9556: "Feature Policy" has been renamed "Permissions Policy"
https://github.com/mdn/browser-compat-data/blob/master/http/headers/feature-policy.json

- File and feature name will need to be renamed.
- Name change history will need to be captured.

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the `Feature-Policy` HTTP header from BCD. This fixes #9556 by removing the old file for `Feature-Policy`, which has already been folded into the new `Permissions-Policy` header.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Any reason not to merge this?

**Comment by queengooborg** [comment]
Not that I would know of, I've just been waiting on approval before making the content changes and merging.

**Comment by hamishwillee** [comment]
I can't grant approval. But content is changed earlier in the year or even last year.

**Comment by hamishwillee** [comment]
Hurray!

**Pull request merged**
