### PR TITLE
inset-area renamed to position-area

### PR DESCRIPTION
**Pull request by chrisdavidmills**
**DO NOT MERGE THIS UNTIL THE ASSOCIATED DOCS UPDATES ARE DONE**: see https://github.com/mdn/content/pull/35390

#### Summary

The [CSS Anchor Positioning](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_anchor_positioning) `inset-area` property has been renamed to `positioned-area`. See the [change discussion](https://github.com/w3c/csswg-drafts/issues/10209), and the [`position-area`](https://drafts.csswg.org/css-anchor-position-1/#propdef-position-area) spec definition.

I have been told by Chrome engineering that `position-area` is being added alongside `inset-area` as of Chrome 129, and they are removing it around Chrome 132-ish (I'll make changes related to that in a subsequent PR).

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@Elchi3 ack. I just noticed that you've already submitted a PR for this; sorry about that. Before closing, you might want to check mine to see if there is anything else you should include in yours.

**Comment by Elchi3** [comment]
Thanks Chris, my PR is more minimal as it doesn't record any data about Chrome 129 yet. (there is no beta for 129 just yet and we can't yet verify if the rename really ships in 129). 

The fact that you had to add new entries to the browser/ folder is a good warning sign that compat data is being added prematurely. So, my recommendation would be to merge my PR and wait until we're in the 129 beta cycle for any other changes. Does that make sense?

**Comment by chrisdavidmills** [comment]
> Thanks Chris, my PR is more minimal as it doesn't record any data about Chrome 129 yet. (there is no beta for 129 just yet and we can't yet verify if the rename really ships in 129).
> 
> The fact that you had to add new entries to the browser/ folder is a good warning sign that compat data is being added prematurely. So, my recommendation would be to merge my PR and wait until we're in the 129 beta cycle for any other changes. Does that make sense?

@Elchi3 that works for me. Get yours merged, and let me know when that happens, then I'll merge the corresponding content PR. Then let's revisit this once the 129 beta cycle starts.

**Comment by Elchi3** [comment]
@chrisdavidmills can you review https://github.com/mdn/browser-compat-data/pull/23993? That could land and then I can see about Chrome 129 next week with a collector run.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills can you review #23993? That could land and then I can see about Chrome 129 next week with a collector run.

Done!

**Comment by Elchi3** [comment]
Closing in favor of https://github.com/mdn/browser-compat-data/pull/24210

**Pull request closed without merging**
