### PR TITLE
Update LargestContentfulPaint spec URLs

### PR DESCRIPTION
**Pull request by sideshowbarker**
These should be using https://w3c.github.io/largest-contentful-paint URLs rather than https://www.w3.org/TR/largest-contentful-paint URLs.

### CODE REVIEW

**Comment by sideshowbarker** [comment]
CI is failing on this because the current Editors Draft URL not in browser-specs generated `index.json` file — and the reason it’s not is that I think browser-spec gets the ED URL from scraping https://www.w3.org/TR/largest-contentful-paint/ and that incorrectly still has https://wicg.github.io/largest-contentful-paint as the ED URL.

The ED moved from wicg.github.io to w3c.github.io a while back. And https://github.com/w3c/largest-contentful-paint/commit/4a0930ca74a98941237635424cd34c8a44825b2d updated the ED URL in the spec source a few days ago, but that’s not yet been pushed/re-published to https://www.w3.org/TR/largest-contentful-paint.

So pinged one of the spec’s editors to ask them to update it. After they update, I guess we need to wait for browser-specs to be rebuild (and re-released?).

**Comment by foolip** [comment]
> So pinged one of the spec’s editors to ask them to update it. After they update, I guess we need to wait for browser-specs to be rebuild (and re-released?).

Yes, and for Dependabot to send a PR to update the dependency in BCD.

**Comment by organicghemp** [comment]
> Estos deben usar [URL https://w3c.github.io/largest-contentful-paint](https://w3c.github.io/largest-contentful-paint) en lugar de [URL https://www.w3.org/TR/largest-contentful-paint](https://www.w3.org/TR/largest-contentful-paint).

**Comment by queengooborg** [comment]
Perhaps we should add this as an exception to the spec URLs test, and then remove it when the spec URLs are updated?

**Pull request merged**
