### PR TITLE
Add RelativeTimeFormat constructor

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change updates the spec URL for the Intl.PluralRules constructor (subfeature of the Intl.PluralRules object), to point to the specific section of the Ecma 402 spec about the constructor itself.

Otherwise, without this change, the spec URL instead points to the general section introduction for the Intl.PluralRules object. But in the BCD content, we already have a spec URL for the Intl.PluralRules objects itself (the parent feature of the subfeature this patch changes).

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
From what I can tell in the other JavaScript objects, they all seem to point to the objects themselves, and not specifically the constructor.  (Feel free to correct me if I'm wrong -- I just skimmed through a couple of existing files.)  Is there a particular reason to point to the constructor specifically?

**Comment by sideshowbarker** [comment]
> Is there a particular reason to point to the constructor specifically?

The corresponding MDN articles are specifically about the constructors:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules

Also note the following change from @Elchi3 that explicitly changed the MDN article’s spec URL to point to the specific spec section for the constructor:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat$compare?to=1451597&from=1451583

**Comment by vinyldarkscratch** [comment]
Gotcha -- I don't feel 100% confident in my reviewing abilities on this particular PR, so I will request @Elchi3's review for when they return!

**Comment by sideshowbarker** [comment]
OK, based on having looked into things a bit further, I just force-pushed a change the drops the `RelativeTimeFormat` part of the patch and only updates the `PluralRules` part.

Here’s the summary:

So, I noticed that in the BCD content we already have a spec URL for the `PluralRules` object itself:

https://github.com/mdn/browser-compat-data/blob/830b9501485f70d9af3d262b95ec26e1f7cb2190/javascript/builtins/Intl.json#L2289-L2292

…but there’s another `PluralRules` that’s a “subfeature”:

https://github.com/mdn/browser-compat-data/blob/830b9501485f70d9af3d262b95ec26e1f7cb2190/javascript/builtins/Intl.json#L2340-L2344

…and as can be seen that has `"<code>PluralRules()</code> constructor"` as its description. So the current patch in the PR is changing the spec URL for that one (not the parent `PluralRules` object).

But in comparing what we currently have in BCD for the `RelativeTimeFormat` object, I found that there’s only the `RelativeTimeFormat` object itself:

https://github.com/mdn/browser-compat-data/blob/830b9501485f70d9af3d262b95ec26e1f7cb2190/javascript/builtins/Intl.json#L2598-L2601

…but there’s no “subfeature” for the `RelativeTimeFormat` constructor specifically.

So I updated the PR to not change the `RelativeTimeFormat` spec URL. It seems like instead what we should do there is to have a separate patch/PR that adds a subfeature specifically for the constructor (to correspond to how the `PluralRules` data handles the similar case).

**Comment by Elchi3** [comment]
There seems to have been some back and forth and now I'm not sure I understand what this PR tries to do.

Before this PR, we have:

- javascript.builtins.Intl.PluralRules: https://tc39.es/ecma402/#pluralrules-objects
- javascript.builtins.Intl.PluralRules.PluralRules: https://tc39.es/ecma402/#sec-intl-pluralrules-constructor
- javascript.builtins.Intl.RelativeTimeFormat: https://tc39.es/proposal-intl-relative-time/#relativetimeformat-objects

With this PR, we get:

- javascript.builtins.Intl.PluralRules: https://tc39.es/ecma402/#sec-intl-pluralrules-constructor
- javascript.builtins.Intl.PluralRules.PluralRules: https://tc39.es/ecma402/#sec-intl-pluralrules-constructor
- javascript.builtins.Intl.RelativeTimeFormat: https://tc39.es/proposal-intl-relative-time/#relativetimeformat-objects

I would expect the fix to be:

- javascript.builtins.Intl.PluralRules: https://tc39.es/ecma402/#pluralrules-objects
- javascript.builtins.Intl.PluralRules.PluralRules: https://tc39.es/ecma402/#sec-intl-pluralrules-constructor
- javascript.builtins.Intl.RelativeTimeFormat: https://tc39.es/proposal-intl-relative-time/#relativetimeformat-objects
-  (new) javascript.builtins.Intl.RelativeTimeFormat.RelativeTimeFormat: https://tc39.es/proposal-intl-relative-time/#sec-intl-relativetimeformat-constructor

**Comment by sideshowbarker** [comment]
Ack. I’m not ignoring this — just haven’t made time yet to get back to it

**Comment by ddbeck** [comment]
Hi @sideshowbarker, let us know if you expect to come back to this—if not, we can take over these changes, if needed. Thank you!

**Comment by sideshowbarker** [comment]
> Hi @sideshowbarker, let us know if you expect to come back to this—if not, we can take over these changes, if needed. Thank you!

Yes, if y’all have time to get to it, please feel free to take it over — either by picking up this PR, or else raising a new one (in which case we could just close this one).

(And apologies for not having made time yet to get back to this…)

**Comment by Elchi3** [comment]
I've updated this here now. The idea is that we should add a RelativeTimeFormat constructor, so that the data and the spec references are more consistent. See my comment above.

**Comment by Elchi3** [comment]
Thanks for bringing this up @sideshowbarker :+1:

**Comment by sideshowbarker** [comment]
Cheers

**Pull request merged**
