### PR TITLE
Fixes to api.HTMLImageElement

### PR DESCRIPTION
**Pull request by a2sheppy**
Changes made to HTMLImageElement:

* One wrong link fixed
* Fixed capitalization of `crossOrigin`
* Added missing `error_event` entry

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Looking pretty good!  For documentation's sake, where did "51" come from for the error event if I may ask?  I noticed the note mentioning that it may be supported even earlier, so I'm wanting to follow up on that.

**Comment by a2sheppy** [comment]
I literally copied the data from “onerror”. I generally assume that support
for on<eventname> means the event <eventname> is also supported. :)

On August 29, 2019 at 3:37:53 PM, Queen Vinyl Darkscratch (
notifications@github.com) wrote:

Looking pretty good! For documentation's sake, where did "51" come from for
the error event if I may ask? I noticed the note mentioning that it may be
supported even earlier, so I'm wanting to follow up on that.


Eric Shepherd
Senior Technical Writer
MDN Web Docs <https://developer.mozilla.org/>
Blog: https://www.bitstampede.com/

**Comment by thw0rted** [comment]
This commit touches on the `error` event, which shows up as unsupported in Chrome and Edge.  It works today, though I haven't done any kind of regression checks to see if there was a point in the past where it didn't.  Any ideas how we got here?  (I commented on https://github.com/mdn/browser-compat-data/pull/388 looking for more insight, also.)

**Comment by vinyldarkscratch** [comment]
@thw0rted, can you open up a new issue for this?

**Pull request merged**
