### PR TITLE
Mark parent as true when children are truthy in api/*

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR marks features as supported if their children contain a true-based value (either "true" or a version number).  NOTE: This should be reviewed with extreme caution, as the data has not been validated for accuracy, only consistency.

### CODE REVIEW

**Comment by ddbeck** [comment]
> NOTE: This should be reviewed with extreme caution, as the data has not been validated for accuracy, only consistency.

OK, this is just me talking here—I'm not putting forward a _policy_—but I think a PR with a lot of automated changes of unknown quality needs to do more to guide reviewers.

Is it possible you could generate a list of changes made here with their antecedents? For example, if some value is flipped to true, then I'd like to know what subfeature(s) caused that to bubble up without having to dig through the full JSON myself to reverse engineer a justification for a change.

I realize that's some extra work. But I worry changes like this will languish until someone gets _seriously_ motivated to go through a set of changes of this side. (I suppose that's the alternative: slice this into very fine pieces so they can be reviewed and merged separately.)

**Comment by vinyldarkscratch** [comment]
Sorry for the delays in responding to this!  I took a small break from BCD to give some well-needed TLC to my business' website.

> Is it possible you could generate a list of changes made here with their antecedents? For example, if some value is flipped to true, then I'd like to know what subfeature(s) caused that to bubble up without having to dig through the full JSON myself to reverse engineer a justification for a change.

Yeah, I could totally do this!  To be honest, I should have been doing it already (especially since I'm manually going through and performing the changes, haha).

> I suppose that's the alternative: slice this into very fine pieces so they can be reviewed and merged separately.

I've REALLY started seeing the value in smaller chunks of changes in pull requests.

I think the best way to solve both of those comments is to close out this PR and then open smaller ones, cherry-picking the changes and listing the exact conflicts.  I shall begin on that right away!

**Comment by ddbeck** [comment]
> I think the best way to solve both of those comments is to close out this PR and then open smaller ones, cherry-picking the changes and listing the exact conflicts. I shall begin on that right away!

Thank you, @vinyldarkscratch! That's music to my ears (actually this is a terrible metaphor for text, but you get the idea).

**Comment by vinyldarkscratch** [comment]
Alright, cherry-picking and documentation of changes complete!  Closing this PR in favor of all the new ones.

**Pull request closed without merging**
