### PR TITLE
Remove -webkit-perspective-origin-x/y

### PR DESCRIPTION
**Pull request by foolip**
These are just longhands of -webkit-perspective-origin, which is tracked
as a prefix of perspective-origin:
https://github.com/mdn/browser-compat-data/blob/main/css/properties/perspective-origin.json

### CODE REVIEW

**Comment by queengooborg** [comment]
We're tracking the prefixed longhands for `mask-position`, `mask-repeat` and `transform-origin` as separate properties as well.  I feel that's the right way to track the data, since they technically are separate properties, but I don't feel strongly about it as long as we're consistent.

**Comment by foolip** [comment]
@queengooborg ah, so is the rule that if there was a prefixed longhand property like `-webkit-perspective-origin-x`, but no unprefixed form like `perspective-origin-x` exists, then we track it? That would make sense to me.

**Comment by queengooborg** [comment]
We don't have a _rule_ for this, but yeah, that would be the best way to track those properties in my opinion!

**Comment by foolip** [comment]
OK, makes sense to me!

**Pull request closed without merging**
