### PR TITLE
Remove irrelevant api.HTMLMediaElement.onmozinterrupt feature

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the irrelevant `onmozinterrupt` member of the `HTMLMediaElement` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.2.9), even if the current BCD suggests support.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Looks like the MDN content has already been removed!

**Comment by ddbeck** [comment]
> Looks like the MDN content has already been removed!

[Not quite, unfortunately](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#obsolete_event_handlers). Looks like there's still an "Obsolete event handlers section" on that page (unless there's a PR I've missed).

**Comment by queengooborg** [comment]
> [Not quite, unfortunately](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#obsolete_event_handlers). Looks like there's still an "Obsolete event handlers section" on that page (unless there's a PR I've missed).

Ack, good catch, I hadn't looked for other references, just the linked pages... 😅   Content PR incoming!

**Review by ddbeck — APPROVED** [review]
Looks good. Thank you! 🎉

**Comment by ddbeck** [comment]
@queengooborg While writing the release note for this, I noticed this actually _adds_ a new feature called `onerror`. Was that intentional?

**Pull request merged**
