### PR TITLE
feat(exslt): Convert EXSLT compat data

### PR DESCRIPTION
**Pull request by ExE-Boss**
Since [EXSLT](https://developer.mozilla.org/docs/Web/EXSLT) Firefox compatibility data was documented in a simple manner (and the first, and only, batch of EXSLT functions implemented in Firefox came in version 3), I decided to just convert the whole tree in a single commit.

See also #2027, #2026, #2287 and https://github.com/mdn/kumascript/pull/734.

---

review(@Elchi3)

### CODE REVIEW

**Comment by Elchi3** [comment]
(E)XSLT is not at all my area of expertise.

I'm wondering if we really need a new top-level export for this, or if it wouldn't be better to put this into the xslt folder.

**Comment by ExE-Boss** [comment]
Well, EXSLT is located under docs/Web/EXSLT on MDN.

It’s also a separate standard.

**Comment by Elchi3** [comment]
The docs/Web/XSLT page tree has 35 pages and the docs/Web/EXSLT page tree has 23 pages.

@chrisdavidmills do you think these docs should be organized under just one page tree? I'm no subject matter expert, but it seems to me that EXSLT is just an extension to XSLT and it's not worth having it's own organization when it comes to the MDN page structure, the navigation or the bcd exports. I might be wrong, though. I have no clue about XML technologies.

**Comment by chrisdavidmills** [comment]
EXSLT is just a bunch of extensions to XSLT, led by the XSLT community. I think it makes total sense to have the EXSLT stuff inside the XSLT directory, both on MDN and BCD. On MDN, both of them use the same macro to generate the sidebar.

See http://exslt.org/ for more info.

I'd be ok to move this on MDN.

**Comment by Elchi3** [comment]
Lets move the docs first then. I've marked this as "not ready" until we're done with moving.

**Comment by ddbeck** [comment]
@Elchi3 was there some reason to not include EXSLT data in BCD until after the docs had moved on MDN? If there's a real dependency (i.e., it's more complicated than updating `mdn_url`s after those docs move), then I think we should open an issue against mdn and close this. Otherwise, well, there's some work to do here. 😃

**Comment by Elchi3** [comment]
Consensus seems to be to have EXSLT organized under XSLT, but this PR proposes a new top-level EXSLT export. We could land things with current `mdn_urls`, but I don't want to introduce a new top-level export that we will remove once we do this properly. That said, this PR is probably still wont fix unless it is update quite substantially to not have a new top-level EXSLT export.

**Comment by ddbeck** [comment]
Thanks, @Elchi3! That makes sense.

@ExE-Boss, I think it's up to you where we go from here. If you want to update this PR to organize this data under the existing `xslt` tree, then we can review and go from there. Or we can close this up. Either way, thank you for bringing this whole issue to everyone's attention. 👍

**Comment by ddbeck** [comment]
@ExE-Boss not sure if you noticed, but the linter failed on this (since there's not a complete list of browsers in the new files).

**Comment by Elchi3** [comment]
Thanks @ExE-Boss, this works! 

One last thing I would like to understand: Why do we need separate files for each of the functions? In other areas, we have methods of classes together in one file (say JS `Array`, for example), but here you've introduced folders and one file per function.

**Pull request merged**
