### PR TITLE
Update Storage Access API data

### PR DESCRIPTION
**Pull request by chrisdavidmills**
#### Summary

This PR updates the compat data for the [Storage Access API](https://privacycg.github.io/storage-access/), which is being shipped in Chrome 113. In particular I:

- Did updates to `hasStorageAccess()`/`requestStorageAccess()`
- Added `storage-access` permissions policy directive
- Updated `sandbox="allow-storage-access-by-user-activation"` to say supported in Chrome
- Added `storage-access` Permissions API `name` value

Note: I have added a number of notes about the type of behavior implemented by different browsers for requestStorageAccess(). This is not really normal for BCD, in that they are talking about "old spec, new spec" differences rather than browser-specific implementation differences. But I thought these differences needed to be highlighted, as they are pretty important, security-wise.

See my [research document](https://docs.google.com/document/d/1ukOLx-MlKnlR8bufp4Wxmf7kCpqmlKJ6QvEwS2RfIyI/edit#) for the overall details of what this project entails.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Note: tech reviewed by Chris Fredrickson from the Chromium engineering team (he chose to give me feedback via email) — he approved the data changes.

**Comment by chrisdavidmills** [comment]
@queengooborg can you have a look at this one, when you get the chance? ta ;-)

**Review by Elchi3 — APPROVED** [review]

**Comment by queengooborg** [comment]
Hmm, it seems like this one might've gotten pushed back in Chrome -- looking at the [ChromeStatus entry](https://chromestatus.com/feature/5612590694662144), I don't see any milestones marked, and the [linked bug](https://bugs.chromium.org/p/chromium/issues/detail?id=989663) is Open.  Additionally, the mdn-bcd-collector states this feature is unsupported.

**Comment by chrisdavidmills** [comment]
Hi @cfredric! Can you please give us a definitive answer as to the support status of the Storage Access API in release Chrome?

I did some testing in 113 and it looked to be supported, but my results may have been skewed by the fact that I was testing in Canary.

It is also supported only for sites in first-party sets; could that have skewed the bcd collector results?

**Comment by cfredric** [comment]
> Can you please give us a definitive answer as to the support status of the Storage Access API in release Chrome?

Thanks for the callout. I think we hadn't updated the chromestatus entry since we're only shipping *limited* support in M113 (rather than full support) -- but we are shipping in M113, which is [Stable now](https://chromiumdash.appspot.com/schedule). @johannhof has updated the status entry.

(We're still in the middle of a phased rollout, so it's possible you could test locally and not get the right behavior yet. That will be resolved over the next few weeks -- I'm posting periodic progress updates on https://groups.google.com/u/1/a/chromium.org/g/blink-dev/c/7_6JDIfE1as.)

I think it's possible that the phased rollout and the FPS limitation both skewed the bcd collector results?

**Comment by chrisdavidmills** [comment]
Thanks @cfredric, this is really helpful. When you say "limited support", I'm assuming you are talking about the "only supported in first-party sets" thing?

@queengooborg what are you thoughts on this data, in light of the previous comment?

**Comment by queengooborg** [comment]
I'm unfamiliar with the term "first-party sets", may you describe what that means?

**Comment by cfredric** [comment]
@chrisdavidmills Yep, that's what I meant ("limited support" == "only supported within First-Party Sets"). Sorry for being a little hand-wavy :)

@queengooborg Let me know if you have other questions on First-Party Sets; the link that Chris shared is a good one and has a bunch of links in the "Find out more" section at the end, for more detail.

**Comment by queengooborg** [comment]
Okay, so I see what's going on here now.  Please feel free to correct me if I'm wrong, but this is what I've determined:

- First-Party Sets...
  - ...have an official definition [within Chrome's source](https://github.com/GoogleChrome/first-party-sets/blob/main/first_party_sets.JSON)
    - Pull requests may be submitted to add additional First-Party Sets, subject to review
  - ...may be [custom defined by users with runtime flags](https://developer.chrome.com/docs/privacy-sandbox/first-party-sets-integration/#example)
- The Storage Access API is available...
  - ...if the corresponding flag is enabled
  - ...if the site is within a First-Party Set

To me, this seems like a good reason to consider the features _unsupported_ in Chrome, or at least mark them as partial implementation.  As a consumer of BCD, I would expect support to mean that I can start using this feature in my own site without any worry or additional configuration.  However, with the First-Party Sets, as a developer, I would have to enable a flag or submit a PR to an upstream database before I can start using the feature.  As such, I think that it would be more appropriate to revert this PR and re-mark the feature as gated behind a flag (preferably the "Storage Access API" flag as it is the easiest to toggle).

**Comment by Elchi3** [comment]
> I'm on board if you think it's clearest to call Storage Access API _partially_ supported in Chrome (with respect to BCD),

Calling it partial support with a note about first party sets etc. seems like a good way forward then?

**Comment by Elchi3** [comment]
> Cool. Would you like me to make this change inside this PR?

I think we can use @queengooborg's PR https://github.com/mdn/browser-compat-data/pull/19938. Vinyl, do you want to make the changes?

**Comment by queengooborg** [comment]
#19938 is a direct revert of this one, so I think it might be better to open a new PR instead -- @chrisdavidmills, if you're down to open one up, I'd be more than happy to review and merge it!

**Comment by chrisdavidmills** [comment]
> #19938 is a direct revert of this one, so I think it might be better to open a new PR instead -- @chrisdavidmills, if you're down to open one up, I'd be more than happy to review and merge it!

Sure thing, I'll open a PR to sort this out at the start of next week.

**Pull request merged**
