### PR TITLE
Remove CryptoKeyPair dictionary from BCD

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the CryptoKeyPair dictionary from BCD.

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/mdn/content/pull/8846 was closed without being merged, what does that mean for this PR?

**Comment by queengooborg** [comment]
As discussed in the content PR, the decision was to keep `CryptoKeyPair` as a separate entry in MDN, so we'll just be removing the compat table from the MDN page.  We'll still be removing this from BCD!

**Review by foolip — APPROVED** [review]
I don't think there's an open MDN PR for this yet, I'm approving but please land the MDN change before merging this.

**Comment by queengooborg** [comment]
Alright, this one's ready to go now!

**Comment by ashnicdill** [comment]
I did not do anything with a crypto key and I have been replying to other
GitHub personnel about the issue that I am facing.My husband is very smart,
knows how to build apps, and I need to figure out how to make it stop. He
has access to all of my apps, like Facebook, Instagram, Snapchat. He checks
everything on the web although I don't know what, messes with my security
settings, passphrases. I don't know what to do. We have been separated for
months. He has never had permission to use my phone and I do believe has
access to 100% of it. I can't even change some settings. I bought this new
Motorola because he did the same thing to my last phone. Can someone help
me? Please?

**Review by foolip — APPROVED** [review]

**Pull request merged**
