### PR TITLE
adding DocumentOrShadowRoot mixin data to BCD

### PR DESCRIPTION
**Pull request by chrisdavidmills**
See https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot

### CODE REVIEW

**Comment by teoli2003** [comment]
We don't add mixins, we add the properties and methods of mixins on the specific interfaces that implement them.

**Comment by chrisdavidmills** [comment]
@teoli2003 so, after our conversation about mixins, are we going to merge this for now?

**Comment by Elchi3** [comment]
I would like to avoid mixins on MDN and in browser-compat-data, too, but for now it seems like it's best to migrate what we have and make a plan about how to solve this for both MDN and BCD in the future.

"Features still implemented on the <a href='https://developer.mozilla.org/docs/Web/API/Document'>Document</a> interface" is this of any relevancy to a web developer where it's installed? If not, I'm not sure these notes should be here.

There are two sub pages here, that have no compat-data added:
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/pointerLockElement
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement

**Comment by chrisdavidmills** [comment]
I accidentally deleted the branch, so I'm going to close this one, recreate the PR, then submit it again.

**Pull request closed without merging**
