### PR TITLE
Add compat data for symbols() CSS function

### PR DESCRIPTION
**Pull request by ddbeck**
This PR adds the [`symbols()`](https://developer.mozilla.org/en-US/docs/Web/CSS/symbols) CSS function. I _think_ this is the first CSS function to be migrated, so I started a new directory for functions; a close review of the key names here is probably a good idea.

### CODE REVIEW

**Comment by teoli2003** [comment]
There is no such thing that a formal "function" in CSS. Functions are special syntax uses as values on a specific CSS property.

That means that a max() function on property X is completely unrelated to a max() function on property Y: they can have a completely different syntax, can be used in different context and can have a different behaviour.

That's why I think we should describe these functional notations, like symbols(), as a subfeature of the property they belong too.

@Elchi3 : what do you think?

**Comment by Elchi3** [comment]
I agree with Jean-Yves and I also question the existence of that symbols MDN page.

1. There is counter-style symbols: https://github.com/mdn/browser-compat-data/blob/master/css/at-rules/counter-style.json#L470 and https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style/symbols

2. There is https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type and https://developer.mozilla.org/en-US/docs/Web/CSS/list-style where symbols are not documented and also not mentioned in the compat data. 

So, in my opinion the symbols MDN page is not needed, and the information should be on the list-style and list-style-type pages like it is already done for the counter-style at rule.

**Comment by ddbeck** [comment]
OK, I'll make this one a sub-feature of `list-style-type` and `list-style`. Is this a general rule, @Elchi3? For example, does the same go for something like [`fit-content()`](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content), which is going to impact about ten properties?

**Comment by Elchi3** [comment]
I would say it is a general rule. What do you think @teoli2003?

**Comment by teoli2003** [comment]
I thought a bit about this and I think there are two cases:
1. The general rule where functional notations are defined as part of the syntax of a property and we should describe it as a subfeature of the property.
2. The type rule where functional notations are defined as part of the syntax of a type. I'm thinking of the linear-gradient() and other gradients, defined as part of <image>, and the weird calc() that works for several types (<integer>, <percentage>,…). I tend to think these should be subfeatures of these language-wide types.

@Elchi3 ?

**Comment by Elchi3** [comment]
I'm not a subject-matter expert for CSS, but I think that sounds good to me.

**Pull request merged**
