### PR TITLE
IE versions before 8 do not support NodeList.

### PR DESCRIPTION
**Pull request by Kravimir**
A checklist to help your pull request get merged faster:
- [ ] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by ddbeck** [comment]
Hi @Kravimir and welcome to the BCD project. Thanks for this PR. Could you provide some background on where this data came from, like a link to a changelog or a test? This would help to review this PR. Thank you again!

(Also, the browser version must be a string, rather than an integer. Take a look at the Travis CI build for details.)

**Comment by Kravimir** [comment]
Thanks for the welcome.

My searches didn't turn up any authoritative results, so I used my VMs to test the following simple support check in IE8, IE7, and IE6.
`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title></title>
</head>
<body>
<script>
alert(typeof NodeList)
</script>
</body>
</html>`

**Comment by ddbeck** [comment]
Great. That works for me. If you'd fix the quotes, we can get this merged. Thank you again!

**Comment by Kravimir** [comment]
Ok. I've added the quotes.

**Pull request merged**
