### PR TITLE
Update data for Document.getAnimations()

### PR DESCRIPTION
**Pull request by lpd-au**
This pull request updates the data for [DocumentOrShadowRoot.getAnimations()](https://developer.mozilla.org/en-US/docs/Web/API/Document/getAnimations). Please note that this is a different entry but similar function to [Element.getAnimations()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAnimations).

For now, I'm not moving the data from `api.Document` to `api.DocumentOrShadowRoot`. This seems like something that should be done later by someone who can also move the page on MDN.

This feature used to exist as `AnimationTimeline.getAnimationPlayers`, ie on a different interface with an alternative name. This changed several details about the spec in a backwards-incompatible way, that imo isn't worth mentioning in BCD. You can read about the change here: https://lists.w3.org/Archives/Public/public-fx/2015JulSep/0073.html

Tests used are here:
* Basic support: https://jsbin.com/febomo/edit?html,css,js,output
* Returns css animations: https://jsbin.com/wojijux/edit?html,css,js,output
* Returns animations on pseudo-elements: https://jsbin.com/tihuvop/edit?html,css,js,output
* Web platform tests: http://wpt.live/web-animations/interfaces/DocumentOrShadowRoot/getAnimations.html

### Firefox & Firefox for Android ###

Firefox data is taken from the relevant bugs below and manual testing. The latest Android version appears to match Firefox 68 for desktop so I mirrored the data up until that release.

Web platform test results:
* v46: broken
* v52: 7 pass, 3 fail, 1 timeout
* v53: 8 pass, 3 fail
* v72: 11 pass

Relevant bugs:
* Previous implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=1150810
* Basic + css animation support: https://bugzilla.mozilla.org/show_bug.cgi?id=1212720
* Returns pseudo-element animations: https://bugzilla.mozilla.org/show_bug.cgi?id=1234403
* Rename pref: https://bugzilla.mozilla.org/show_bug.cgi?id=1471814
* Supported on ShadowRoot: https://bugzilla.mozilla.org/show_bug.cgi?id=1590971
* Shipped: https://bugzilla.mozilla.org/show_bug.cgi?id=1619821

### Chrome & Chrome for Android ###

Chrome data is taken from the relevant bugs below and manual testing. The only anomaly is despite merging a fix to always flush pending style changes in the 66 branch, I still have intermittent failures until 67. The latest Android version appears to match the latest desktop version so I mirrored the data.

Web platform test results:
* v61: 3 pass, 7 fail, 1 timeout
* v67: 5 pass, 5 fail, 1 timeout
* v74: 6 pass, 5 fail
* v83: 11 pass

Relevant bugs:
* Previous implementation: https://bugs.chromium.org/p/chromium/issues/detail?id=391364
* Rename function: https://bugs.chromium.org/p/chromium/issues/detail?id=483272
* Move to Document interface: https://bugs.chromium.org/p/chromium/issues/detail?id=624639
* Flush pending style changes: https://bugs.chromium.org/p/chromium/issues/detail?id=813908
* Update to latest spec: https://bugs.chromium.org/p/chromium/issues/detail?id=828424 and https://bugs.chromium.org/p/chromium/issues/detail?id=828585
* Support on ShadowRoot: https://bugs.chromium.org/p/chromium/issues/detail?id=1046916
* Shipped: https://bugs.chromium.org/p/chromium/issues/detail?id=978551

### Safari & Safari for iOS ###

Stable Safari data is taken from manual testing and Technology Preview data is taken from the [Web Platform Tests Dashboard here](https://wpt.fyi/results/web-animations/interfaces/DocumentOrShadowRoot/getAnimations.html?run_id=524320002&run_id=518530001&run_id=528080001&run_id=499760002). Unfortunately due to the limitations of browserstack and Apple's bug tracking, I can't narrow down the versions before 13 any further. The latest Technology Preview still fails two web platform tests but these seem minor to me compared to eg Safari 13.1, Chrome 81, etc, so I have marked Safari 14 as supported for the time being.

Web platform test results:
* v10-10.1: 1 pass, 10 fail
* v11-11.1: 1 pass, 9 fail, 1 timeout
* v12-12.1: 6 pass, 5 fail
* v13: 6 pass, 5 fail
* v13.1: 6 pass, 5 fail
* TP105: 9 pass, 2 fail

Relevant bugs:
* Basic support: https://bugs.webkit.org/show_bug.cgi?id=156096, https://bugs.webkit.org/show_bug.cgi?id=179535 and https://bugs.webkit.org/show_bug.cgi?id=179536
* Support on ShadowRoot: https://bugs.webkit.org/show_bug.cgi?id=202192

### Edge ###

Edge 18 does not support the web animations API at all so the Edge data is mirrored from Chrome.

### Opera & Opera for Android ###

Mirrored from Chrome and Chrome for Android. I verified Opera 69 data manually since its engine version data in BCD is out of date.

### CODE REVIEW

**Comment by lpd-au** [comment]
@birtles and @graouts you may be good reviewers for the Firefox and Safari data here respectively :)

**Comment by birtles** [comment]
> Relevant bugs:
> 
>     * Previous implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=1150810
> 
>     * Basic + css animation support: https://bugzilla.mozilla.org/show_bug.cgi?id=1212720
> 
>     * Returns pseudo-element animations: https://bugzilla.mozilla.org/show_bug.cgi?id=1234403
> 
>     * Rename pref: https://bugzilla.mozilla.org/show_bug.cgi?id=1471814
> 
>     * Supported on ShadowRoot: https://bugzilla.mozilla.org/show_bug.cgi?id=1590971
> 
>     * Shipped: https://bugzilla.mozilla.org/show_bug.cgi?id=1619821

This is amazing research!

**Comment by lpd-au** [comment]
> The `firefox_android` data should be the same as the desktop data however. I suspect it's simply that we haven't shipped a release version of Firefox for Android based on Gecko 75 yet but any of the recent Firefox Preview builds (which are based on Gecko 75 or later) will ship `getAnimations()`.

It's not a decision I'd take personally, but afaik BCD doesn't accept Firefox Preview data, only regular Firefox for Android data which is stuck on the 68 ESR branch.

**Comment by birtles** [comment]
In that case whar you have seems perfect!

**Comment by graouts** [comment]
@lpd-au Would you mind detailing what the remaining failures you saw in STP 105?

**Comment by lpd-au** [comment]
> Would you mind detailing what the remaining failures you saw in STP 105?

@graouts According to the [Web Platform Tests Dashboard](https://wpt.fyi/results/web-animations/interfaces/DocumentOrShadowRoot/getAnimations.html), the following tests are failing:

* Document.getAnimations() returns animations on elements inside same-origin iframes
* iframe.contentDocument.getAnimations() returns animations on elements inside same-origin Document

**Pull request merged**
