### PR TITLE
Node.js 22.0.0

### LINKED ISSUE #22983: javascript.builtins.Set.union - landed in Node.js 22.0.0
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union#browser_compatibility

### What browsers does this problem apply to, if applicable?

_No response_

### What did you expect to see?

Says No

### Did you test this? If so, how?

image

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.Set.union`
* Report started: 2024-05-01T17:47:29.319Z

</details>

### PR DESCRIPTION
**Pull request by jlweston**
#### Summary

Update compat tables for Node.js v22.0.0

#### Test results and supporting details

https://nodejs.org/en/blog/announcements/v22-release-announce

#### Related issues

Fixes #22983.

### CODE REVIEW

**Comment by theoludwig** [comment]
[`Array.fromAsync`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fromAsync#browser_compatibility) (and probably others Array methods) can also be added to the supported table since Node.js v22.0.0.

**Comment by MrBazlow** [comment]
In addition to what theoludwig mentioned, some other features that landed in version 22 and need updating include:

- [Promise.withResolvers()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers)
- Experimental Iterator helpers
  - [drop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/drop)
  - [every](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/every)
  - [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/filter)
  - [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/find)
  - [flatMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/flatMap)
  - [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/forEach)
  - [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/map)
  - [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/reduce)
  - [some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/some)
  - [take](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/take)
  - [toArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/toArray)
- [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) class
- [Import attributes with `assert` syntax (formerly import assertions)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) is gone.

**Comment by jlweston** [comment]
I think that covers the areas highlighted. I don't see any additional `Array` methods in the v8 code at v12.5 that aren't already listed as supported in Node.

**Review by himself65 — APPROVED** [review]

**Review by queengooborg — APPROVED** [review]
Hey there, thank you for your PR and welcome to BCD!

I've given the changes a spot check, and everything's looking good to me -- let's get this merged!

**Pull request merged**
