### PR TITLE
Adding the display_override manifest member compat data

### PR DESCRIPTION
**Pull request by captainbrosset**
#### Summary
Over in https://github.com/mdn/content/issues/10539 I'm proposing to add MDN documentation for the new Window Controls Overlay PWA feature. One part of this feature is the `display_override` manifest member. So in order to document it in MDN, we need its compat data here on this repo.

#### Test results and supporting details
The Window Controls Overlay feature is documented here: https://web.dev/window-controls-overlay/ and here https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/window-controls-overlay
and its current spec is on the WICG repo here: https://wicg.github.io/window-controls-overlay/#addition-of-window-controls-overlay-to-the-manifest
It was implemented in Chromium in 93 (available as origin trial then).

### CODE REVIEW

**Review by ddbeck — COMMENTED** [review]
Thanks for this PR and the background info @captainbrosset. This feature appears to be gated behind an origin trial. Since origin trials are available by time and enrollment, rather than browser version, we don't track them in BCD. Generally, we expect to cover such features only after they're generally available. With that in mind, I'm going to close this PR, but I invite you to revisit this when the feature does eventually ship. Thanks for your understanding!

The tests are failing because the spec isn't yet recognized by w3c/browser-specs. See https://github.com/w3c/browser-specs/pull/416 for details.

**Comment by captainbrosset** [comment]
@ddbeck  the feature is planned to be generally available in chromium 98. This means it's already today available in Chrome/Edge Canary without having to turn any flags on. I just tested again today, made sure the Window Controls Overlay flag was off in edge://flags (or chrome://flags) and installed a PWA that made use of the feature.  It did work correctly.

Do you want to wait until 98 becomes stable, or do we also track pre-release features in BCD (granted they're not gated behind a pref/flag and origin trial)?

**Comment by captainbrosset** [comment]
Also, this PR is about the `display_override` manifest member which has been implemented in 89, and not only related to the Window Controls Overlay feature. This feature makes use of it, but the manifest member wasn't added only for this.

**Comment by ddbeck** [comment]
Ah, sorry, I've misunderstood some details. I've reopened and I'll come back to this.

**Comment by Elchi3** [comment]
> The tests are failing because the spec isn't yet recognized by w3c/browser-specs. See [w3c/browser-specs#416](https://github.com/w3c/browser-specs/pull/416) for details.

I've merged https://github.com/mdn/browser-compat-data/pull/13882. Please merge `main` into this PR and the tests should hopefully pass.

**Review by ddbeck — APPROVED** [review]
Thanks for the extra information on this, @captainbrosset. It makes sense now and I'll go ahead and merge this. 🎉

**Comment by captainbrosset** [comment]
Awesome, thanks a lot!

**Pull request merged**
