### PR TITLE
Add Chromium/Edge versions for PushSubscriptionOptions API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) and Edge for the `PushSubscriptionOptions` API, while also correcting the versions for `PushSubscription.options`, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.3.0).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/PushSubscriptionOptions

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

### CODE REVIEW

**Review by foolip — CHANGES_REQUESTED** [review]
This data should likely match https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/options#browser_compatibility, it's not possible for `myPushSubscription.options` to be supported without `PushSubscriptionOptions`.

**Comment by queengooborg** [comment]
It appears that the collector is also indicating that `api.PushSubscription.options` was also added in Chrome 54, rather than Chrome 42 as currently indicated.  The original data comes from the wiki migration so I trust the collector results more.  The [commit history](https://storage.googleapis.com/chromium-find-releases-static/888.html#8882a829851f9bfe6e1857c9d8b0a7c679d89c00) also backs this up.

I'll also fix `api.PushSubscription.options` in this PR!

**Comment by foolip** [comment]
@queengooborg can you also check if other related APIs have the same error and fix them up at the same time?

**Comment by queengooborg** [comment]
The rest of the Push-related APIs are looking good to me!  The collector _is_ changing them up, but it's mostly changes like Chrome 42 -> 43, all-false, etc. which I don't trust without some custom tests.

**Review by foolip — APPROVED** [review]

**Pull request merged**
