### PR TITLE
Remove irrelevant MouseWheelEvent API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the irrelevant `MouseWheelEvent` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.3.0), even if the current BCD suggests support.  I've also manually confirmed a lack of support by checking Chrome's and Safari's sources, and checked Edge for compatibility.

### CODE REVIEW

**Comment by foolip** [comment]
Was this in Edge 18? If so it's still too early to remove per guideline.

**Comment by queengooborg** [comment]
It was not in Edge 18, I did check that!

**Comment by foolip** [comment]
Excellent!

**Review by foolip — APPROVED** [review]
Not merging, please land the MDN change first.

**Comment by hamishwillee** [comment]
What about the associated event https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onmousewheel ?

Even though we redirect, could you clean up some of the internal links? e.g. 
- https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent

might be simple enough just to turn them from links to code-only.

**Comment by queengooborg** [comment]
I've opened a follow-up PR to the content repo!  I'll go ahead and merge this since the main removal is complete.

**Comment by ddbeck** [comment]
> I've opened a follow-up PR to the content repo! I'll go ahead and merge this since the main removal is complete.

@queengooborg could you link to the corresponding content PR? It's not clear to me that the needs-content-update label was satisfied before merging.

**Pull request merged**
