### PR TITLE
Update data for Element.getAnimations()

### PR DESCRIPTION
**Pull request by lpd-au**
This pull request updates the data for [Element.getAnimations()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAnimations). Please note that this is a different entry but similar function to [DocumentOrShadowRoot.getAnimations()](https://developer.mozilla.org/en-US/docs/Web/API/Document/getAnimations).

Tests used here are:

* Basic support: https://jsbin.com/hogequp/edit?html,css,js,console,output
* Returns css animations: https://jsbin.com/pojudek/edit?html,css,js,console,output
* Supports options.subtree: https://jsbin.com/mofeyuy/edit?html,css,js,console,output
* Returns animations on pseudoelements: https://jsbin.com/fubunuw/1/edit?html,css,js,console,output

### Firefox ###

Firefox data is mostly taken from the relevant bugs:

* Initial implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=1032573
* Function rename: https://bugzilla.mozilla.org/show_bug.cgi?id=1145246
* Support options.subtree and pseudoelements: https://bugzilla.mozilla.org/show_bug.cgi?id=1254761 and https://bugzilla.mozilla.org/show_bug.cgi?id=1254418
* Rename pref: https://bugzilla.mozilla.org/show_bug.cgi?id=1471814

I verified basic support is present and css animations are returned with the necessary flags in Firefox 40 on Windows 7.

### Firefox for Android ###

Tested on a Samsung Galaxy S10e with Firefox for Android 68, the function does not appear to return any animations added via CSS. This is different to desktop support and I have no way of verifying support on previous versions, so the version is set to true.

### Chrome & Chrome for Android ###

Chrome data was tested using various desktop versions on Windows 7. The relevant bugs are below:

* Initial implementation: https://bugs.chromium.org/p/chromium/issues/detail?id=391364
* Function rename: https://bugs.chromium.org/p/chromium/issues/detail?id=483272
* Return css animations: https://bugs.chromium.org/p/chromium/issues/detail?id=813908
* Support options.subtree and pseudoelements: https://bugs.chromium.org/p/chromium/issues/detail?id=981898

Chrome for Android latest version appears to match the current desktop implementation, so I've mirrored the data.

### Android WebView ###

Android WebView data is mirrored from Chrome for Android data.

### Edge ###

Edge 18 does not support the web animations API at all so the Edge data is mirrored from Chrome.

### Opera & Opera for Android ###

Opera and Opera for Android data is mirrored by mapping the Chrome versions using their release notes: https://help.opera.com/en/opera-version-history/.

### Samsung Internet Browser ###

Samsung Internet Browser data is mirrored from Chrome for Android data using the engine version data in [browsers/samsunginternet_android.json](https://github.com/mdn/browser-compat-data/blob/master/browsers/samsunginternet_android.json).

### Safari & Safari for iOS ###

The Safari data should look like this:

* Safari 9.1: Does not support experimental features at all afaik? (Or in some different way I do not know of.)
* Safari 10-10.1: Function exists _with no preferences_ but always returns an empty array.
* Safari 11-11.1: Function exists behind "Web Animations" preference as an initial implementation.
* Safari 12-12.1: Returns css animations behind the "CSS Animations via Web Animations" preference.
* Safari 13: No change.
* Safari TP: [Release notes](https://developer.apple.com/safari/technology-preview/release-notes/) indicate that options.subtree will be supported.

Data (except for TP) is tested via browserstack. Unfortunately I have no idea how I can represent these ranges in the data format, so instead I have just added the Safari 12.1 data with version set to true.

Safari 13 for iOS appears to have the same support as regular Safari 13 on desktop, so I have mirrored the data.

### CODE REVIEW

**Comment by lpd-au** [comment]
@Elchi3 could I request a review from someone please

**Comment by Elchi3** [comment]
Thanks for your detailed explanations and work on this PR, @lpd-au :+1: 

I will try to look this through, but also ping @birtles who knows a lot more about Web Animations and its availability than I do. Brian, if you have a minute to double check this, we would appreciate it.

**Comment by birtles** [comment]
`getAnimations()` (for both `Element` and `DocumentOrShadowRoot`) is enabled by default in Firefox on all channels starting from 75 (current beta). Prior to that it was only enabled by default in Nightly.

Other than that, for the Web Animations API, we've generally taken the approach of not reporting support for features that haven't shipped to release channels (since there have been so many changes in behavior while they have been behind a flag--so it's hard to say when it was first "supported"). I'm not opposed to adding the detailed information, but if it proves difficult, I wouldn't hesitate to drop it.

**Comment by birtles** [comment]
> `getAnimations()` (for both `Element` and `DocumentOrShadowRoot`) is enabled by default in Firefox on all channels starting from 75 (current beta). Prior to that it was only enabled by default in Nightly.

Bug reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1619821

**Comment by birtles** [comment]
Which is all to say, this looks great to me. Thanks for the very detailed research!

**Comment by lpd-au** [comment]
> `getAnimations()` (for both `Element` and `DocumentOrShadowRoot`) is enabled by default in Firefox on all channels starting from 75 (current beta).
> Bug reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1619821

Thanks! That bug is newer than this PR so I've updated it accordingly now.

**Pull request merged**
