### PR TITLE
Update structure of BCD data for Service Worker interfaces

### PR DESCRIPTION
**Pull request by dontcallmedom**
Generated via https://github.com/dontcallmedom/webidl2mdnbcd from https://w3c.github.io/ServiceWorker/

### CODE REVIEW

**Comment by dontcallmedom** [comment]
I have rebuilt this pull request to integrate the data from #1055 and also complete HTML interfaces added in #1404

**Comment by dontcallmedom** [comment]
actually, just pushed another version without the dependency on #1055 since it is orthogonal to it

**Comment by Elchi3** [comment]
Sorry, why does this add the HTML interfaces now?

**Comment by dontcallmedom** [comment]
rebased on just Navigator now

**Pull request merged**
