### PR TITLE
Add draft GUIDE_WORKFLOW.md

### PR DESCRIPTION
**Pull request by bunnybooboo**
Worked on a draft document to express my workflow. Assuming these tips will help others somewhere along the line. Currently incomplete, so introduced as potential repo content OR blog content.

### CODE REVIEW

**Comment by bunnybooboo** [comment]
Ugh. Looking the files changed I can see I need to rebase to reflect that this PR is for 1 file only.

**Comment by bunnybooboo** [comment]
Fixed via rebase. Yes I learned a thing or two today. PR now proper bang tidy y'all.

**Comment by teoli2003** [comment]
I'm curious to understand what is the goal of the document: what needs does it address? Once this is known and agreed, we will be able to start reviewing this.

**Comment by bunnybooboo** [comment]
Simply by switching to this workflow I noticed a significant increase in my output. Noted it to share with other Mozillians I might discuss the process to. Thought to PR as well, I'd done it anyway. Content was not created for the the purpose of repo use, but could be.

i.e. You can do this any number of way but this contributor found this process to be streamlined and systematic. To assist in onboarding process.

**Comment by Elchi3** [comment]
I think we could improve [Contributing.md](https://github.com/mdn/browser-compat-data/blob/master/CONTRIBUTING.md) and I would review a PR that adds more polished guidelines to that file. This PR looks more like raw note pad, which we could maybe add to the wiki or elsewhere first with the goal to figure out a better contributing file. 
I'm closing this as we're not intending to merge as-is, but you are definitely encouraged to improve the contributing docs (maybe have a session in Paris about this to get us to a good contributing file?) 
In any case, thanks for sharing this with us!

**Pull request closed without merging**
