### PR TITLE
Set Firefox to 53 for api.BaseAudioContext.*

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
`BaseAudioContext` has been a weird API in terms of consistency.  It seems that most of the properties were implemented in `AudioContext`.  I have confirmed that `BaseAudioContext` was [implemented in Firefox 53](https://bugzilla.mozilla.org/show_bug.cgi?id=1324352).

This PR sets said version number accordingly, which additionally eliminates version inconsistency.

### CODE REVIEW

**Comment by Elchi3** [comment]
@chrisdavidmills can you review this? From the bug it looks like you might have documented this.

**Comment by Elchi3** [comment]
@chrisdavidmills ping? :) 
Maybe this is too complicated/weird because BaseAudioContext is a mixin or something?

**Comment by vinyldarkscratch** [comment]
I’d have to say it’s more that it many properties were moved from the AudioContext interface to this one, so version numbers may refer to the ones when implemented in AudioContext.  I know Joe Medley and I found that one out with Chrome during the start of the version consistency linter.  I believe that our solution was to simply bump the values up like I’m doing here.

Perhaps we should add a note like in #4735?

**Comment by vinyldarkscratch** [comment]
Notes have now been added!

**Comment by vinyldarkscratch** [comment]
Thanks @chrisdavidmills!

**Pull request merged**
