### PR TITLE
Sort browser compatibility order

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR is intended to sort the browsers' order in all of the existing files and adhere to the new style linting proposed by #1474.  This is one of two PRs that supersedes #1474, whereas the other one (~~#2890~~ #1882) includes the linting test itself.  I will be updating changes on a daily or bi-daily basis to ensure compatibility.

**WARNING:** this may break PRs that modify existing data and require them to rebase.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Fixed to leave #1882 open -- as mentioned in the other PR, I assumed it was only for the data, whoops!

@Elchi3 you up for merging this, or would you rather get the PR backlog down a little more?

**Comment by Elchi3** [comment]
> @Elchi3 you up for merging this, or would you rather get the PR backlog down a little more?

I don't think it is useful create merge conflicts for open PRs that actually do useful stuff. I mean sorting is useful, too, but this kind of PR can be created programmatically at any time and other PRs often can't. So I think it would have been appropriate to ask in existing sorting PRs like #1882 what the plan is before investing the time :)

**Comment by Elchi3** [comment]
I will review and accept separate PRs for the following folders, because they don't break existing PRs.
(It might make sense to have one PR per folder to ease reviewing.)
- html/
- http/
- javascript/
- mathml/
- svg/
- webdriver/
- xpath/
- xslt/

I will let know you when is a good time to proceed with the rest. Thank you!

**Comment by ExE-Boss** [comment]
Well, XSLT and XPath data was so far contributed entirely by me in #2026 and #2287, so they’re currently sorted.

**Comment by vinyldarkscratch** [comment]
Alright, cherry-picking it is!  Sending separate PRs shortly.  :wink:

**Comment by Elchi3** [comment]
The PR backlog for css/* is low enough now as well, I think.

**Comment by vinyldarkscratch** [comment]
PR for css/* has now been made!

**Pull request closed without merging**
