### PR TITLE
Aspect-ratio supported in Chrome

### PR DESCRIPTION
**Pull request by Onset**

### CODE REVIEW

**Comment by ddbeck** [comment]
Hi @Onset, thank you for starting this PR. Do you have any more information about this new support (I couldn't find any details about it on own)? It maybe possible to update Android or WebView data, while we're at it.

**Comment by Onset** [comment]
Hi @ddbeck, I've had trouble finding any support information in release notes of browsers so I've made a small pen to test the `aspect-ratio`, `min-aspect-ratio` and `max-aspect-ratio`. https://codepen.io/Onset/full/dKNgmG/

I'm happy to know now that aspect ratio is supported in all latest browsers.

## Google Chrome 67
image

## Safari 9.1
image

## MS Edge 17
image

## IE 11
image

## Firefox 60
image

## Opera 53
image

## Samsung Internet 6.4
image

## UC Browser
image

## Google Chrome 51 inside Facebook Messenger
image

**Comment by paulirish** [comment]
afaik it's "always" been supported in chrome: https://chromium.googlesource.com/chromium/src/+/64c713c8f749364f758d3fcc5648fe12686425fd

i can't see that this was even disabled by default.

**Comment by paulirish** [comment]
fwiw. here's one way to try tracking down this info for chrome

1. open https://cs.chromium.org/
1. try searching for a useful string like [`max-aspect-ratio`](https://cs.chromium.org/search/?q=max-aspect-ratio&sq=package:chromium&type=cs)
1. choose a useful file. we'll go with the top one: [`mq-aspect-ratio.html`](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/media/mq-aspect-ratio.html?type=cs&q=max-aspect-ratio&sq=package:chromium&g=0&l=11)
1. in the top right open View > Git revision Log. (Sometimes Git Blame is slightly more useful)
image

This hopefully should reveal some commits which point to where a feature was added or flipped on.

**Comment by Onset** [comment]
@paulirish Valuable tool! Thank you for the links and step by step guide.

I'm not sure which version to attribute though.

**Comment by paulirish** [comment]
> I'm not sure which version to attribute though.


either Chrome 4 or Chrome 5. 
:)

**Comment by Onset** [comment]
Now I see the version is not required and `"version_added": true` works just fine. But still, thank you.

**Comment by ddbeck** [comment]
Thank you for the update, @Onset and thank you, @paulirish, for the lesson in searching Chrome's history!

**Pull request merged**
