### PR TITLE
Update Microsoft Edge WebExtension bookmarks API

### PR DESCRIPTION
**Pull request by GauthamBanasandra**
Microsoft Edge version 40 supports a few of the bookmarks API.
All the APIs supported currently by the Microsoft Edge browser can
be found here -
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis

### CODE REVIEW

**Comment by wbamberg** [comment]
This looks great, except that according to @erikadoyle's comment here: https://github.com/mozilla/kumascript/pull/131#issuecomment-291992318 we should use the "2-digit EdgeHTML version" in the browser compat data, so instead of "40.0" we should use "15".

I'm sorry not to have been clearer about this before :(. We need to be better at documenting how to document browser versions.

**Comment by GauthamBanasandra** [comment]
No problem William. I've changed "40.0" to "15".

**Comment by wbamberg** [comment]
Thanks @GauthamBanasandra !

**Comment by erikadoyle** [comment]
Yes, thank you @GauthamBanasandra :-)

**Comment by GauthamBanasandra** [comment]
Much obliged. :)

**Pull request merged**
