### PR TITLE
WebXR Hand Input is in Edge 93 (Hololens 2)

### PR DESCRIPTION
**Pull request by Elchi3**
See https://learn.microsoft.com/en-us/windows/mixed-reality/develop/javascript/webxr-overview

### CODE REVIEW

**Review by lucalves — APPROVED** [review]

**Comment by queengooborg** [comment]
If it's only available through the Hololens but not any other XR system that supports hand tracking (i.e. the Valve Index), should we mark this as `partial_implementation`?

**Comment by Elchi3** [comment]
The collector detected this one as well. So I'm not sure how partial it really is. "HoloLens 2 only" was mentioned on the Microsoft site.

**Comment by captainbrosset** [comment]
So, I don't know anything about this myself, but I asked people who know. Hopefully this helps:

The APIs exist in the desktop browser as well (see the available `window.XRHand` object). **But**, we can't really test if the entire API is available on other devices, such as desktop. The basic hand data is working, but we can't test the full functionality (which is available on Hololens) and can only assume that it is the same implementation and is the full implementation.

I would personally go for a note, as Florian is suggesting in this PR, rather than "partial" which suggests that something is missing or broken (which we just don't know for a fact).

**Comment by Elchi3** [comment]
> I would personally go for a note, as Florian is suggesting in this PR, rather than "partial" which suggests that something is missing or broken (which we just don't know for a fact).

Yes, I think nothing is broken in terms of the implementation of this API. If you don't use a capable device for this API then you won't have the functionality obviously. So, just a note recommending the device to use this with seems good.

**Review by queengooborg — APPROVED** [review]

**Pull request merged**
