### PR TITLE
Add data for cross-document view transitions features

### PR DESCRIPTION
**Pull request by chrisdavidmills**
#### Summary

Chrome 123/124 includes features required for developers to create cross-document [View Transitions](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API). This includes:

- The [`PageRevealEvent` interface](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-pagerevealevent-interface)
- The [`pagereveal` event](https://html.spec.whatwg.org/multipage/indices.html#event-pagereveal)
- The [`PageSwapEvent` interface](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-pageswapevent-interface)
- The [`pageswap` event](https://html.spec.whatwg.org/multipage/indices.html#event-pageswap)
- The [`NavigationActivation` interface](https://html.spec.whatwg.org/multipage/nav-history-apis.html#navigationactivation)
- The [`@view-transition` at rule](https://drafts.csswg.org/css-view-transitions-2/#view-transition-rule)
- [`<link rel="expect">`](https://html.spec.whatwg.org/multipage/links.html#link-type-expect)

This PR adds/updates the BCD for all of these.

Related ChromeStatus entries:

- https://chromestatus.com/feature/5118874666663936
- https://chromestatus.com/feature/5205586941837312
- https://chromestatus.com/feature/5113053598711808 

#### Related issues

- dom-examples demo: https://github.com/mdn/dom-examples/pull/265
- MDN content update: https://github.com/mdn/content/pull/32723

### CODE REVIEW

**Comment by captainbrosset** [comment]
I know this is a stretch, and don't want to derail you from your work here but if, by any chance, you know the bug URLs for implementing cross-document view transitions in Firefox and in Safari, it would be awesome to add them as `impl_url` fields next to `version_added:false` for those browsers.

**Comment by chrisdavidmills** [comment]
> I know this is a stretch, and don't want to derail you from your work here but if, by any chance, you know the bug URLs for implementing cross-document view transitions in Firefox and in Safari, it would be awesome to add them as `impl_url` fields next to `version_added:false` for those browsers.

I don't, I'm afraid ;-)

**Review by Elchi3 — CHANGES_REQUESTED** [review]
I wonder why the collector says unsupported for the viewTransition properties.
https://mdn-bcd-collector.gooborg.com/tests/api/PageRevealEvent 
https://mdn-bcd-collector.gooborg.com/tests/api/PageSwapEvent

I bet you've written some code that uses the property and saw it working, though?

LGTM otherwise, just one tag that was added accidentally.

**Comment by chrisdavidmills** [comment]
> I wonder why the collector says unsupported for the viewTransition properties. https://mdn-bcd-collector.gooborg.com/tests/api/PageRevealEvent https://mdn-bcd-collector.gooborg.com/tests/api/PageSwapEvent
> 
> I bet you've written some code that uses the property and saw it working, though?
> 
> LGTM otherwise, just one tag that was added accidentally.

Ah yes, some of the features are still hidden behind the "viewTransition API for navigations" Chrome flag; the versions I've added in are the ones they'll be enabled for in those cases.

Sorry, forgot to mention that.

**Comment by Elchi3** [comment]
> Ah yes, some of the features are still hidden behind the "viewTransition API for navigations" Chrome flag; the versions I've added in are the ones they'll be enabled for in those cases.

okay, in this case I think we need to mark them behind a flag for now.

**Comment by chrisdavidmills** [comment]
> > Ah yes, some of the features are still hidden behind the "viewTransition API for navigations" Chrome flag; the versions I've added in are the ones they'll be enabled for in those cases.
> 
> okay, in this case I think we need to mark them behind a flag for now.

@Elchi3 OK, done

**Comment by Elchi3** [comment]
Looks good to me for PageSwapEvent but what about:
- api.PageRevealEvent.PageRevealEvent
- api.PageRevealEvent.viewTransition 

These show up unsupported in Chrome 124 for me in https://mdn-bcd-collector.gooborg.com/tests/api/PageRevealEvent

**Comment by chrisdavidmills** [comment]
> Looks good to me for PageSwapEvent but what about:
> 
>     * api.PageRevealEvent.PageRevealEvent
> 
>     * api.PageRevealEvent.viewTransition
> 
> 
> These show up unsupported in Chrome 124 for me in https://mdn-bcd-collector.gooborg.com/tests/api/PageRevealEvent

Flag information added to these too. I've definitely tested them as working with the flag enabled.

**Comment by chrisdavidmills** [comment]
> Thanks Chris!
> 
> If these interfaces are behind a flag, I'm skeptical about the availability of pageswap_event and pagereveal_event on Window but I think we should land this PR for now and correct the data if needed later on (hopefully we will soon have a version number for unflagged support and then the flags will disappear anyways).

Yup, this is what I was hoping for; also, it will be a little while until we get the docs reviewed anyway, and by then I'm hoping it will be out from behind the flag.

 
> Note: I'm always happy to review early BCD entries for flagged features, but as you can see, work is required to sort things out properly. So, if it is not absolutely pressing, I would wait until things are shipping properly and only then submit BCD (or have it submitted by the collector).

Yeah, I totally understand the reasoning here. Usually I am a bit further behind the curve than this, but I do get a few work items that are high priority and therefore they want me to get done earlier.

**Pull request merged**
