### PR TITLE
adds Element.isVisible

### PR DESCRIPTION
**Pull request by rachelandrew**
[Element.isVisible](https://drafts.csswg.org/cssom-view/#dom-element-isvisible) is in [Chrome 103](https://chromestatus.com/feature/5163102852087808). This PR adds BCD.

### CODE REVIEW

**Review by queengooborg — CHANGES_REQUESTED** [review]
Thank you for adding this!  We recently added a feature that allows derivative browsers to mirror from their upstream counterparts.  Let's utilize it here, if that sounds good (this applies to all other PRs as well)!

**Comment by foolip** [comment]
https://github.com/w3c/csswg-drafts/issues/7317 resolved to rename this to `isHidden`.

**Comment by rachelandrew** [comment]
@foolip I'll update it when I do the other change

**Comment by queengooborg** [comment]
It looks like this has been renamed to `isHidden` in the spec, and it has not been included in Chrome 103 with either name.  I'm going to mark this as a draft since no implementation has been made in any browser yet.

**Comment by foolip** [comment]
It was actually renamed to `checkVisibility` in the end.

**Comment by queengooborg** [comment]
Alright, since there's no implementation and the spec has been renaming this, I think we should wait until a browser has implemented this before creating a PR.

**Pull request closed without merging**
