### PR TITLE
Edge supports text-combine-upright

### PR DESCRIPTION
**Pull request by Elchi3**
Fix https://github.com/mdn/browser-compat-data/issues/20224

### CODE REVIEW

**Comment by darksunlight** [comment]
Hello. I'm not sure what "mirror" does, but just FYI `text-combine-upright: digits` is not currently supported on Chromium based Edge.

**Comment by queengooborg** [comment]
Hey @darksunlight, your statement just now contradicts what you have said in the issue you opened (#20224).  In the issue, you indicated that our compatibility tables incorrectly state Chromium-based Edge _does not_ support the feature when it _does_, but just now you said the opposite is the case.

**I can confirm that Chromium-based Edge supports this feature, using the following code:**

```html
<style>
    p {
        text-combine-upright: all;
        writing-mode: vertical-rl;
    }
</style>
<p>2022年12月8日から楽しい</p>
```

Performing some additional tests, however, I found that there are other issues with our data:
- `-ms-text-combine-horizontal` is an alternative name for the entire property (not the `digits` value) that has been supported in pre-Chromium Edge.
- Pre-Chromium Edge does support `digits` as a value; however...
  - ...the `all` value is not supported until Edge 79.
  
@Elchi3, would you be down to make the appropriate adjustments?

**Comment by queengooborg** [comment]
Ah, wait- sorry, I misread your comment, @darksunlight.  I see now that you're referring to the `digits` value specifically in your latest comment, not the entire property.  My mistake!

I can confirm that the `digits` value is also not supported in Chromium, so no changes are needed there!

**Comment by Elchi3** [comment]
> so no changes are needed there!

Can this PR get merged then?

**Review by queengooborg — APPROVED** [review]
Yep, this looks good to me!

**Pull request merged**
