### PR TITLE
Add `browser_style`

### PR DESCRIPTION
**Pull request by ExE-Boss**
## External links:
- https://developer.mozilla.org/Add-ons/WebExtensions/user_interface/Browser_styles

### CODE REVIEW

**Comment by ExE-Boss** [comment]
The reason why I want to add this, is to document that since Firefox 55, Firefox requires the `browser-style` class to be applied on `<button>`, `<select>`, `<textarea>` and `<input>` in order to apply the styles, which Chrome and Opera both apply regardless of whether or not the `browser‑style` class is present.

As for documenting `browser_style` as sub‑features of the relevant manifest keys, #1799 would allow them to be de‑duplicated.

**Comment by wbamberg** [comment]
Thanks for the clarification!

I agree then that we should tell people that they need to use `browser-style` on elements with Firefox. But I don't think this should be represented as a separate subfeature of a separate `browser_style` feature. I think it would be more useful to developers to represent this as a note attached to the existing `browser_style` subfeatures of the various manifest keys, such as https://github.com/mdn/browser-compat-data/blob/master/webextensions/manifest/browser_action.json#L31.

**Comment by Elchi3** [comment]
@ExE-Boss @wbamberg what's the status here? https://github.com/mdn/browser-compat-data/pull/2590 was merged. Is this one a wontfix?

**Comment by ExE-Boss** [comment]
I don’t think so, as this one adds information about the functionality of `browser_style` itself, eg. if the [`browser-style` class is necessary](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_styles).

**Comment by wbamberg** [comment]
As far as I can tell the status is still as it was in https://github.com/mdn/browser-compat-data/pull/2154#issuecomment-404334988 - I think it would be better to handle this using notes attached the the existing `browser_style` subfeatures, not using a separate `browser_style` feature.

**Comment by wbamberg** [comment]
Closing this since it appears to be stuck.

**Pull request closed without merging**
