### PR TITLE
Update DataTransfer.json

### PR DESCRIPTION
**Pull request by Yaffle**
A small details about Opera 12

### CODE REVIEW

**Comment by ddbeck** [comment]
Thanks for this PR, @Yaffle. Can you tell me more about how you came to know this? Do you have a source for this note?

**Comment by Yaffle** [comment]
@ddbeck , manual testing in Opera 12

**Comment by ddbeck** [comment]
Thanks for the update, @Yaffle. One more question, then: did you try it in a version before Opera 12. In other words, do you know that Opera 12 was the first version to exhibit this behavior or is it possible it did so before that?

**Comment by Yaffle** [comment]
@ddbeck , DataTransfer is not supported at all before this version according to https://caniuse.com/#feat=dragndrop

**Comment by Yaffle** [comment]
@ddbeck, thanks for merging

**Pull request merged**
