### PR TITLE
Remove CSSStyleDeclaration.@@iterator

### PR DESCRIPTION
**Pull request by Elchi3**
See https://github.com/openwebdocs/mdn-bcd-collector/pull/1677 (apparently this is in the custom IDL in the OWD collector but I can't find it in specs or in browsers, so we should remove this)

### CODE REVIEW

**Comment by skyclouds2001** [comment]
it seems to be iterable in latest Chrome and Firefox

image

image

**Comment by Elchi3** [comment]
hm, interesting. I guess the interface implements the symbol but not the methods (keys, entries, values, forEach).

**Comment by Elchi3** [comment]
@foolip by chance, do you happen to know what is going on here?

**Comment by queengooborg** [comment]
I think that we should leave this in because the iterator symbol _is_ defined, and we list the individual iterator methods in BCD already.

**Pull request closed without merging**
