### PR TITLE
Referrer-Policy - Update for "Safari on iOS", Safari and IE (#14675)

### LINKED ISSUE #14675: http.headers.Referrer-Policy - Update for "Safari on iOS", Safari and IE
#### What information was incorrect, unhelpful, or incomplete?

- It is written as `No (No support)` for iOS Safari and IE in the MDN. But current iOS Safari supports it as well as Safari.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
- And IE11 partially supports it.
- **NOTES**: about `Default policy is strict-origin-when-cross-origin`
    - At least Safari 15.3 **supports** this. (I have not been able to test with version 15.0)
        - Safari 14.1.2 **does not** support this.
    - iOS Safari (iOS 15.0) **supports** this.
        - iOS Safari (iOS 14.0) **does not** support this.

refs. https://caniuse.com/referrer-policy

#### What did you expect to see?

| *(The table before revision)* | IE | Safari | Safari on iOS |
|:---:|:---:|:---:|:---:|
| **Referrer-Policy** | No | 11.1 | No |
| **Default policy is<br> strict-origin-when-cross-origin** | No | No | No |
| **same-origin** | No | 11.1 | No |
| **strict-origin** | No | 11.1 | No |
| **strict-origin-when-cross-origin** | No | 11.1 | No |

| *(The table after revision)* | IE | Safari | Safari on iOS |
|:---:|:---:|:---:|:---:|
| **Referrer-Policy** | **11<br> (partial support)** | 11.1 | **12** |
| **Default policy is<br> strict-origin-when-cross-origin** | No | **15** | **15** |
| **same-origin** | No | 11.1 | **12** |
| **strict-origin** | No | 11.1 | **12** |
| **strict-origin-when-cross-origin** | No | 11.1 | **12** |

I'm not sure, but I made the following difference for reference.

```diff
diff --git a/http/headers/referrer-policy.json b/http/headers/referrer-policy.json
index 20ea3093f..bb5de2cc5 100644
--- a/http/headers/referrer-policy.json
+++ b/http/headers/referrer-policy.json
@@ -22,7 +22,9 @@
               "version_added": "50"
             },
             "ie": {
-              "version_added": false
+              "version_added": "11",
+              "partial_implementation": true,
+              "notes": "Browsers initially supported an <a href='https://wiki.whatwg.org/wiki/Meta_referrer'>early draft</a> of the specification which can only use a meta tag and is only compatible with the <code>origin</code> value from the new spec."
             },
             "opera": {
               "version_added": "43"
@@ -34,7 +36,7 @@
               "version_added": "11.1"
             },
             "safari_ios": {
-              "version_added": false
+              "version_added": "12"
             },
             "samsunginternet_android": {
               "version_added": "7.2"
@@ -78,10 +80,10 @@
                 "version_added": "60"
               },
               "safari": {
-                "version_added": false
+                "version_added": "15"
               },
               "safari_ios": {
-                "version_added": false
+                "version_added": "15"
               },
               "samsunginternet_android": {
                 "version_added": "14.0"
@@ -129,7 +131,7 @@
                 "version_added": "11.1"
               },
               "safari_ios": {
-                "version_added": false
+                "version_added": "12"
               },
               "samsunginternet_android": {
                 "version_added": "7.2"
@@ -177,7 +179,7 @@
                 "version_added": "11.1"
               },
               "safari_ios": {
-                "version_added": false
+                "version_added": "12"
               },
               "samsunginternet_android": {
                 "version_added": "7.2"
@@ -225,7 +227,7 @@
                 "version_added": "11.1"
               },
               "safari_ios": {
-                "version_added": false
+                "version_added": "12"
               },
               "samsunginternet_android": {
                 "version_added": "7.2"
```

#### Did you test this? If so, how?

I built [a test site](https://rp1.lavoscore.org/path/to/0_NULL.php) for Referrer Policy and tested it on each browser. Especially, I tested about support of `Default policy is strict-origin-when-cross-origin`.

| Browser | **Default policy** | testing environment |
|:---:|:---:|:---:|
| Safari 14.1.2 | no-referrer-when-downgrade | Native macOS |
| Safari 15.0 | unknown (no test) | nothing |
| Safari 15.3 | **strict-origin-when-cross-origin** | Native macOS |
| Safari on iOS 14.0 | no-referrer-when-downgrade | BrowserStack |
| Safari on iOS 15.0 | **strict-origin-when-cross-origin** | BrowserStack |

#### MDN page report details

* Query: `http.headers.Referrer-Policy`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
* Report started: 2022-01-26T07:55:16.261Z

### PR DESCRIPTION
**Pull request by debiru**
#### Summary
Update for "Safari on iOS", Safari and IE.
The "notes" in IE is reprinted from https://caniuse.com/referrer-policy

#### Test results and supporting details
see #14675

#### Related issues
Fixes #14675

### CODE REVIEW

**Comment by debiru** [comment]
@ddbeck If you don't mind, I'd appreciate it if you could take a look. It would be great if you could merge it or comment.

**Review by ddbeck — CHANGES_REQUESTED** [review]
Hi and thank you for this PR. I see it's your first to the project—welcome!

I think the IE details may be misplaced. See the line comment for more detail

**Comment by debiru** [comment]
Thank you for reviewing. I overlooked that https://developer.mozilla.org/ja/docs/Web/HTML/Element/meta was there.

There seems to be no information about referrers other than IE, so I'll investigate that while I'm at it.

**Comment by debiru** [comment]
I have checked on the corresponding versions of each.

- for HTTP/Headers/Referrer-Policy
    - the test page is https://rp1.lavoscore.org/path/to/0_NULL.php
- for HTML/Element/meta name.referrer
    - the test page is https://rp3.lavoscore.org/path/to/0_NULL.php

And I also referred to https://caniuse.com/referrer-policy

I could not test Opera Android because I do not have the environment to test it.

**Review by ddbeck — APPROVED** [review]
Looks good. Thank you! 🎉

**Pull request merged**
