### PR TITLE
Revert "Update Safari data for aspect-ratio CSS property"

### PR DESCRIPTION
**Pull request by foolip**
Reverts mdn/browser-compat-data#19570

### CODE REVIEW

**Comment by foolip** [comment]
In https://github.com/mdn/browser-compat-data/pull/19570, I think the only evidence for the change is https://mdn-bcd-collector.gooborg.com/tests/css/properties/aspect-ratio, and I couldn't confirm any effect of `aspect-ratio` in Safari 14.1. I've tested `<div>`, `` and `<video>`.

**Comment by gsnedders** [comment]
This was probably caused by the bug where `CSS.supports` didn't take settings into account, and would return false-positives.

**Comment by foolip** [comment]
Ah, that would make sense! Would you happen to know how far back that bug goes, and is there a way to list flags? I suspect there are more errors in BCD due to this...

**Comment by gsnedders** [comment]
It might be worthwhile using that code branch for Safari < 15, dunno.

**Comment by queengooborg** [comment]
> It might be worthwhile using that code branch for Safari < 15, dunno.

Oh it's already been in use; that branch is the main deployment of the collector at https://mdn-bcd-collector.gooborg.com!  I've also modified the test in https://github.com/GooborgStudios/mdn-bcd-collector/commit/55ba62d7630e4b0ecdf9b22d29bcff570abc04a3 to pass an applicable value (instead of just `inherit`), which will be released in v10 of the collector!

**Comment by gsnedders** [comment]
Did https://github.com/GooborgStudios/mdn-bcd-collector/commit/55ba62d7630e4b0ecdf9b22d29bcff570abc04a3 cause any changes? I don't think it should for Safari? Maybe it does.

The better fix would just be what I meant above—not using the `if ('CSS' in window && window.CSS.supports)` branch on Safari < 15.

**Comment by queengooborg** [comment]
> Did https://github.com/GooborgStudios/mdn-bcd-collector/commit/55ba62d7630e4b0ecdf9b22d29bcff570abc04a3 cause any changes? I don't think it should for Safari? Maybe it does.

It did, yes -- it reports `false` in Safari 14.1!

**Pull request merged**
