### PR TITLE
Update compat data for bookmarks API

### PR DESCRIPTION
**Pull request by a2sheppy**
Updated support version numbers for Chrome on a few things from info
gleaned while researching the bookmarks API.

### CODE REVIEW

**Comment by Elchi3** [comment]
Travis failure is legit. 
This is not valid JSON, there is a "clip" string that doesn't belong there.

**Comment by a2sheppy** [comment]
Where the heck did that come from?It wasn't there when I did my diff while checking my work... it must have gotten slid in there right after the check and before I committed. I will see if I can fix it. I really really hate git. :)

**Comment by a2sheppy** [comment]
OK, try this one.

**Comment by a2sheppy** [comment]
Gah.

**Comment by a2sheppy** [comment]
Ah, I see what's wrong. OK.

**Comment by a2sheppy** [comment]
OK, now I know it's good, because I actually installed the test tools and ran them manually here locally before the commit.

**Comment by Elchi3** [comment]
Ideally, you would squash the broken commits into a single good commit.

**Comment by a2sheppy** [comment]
Yeah, I was hoping it wasn't mandatory on this project. I've never understood why that's how so many people want it done. Seems like a lot of trouble to go through just to hide mistakes.

--

Eric "Sheppy" Shepherd
http://www.sheppyware.net/
http://www.bitstampede.org/

**Comment by wbamberg** [comment]
Please don't use markup in notes, they need to be just text.

**Comment by a2sheppy** [comment]
I give up. I tried to fix all this stuff and squash them and all that and I've left my local git in a total disaster. Git and I are not meant to coexist.

**Pull request closed without merging**
