### PR TITLE
Drop parens() from cancelValuesAndHoldAtTime() alternative_name

### PR DESCRIPTION
**Pull request by foolip**
This is the only method where the alternative_name has parens.

### CODE REVIEW

**Comment by foolip** [comment]
@ddbeck not sure if we should have a lint for this? It's not a hard rule, since css/selectors/is.json has `"alternative_name": ":matches()"` and similar...

**Comment by Elchi3** [comment]
(drive-by comment: https://github.com/mdn/browser-compat-data/issues/3488#issuecomment-470122702 discusses options to make `prefix` and `alternative_name` better altogether. This PR looks fine to me and additional linting could avoid this, but #3488 should probably happen at some point as The Proper Fix™).

**Comment by foolip** [comment]
I will not bother with the linting, then :)

**Review by ddbeck — APPROVED** [review]
Looks good. Thank you! 🎉

**Pull request merged**
