### PR TITLE
Adding Storage Access API compat data

### PR DESCRIPTION
**Pull request by chrisdavidmills**
As per https://trello.com/c/L48xh7RS/11-storage-access-api-fx-64

### CODE REVIEW

**Comment by Elchi3** [comment]
The Firefox version data updates would be better in a separate PR. Also, we probably want to add some more future versions, so that we don't have to update this too frequently. I think last time we added like the next 5 Firefox releases.

**Comment by chrisdavidmills** [comment]
I appreciate that; I only added it here because I was worried that the data would error if it didn't have the versions in place.

**Comment by Elchi3** [comment]
Done in https://github.com/mdn/browser-compat-data/pull/2995

**Comment by Elchi3** [comment]
Three things before this is good to go:

1) If you rebase against master, the failures should be gone, because, yes, I merged the Firefox version updates to master.

2) It would be nice to have an agreement on https://github.com/mdn/browser-compat-data/pull/2994 first and have the addition here be aligned with that agreement.

3) Notes should always end with a full stop. Yours don't do that here.

**Comment by chrisdavidmills** [comment]
OK, I've tried fixing this according to your comments, but the merge conflict fixing has turned it in a mess. I'm not sure if this is correct or not now.

**Comment by chrisdavidmills** [comment]
Lovely, nice one @Elchi3 !

**Pull request merged**
