### PR TITLE
Sort browsers for api/*

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
Depends on #1882.  Sorts all browsers in the API files.

### CODE REVIEW

**Comment by Elchi3** [comment]
+12,042 −12,043

Something is else is changed? :)

**Comment by Elchi3** [comment]
Ah, https://github.com/mdn/browser-compat-data/pull/3049/files#diff-04466bc6c370adc5fc2bcea4942e9e12 
A new line was removed in api/AudioNodeOptions.json. Can you undo that? (or tell the script to not fiddle with this?)

**Comment by vinyldarkscratch** [comment]
Actually, @Elchi3, it looks like there was originally two newlines at the end of the file -- the script just removed the second newline!

**Comment by Elchi3** [comment]
Makes sense, thank you! :)

**Pull request merged**
