### PR TITLE
CI: Test on NodeJS 16 and 18

### PR DESCRIPTION
**Pull request by bershanskiy**
#### Summary

Run tests on NodeJS 16 and 18.

#### Test results and supporting details

N/A

#### Related issues

#16668

### CODE REVIEW

**Comment by bershanskiy** [comment]
Do we still plan to merge this?

**Comment by bershanskiy** [comment]
Is this PR still relevant or should I close this?

**Comment by queengooborg** [comment]
I think this would be great to merge, however I'm waiting to obtain permissions to change which tests are required -- I'll keep you posted!

**Comment by bershanskiy** [comment]
Sure, there is absolutely no rush, I just wanted to check in. Also, this is pretty low-priority since the original issue which motivated this change (`ts-node` bug) was already resolved anyway.

**Pull request closed without merging**
