### PR TITLE
test: Fix JSDoc

### PR DESCRIPTION
**Pull request by ExE-Boss**
This&nbsp;fixes **JSDoc**&nbsp;comments in&nbsp;the&nbsp;`test`&nbsp;directory.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
It looks like there’s a bit of inconsistency in changes presented.  On some files you’re removing the hashbang comment, but on others you’re adding it in?

**Comment by ExE-Boss** [comment]
I’m&nbsp;removing&nbsp;it from&nbsp;those&nbsp;files that&nbsp;aren’t&nbsp;executable from&nbsp;the&nbsp;commandline, because&nbsp;they&nbsp;only export&nbsp;a&nbsp;function, and&nbsp;don’t&nbsp;execute any&nbsp;code until&nbsp;that&nbsp;function is&nbsp;called.

Including the&nbsp;hashbang&nbsp;comment in&nbsp;those&nbsp;files is&nbsp;misleading.

**Comment by vinyldarkscratch** [comment]
In that case, there’s a little more of an underlying issue I see — we should consider making all of the linters executable, or none of them.  (I’m pretty big on consistency within code.) I’ll talk with the others later today and see what we’d want to do!

**Comment by vinyldarkscratch** [comment]
Another thing: the PR is about the JSDoc comments, however I wouldn't really classify the hashbang comments or copyright notices as JSDoc changes.  I do think that they're useful changes (especially the copyright notices), however we should separate them into their own PRs.

**Review by alshamiri5 — APPROVED** [review]

**Comment by queengooborg** [comment]
I opened up #16131 to supersede this, since it's been completely inactive and the PR author has not had any activity on this project in the last year or so.  Thank you for your work on this, I'll keep working on it and work to get it merged!

**Pull request closed without merging**
