### PR TITLE
Add Chrome support for HTML data URLs

### PR DESCRIPTION
**Pull request by TheDude53**
Added Chrome support for HTML data URLs.

Example: data:text/html;base64,PHA+SGVsbG8gV29ybGQ8L3A+

### CODE REVIEW

**Comment by jpmedley** [comment]
@foolip Do you know a way to find if this is supported on Android and WebView? I don't.

**Comment by vinyldarkscratch** [comment]
Good news is that a quick test run in Chrome Android revealed that `data:text/html,%3Ch1%3EHello%2C%20World!%3C%2Fh1%3E` works as expected!  (I'm not able to test Webview Android -- it's system disabled and I have not been able to find a way to enable it -- but I'm certain it works in there as well).  Opera reveals the same results -- and even Firefox.

**Comment by foolip** [comment]
@jpmedley I'd test it in Firefox Focus or some other WebView-based browser.

**Comment by ddbeck** [comment]
> I'd test it in Firefox Focus or some other WebView-based browser.

I just tried this and it works!

@TheDude53 would you be willing to set `"webview_android": true` as well? Thank you and welcome to BCD! 😄

**Comment by TheDude53** [comment]
I added "webview_android".

**Comment by ddbeck** [comment]
@TheDude53 is there a reason that you closed this PR? The change you added looks fine to me

**Comment by vinyldarkscratch** [comment]
I think it was accidentally closed -- aside from needing Opera and Opera Android set to `true` as well, this looked like a good PR!  I also tested support in Firefox and Safari, and confirmed that both worked, so I added them into a new PR.

**Comment by ddbeck** [comment]
OK, I just took a look at @vinyldarkscratch's and it does seem to cover it. I'll merge that one in a moment. Thank you so much for kicking this off and helping move it along, @TheDude53!

**Pull request closed without merging**
