### PR TITLE
Update Chromium data for Magnetometer API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects version values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `Magnetometer` API. Other

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
This blog post says it is behind the `#enable-generic-sensor-extra-classes` flag. https://developer.chrome.com/articles/generic-sensor/

Maybe @tomayac knows more?

**Comment by tomayac** [comment]
I just verified, and yes, `Magnetometer` is still behind the flag, as outlined in the article.

**Comment by queengooborg** [comment]
It appears that this feature can be enabled using either the

**Comment by queengooborg** [comment]
(Ignore the PR close, I misclicked...)

It looks like this API can be enabled using either #enable-generic-sensor-extra-classes or #enable-experimental-web-platform-features.  In the past, I've been told that the latter flag is preferred in favor of other flags, is that still the case?

**Comment by queengooborg** [comment]
I'm down for that -- I've made the change to our data to use `#enable-generic-sensor-extra-classes` instead!

**Pull request merged**
