### PR TITLE
Chrome Android 109 adds FileSystemWritableFileStream API support

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects version values for Chrome Android for the `FileSystemWritableFileStream` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).

_Check out the [collector's guide on how to review this PR](https://github.com/openwebdocs/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemWritableFileStream

### CODE REVIEW

**Comment by Elchi3** [comment]
https://issues.chromium.org/issues/40101963 is still open so I'm not sure about this one.

**Comment by nya3jp** [comment]
I believe it's available since Android Chrome 109. #23479

**Comment by Elchi3** [comment]
@nya3jp thank you!
@queengooborg would the collector agree with Chrome Android 109?

**Comment by queengooborg** [comment]
We don't have results for all of the specific Android browsers (and I don't have a way to test older releases of Android browsers at the moment), but the collector confirmed support in the latest version of the browser.  Based upon the sources linked in the issue, I'll trust 109 is accurate!

**Review by caugner — APPROVED** [review]

**Pull request merged**
