### PR TITLE
Fix browser key enumeration for subfeatures

### PR DESCRIPTION
**Pull request by Elchi3**
This should fix the problem stated in https://github.com/mdn/browser-compat-data/pull/318#discussion_r138344245

### CODE REVIEW

**Comment by wbamberg** [comment]
Can you give me a JSON that will reproduce the original problem? I tried this: https://github.com/teoli2003/browser-compat-data/blob/e5f3d249f041952731c71f02e50a3402c9f6d298/html/elements/menu.json, which seems like it ought to do it (and has the same structure you describe in https://github.com/mdn/browser-compat-data/pull/318#discussion_r138344245, but it works with the version of render.js in master.

**Comment by Elchi3** [comment]
Weird. I can't reproduce anymore either... @teoli2003 do you still see the render.js crashing with your updated html interactive elements branch?

**Comment by teoli2003** [comment]
No, it isn't crashing anymore. Weird.

**Comment by Elchi3** [comment]
So, the bug was that the browser names weren't available somehow. I thought this would fix that, but if this isn't a problem, I would say let's close this change unmerged for now. If there really is a problem, it will come back :)

**Comment by teoli2003** [comment]
Seems like a good plan.

**Pull request closed without merging**
