### PR TITLE
Update Firefox versions for referrerPolicy property

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects the real values for Firefox for the `referrerPolicy` member of various APIs, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v6.1.0).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/SVGAElement/referrerPolicy

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

This effectively reverts the SVGAElement changes of #2858.

### CODE REVIEW

**Review by foolip — COMMENTED** [review]
Can you investigate if this should match svg.elements.a.referrerpolicy? That still says "52".

It could be that the content attribute was supported before the IDL attribute and vice-versa.

**Comment by queengooborg** [comment]
Hmm...  It looks like the feature was originally set to "61", but was then set to "52" in https://github.com/mdn/browser-compat-data/pull/2858.

**Comment by foolip** [comment]
I see, so https://github.com/mdn/browser-compat-data/pull/2858 incorrectly updated a bunch of data based on https://chromium.googlesource.com/chromium/src/+/a8e98a61a6144db6a2b45baaff9eeb8930f0296f which was only about  the Fetch API.

`npm run traverse -- -b chrome -f 52 | grep -i referrerpolicy` now lists:

```
api.HTMLAnchorElement.referrerPolicy
api.HTMLAnchorElement.referrerPolicy (as referrerpolicy)
api.HTMLAreaElement.referrerPolicy
api.HTMLAreaElement.referrerPolicy (as referrerpolicy)
api.HTMLIFrameElement.referrerPolicy
api.HTMLIFrameElement.referrerPolicy (as referrerpolicy)
api.HTMLImageElement.referrerPolicy
api.HTMLImageElement.referrerPolicy (as referrerpolicy)
api.Request.referrerPolicy
api.fetch.init_referrerPolicy_parameter
```

Can you check/update all of api.HTML*Element.referrerPolicy to fix this?

**Review by foolip — APPROVED** [review]

**Comment by queengooborg** [comment]
So apparently, the collector is reporting that "50" is correct for the other three APIs ("61" is still correct for SVGAElement).  This is backed by Bugzilla bugs:

SVGAElement: https://bugzilla.mozilla.org/show_bug.cgi?id=1451823
Others: https://bugzilla.mozilla.org/show_bug.cgi?id=1187357

**Pull request merged**
