### PR TITLE
Add missing CSS units; update CSS unit support data

### PR DESCRIPTION
**Pull request by pepelsbey**
#### Summary

- Adds missing units: `rcap`, `rch`, `rex`, `ric`, `rlh`
- Update Chrome and Safari support for `cap`
- Update Chrome support for `rlh`

#### Test results and supporting details

- Chrome 111: [rex, rch, ric, rlh](https://chromestatus.com/feature/5073969265246208) (Chrome Platform Status)
- Chrome 117: [cap, rcap](https://chromestatus.com/feature/5137204166262784) (Chrome Platform Status)
- Safari TP 179: [cap, rcap, rex, ric, rch](https://webkit.org/blog/14532/release-notes-for-safari-technology-preview-179/) (release notes)

WPT: [cap](https://wpt.fyi/results/css/css-values/cap-unit-001.html), [rcap](https://wpt.fyi/results/css/css-values/rcap-invalidation.html), [rch](https://wpt.fyi/results/css/css-values/rch-invalidation.html), [rex](https://wpt.fyi/results/css/css-values/rex-invalidation.html), [ric](https://wpt.fyi/results/css/css-values/ric-invalidation.html), [rlh](https://wpt.fyi/results/css/css-values/rlh-invalidation.html)

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey there, thank you for your PR and welcome to BCD!

Would you be down to add the other units in this PR as well?

I also recently submitted a PR to add the missing static methods of the `CSS` interface, which may give some assistance/inspiration: https://github.com/mdn/browser-compat-data/pull/20984

**Comment by pepelsbey** [comment]
@queengooborg done!

**Comment by teoli2003** [comment]
The CI complains. I guess some `""` are missing. Note that you can run the tests locally, with `npm run test`, if I remember correctly.

**Review by queengooborg — APPROVED** [review]
Thank you for adding/updating the other CSS units as well!  LGTM!

**Pull request merged**
