### PR TITLE
Remove data for CSS type <length-percentage>

### PR DESCRIPTION
**Pull request by foolip**
This is just the union of <length> and <percentage>:
https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/CSS/percentage#browser_compatibility

### CODE REVIEW

**Comment by foolip** [comment]
@Elchi3 do you think this is a good idea? If so, I assume there are more cases like this, and MDN pages would need updating too.

**Comment by Elchi3** [comment]
@foolip Can you file an mdn/content issue that discusses removing https://developer.mozilla.org/docs/Web/CSS/length-percentage? I'm not a CSS docs maintainer really and I'm not sure how useful and needed this page is. A solution could be that the page remains but refers to two compat tables, one for length and another for percentage.

From a BCD point of view it probably makes sense to remove it. Now it is duplicating data because BCD has no way to export a collection of features as a group otherwise.

**Comment by foolip** [comment]
@Elchi3 I've filed https://github.com/mdn/content/issues/13066

**Comment by foolip** [comment]
I'll close this while https://github.com/mdn/content/issues/13066 is open, I don't feel like driving this to completion myself right now.

**Pull request closed without merging**
