### PR TITLE
Add Firefox for iOS

### PR DESCRIPTION
**Pull request by ExE-Boss**
There are plans for Firefox for iOS to [support lightweight themes](https://bugzil.la/1210119), probably by using the WebExtensions `theme` [manifest keys](https://bugzil.la/1466496).

### CODE REVIEW

**Comment by connorshea** [comment]
I'd be concerned that some contributors might try to add data about Firefox for iOS to properties that aren't WebExtensions-related, which doesn't really have a point because of iOS browsers all just using WebKit as their engine.

**Comment by ExE-Boss** [comment]
Well, which browsers are visible for which category is controlled by [`browser‑compat‑toolkit`](https://github.com/mdn/browser-compat-toolkit/blob/master/src/renderers/mdn-feature-table.js#L28-L34) (and [`kumascript`](https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs#L65-L90)), so even if someone were to try to add **Firefox for iOS** to non-WebExtension features, it wouldn’t show up in MDN anyway.

**Comment by connorshea** [comment]
Regarding my previous comment, I wonder if we shouldn’t have the linter check for certain browsers in certain feature categories? E.g. Firefox for iOS info being added for a feature in html/ would cause the linter to fail. I think that’d make it easier to add these “edge-case” browses safely.

**Comment by ExE-Boss** [comment]
At first, I thought that wouldn’t be a problem, but after seeing #2484, I’ll add that to the linter in a separate PR.

**Comment by Elchi3** [comment]
There is still no implementation of themes in Firefox for iOS. I think it is too early to even add Firefox iOS to this repo (even if it is just for webextensions). Implementation might never happen at all and I think it is too much overhead for us now to maintain this here. What do you think @wbamberg?

**Comment by wbamberg** [comment]
>  I think it is too early to even add Firefox iOS to this repo (even if it is just for webextensions). Implementation might never happen at all and I think it is too much overhead for us now to maintain this here. What do you think @wbamberg?

I agree.

**Comment by Elchi3** [comment]
I'm closing here then. We can re-consider this if it should become a reality.

**Pull request closed without merging**
