### PR TITLE
Add WebGL2 functions recently implemented in Chrome

### PR DESCRIPTION
**Pull request by jpmedley**
I cannot account for the screwy way github is presenting this.

### CODE REVIEW

**Comment by jpmedley** [comment]
Is there anything I can do to move this forward?

**Comment by Elchi3** [comment]
Thanks for your patience, @jpmedley. 

My summary of this PR is, that it does the following two changes. (I always appreciate PR summaries, so that I know what the motivation is. It might ease review or speed it up, too).

1) This adds a function `WebGL2RenderingContext.compressedTexImage2D`.
I think is actually installed on the `WebGLRenderingContext` and therefore present in the [WebGLRenderingContext.json](https://github.com/mdn/browser-compat-data/blob/master/api/WebGLRenderingContext.json#L1770) compat file. See it on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/compressedTexImage2D) where it then also mentions how it is different in a WebGL2 environment. r- on this.

2) It removes `WebGL2RenderingContext.uniform1i, WebGL2RenderingContext.uniform1f, WebGL2RenderingContext.uniform2i, WebGL2RenderingContext.uniform2f, WebGL2RenderingContext.uniform3i, WebGL2RenderingContext.uniform3f, WebGL2RenderingContext.uniform4i, WebGL2RenderingContext.uniform4f`.
I confirm these are all on the `WebGLRenderingContext`, and we have the compat data in the WebGL 1 file already. Great catch, r+ on this change!

It seems like the first commit did many other changes, and the second reverted these then. I have only looked at the overall diff and I think I will squash this PR when merging.

**Comment by jpmedley** [comment]
The reason for the reversal is because I didn't realize until after I'd done it the difference between how the Chrome source files organize these functions and how they're represented on MDN.

**Comment by jpmedley** [comment]
Florian,

I'll be closing these requests shortly and submit the changes in smaller fragments. I think these are going to take me a while to get right. If I focus on one aspect of it at a time, my working branches are shorter-lived, meaning there's less chance of a merge conflict. Plus I think reviewing them might be easier.

I apologize for the time you've already spent.

Joe

**Pull request closed without merging**
