### PR TITLE
FF114 remove cache directive from HTTP  Clear-Site-Data

### PR DESCRIPTION
**Pull request by hamishwillee**
FF114 removes this in https://bugzilla.mozilla.org/show_bug.cgi?id=1821651

Other docs work for this can be tracked in https://github.com/mdn/content/issues/26246

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Is the flag range still useful to anyone or does it just add confusion?

**Comment by hamishwillee** [comment]
@Elchi3 I just go for informational accuracy by default and you guys tell me if you want to fudge it for other reasons. 

I have removed on assumption you want this. I don't think anyone will be wondering how to re-enable this on 113.

**Review by queengooborg — APPROVED** [review]
It's our policy to remove flag data as soon as it becomes irrelevant, so this is LGTM!

**Review by queengooborg — APPROVED** [review]
It's our policy to remove flag data as soon as it becomes irrelevant, so this is LGTM!

**Pull request merged**
