### PR TITLE
New features support added to Nodejs 15.0.0

### PR DESCRIPTION
**Pull request by TheMoniV**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data:
[Node v15.0.0 release](https://nodejs.org/en/blog/release/v15.0.0/)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by sideshowbarker** [comment]
CI error says:
https://github.com/mdn/browser-compat-data/runs/1284297607
> javascript.builtins.String.replaceAll - version_added: "15.0.0" is NOT a valid version number for nodejs

**Comment by TheMoniV** [comment]
> CI error says:
> https://github.com/mdn/browser-compat-data/runs/1284297607
> 
> > javascript.builtins.String.replaceAll - version_added: "15.0.0" is NOT a valid version number for nodejs

Yeah I see, but Nodejs 15.0.0 is out now.

**Comment by sideshowbarker** [comment]
> Yeah I see, but Nodejs 15.0.0 is out now.

OK, then I guess we need to update our version data here. I’ll try to create a PR for that right now

**Comment by sideshowbarker** [comment]
> Yeah I see, but Nodejs 15.0.0 is out now.

Raised https://github.com/mdn/browser-compat-data/pull/7015. After that’s merged, we can rebase this PR branch, and that should make the CI linter happy.

**Comment by sideshowbarker** [comment]
Thanks much, and welcome to the browser-compat-data project 🎉

**Pull request merged**
