### PR TITLE
Move constructor compat data for ArrayBuffer/DataView

### PR DESCRIPTION
**Pull request by Elchi3**
This moves the constructor compat data under the respective constructor tree.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer#Browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView#Browser_compatibility 

review @bershanskiy ?

### CODE REVIEW

**Comment by bershanskiy** [comment]
@Elchi3 Thanks for pinning me!

I think there is a duplication of the same information in BCD: `SharedArrayBuffer.sab_in_dataview` and `DataView.sharearraybuffer_support` (and the first one is more complete).

https://github.com/mdn/browser-compat-data/blob/c6f78bcf559856633c3f07eb7f11573839123959/javascript/builtins/SharedArrayBuffer.json#L358-L472

https://github.com/mdn/browser-compat-data/blob/c6f78bcf559856633c3f07eb7f11573839123959/javascript/builtins/DataView.json#L159-L212

If they indeed represent the same information, I'd rather see this information condensed in a single place, preferably under `DataView` constructor.

On a different topic, [ArrayBuffer.transfer()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/transfer) is just a [Stage 2 proposal](https://github.com/tc39/proposals) and is not (yet) available on any platform. Is there any point in keeping a documentation page about a feature that no platform committed to implement and might change during the implementation?

**Comment by Elchi3** [comment]
> If they indeed represent the same information, I'd rather see this information condensed in a single place, preferably under DataView constructor.

I think you're right here, and I've just pushed a commit to do exactly that.

> On a different topic, ArrayBuffer.transfer() is just a Stage 2 proposal and is not (yet) available on any platform. Is there any point in keeping a documentation page about a feature that no platform committed to implement and might change during the implementation?

Yes, premature features in documentation are confusing. People might search for "arraybuffer transfer" then find this page and be disappointed is not present in reality. We should avoid this. Lets remove this in a separate PR.

**Comment by bershanskiy** [comment]
@Elchi3 FYI, I filed #5705 for removing `ArrayBuffer.transfer()`.

**Comment by bershanskiy** [comment]
I think this info is correct, and it just needs manual merging and a rebase now.

Thanks for giving me time to look at it.

**Comment by Elchi3** [comment]
Thanks @bershanskiy! Resolved the merge conflicts now and merging so it will make today's release.

**Pull request merged**
