### PR TITLE
Create .nvmrc

### PR DESCRIPTION
**Pull request by queengooborg**
This PR creates a `.nvmrc` file to allow for easy (and depending on one's shell configuration, automatic) switching to NodeJS v14 when working on BCD.  With the presence of this file, running `nvm use` will switch the NodeJS version to v14, and with certain shell plugins/scripts, will automatically switch when the user `cd`s to the BCD folder.

Note: I would love to do the same for `nodenv`, but Daniel had brought up in #12137 that plugins are needed to allow for version shorthands.

### CODE REVIEW

**Comment by foolip** [comment]
Is this still needed after https://github.com/mdn/browser-compat-data/pull/11335? What does `nvm use` do by default?

**Comment by queengooborg** [comment]
`nvm use` will just throw an error if the `.nvmrc` file doesn't exist or the version argument isn't specified (i.e. `nvm use 16`).  #11335 ensures that all contributors are using at least NodeJS 14, whereas this is to suggest that contributors should use v14 specifically (since v15+ uses package-lock v2).

**Comment by foolip** [comment]
Makes sense! Will this file be included in the released package, does it need to be excluded somehow?

**Comment by foolip** [comment]
Right you are, only a few files are copied over:

https://github.com/mdn/browser-compat-data/blob/a4b6eed10ad30aa719d5acb819ba21210510c9d5/scripts/release-build.js#L8

**Review by foolip — APPROVED** [review]
I approve, but would like one other [owner](https://github.com/mdn/browser-compat-data/blob/main/GOVERNANCE.md#owners) to also approve, as this is (I think) the first infra change I'm approving.

**Comment by queengooborg** [comment]
It's pretty conventional from what I've seen and helps ensure that contributors are on the same page.  I use NVM and have NodeJS v16 as my default (will soon switch to v18 when that's released, so having my Node version automatically switch to ensure I'm not replacing `package-lock.json` with a v2 lockfile would be pretty great.

**Comment by foolip** [comment]
If the main problem here is the new lockfile format, can we just go ahead and require Node.js 16 for contributors? That's what I have installed now, and I don't use nvm, I just keep ignoring the package-lock.json changes instead.

**Comment by queengooborg** [comment]
We could do that actually, though I'm realizing we should probably ask the top contributors how they'd feel about having to use NodeJS v16 for contributions?  I assume the response will be positive, but better safe than sorry!

**Comment by Elchi3** [comment]
I'm using v16 too.

**Comment by queengooborg** [comment]
Pinging @bershanskiy @sideshowbarker @hamishwillee @lukewarlow @lucacasonato about NodeJS v16 -- how do you guys feel about upgrading to NodeJS v16 for contributions?

**Comment by bershanskiy** [comment]
> about NodeJS v16 -- how do you guys feel about upgrading to NodeJS v16 for contributions?

Sure thing. I can accommodate any version but would always prefer to use Active LTS (as recommended by NodeJS itself). This version agility was [the primary motivation for pre-built bundles](https://github.com/mdn/browser-compat-data/pull/7398#discussion_r613436129) :).

Please also make sure to update CI, e.g.:
https://github.com/mdn/browser-compat-data/blob/825f48679f783d54f3ee5d02d87babe0185f7d0a/.github/workflows/node.js.yml#L20

For completeness:
```
$ grep "node-version" .github/ -r
.github/workflows/add-push-artifacts.yml:        node-version: 14.x
.github/workflows/node.js.yml:        node-version: 14.x
.github/workflows/release.yml:        node-version: 14.x
```

**Comment by saschanaz** [comment]
(What's interesting is that `nvm install 14` installs npm 6, so upgrading to package lock v2 shouldn't even be blocked by upgrading to Node.js 16)

**Comment by queengooborg** [comment]
`package-lock` v2 was actually introduced in NPM 7 / NodeJS v15!

**Comment by hamishwillee** [comment]
@queengooborg Sorry, late to the party - I work here Monday, Tuesday, Friday. Very happy to update, because I also use NVM (was there ever such a welcome tool!).

My only "requirement" is that if I am using the wrong node for BCD then BCD should tell me this - not pop up some other  spurious error.

**Pull request closed without merging**
