### PR TITLE
Mark non-standard prefixed keys as non-standard

### PR DESCRIPTION
**Pull request by jamesnw**
#### Summary
There were ~7~ 2 prefixed keys that are not part of a standard, but were marked as standard track.

#### Test results and supporting details

They were added in #21623  and #21621, both of which note that they are non-standard keys. I also checked each MDN entry, and they were all noted as non-standard, or had no link to a spec.

### CODE REVIEW

**Comment by jamesnw** [comment]
@ddbeck This change will remove 7 keys from the Web Features backlog.

**Review by ddbeck — CHANGES_REQUESTED** [review]
It looks like the `-webkit-mask-box-*` entries _are_ standardized. There's a proposal to make these aliases `"alternative_name"` data in their corresponding standardized aliases: https://github.com/mdn/browser-compat-data/issues/22727 (though I'd like to get @Elchi3's take on it before doing it).

The `-webkit-slider-` entries look correct.

**Comment by Elchi3** [comment]
> It looks like the `-webkit-mask-box-*` entries _are_ standardized. There's a proposal to make these aliases `"alternative_name"` data in their corresponding standardized aliases: #22727 (though I'd like to get @Elchi3's take on it before doing it).

+1

**Comment by jamesnw** [comment]
Oh right, sorry for missing that. I've removed the -webkit-mask-box-* changes from this PR now.

**Review by ddbeck — APPROVED** [review]

**Pull request merged**
