### PR TITLE
Update css.properties.position.fixed/sticky

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
I found `sticky` positioning a few moments ago, and immediately fell in love with it, so I [integrated it into my company's website](https://www.gooborg.com/team).  I decided to show it off to my boyfriend, but when he couldn't find out what I was talking about, we realized that `sticky` positioning simply isn't supported in Firefox ~~Android~~.  So, I decided to do some digging around to check on `fixed` and `sticky` positioning on all the browsers.

This PR reflects manual checks on the properties during my development of my studio's website.

### CODE REVIEW

**Comment by Elchi3** [comment]
From reading articles, there seem to have been quite a bit back and forth with position: sticky. Maybe @rachelandrew could help reviewing this one? I think it would be good if the compat table at https://developer.mozilla.org/en-US/docs/Web/CSS/position#Browser_compatibility talks about the compat minefields, especially if they aren't defused yet.

https://caniuse.com/#feat=css-sticky says it works in Firefox Android, so I don't know.

**Comment by vinyldarkscratch** [comment]
If it helps, here's a side-by-side comparison of https://www.gooborg.com/team (the website I mentioned above) on both Chrome and Firefox for Android:

Screen Shot 2019-04-30 at 10 25 02

**Comment by freaktechnik** [comment]
`postition: sticky` most definitely works on Firefox for Android. And from your screenshot it looks like it works properly in Firefox for Android but not in Chrome? However it's working correctly in Chrome, too for me.

**Comment by vinyldarkscratch** [comment]
Ah, sorry, I realize that my screenshots are a little confusing about what I’m focusing on.  The word “Artist” is `position: sticky`, not the menubar (should have circled them to show, haha).  It works just fine in Firefox Desktop, Chrome Desktop, Chrome Android, and Safari, but Firefox Android doesn’t seem to give the intended results.

If it’s functioning, then perhaps it’s a faulty/partial implementation?

**Comment by freaktechnik** [comment]
That sticky doesn't work for me in Firefox at all (i.e. not working in desktop nightly).

I've seen Firefox have trouble with sticky in some contexts, though I have never really dug into if it's Firefox's fault or my fault of how I use sticky.

**Comment by vinyldarkscratch** [comment]
Oh you're right, huh...  I could have sworn I tested it in Firefox and it worked!  But then again, that makes more sense to me.

Alright then, I'll be expanding the scope of this to include Firefox Desktop

**Comment by vinyldarkscratch** [comment]
So after some quick testing, it looks like there may be some bugs in the way that sticky positioning functions.  On https://developer.mozilla.org/en-US/docs/Web/CSS/position, it works perfectly fine -- both the example at the top and the one specific to just sticky positioning.  But on my own website, Firefox doesn't know what to do.  I've tried to add several properties from the example to my own code, none of which seem to do the trick.  Tried adding the positioning property onto other types of elements as well with no luck.

I'm stumped as to what exactly is going on with this property, and why it's only non-functional on my website...

**Comment by rachelandrew** [comment]
Do you have a reduced test case of the issue? As far as I know position: sticky "works" you may have found a bug, or you may have missed something, but it is hard to say from this thread!

**Comment by vinyldarkscratch** [comment]
I tried it with a [reduced test case](https://github.com/mdn/browser-compat-data/files/3186125/test.html.zip) in Firefox and found that it works just fine, leaving the only reasonable explanation as that it's a conflict somewhere in my own website.  I've got `position: -webkit-sticky; position: sticky; top: 3em;`, and I've only got siblings after the element with `position: sticky;`, so I don't know what's different...

I know it sounds a little egotistical to say that I don't think it's a problem in my code in particular, but...I don't think it's a fault in my development, and most likely a bug in Firefox.  Comparing Firefox's computed output, the properties are virtually identical:

Screen Shot 2019-05-16 at 01 38 48
Screen Shot 2019-05-16 at 01 39 01

**Comment by vinyldarkscratch** [comment]
I'm adding "info needed" and "not ready" flags to this PR as we're not sure what exactly is going on with the sticky property.

**Comment by ddbeck** [comment]
@vinyldarkscratch do you plan to revisit this question of the sticky property? If not, it might make sense to revert the Firefox data and merge without it (or close this PR until later).

**Comment by vinyldarkscratch** [comment]
I haven't been planning on returning to this PR just yet, though I realize I didn't write a bug report in Bugzilla either.  It makes sense to separate the non-Firefox changes out and get those merged, since we can prove them fully!

**Comment by vinyldarkscratch** [comment]
After tons of research, I've finally figured out the exact issues with `position: fixed;` on Firefox on my site.  If the following CSS is present, `position: fixed;` doesn’t function:

```
html {
	scroll-behavior: smooth;
}

body {
	overflow-x | overflow-y | overflow: auto | hidden | scroll | -moz-hidden-unscrollable;
}
```

It does not occur with one statement or the other.  Both must be present.

I'll be closing this issue and opening up a bug in Bugzilla!

**Pull request closed without merging**
