### PR TITLE
Set Chromium versions from Safari versions for several column properties

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR adds version numbers to Chrome (and Chrome-based browsers) based upon data from Safari to six different CSS column properties.

### CODE REVIEW

**Comment by jpmedley** [comment]
Chrome stuff looks good to me.

**Comment by vinyldarkscratch** [comment]
Since this PR is solely Chrome-based changes and nothing else, may I interpret your response as an official approval of these changes, @jpmedley?

**Comment by jpmedley** [comment]
I didn't want to use the approve feature because this includes a Samsung change, which I can't confirm. I didn't want you to think that I had.

**Comment by vinyldarkscratch** [comment]
Ah, that makes sense -- no worries, thanks for the response and review!

**Pull request merged**
