### PR TITLE
Add data guideline on `partial_implementation`

### PR DESCRIPTION
**Pull request by jugglinmike**
#### Summary

Because the `partial_implementation` property describes an incomplete feature, it is somewhat ambiguous whether the feature it describes should be considered "supported." As of this commit, the property is exclusively included in affirmative support statements. Formalize this trend with an explicit data guideline.

#### Test results and supporting details

n/a

### CODE REVIEW

**Comment by jugglinmike** [comment]
This patch is based on my interpretation of BCD's data guidelines. [I've recently suggested making it a formal policy.](https://github.com/mdn/browser-compat-data/pull/17861)

**Comment by queengooborg** [comment]
I'm not sure if this is explicitly needed.  Since we are working towards 100% real values everywhere, we are planning to eliminate all uncertain version data anyways, including those on `partial_implementation`.  I'm not against merging this though, so I'll leave it open for another to review!

**Comment by jugglinmike** [comment]
That makes sense to me! I didn't realize that `partial_implementation` is expected to be removed. Maybe it would be best to abandon this patch and instead add a note discouraging its use.

**Comment by queengooborg** [comment]
What I mean is that we're working on replacing all non-real values (that is, "true" and "null") with real values (proper version numbers or "false").  Eventually, the requirement for real values will apply everywhere in BCD.  It's not that this patch is _wrong,_ it's just a subset of the bigger goal!

**Pull request closed without merging**
