### PR TITLE
Add Firefox versions for PerformanceEntry API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR adds real values for Firefox and Firefox Android for the `PerformanceEntry` API, based upon browser bug history.

Bugs:
https://bugzil.la/822480
https://bugzil.la/1047848

### CODE REVIEW

**Review by foolip — CHANGES_REQUESTED** [review]
The original "25" for Firefox Android came from https://github.com/mdn/browser-compat-data/pull/1298 with no discussion about the version that I can see.

https://developer.mozilla.org/en-US/docs/Web/API/Performance#browser_compatibility says `performance.getEntries()` and a bunch of other things were shipped in Firefox 35, but that implies support for `PerformanceEntry` since that's what's returned. Can you double check which is correct and change things to be consistent?

**Comment by vinyldarkscratch** [comment]
I think the original "25" was either a mistake (copied from Chrome Android), or bad data from the wiki tables (which could have also been caused by someone copying the value from Chrome Android).

Regarding the values in this PR however, it seems this is a bit of a problem with our test.  I'm submitting a PR to the collector now to resolve this and use `getEntries()` instead!

**Comment by vinyldarkscratch** [comment]
The new collector updates will fix this, yes!  Since my laptop's out of commission for a while though, it'll be some time before I can get updated results.

**Comment by vinyldarkscratch** [comment]
Hmmm...the recent collector results (v3.1.12) also indicate support in Firefox 38.  Looks like I'll need to revise the custom test again and try to generate an entry before getting any of them, probably.

**Comment by queengooborg** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=822480 marks this interface as implemented in Firefox 31.  Based upon the collector results for `getEntries()`, I'm assuming that it was behind a flag to begin with, so I'll set this to "35" to match.

**Review by foolip — APPROVED** [review]
Matching the methods that return`PerformanceEntry` makes sense!

**Pull request merged**
