### PR TITLE
Reorganize linters and fixers

### PR DESCRIPTION
**Pull request by queengooborg**
This PR reorganizes the linters and fixers structure, as discussed in the last BCD meeting.  This places all of the fixer scripts under the same folder that the linters are, and renames the folder from `test/` to `lint/`.

This ensures both better organization and prepares for a potential linter overhaul in the future.

### CODE REVIEW

**Comment by Elchi3** [comment]
Why was this merged without review?

**Comment by queengooborg** [comment]
We had agreed to do this during the BCD call on March 12th.  I didn't think this would require review since it is solely reorganizing internal infrastructure.

**Comment by Elchi3** [comment]
It would have been useful to still review in more details. In meetings we usually only assess if a PR makes sense generally, ie. if we agree with the notion of it and/or general direction. 

These file names seem not ideal:

test-browsers-data.ts
test-browsers-presence.test.ts

Why not omit the first "test"?
browsers-data.ts
browsers-presence.test.ts

**Comment by queengooborg** [comment]
That's a fair point.  I figured that this particular change was straightforward enough that it wouldn't need a thorough technical review.

The filenames for the linters is something that I've also been wanting to update to remove the redundant `test-` prefix, but I figured that would be better to do in another PR since that had a stronger likelihood of creating merge conflicts with other PRs.  (Turns out that the open linter-related PRs all had merge conflicts anyways...!)

**Pull request merged**
