### PR TITLE
fix spec_url of `ServiceWorkerRegistration`

### PR DESCRIPTION
**Pull request by skyclouds2001**
#### Summary

we should not keep the link to the Push API extensions on `ServiceWorkerRegistration`

### CODE REVIEW

**Comment by teoli2003** [comment]
Why? On an interface, I think we should list specs defining the main `interface` in webidl, as well as `partial interface` additions: only all these webidl together really define `ServiceWorkerRegistration`.

**Comment by skyclouds2001** [comment]
but *partial interface* means extenstions to the interface, not define the interface; personnaly I don't think we should list the spec that is extensions to the interface, only list in the the extended property or method is enough

and, if we keep the link of Push API, we could also keeps links to Content Index API, Background Fetch API, Background Sync API, Cookie Store API, Payment Handler API, Periodic Background Sync API, Notification API, because they all extended `ServiceWorkerRegistration` via *partial interface* additions

**Comment by teoli2003** [comment]
Personally, I think we should add these: that way, the _specification_ list will be the complete set of relevant specs for this feature. Very few features will have several entries, even less many. We could also add an additional rule to start with the single entry that is not `partial`.

Let's wait for other opinions.

**Comment by skyclouds2001** [comment]
see https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration#specifications

image

I mean, only mention the spec of Push API in its extended `ServiceWorkerRegistration.pushManager` property is enough, it is not needed to mention in `ServiceWorkerRegistration` interface (Push API is not the spec that defines the interface)

**Comment by queengooborg** [comment]
I'm not sure that we can have a specific rule of whether or not to include specs with partial definitions, as there will always be exceptions.  One great example of where we _do_ want to include a partial interface definition is the Document API, where about a third is defined in the [DOM Standard](https://dom.spec.whatwg.org/#interface-document), and about two thirds are defined in the [HTML Standard](https://html.spec.whatwg.org/multipage/dom.html#the-document-object).  However, the main spec (where it isn't `partial interface`) is the DOM Standard.

---

Honestly, though, I don't think that this is a big issue.

**Comment by Elchi3** [comment]
I think it is useful to have pointers to all places where the interfaces is defined/extended.

**Pull request closed without merging**
