### PR TITLE
Demix error event from GlobalEventHandlers

### PR DESCRIPTION
**Pull request by queengooborg**
This PR demixes the `error` event from the GlobalEventHandlers mixin.

### CODE REVIEW

**Comment by foolip** [comment]
I've reverted the additions, which aren't specific enough.

**Review by foolip — CHANGES_REQUESTED** [review]
This (the string "error") is probably the most widely used event type, fired in lots of places. For this cleanup we only need to worry about the `Node` hierarchy and `Window`, however.

There's already an entry for `Window`, and these are the elements I can find where there's an "error" event:
- `HTMLImageElement`
- `HTMLLinkElement`
- `HTMLMediaElement` (already in BCD)
- `HTMLObjectElement`
- `HTMLScriptElement`
- `HTMLSourceElement`
- `HTMLStyleElement`
- `HTMLTrackElement`
- `SVGImageElement`
- `SVGScriptElement`
- `SVGStyleElement`
- `SVGUseElement`

Can you add all of these, and remove the "error_event" entry on `Element`? There is no generic "error" event, all of these are separate code paths.

**Comment by foolip** [comment]
Looks like there's also `HTMLInputElement` when `type=image`.

**Comment by queengooborg** [comment]
I've isolated this PR to only focus on removing the event handler from GEH, and have opened an issue for adding the event to the other interfaces.  This should help us remove GEH while we get to the bottom of each interface!

**Review by foolip — APPROVED** [review]

**Pull request merged**
