### PR TITLE
Update Opera versions for DataTransferItem API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects the real values for Opera and Opera Android for the `DataTransferItem` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v4.0.0).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/DataTransferItem

_Check out the [collector's guide on how to review this PR](https://github.com/foolip/mdn-bcd-collector#reviewing-bcd-changes)._

### CODE REVIEW

**Comment by foolip** [comment]
Is this based on testing the real Opera 12 on Android?

**Comment by queengooborg** [comment]
I don't have older browser testing for Android-based browsers set up just yet, so instead, this is based upon testing in the latest Opera Android and then mirroring from Opera Desktop.  I do plan on running tests for every Android browser version in the future!

**Comment by foolip** [comment]
Can you make sure that the PRs say when the data is based on mirroring vs. testing? When it's based on testing I wouldn't doubt it at all, but if mirroring one has to think about assumptions. Here, I think there's a chance that `DataTransferItem` wasn't supported on Opera mobile, because it's part of a drag-and-drop API that I suspect doesn't work on mobile at all.

**Comment by queengooborg** [comment]
I'll replace Opera Android's data with a range then!

**Review by foolip — APPROVED** [review]

**Pull request merged**
