### PR TITLE
Add ConstrainULong/ULongRange; deprecate signed

### PR DESCRIPTION
**Pull request by sideshowbarker**
https://github.com/w3c/mediacapture-main/commit/7f2c65d replaced the `MediaStreamTrack`-related dictionaries `ConstrainLong` and `LongRange` (signed) with `ConstrainULong` and `ULongRange` (unsigned) equivalents.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Looking good to me!  May I ask where you sourced the data for the new API files?  (Manual testing is a perfectly fine answer, I just want to confirm!)

**Comment by sideshowbarker** [comment]
>  May I ask where you sourced the data for the new API files?

I looked at the IDL definitions in the source code. Or at least I thought I did. But it turns out that I was looking at the wrong place. I looked here:

* https://dxr.mozilla.org/mozilla-central/source/testing/web-platform/tests/interfaces/mediacapture-streams.idl
* https://github.com/chromium/chromium/blob/master/third_party/blink/web_tests/external/wpt/interfaces/mediacapture-streams.idl

…but looking back now, I realized those are not the actual IDL definitions that those engines use, but are instead just the definitions from web-platform-tests.

The IDL definitions that the engines actually use is here:

* https://dxr.mozilla.org/mozilla-central/source/dom/webidl/MediaStreamTrack.webidl
* https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/modules/mediastream/media_track_constraint_set.idl
* https://github.com/WebKit/webkit/blob/master/Source/WebCore/Modules/mediastream/MediaTrackConstraints.idl

…which indicate that none of those engines have yet  updated their IDL definitions
to use `ConstrainULong` and `ULongRange`.

So, I’ve pushed another commit that sets `"version_added": false for them all.

>  (Manual testing is a perfectly fine answer, I just want to confirm!)

Thanks for asking for confirmation — it prompted me to go back and doublecheck.

**Comment by vinyldarkscratch** [comment]
Thanks for double-checking and revising your PR!  I'll check it out sometime tomorrow during my flight to Berlin (heading to All Hands 2020).  :wink:

**Comment by sideshowbarker** [comment]
@vinyldarkscratch friendly reminder on this one — I think it’s waiting on you but if not and there’s something more I need to do here, please lemme know

**Comment by vinyldarkscratch** [comment]
Ah sorry, I did totally forget (things have been pretty chaotic for me lately, haha) -- I'd say this is looking good to me!  Can we also set Edge to `false`?

**Comment by sideshowbarker** [comment]
> Can we also set Edge to `false`?

Yup — done

> Ah sorry, I did totally forget (things have been pretty chaotic for me lately, haha)

No worries — I hope the chaos has subsided for you a bit :) But if not, please consider all my other open PRs extremely low-priority :) They’re blocking anything

**Pull request merged**
