### PR TITLE
[Chrome] Bug 1041095: Track `[attr=val s]` implementation

### PR DESCRIPTION
**Pull request by ExE-Boss**
**Chromium** has&nbsp;[bug&nbsp;1041095](https://bugs.chromium.org/p/chromium/issues/detail?id=1041095)&nbsp;open to&nbsp;implement&nbsp;this.

---

review?(@jpmedley)

### CODE REVIEW

**Comment by jpmedley** [comment]
This looks accurate to me. 

This is an example of why I'm never crazy about adding bug links to BCD. This does bug currently doesn't have an owner and I can't tell you when it will get one. To people outside of Chromium development, listing this bug may be taken as a level of prioritization that may not match reality.

**Comment by ddbeck** [comment]
> This is an example of why I'm never crazy about adding bug links to BCD. This does bug currently doesn't have an owner and I can't tell you when it will get one. To people outside of Chromium development, listing this bug may be taken as a level of prioritization that may not match reality.

@jpmedley I'm not certain that that issue links _say_ anything in particular. Across all of BCD, there are bug links that point to issues ranging from implented-and-shipped to wontfix and most points between. Though I suppose we could open an issue to actually find out what BCD consumers think a bug link means. But is there a better place than a Chromium issue for a web developer to find out the status of a feature like this?

**Comment by jpmedley** [comment]
If it's prioritized, it will be on Chrome Status.

**Comment by ddbeck** [comment]
I've approved this and I'm about to merge it. I think the question of whether we ought to have some qualifying criteria for bug links is beyond the narrow focus of this PR, and I think it makes sense to break that out into its own discussion.

@jpmedley like my idea on https://github.com/mdn/browser-compat-data/pull/5504#issuecomment-576947311, I think it'd be great to see an issue or PR with proposed guidelines for links to Chrome issue tracking. I was previously under the impression that Chrome Status has caveats (I think you've mentioned in the past that it's not authoritative for release data). Knowing more about what you think ought to get a link (or not), in depth, would be really helpful.

**Pull request merged**
