### PR TITLE
Chrome/Webview Android 109 support FileSystemHandle API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects version values for Chrome Android for the `FileSystemHandle` API. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.7.1).

_Check out the [collector's guide on how to review this PR](https://github.com/openwebdocs/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/FileSystemHandle

### CODE REVIEW

**Review by Elchi3 — DISMISSED** [review]
https://issues.chromium.org/issues/40101963 is still open so I'm not sure about this one.

**Comment by Elchi3** [comment]
err didn't mean to improve

**Comment by Elchi3** [comment]
@RupertBenWiser can you help us? Is the FileSystemHandle API supported in Android WebView or not?

**Comment by Elchi3** [comment]
Maybe this is 109 for Chrome Android and Android WebView given https://chromestatus.com/feature/5079634203377664?

**Comment by caugner** [comment]
> can you help us?

@Elchi3 Should we re-ping, or what do we usually do?

**Comment by queengooborg** [comment]
I feel that the inquiry has already been answered from our own research (the ChromeStatus page), so we can probably just review it right away?

**Comment by caugner** [comment]
> I feel that the inquiry has already been answered from our own research (the ChromeStatus page), so we can probably just review it right away?

> Maybe this is 109 for Chrome Android and Android WebView given https://chromestatus.com/feature/5079634203377664?

@queengooborg Based on this, the proposed changes are not right though, because `mirror` would set 86, not 109. Or am I misunderstanding the research?

**Review by caugner — CHANGES_REQUESTED** [review]
(Repost as review)

> I feel that the inquiry has already been answered from our own research (the ChromeStatus page), so we can probably just review it right away?

> Maybe this is 109 for Chrome Android and Android WebView given https://chromestatus.com/feature/5079634203377664?

@queengooborg Based on this, the proposed changes are not right though, because `mirror` would set 86, not 109. Or am I misunderstanding the research?

**Review by caugner — APPROVED** [review]

**Pull request merged**
