### PR TITLE
Compat data for multi-keyword syntax in CSS overflow

### PR DESCRIPTION
**Pull request by Loirooriol**
Firefox 61 accepts two keywords in `overflow`:

https://bugzilla.mozilla.org/show_bug.cgi?id=1453148
https://groups.google.com/forum/#!topic/mozilla.dev.platform/4vy-a5_a35o
https://github.com/mdn/data/commit/5f28d73672718f555e2cfd76d06ec29c904cc828

### CODE REVIEW

**Comment by csnardi** [comment]
Could you update this for Chrome as well, showing support in Chrome 68? (https://www.chromestatus.com/feature/5090725653905408)

**Comment by csnardi** [comment]
Yep, sorry for not mentioning that, it'll be Opera 55 per that link and then `webview_android` will be the same as the Chrome version (68).

**Comment by Loirooriol** [comment]
Oh, thanks, I didn't realize chromestatus says the versions.

**Comment by csnardi** [comment]
Yep, might sometimes be hit or miss, since it only autofills from Chrome desktop version to Opera desktop and Chrome Android to Opera Android, so the absence of some values might not indicate that the feature isn't supported on e.g. Android/WebView. But generally a helpful resource. :)

**Pull request merged**
