### PR TITLE
WebGPU is enabled in Safari 18.2 beta

### PR DESCRIPTION
**Pull request by Elchi3**
Fixes https://github.com/mdn/browser-compat-data/issues/25042

I already observed GPU interfaces enabled by default in earlier Safari 18.2 beta versions, see https://github.com/mdn/browser-compat-data/pull/24939, and I'm still seeing it enabled in the lastest version 18.2 (20620.1.15.1).

Still not seeing it mentioned in release notes, though: https://developer.apple.com/documentation/safari-release-notes/safari-18_2-release-notes. cc @jdatapple and @jensimmons 

This PR updates what the collector can automatically test. I know @chrisdavidmills has been adding quite a few GPU sub features which will need to be tested and updated separately for Safari.

### CODE REVIEW

**Review by caugner — APPROVED** [review]
LGTM.

**Comment by jensimmons** [comment]
Web GPU was intentionally not listed in the Safari 18.2 beta release notes. I wish you had waited to hear from us before merging.

**Comment by caugner** [comment]
@jensimmons Thank you for clarifying, and I apologize for the misunderstanding. @Elchi3 cc'd you on [the Safari 18.2 beta PR](https://github.com/mdn/browser-compat-data/pull/24939) on November 4th, so I assumed that any concerns would have been flagged before I merged it on November 15th. I now realize I should have waited for explicit confirmation. Apologies again for the oversight.

To address the situation, I have a few questions:

1. Would you prefer that we revert these changes, or should we wait to see if they are backed out of Safari 18.2? (The next BCD release (v5.6.18) is scheduled for publication in the next 24 hours.)
2. Is there a way for us to disable or exclude early-exposure features like this during collector runs? Alternatively, could we identify such features by specific terminology in WebKit commit messages (e.g., language indicating they are not ready for public use)?
3. Would it be helpful if you flagged potential concerns on PRs with a 👀 reaction (indicating "looking into it") when commenting isn't possible? This would help us know when to hold off on merging.

Let me know how you'd like to proceed, and thank you for your guidance.

**Comment by jensimmons** [comment]
I believe if you rerun the tests on the latest Safari 18.2 beta (v3 came out Nov 11) you will see the Web GPU is not enabled.

**Comment by jensimmons** [comment]
Thank you!! As for your question about future process... well, sometimes humans are just necessary. I don't have a suggestion how to systematize situations like this one. It's understandable that you assumed the "missing release note" was a mistake, since sometimes that is what's happening. I'm glad you reached out to Jon & I. Hopefully we will see the ping and respond more quickly next time — which is what happened here: https://github.com/Fyrd/caniuse/pull/7206

**Pull request merged**
