### PR TITLE
Removes duplicate link prefetch entry

### PR DESCRIPTION
**Pull request by tunetheweb**
#### Summary

The `prefetch` attribute was in the `html`->`elements`->`link` BCD data twice:
1) As a direct `prefetch` attribute. As far as I know this was never supported and I think it was a typo.
2) As a `rel=prefetch` attribute. This is the correct one.

This is confusing as gives incorrect - and conflicting - support information on the [`<link>` MDN page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) and in [caniuse](https://caniuse.com/?search=prefetch).

As part of this PR, I also moved the "Secure context required" setting to a note -  it was also incorrect (it only said Chrome needed it, when Firefox needs it too), and added Safari support behind a flag.

#### Test results and supporting details

https://wpt.fyi/results/preload/prefetch-types.https.html?label=experimental&label=master&aligned

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Thanks for fixing this!
We usually use a sub feature entry for "secure context" (especially in APIs) but maybe it is better as a note here deep in the HTML link element tree.
Probably all sub features here would benefit from a description like `rel=prefetch`, `rel=preconnect`, `rel=icon`, etc. Happy to review a follow-up PR for that.

**Comment by tunetheweb** [comment]
> We usually use a sub feature entry for "secure context" (especially in APIs) but maybe it is better as a note here deep in the HTML link element tree.

I'm not sure this is a sub feature though. It's more a restriction of the feature (you can use `rel=prefetch` but only over HTTPS). It's not like you can use `rel=prefetch` **and** also on some browsers use this extra feature of that.

> Probably all sub features here would benefit from a description like `rel=prefetch`, `rel=preconnect`, `rel=icon`, etc. Happy to review a follow-up PR for that.

I think only `rel=prefetch` has this HTTPS restriction. Possibly `rel=prerender` too, but since that's deprecated and only supported in Chromium (which is looking to replace it), I'm less worried about that one.

Or did you mean some other sub features?

**Comment by Elchi3** [comment]
> I'm not sure this is a sub feature though. It's more a restriction of the feature (you can use `rel=prefetch` but only over HTTPS). It's not like you can use `rel=prefetch` **and** also on some browsers use this extra feature of that.

Yes, good point!

> I think only `rel=prefetch` has this HTTPS restriction. Possibly `rel=prerender` too, but since that's deprecated and only supported in Chromium (which is looking to replace it), I'm less worried about that one.
> 
> Or did you mean some other sub features?

Sorry, I was talking about adding a "description" property to the feature. It currently doesn't have that so the MDN table renders "rel.prefetch". If you would add `"description: "<code>rel=prefetch</code>" to the BCD entry,` the MDN table would render it better. And I think the same would be nice for the others.

**Comment by tunetheweb** [comment]
Ah gotcha. Raised: https://github.com/mdn/browser-compat-data/pull/20673

**Pull request merged**
