### PR TITLE
Add compat data for Supported Media Formats

### PR DESCRIPTION
**Pull request by maboa**
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

Note - I purposely did not represent the last row: "any other format".

### CODE REVIEW

**Comment by Elchi3** [comment]
We have not yet decided on a structure or on where to install "media formats" or "file type support" in the browser-compat-data tree. See also https://discourse.mozilla.org/t/add-image-format-support-information-to-this-page/28832

Marking as not ready for now.

**Comment by Elchi3** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1506824

@wbamberg In Portland we briefly talked about this. I think you had a good idea about this. Was it to have a formats/ folder?

**Comment by wbamberg** [comment]
>  I think you had a good idea about their organization. Was it to have a formats/ folder?

I think so although I'm no longer sure whose idea it was. From an end-user perspective it seems like it would be useful for, say, the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video to embed 2 compat tables:

* the existing one for the element itself, and its attributes, and so on
* another one for the video formats supported

These 2 concepts seem to be orthogonal, so trying to represent them in a single table would get messy.

And then we thought that the information of on video formats supported (or audio or image formats too of course) might be useful in other pages too.

So having a "formats" folder seems like a good idea to me. My only concern is: I wonder how often this kind of thing might come up in different applications and whether that might affect the way we wanted to model it.

The only other possible example I know of is in the Web Crypto docs, where different browsers might have different levels of support for different algorithms, and that might cut across multiple actual methods of the API.

For example Edge doesn't support `AES-CTR`, and that affects compat for `encrypt`, `decrypt`, `wrapKey`, `unwrapKey` and so on. So you could imagine a standalone `crypto-algorithms` object describing compat for different algorithms, then `encrypt` could include 2 compat tables, one for the `encrypt` method and one for the algorithms.

I **don't** think this is worth doing for Web Crypto actually, since that's a very specialised application compared with video formats. But it's an example of other places where this could crop up. But I think it would be OK to have "formats" for now and reconsider if further examples make that seem like a weird choice :).

**Comment by a2sheppy** [comment]
There are a few things we have to consider when providing compatibility information for media:

## Containers (File types)
* What types are supported by each browser (MPEG, MP4, AVI, MOV, etc)?
* For each type, need to specify its full name and optional short name (MPEG 4 vs MP4) mimetype(s), extension(s), supported codecs (according to the spec; what each browser actually allows is another issue covered later), spec URL, container features (VBR, VFR, captions, metadata, streaming, etc) and potentially any notes about the file type
* Also for each type, whether it's patent encumbered and potentially who owns it

## Codecs (Content formats)
* For each type of media (audio or video), list of the known codecs and data about them, including: codec full name and optional short name (MPEG 1 Layer III vs MP3), spec URL, notes, codec features (VBR, VFR, captions, streaming, etc) per the codec specs (what browsers really support covered separately)
* Whether the codec is patent encumbered and if so who owns it
* For each browser, which codecs does it permit in which container types? Which of the codec features does it support and perhaps optional notes about the support level
* Notes about the codec overall

A setup structured roughly like that makes it possible to look at the container list, see that a browser supports a given container, and from there also get a list of the codecs permitted by that browser in that container. Then we can look up the information about those codecs in the codec database, pulling out the browser-specific details so we can build a table that lists the video codecs down one axis, the video container types across the other, and in each table cell whether or not a given browser supports that pair of codec and container and any added info of note about that pairing.

But we have the flexibility to do a lot of different things, like offer a tool to let people isolate all the combinations available to them that can be used on a given selection of browsers.

**Comment by a2sheppy** [comment]
I've started a [thread on Discourse](https://discourse.mozilla.org/t/deciding-on-how-to-track-media-format-information/35531) to discuss this issue in a broader setting than this. I have a need to get this resolved sooner rather than later.

**Comment by Elchi3** [comment]
The discussion and https://github.com/mdn/browser-compat-data/pull/3446 supersedes this PR. Closing here.

**Pull request closed without merging**
