### PR TITLE
Demix GeometryUtils to Document/Element/Text.getBoxQuads

### PR DESCRIPTION
**Pull request by foolip**
Nothing of GeometryUtils has shipped in any browser yet. Preserve just
the minimum of what already had flag data, which is getBoxQuads.

CSSPseudoElement includes GeometryUtils in the spec, but not in Gecko
source, so it is omitted.

### CODE REVIEW

**Comment by foolip** [comment]
@vinyldarkscratch FYI

**Comment by vinyldarkscratch** [comment]
Thanks @foolip!  Based upon the [spec](https://drafts.csswg.org/cssom-view/#the-geometryutils-interface), it looks like `GeometryUtils` is also included on `CSSPseudoElement`?

**Comment by foolip** [comment]
> Thanks @foolip! Based upon the [spec](https://drafts.csswg.org/cssom-view/#the-geometryutils-interface), it looks like `GeometryUtils` is also included on `CSSPseudoElement`?

Yes, but to quote myself:

> CSSPseudoElement includes GeometryUtils in the spec, but not in Gecko source, so it is omitted.

The entry would have only false values.

**Comment by vinyldarkscratch** [comment]
Ah, apologies, didn't read that part until just now -- looks good to me!

**Review by vinyldarkscratch — APPROVED** [review]

**Comment by foolip** [comment]
MDN cleanup in https://github.com/mdn/content/pull/5579.

**Pull request merged**
