### PR TITLE
Populate tags from web-features

### PR DESCRIPTION
**Pull request by foolip**
This was created using the script in https://github.com/web-platform-dx/web-features/pull/473
and running the lint:fix script to fix JSON ordering.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
LGTM (nor merging to give more people the time to review this, as this is fairly new)

**Review by ddbeck — APPROVED** [review]
I [diffed](https://gist.github.com/ddbeck/07e1c4812bb04cce47753c1a6acfe13c) feature lists from web-features's YAML and BCD's `npm run traverse` for a handful of features here. I'm satisfied that the features tagged here are correct and complete.

@foolip I'd be happy to see this merged here immediately and the feature lists removed from web-features tomorrow.

**Review by caugner — CHANGES_REQUESTED** [review]
Do we have a good reason to introduce/use a universal `tags` key (just like we used to have in content) rather than a specific `web_features` key?

**Comment by ddbeck** [comment]
@caugner to your question, I'd strongly encourage you (and Vinyl) to take a look at the discussion on https://github.com/mdn/browser-compat-data/pull/21081. These aren't "just like" what used to be in content (in particular, we have a controlled vocabulary). But to summarize, there are three big reasons this is generalized as tags rather than a narrower web-features mechanism:

- @Elchi3 initially suggested additional, non-web-features groups or annotations (e.g., a `constructors` group, to find all the constructors across all APIs).
- web-features' groups semantics are partly unfinished, particularly when it comes to feature relationships and renaming. Changes in web-features should not, ipso facto, require changes to BCD's schema. Namespaces preserves just enough flexibility.
- It _is_ a tagging authorship model (whether it's called something else or not). Unlike web-features' top-down grouping, grouping in BCD is bottom-up. A rose by any other name…

(All that said, I cannot for the life of me find the change requested.)

**Pull request merged**
