### PR TITLE
inputmode is supported on Firefox 79 for Android

### PR DESCRIPTION
**Pull request by makotokato**
Shipped by https://bugzilla.mozilla.org/show_bug.cgi?id=1631681.

Also, `inputmode` preference should be same version of Firefox Desktop.

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by ddbeck** [comment]
Thanks for this PR!

> Also, `inputmode` preference should be same version of Firefox Desktop.

Do you want to include this change in this PR, @makotokato? I'd welcome that addition, or a follow-up. If you don't want to do it at all, we could open an issue to track that suggestion separately.

**Comment by foolip** [comment]
I think only remaining question here is missing flag data. Since we're definitely missing flag data all over the place, that seems quite OK to me. It will become consistent in 2 years when the existing flag data can be removed :)

**Comment by makotokato** [comment]
> Do you want to include this change in this PR, @makotokato? I'd welcome that addition, or a follow-up. If you don't want to do it at all, we could open an issue to track that suggestion separately.

Hmm, OK, this PR is Firefox Android 79 only. So I will update this PR.

Also, I will file another PR that is https://github.com/mdn/browser-compat-data/pull/6468 is incorrect.

**Review by ddbeck — APPROVED** [review]
Thank you, @makotokato! 

Also, I wasn't entirely clear on what the situation was for Firefox on the desktop, so I opened #6921 to track that independently.

**Pull request merged**
