### PR TITLE
Add missing __compat+mdn_url to top-level extension namespaces

### PR DESCRIPTION
**Pull request by Rob--W**
#### Summary

Add `__compat and missing `mdn_url` to every extension API namespace that lacks such an entry at the API namespace level. Also fixed up some individual entries.

To populate the `__compat` objects, I copied and pasted an existing entry from another API entry within the file (ideally the oldest supported entry where possible), then modified the support state. I used my knowledge of Chrome and Firefox extension API support to resolve non-trivial cases. E.g. `search.search` and `search.query` have different support ranges in Firefox and Chrome, but the namespace they belong to (search) is set to the earliest version that supports either method.

The contextualIdentities entry has a note on Android compat, for consistency with the other entries as added in #22337, generated by https://github.com/mdn/browser-compat-data/pull/22337#issuecomment-1971066556

### CODE REVIEW

**Comment by Rob--W** [comment]
CI is failing because the contextualIdentities entry depends on the fixup from #22337. I'll rebase this PR when the other gets merged.

And after adding `__compat`, suddenly the style linter complains about the ordering of some keys. I'll fix that before merging, perhaps by running `npm run fix`

**Comment by Rob--W** [comment]
Another note: after adding the top-level compat info, the linter complained about incorrect entries in between. E.g. Safari liststs devtools API methods but missed entries at the individual subnamespaces. I fixed these too.

In tabs.json, executeScript was flagged as supported in 43. I bumped it to 45 for consistency with the others. I think that the support status is based on when the schema landed, which is in 45: https://hg.mozilla.org/mozilla-central/rev/7b0f6544f9b6b18c87e0bcacc215726a5804f2f2
In reality, large chunks of the tabs API already landed before in 42: https://hg.mozilla.org/mozilla-central/rev/0364858aed56#l5.3

**Review by rebloor — APPROVED** [review]
@Rob--W I've done a spot check for URLs and version information, everything looks OK, let me know if I should be doing comprehensive check.

**Review by abirhasan132 — COMMENTED** [review]
66100af9bb891df5f5cc4e12b6c66f77184e1cc1

**Pull request merged**
