### PR TITLE
Remove MediaStreamTrackProcessor API from BCD

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the irrelevant `MediaStreamTrackProcessor` API as per the corresponding [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features). The lack of current support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v7.1.2), even if the current BCD suggests support.

### CODE REVIEW

**Comment by queengooborg** [comment]
I see what the problem is.  In the spec, `MediaStreamTrackProcessor` is only supposed to be exposed on dedicated workers (see https://w3c.github.io/mediacapture-transform/#track-processor-interface), but Chrome exposes it on (and only on) the Window instead.  So, while this PR is incorrect, I think we should mark the feature as `partial_implementation` with a note describing the off-spec behavior.  WDYT?

**Comment by Elchi3** [comment]
cc'ing @foolip here for thoughts. Does this have the wrong exposure? Mark it partial then?

**Comment by foolip** [comment]
I came across this case recently too when reviewing another PR.

Note that the spec has this note:

> There is WG consensus that the interface should be exposed on DedicatedWorker. There is no WG consensus on whether or not the interface should not be exposed on Window.

In other words, the people in the WG had a disagreement and couldn't come to an agreement.

I think partial implementation with note is appropriate here.

**Comment by queengooborg** [comment]
Closing in favor of #19324.

**Pull request closed without merging**
