### PR TITLE
Add Chromium versions for ContentIndex APIs

### PR DESCRIPTION
**Pull request by queengooborg**
This PR adds real values for Chromium (Chrome, Opera, Samsung Internet, WebView Android) for the `index` member of the `ServiceWorkerRegistration` API, as well as the `oncontentdelete` member of the `ServiceWorkerGlobalScope` API, based upon commit history and date.

Commit: https://storage.googleapis.com/chromium-find-releases-static/30b.html#30b5b32bf56c328e6655f3ab56fe9199d754d62b

### CODE REVIEW

**Review by lucalves — APPROVED** [review]

**Comment by foolip** [comment]
https://chromium.googlesource.com/chromium/src/+/30b5b32bf56c328e6655f3ab56fe9199d754d62b isn't the commit that introduced this, that's importing tests only.

**Comment by foolip** [comment]
@queengooborg can you test this with https://mdn-bcd-collector.appspot.com/tests/api/ServiceWorkerRegistration/index instead?

**Comment by foolip** [comment]
https://storage.googleapis.com/chromium-find-releases-static/a5d.html#a5da464cae9a28fc87666e515a53091deb54b926 suggests Chrome 84 is correct. @queengooborg can you update all of the APIs shipped together there? That's anything with `RuntimeEnabled=ContentIndex` in the IDL files at the time, which is `ContentIndex`, `ContentIndexEvent`, this `index` property, and also a `oncontentdelete` property.

Some of the data already looks correct, but not all of it.

**Comment by queengooborg** [comment]
Data updated!

**Review by foolip — APPROVED** [review]

**Pull request merged**
