### PR TITLE
Fix Chrome wasm streaming compilation and instantiation results

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://v8project.blogspot.ru/2018/02/v8-release-65.html

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Maybe it's better to add something like this
```json
        [
                {
                  "version_added": "65"
                },
                {
                  "version_added": "61",
                  "version_removed": "64",
                  "notes": "While this API is available, the initial implementation didn’t actually use streaming compilation."
                }
        ]      
```
?

**Comment by Elchi3** [comment]
Sorry for the slow response! The way you've described this currently in the PR looks good to me. 
cc'ing @jpmedley for confirming the Chrome info.

**Comment by jpmedley** [comment]
I've confirmed that 61 did not have it. I'm still trying to confirm 65.

**Comment by chicoxyzzy** [comment]
From v8 blog post I mentioned in first message:

> This API has been available since V8 v6.1 and Chrome 61, although the initial implementation didn’t actually use streaming compilation. However, with V8 v6.5 and Chrome 65 we take advantage of this API and compile WebAssembly modules already while we are still downloading the module bytes. As soon as we download all bytes of a single function, we pass the function to a background thread to compile it.

**Comment by jpmedley** [comment]
Yeah, I actually went to the engineers who built it because I never assume it was written well or correctly. What's going on here is frankly confusing or potentially confusing. 

This was implemented in 61. What happened in 65 was just an optimization. We optimize things all the time and don't reflect it in compatibility data. I would just say, `"version_added": "61"` and leave the rest of it out.

**Comment by Elchi3** [comment]
> This was implemented in 61. What happened in 65 was just an optimization. We optimize things all the time and don't reflect it in compatibility data. I would just say, "version_added": "61" and leave the rest of it out.

If this is the case, this PR isn't going to get merged. Closing.

**Pull request closed without merging**
