### PR TITLE
docs: `notes` to `impl_url` property migration leftovers

### PR DESCRIPTION
**Pull request by mfranzke**
#### Summary

Resolves https://github.com/mdn/browser-compat-data/issues/20795

Some but not all `notes` entries mention bug tickets that especially resolve a missing functionality for feature completeness against the standard, that for I've included this one within the new `impl_url` entry, but not the previous, "original" bug ticket (with which the ticket has been partially implemented) for two reasons:
- easier implementation: I would have needed to research the original ticket with the partial implementation
- relevance: From my understanding the `impl_url` entries relevance is mainly about "feature completeness", so it would be more relevant to have an insight into the remaining work, than an already resolved ticket.

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey @mfranzke, thanks for your work on this, however this adds `impl_url` in too many places.  It seems there's some confusion on what `impl_url` is used for, and I feel that's my fault for not explaining it properly, I apologize.

We use `impl_url` to track the bug/commit for tracking when the entire feature was implemented (see the [schema docs](https://github.com/mdn/browser-compat-data/blob/main/schemas/compat-data-schema.md#impl_url)).  It is meant to be used in cases where a feature is not yet supported, but there is a tracking bug indicating an intent to implement/ship the feature.  Notes such as "Not implemented yet, see [this bug]." are a perfect example of where `impl_url` should be used instead.

`impl_url` shouldn't be used to track caveats or issues in features that are already implemented, however, and the bug URL should only remain in the notes.  For example, if a note says "Only [some interface] is supported as an argument, see [this bug].", we should not take the bug link and apply it to `impl_url`.

**Comment by mfranzke** [comment]
@queengooborg, my bad, I could have looked those up previously. Thanks for your explanation.

**Comment by Elchi3** [comment]
@mfranzke Are you planning to come back to this PR? Did you see https://github.com/mdn/browser-compat-data/pull/20962#issuecomment-1771031119?

**Comment by Elchi3** [comment]
Closing this due to inactivity. @mfranzke feel free to come back to this or open a new PR. Thanks!

**Pull request closed without merging**
