### PR TITLE
Update chrome and chrome_android entries in RemotePlayback.json

### PR DESCRIPTION
**Pull request by muyao-xu**
Chrome is shipping Remote Playback API on desktop: https://chromestatus.com/feature/5778318691401728

### CODE REVIEW

**Comment by queengooborg** [comment]
Hi @muyao-xu, thank you for your PR and welcome to BCD!

Because the interface is defined, the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com/tests/api/RemotePlayback) states this interface as supported on desktop.  Do you know if there is a good way to programmatically and automatically test for support (i.e., without calling `.prompt()` or otherwise displaying prompts that require user action)?

**Comment by muyao-xu** [comment]
Hi @queengooborg ,

Sorry for the late reply.
The [Remote Playback API](https://w3c.github.io/remote-playback/#prompt-user-for-changing-remote-playback-state) defines that the browser rejects the watchAvailability() or prompt() calls with a [NotSupportedError](https://webidl.spec.whatwg.org/#notsupportederror) when the API is not supported. I don't think it's possible to bypass this step but this process should be able to complete without user actions.

**Comment by muyao-xu** [comment]
Hi @queengooborg :)

Is there anything else I need to do to get this PR merged?

**Review by Elchi3 — COMMENTED** [review]
Sorry for being slow, @muyao-xu!

Would you mind also updating:
- `remote` and `disableRemotePlayback` in https://github.com/mdn/browser-compat-data/blob/main/api/HTMLMediaElement.json
- `disableremoteplayback` in https://github.com/mdn/browser-compat-data/blob/main/html/elements/audio.json
- `disableremoteplayback` in https://github.com/mdn/browser-compat-data/blob/main/html/elements/video.json

That would be very much appreciated!

**Comment by muyao-xu** [comment]
Done!

**Pull request merged**
