### PR TITLE
Added Chrome version for prefer_related_applications

### PR DESCRIPTION
**Pull request by Yash-Singh1**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

# Summary

Added Chrome version for `prefer_related_applications`

# Data

Commits in the chromium repository show `prefer_related_applications` being used as early as Chrome 44:
https://github.com/chromium/chromium/commit/51f7dbdc3d92a014d96f13c3193fed86cd063463

I searched through: https://github.com/chromium/chromium/search?o=asc&q=prefer_related_applications&s=indexed

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
I think this should be labeled `data:api`

**Comment by ddbeck** [comment]
Sorry for the long wait on reviewing this, @Yash-Singh1. I have a question about this change, however. Looking through some of the related bugs (this [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/OcJ0b7JPZ5M) provided a bunch of context), I'm not sure whether Chrome actually does anything with `prefer_related_applications`. Have you tried this out in a browser? Can you demonstrate what happens when a web developer uses this?

**Comment by Yash-Singh1** [comment]
@ddbeck I think the information that I added in is incorrect. In reality, Chrome for Android supported `related_applications` and `prefers_related_applications` on version 44+. There was an article about this: https://pracucci.com/chrome-related-applications.html. I will create a commit for this.

**Review by ddbeck — APPROVED** [review]
Thanks for the update, @Yash-Singh1! That link was really helpful—there's a lot to corroborate this on Android.

**Pull request merged**
