### PR TITLE
Fixed to webRequestFilterResponse.serviceWorkerScript

### PR DESCRIPTION
**Pull request by rebloor**
#### Summary

Fixes incorrect presentation of webRequestFilterResponse.serviceWorkerScript made in #18665

### CODE REVIEW

**Comment by queengooborg** [comment]
Rather than prefixing the name of the feature, it should actually be indented one level and made as a sub feature, since we already represent `webRequestFilterResponse`.

**Comment by queengooborg** [comment]
Actually, I see that's how it already is now, so the feature is already good and its placement does not need to be changed.

**Comment by rebloor** [comment]
@queengooborg however, this is not the way we present information about dot permissions. For example, see https://github.com/mdn/browser-compat-data/blob/11c77b5ccffa8519513d45110c5a24f180326f7a/webextensions/manifest/permissions.json#L397

**Comment by queengooborg** [comment]
Ah, I see what's going on.  These aren't properties, but string values that can be used.  We definitely should update the format to better represent this.

**Review by queengooborg — APPROVED** [review]

**Pull request merged**
