### PR TITLE
Update formatting globs

### PR DESCRIPTION
**Pull request by nschonni**
#### Summary

The `npx` calls aren't needed inside NPM scripts, and expanding the globs will allow prettier to pick up addition files like the YML ones as the `.prettierignore` has been updated

### CODE REVIEW

**Comment by nschonni** [comment]
I'd like to follow on with a PR to get the YML formatted, as I noticed when looking at https://github.com/mdn/browser-compat-data/pull/17594 that the actions are currently ignored in the `.prettierignore`

**Comment by queengooborg** [comment]
Hey @nschonni -- could we just stick with the glob changes?  It's hard to review changes to `package-lock` so we typically reserve such changes for owners to perform!

**Comment by nschonni** [comment]
I rebased off the package-lock change, but if you want to redo it yourself, it was just `rm -rf node_modules package-lock.json` then `npm i`

**Review by queengooborg — APPROVED** [review]
I'm not seeing any issues with switching the globs or removing `npx` calls, so this is LGTM!

**Pull request merged**
