### PR TITLE
ie version 10 added for History.state

### PR DESCRIPTION
**Pull request by tprdeepaklal**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Thanks for your PR, and welcome to BCD!  To help with the review process, would you be willing to link any sources that you have used to find this information?  (You can also say "manual testing"!)

**Comment by tprdeepaklal** [comment]
@vinyldarkscratch yes, I have tested manually in IE 10

**Comment by vinyldarkscratch** [comment]
What about older versions like IE 9?  Have you given them a try as well?

**Comment by tprdeepaklal** [comment]
@vinyldarkscratch when will this get reflected in this web page "https://developer.mozilla.org/en-US/docs/Web/API/History" ??

**Comment by vinyldarkscratch** [comment]
Looks like this PR made it into the v0.0.85 release.  You can force a refresh to regenerate the compat table via the following instructions: https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Bypassing_cache

**Pull request merged**
