### PR TITLE
Change backslash-escaped asterisk into a footnote in testing.md

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR turns the backslash-escaped asterisk note into a note surrounded by brackets.

### CODE REVIEW

**Comment by Elchi3** [comment]
Maybe it is just me, but I had search for what the asterisk is referring to. Should we maybe move this explanation into brackets so that it isn't all the way down in the doc?

**Comment by vinyldarkscratch** [comment]
That's a possibility, yeah!  We could also make it more like a proper footnote with a link?

**Comment by Elchi3** [comment]
That would work, too, I guess.

**Comment by vinyldarkscratch** [comment]
Changes applied!  How does it look?

**Comment by Elchi3** [comment]
Hm, it looks like footnotes aren't part of github flavoured markdown / commonmark.

**Comment by vinyldarkscratch** [comment]
Awww, boo...  Alright, I guess brackets it is!

**Pull request merged**
