### PR TITLE
34698 ship starting style

### PR DESCRIPTION
**Pull request by dletorey**
#### Summary

Updated BCD for `@starting-style`

#### Test results and supporting details

Tested in FF129.01a

#### Related issues

- [Firefox Release note PR](https://github.com/mdn/content/pull/34838)

### CODE REVIEW

**Comment by Elchi3** [comment]
Please see https://github.com/mdn/browser-compat-data/pull/23730

**Comment by dletorey** [comment]
> Please see #23730

@Elchi3 this does not include the `partial_imp` and note

```json
            "firefox": {
              "version_added": "129",
              "impl_url": "https://bugzil.la/1834877",
              "partial_implementation": true,
              "notes": "Does not yet support animating from <code>display: none</code>"
            },
```

**Comment by Elchi3** [comment]
Ah, sorry, well, sad it is not fixed upon shipping it. Reopening

**Review by Elchi3 — APPROVED** [review]

**Comment by Elchi3** [comment]
Can't merge because of the merge-conflict. Can you resolve that?

**Review by Elchi3 — APPROVED** [review]
Thanks and sorry again for overlooking the partial implementation!

**Pull request merged**
