### PR TITLE
Add data for MathML global attributes

### PR DESCRIPTION
**Pull request by fred-wang**
#### Summary

This is adding data for MDN articles describing MathML global attributes.

#### Test results and supporting details

This was done by checking the source code of browsers, bug entries as well as the commits.

Note: `npm test` fails with "version_added: 'true' is NOT a valid version number" but that seems to be what other files do to.

#### Related issues

https://github.com/mdn/content/pull/17812

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey @fred-wang, thank you for your PR, and welcome to BCD!

To answer your comment about `true` being disallowed as a `version_added`, it is because a [long-term goal for BCD](https://github.com/mdn/browser-compat-data/issues/3555) is to remove all "non-real values" (that is, data without a specific version number), and `mathml` is one of the categories where this is enforced.

I'd be more than happy to help research version numbers for Firefox and Safari for you, if you'd like!

**Comment by fred-wang** [comment]
Thanks for the information @queengooborg ; I should be able to figure out which version these attributes were implemented. I'll update the PR later to get rid of the failures with version_added.

**Comment by fred-wang** [comment]
@queengooborg I've updated the PR but I'm not sure whether there is an easy way to get Safari's version from the WebKit commit.

**Comment by fred-wang** [comment]
@queengooborg Great, thanks I think I've updated the data and tests pass locally now.

Note that I haven't added data for MathML global attributes that are currently using the equivalent HTML pages. However, I've done that for the `dir` attribute because its syntax is slightly different from HTML's `dir` and I plan to create https://developer.mozilla.org/docs/Web/MathML/Global_attributes/dir

**Review by queengooborg — APPROVED** [review]
Thank you, this is LGTM!  I agree with not duplicating HTML global attributes here.  Welcome to BCD, @fred-wang!  🎉

**Comment by fred-wang** [comment]
@queengooborg Thanks!

**Comment by fred-wang** [comment]
@queengooborg extra question: when is that new data going to be available from MDN? even when testing MDN locally, data is not reachable.

**Comment by queengooborg** [comment]
I release a new version of BCD every Tuesday, and it usually gets updated in Yari within the following two days.  These changes will go live by the end of the week, promise!

**Comment by fred-wang** [comment]
Thanks for the information.

**Pull request merged**
