### PR TITLE
Add specifications and support information for the "size" attribute

### LINKED ISSUE #18443: html.elements.attribute.size and html.elements.attributes.required are missing
### What type of issue is this?

Missing compatibility data

### What information was incorrect, unhelpful, or incomplete?

The specification and compatibility data are missing for the HTML attributes `required` and `size`.

### What browsers does this problem apply to, if applicable?

_No response_

### What did you expect to see?

_No response_

### Did you test this? If so, how?

_No response_

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

MDN pages:
- [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required#browser_compatibility)
- [size](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size#browser_compatibility)

### Do you have anything more you want to share?

_No response_

### MDN URL

_No response_

### MDN metadata

_No response_

### PR DESCRIPTION
**Pull request by jGowgiel**
#### Summary

The "size" attribute doesn't currently have any links, or support data. As an older, core property (introduced in the first version of the HTML spec - https://html.spec.whatwg.org/commit-snapshots/c9e804f04d03a0658bfa689cb0f368a4d2e37936/?C=M&O=A#the-size-attribute) I think it has probably just been overlooked so far.

The information on the "size" attribute page also doesn't align with the spec, which I am hoping to correct with a PR in the [mdn/content ](https://github.com/mdn/content) repository. I'll add a link to this associated PR as a comment once I open this PR!

#### Test results and supporting details

I have verified my changes with `npm test` as instructed for this project.

#### Related issues

Partially fixes #18443.

### CODE REVIEW

**Comment by jGowgiel** [comment]
Associated `mdn/content` PR: https://github.com/mdn/content/pull/33598

**Comment by Elchi3** [comment]
Thanks for your PR and sorry for the merge conflict. Can you resolve that?

I merged https://github.com/mdn/browser-compat-data/pull/21874 first which is the other half to fix https://github.com/mdn/browser-compat-data/issues/18443

**Comment by jGowgiel** [comment]
Hey @Elchi3 - no worries at all! Fixed up those conflicts and just pushed the updated branch. Cheers, and thanks for the review!

**Review by Elchi3 — APPROVED** [review]
Thank you for the quick follow-up and congratulations on your first merged pull request here 🎉

**Pull request merged**
