### PR TITLE
Update Cache API for Deno

### PR DESCRIPTION
**Pull request by bartlomieju**
#### Summary

Updates compat table for "Cache" API for Deno

### CODE REVIEW

**Comment by bartlomieju** [comment]
CC @lucacasonato

**Comment by queengooborg** [comment]
Hey @bartlomieju, thank you for your PR!  Could you attach sources of information for these changes, such as links to changelogs/blog posts, screenshots of testing, etc.?

**Comment by bartlomieju** [comment]
Sure @queengooborg: https://deno.com/blog/v1.26#cache-web-api

**Review by queengooborg — APPROVED** [review]
Thanks for linking the documentation, LGTM!

**Pull request merged**
