### PR TITLE
Update the javascript/ folder for Samsung Internet

### PR DESCRIPTION
**Pull request by AdaRoseCannon**
I'd noticed the way I had been using the mirror script had totally ignored the JavaScript folder, this has those fixes.

#### Summary
javascript/ updates for Samsugn Internet

#### Test results and supporting details
Generated using the mirror script

### CODE REVIEW

**Comment by AdaRoseCannon** [comment]
Is there anything blocking this at the moment?

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Sorry to be slow :) This somehow slipped through.

There is a change to scripts/mirror.js apparently... it looks like a permission change
The GitHub UI says "100644 → 100755". Is that needed? Can you avoid doing that in this PR?

**Comment by AdaRoseCannon** [comment]
Oh nice spot. I forgot about that. At some point for some reason it had
lost it's executable permission and I keep needing to `chmod +x` it.

I'll revert it.

**Comment by vinyldarkscratch** [comment]
It sounds like you're running the mirroring script directly (i.e. `./scripts/mirror.js` vs. `npm run mirror`), or is it not allowing you to run the script through NPM/Node's command if it's not executable?  I can see benefits of us adding the executable permission to all of our executable scripts, though that's another topic for another issue.

As far as the changes to the BCD data, they all look good to me!

**Comment by AdaRoseCannon** [comment]
Mirror script change removed

**Comment by AdaRoseCannon** [comment]
probably ready to go

**Review by vinyldarkscratch — CHANGES_REQUESTED** [review]
Thank you, LGTM!

**Review by vinyldarkscratch — APPROVED** [review]
(Er, it would help to press the right button, haha...)

**Pull request merged**
