### PR TITLE
Add VR data for Edge.

### PR DESCRIPTION
**Pull request by jpmedley**
Please don't merge this yet. I want to get it sanity checked by someone at MS.

### CODE REVIEW

**Comment by Elchi3** [comment]
Hey @erikadoyle @mattwojo, can you take a look at this?

**Comment by jpmedley** [comment]
@

**Comment by jpmedley** [comment]
Close was an accident. Sorry about that.

**Comment by erikadoyle** [comment]
Looks good! I checked it against our published Edge 15 diff: https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/whats-new/edgehtml-15#new-apis-in-edgehtml-15

**Comment by erikadoyle** [comment]
Thank you @jpmedley !

**Pull request merged**
