### PR TITLE
placeholder-shown on Edge 79 (Chromium-based)

### PR DESCRIPTION
**Pull request by massic80**
A checklist to help your pull request get merged faster:
- [ ] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hey there, thanks for your PR, and welcome to BCD!  This makes sense to me, however I think that we're looking to perform a script-based mirroring since there's so many data points -- see #5214 for details on that.  I'll keep this PR open for now.

**Comment by massic80** [comment]
I agree! I think it's the best solution, but I didn't notice you were planning for it :)
I'm sorry I can't help with Python scripts ;)

**Comment by vinyldarkscratch** [comment]
Not a problem!  Actually, the script is written in NodeJS (it was initially in Python when I began on it since I can speak snake better than coffee, but I adapted it to JavaScript so it could be included in the repository) -- I just need to figure out how to code it so it performs mirroring to update existing data rather than just overwrite it all... 😅

**Comment by massic80** [comment]
I'm not used to commit via nodejs, but in case of need, guive me a shout :)

**Comment by vinyldarkscratch** [comment]
So we've decided to go the mirroring route in the end, and as such I've opened up some PRs to perform the mirroring (see #5558 for the one that covers this same file).  As a result, I'm going to go ahead and close this PR.  We'll be reviewing and merging the mirroring PRs shortly, so this should be fixed soon!

**Pull request closed without merging**
