### PR TITLE
Add Safari versions for PerformanceEntry API

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR adds real values for Safari (Desktop and iOS/iPadOS) for the `PerformanceEntry` API, based upon results from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v3.1.4).

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/PerformanceEntry

### CODE REVIEW

**Comment by foolip** [comment]
https://mdn-bcd-collector.appspot.com/tests/api/PerformanceEntry is actually a broken test since it tries to use `window.performance` in a worker, did you really use that test?

https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/Configurations/Version.xcconfig?rev=211594 suggests this should be Safari 11, confirming or disconfirming with testing would be great.

Aside: If you were using BrowserStack to test, I'd recommend using Sauce for all Safari testing, since they make it relatively easy to test both x.0 and x.1 releases.

**Comment by foolip** [comment]
I've sent https://github.com/foolip/mdn-bcd-collector/pull/1238 to fix the tests.

**Comment by vinyldarkscratch** [comment]
I was basing it off of the `toJSON` property, and based it upon whether `PerformanceEntry` was exposed in the worker.  That part hasn't changed since the collector update, so I'm assuming I made a typo on my notepad.  Fixed the data!

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
> I was basing it off of the `toJSON` property, and based it upon whether `PerformanceEntry` was exposed in the worker

I did spot that single test being green, that explains it then. Still it's better to have the fixed tests, `toJSON` could have been added after worker exposure.

**Pull request merged**
