### PR TITLE
Add font element compat data according Caniuse.

### PR DESCRIPTION
**Pull request by myfonj**
* Data taken from Fyrd/caniuse/blob/1ec4dcc442399a70d7ed2000c0d8a344438e23cf/features-json/svg-fonts.json

### CODE REVIEW

**Comment by Elchi3** [comment]
Can you review this @JeremiePat?

**Comment by JeremiePat** [comment]
LGTM :)

**Comment by JeremiePat** [comment]
It can be merge as is however, it should be safe to assume that browsers that never support the font element had never support the associated attributes as well and they should be set to false (like Edge and IE)

**Comment by Elchi3** [comment]
I agree and we're thinking about advanced parent<->children validation in https://github.com/mdn/browser-compat-data/issues/1618 which could catch these kind of things at the linter level.

**Pull request merged**
