### PR TITLE
API: add ProcessingInstruction

### PR DESCRIPTION
**Pull request by caugner**
Sources:
1. DOM Living Standard:
   https://dom.spec.whatwg.org/#processinginstruction
2. Chrome repository:
   https://github.com/chromium/chromium/blob/40e856b910e02f7d0f2644b3ab5204568806706b/third_party/WebKit/WebCore/dom/ProcessingInstruction.idl
3. Firefox bug tracker:
   https://bugzil.la/740069
4. Firefox repository:
   https://github.com/mozilla/gecko-dev/blob/ed510d35069e2e48c5ec411d99e3dab89400f1b3/dom/webidl/ProcessingInstruction.webidl

### CODE REVIEW

**Comment by ddbeck** [comment]
Thanks for this PR @caugner! I'm not quite clear on one thing: how is it that there are subfeatures (attributes?) supported, but those same browsers would be null for `ProcessingInstruction`?

**Comment by ddbeck** [comment]
Ah that's a nice trick! I've got one of my own; I've put it on my to do list to document this sort of thing. Though I hope some day we'll get generated previews in PRs from Travis.

Anyway, this looks good to me. Let's merge it!

**Comment by caugner** [comment]
> Though I hope some day we'll get generated previews in PRs from Travis.

@ddbeck Are you aware of a repo that uses this? Do you know if this requires a bot or can it be accomplished with standard GitHub/Travis integration features?

**Comment by ddbeck** [comment]
@caugner Hrm, I thought there was a bot-less approach but now I can't find an example 😞

**Pull request merged**
