### PR TITLE
Remove "matches" object from schema

### LINKED ISSUE #8945: Remove "matches" object from schema
## Summary

The [`matches`](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-matches-object) has had poor uptake since being introduced to BCD. We should deprecate and remove it from the schema, data, and documentation.

## Background

In https://github.com/mdn/browser-compat-data/pull/3631 we added `matches` to the support object, which provides for tokens or regexes to use to identify code that corresponds to a given BCD feature.

In https://github.com/mdn/browser-compat-data/issues/3709, we tried to solicit more `matches` data, but little activity followed.

Ultimately, we have four features with `matches` data:

- `css.properties.transform-origin.three_value_syntax`
- `css.properties.transform.3d`
- `css.selectors.backdrop`
- `css.types.color.alpha_hexadecimal_notation`

To support those four features we have written 70+ lines of code in an already complex linter, 20+ lines in the schema, and almost 200 words of documentation.

## Proposal

We ought to remove `matches` from the schema. The costs of keeping it are high and the risks of removing it are low.

The psychic cost of keeping `matches` around is high:

- It’s a burden on new BCD consumers and contributors who read the schema documentation. They must learn about `matches` and learn to ignore it.
- It's a burden on BCD's maintainers. I periodically notice this sad, disused bit of the schema and feel wistful about it.

The cost and risk of removing `matches` is low:

- Few parts of BCD itself relies on this—it’s largely self-contained—so stripping it out wouldn't be a particularly complicated or demanding effort.
- Given so little data uses this part of the schema, consumer dependence on it must be rare.

That's not to say that removal is is completely without penalty, however:

- Some consumers do use it, most notably webhintio. See [this example](https://github.com/webhintio/hint/blob/752e027aa54a9a326bd216f8903e4924b2cfab2f/packages/utils-compat-data/src/css.ts#L62-L93). There's not much we can do about this.
- Removal itself could annoy consumers. Removal would cause a backwards-incompatible change, necessitating a SemVer major release. We could partly mitigate this by delaying the removal until we have other breaking changes to make.
 
Overall, I think this points towards removal as a good option.

## Implementation

To do this would require a few tasks:

- Issue a SemVer minor release noting that `matches` is deprecated, will be removed in a future release, and new data will not be accepted for it. Also update the documentation accordingly.
- Remove `matches` from the schema, the data, and any mentions of it in the documentation.
- Issue a SemVer major release with those changes.

## Next steps

To move forward on this, we need to make a decision about whether we actually want to do it. I'd like to hear feedback on this proposal, so the project owners can make a decision.

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the `matches` object from the schema.  The feature is hardly used anywhere other than a few CSS properties and has not been maintained.  On top of it, the linter to verify `matches` regexes was never actually integrated into the linter run.

Note: in regards to the `transform` CSS property, I'm thinking that we should separate the keywords out, but I'm not fully certain on that.

Fixes #8945.

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
r- here until https://github.com/webhintio/hint/issues/5126 is solved on the webhintio side.

**Review by caugner — APPROVED** [review]
LGTM, but ⚠️ major bump

**Comment by antross** [comment]
@queengooborg @Elchi3 @caugner, we've finished preparing for this removal on the webhint side. Feel free to move forward and thanks for giving us the heads-up + some time to adapt before this went in! 😊

**Comment by queengooborg** [comment]
Thanks @antross for the notice!

**Pull request merged**
