### PR TITLE
Expose thirdParty state in WebRequest and proxy onRequest details

### LINKED ISSUE #5539: Firefox 72 exposes third-party state in WebRequest and proxy onRequest details
Recently released Firefox 72 changed network WebExtension APIs to add `thirdParty` property, which is described in blog post ["Extensions in Firefox 72"](https://blog.mozilla.org/addons/2020/01/22/extensions-in-firefox-72/).

### WebRequest `thirdParty`
[Commit](https://github.com/mozilla/gecko-dev/commit/39723a2dd06122ae6f2feec689c759a39a06b889#diff-35cc5da1569d1796a35f26e7eb896890)
[Bugzilla bug 1591900](https://bugzilla.mozilla.org/show_bug.cgi?id=1591900)

Other changes mentioned in the blog post are already documented:

### `browserAction` and `pageAction`
Already documented and data updated in 5285.

#### Captive Portal API
[Already documented](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/captivePortal/canonicalURL) and the compat data updatedin 5326.
#### Browser Settings API
Already documented as [WebExtensions/API/types/BrowserSetting](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/types/BrowserSetting) and the compat data was updated in 5437.

Edit: turns out, only network APIs need to be updated and fixing this will fit in a single commit.

### PR DESCRIPTION
**Pull request by rebloor**
This change adds the `thirdParty` property to:
* [`proxy.RequestDetails`](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/RequestDetails), noting that the properties in this object (`cookieStoreId`, `documentUrl`, `frameId`, `fromCache`, `incognito`, `method`, `originUrl`, `parentFrameId`, `requestId`, `requestHeadersOptional`, `tabId`, `timeStamp`, `type`, and `url`) were not previously exemplified in the compatibility data and have now been added.
* the `details` property of `callback` for all of the events in [`webRequest`](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest).

This property is a Firefox only feature.

Change made in support of bug [1591900](https://bugzilla.mozilla.org/show_bug.cgi?id=1591900) and detailed in  [proxy.json](https://hg.mozilla.org/integration/mozilla-inbound/diff/26616eb7c1749dcbcfd601966da08c6a48db46e5/toolkit/components/extensions/schemas/proxy.json) and [web_request.json](https://hg.mozilla.org/integration/mozilla-inbound/diff/26616eb7c1749dcbcfd601966da08c6a48db46e5/toolkit/components/extensions/schemas/web_request.json).

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)

Fixes #5539.
- [x] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hey @rebloor -- based upon the title, this seems like a duplicate of #5551, but comparing the changes to `proxy.json`, there's some big differences.  Can we cherry-pick this PR so that it doesn't cover any of the `thirdParty` feature additions, thus removing the data duplication?

**Comment by rebloor** [comment]
@vinyldarkscratch I believe the changes in #5551 that differ from those here are wrong, or at least unnecessary. I was commenting on and proceeding with the other PR as I thought it might be quicker than waiting for this 1 to be reviewed.

**Comment by vinyldarkscratch** [comment]
Well, you're the webextensions expert!  Typically when there are duplicate PRs (or PRs with matching changes), I tend to give the older one priority, but if the differing changes are inaccurate, we should close the other PR and keep the more accurate one.  So I guess we should keep this one and close #5551?

**Comment by bershanskiy** [comment]
@vinyldarkscratch 
>  Typically when there are duplicate PRs (or PRs with matching changes), I tend to give the older one priority,

Clearly, @rebloor is more authoritative information source than I am, so I'm fine closing #5551 in favor of #5582 (this). After all, we are not in FIFO or first-come-first-serve "business", but in the eventual correctness "business". :)

> So, I guess that next up, we review them and decide what to do from there?
 - Our `webRequest` changes appear to be identical and files differ only in some Edge data because this PR apparently is missing changes from [#5564](https://github.com/mdn/browser-compat-data/pull/5564/files#diff-24a0b621560d29ca3d391beb441f1839). These changes should merge cleanly and so this file is shouldn't be a problem for either PR.
 - `proxy` differs a lot, and I would trust @rebloor's judgement on this.

**Comment by rebloor** [comment]
@wbamberg my checking suggests that `urlClassification` was added as part of the different piece of work, [expose HttpTrafficAnalyzer information in webrequest](https://bugzilla.mozilla.org/show_bug.cgi?id=1547140) and on that bug it notes " [Since it's a privileged api we shouldn't document on mdn](https://bugzilla.mozilla.org/show_bug.cgi?id=1547140#c21)".

**Pull request merged**
