### PR TITLE
Add HTTP QUERY method

### PR DESCRIPTION
**Pull request by chicoxyzzy**
#### Summary

This PR adds an HTTP QUERY method, which is still an IETF Internet-Draft (https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html) 

#### Related issues

https://github.com/mdn/content/pull/33226

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Still exploring if the method is available in browsers

**Comment by pepelsbey** [comment]
It seems more of a [runtime-compat-data](https://github.com/unjs/runtime-compat/tree/main/packages/runtime-compat-data) thing at the moment since it’s currently Node.js only. Both BCD and MDN don’t document draft features without browser implementations.

**Comment by queengooborg** [comment]
Actually, we track Node.js (and Deno) here in BCD!  :)

**Comment by chicoxyzzy** [comment]
I'm not sure how to fix rest of the errors:
```
Browser Presence - 2 problems (2 errors, 0 warnings):
 ✖ http.methods.QUERY - Error → Has the following browsers, which are invalid for http compat data: nodejs
 ✖ http.methods.QUERY - Error → Missing the following browsers, which are required for http compat data: chrome, edge, firefox, ie, opera, safari
Spec URLs - 1 problem (1 error, 0 warnings):
 ✖ http.methods.QUERY - Error → Invalid specification URL found: https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html. Check if:
         - there is a more current specification URL
         - the specification is listed in https://github.com/w3c/browser-specs
         - the specification has a "good" standing
```

**Comment by queengooborg** [comment]
To answer your questions about the errors:

> ✖ http.methods.QUERY - Error → Has the following browsers, which are invalid for http compat data: nodejs

This error means that NodeJS is actually not allowed in the HTTP data category.  This might be something we should change.

However, I must ask: could you provide supporting documentation that shows that NodeJS supports this?  Additionally, if you have some test code that demonstrates support, could you include that as well?

> ✖ http.methods.QUERY - Error → Missing the following browsers, which are required for http compat data: chrome, edge, firefox, ie, opera, safari

This is because you had removed the support statements for the other browsers altogether.  They should still be present in the data and set to `version_added: false`.

>  ✖ http.methods.QUERY - Error → Invalid specification URL found: https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html.

The URL needs to be added to the exceptions list in `lint/linter/test-spec-urls.ts` as well.

However, upon further inspecting the spec URL, I noticed something interesting: this document had an expiry date of May 13th, 2022.  As such, I actually think that we should mark this feature as _non-standard_ and drop the spec URL.

---

There's also another slight issue, which is that we don't track the individual patch versions of NodeJS.  Rather than using "21.7.2" as the version number, let's use "21.7.0" instead.  (I know it's a little inaccurate -- there's an issue open about dropping the patch version part of the version numbers for NodeJS, see #18777.)

**Comment by queengooborg** [comment]
Hey there -- just checking to see if you plan on returning to this PR and answering the question in my previous comment!

**Comment by queengooborg** [comment]
I'm closing this PR because there has been no response and additional information is needed to be able to continue.

**Pull request closed without merging**
