### PR TITLE
Update IE/Edge compatibility of JavaScript statements

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This updates the IE and Edge compatibility of various JavaScript statements, based upon manual testing.  The data is as follows:

javascript.statements.async_function - 15
javascript.statements.block - 11
javascript.statements.break - 3
javascript.statements.class - 13
javascript.statements.const - 11 (already in data)
javascript.statements.continue - 3
javascript.statements.debugger - 4
javascript.statements.default.switch - 4
javascript.statements.do_while - 4
javascript.statements.empty - 3
javascript.statements.for - 3
javascript.statements.for_in - 6 (already in data)
javascript.statements.for_of.async_iterators - 12
javascript.statements.for_of.closing_iterators - 14
javascript.statements.function - 3
javascript.statements.function.trailing_comma_in_parameters - 14
javascript.statements.generator_function.not_constructable_with_new - 13
javascript.statements.generator_function.trailing_comma_in_parameters - 14
javascript.statements.if_else - 3
javascript.statements.import_meta - false
javascript.statements.label - 4
javascript.statements.return - 3
javascript.statements.switch - 4
javascript.statements.throw - 5
javascript.statements.try_catch - 5
javascript.statements.var - 3
javascript.statements.while - 3
javascript.statements.with - 3

### CODE REVIEW

**Comment by Elchi3** [comment]
> javascript.statements.function.trailing_comma_in_parameters - 5.5

This is super new in Firefox and in Chrome. Can you tell more how you found out this is already in IE 5.5?

Rest looks good to me.

**Comment by vinyldarkscratch** [comment]
Of course!  If I remember correctly, I added a trailing comma to the function's parameters, and passed the function into an `alert()` call.  The earlier IE versions couldn't interpret and parse it, but IE 5 parsed it just fine -- it just showed the trailing comma in the alert.  IE 5.5 parsed the statement but didn't show a trailing comma in the alert.

I could be totally wrong about how to tackle it, and am happy to revisit it!

**Comment by Elchi3** [comment]
In IE 11 it fails for me with "Expected identifier if I enter `function f(p,) { console.log(p)}` in the console. I doubt it is supported.

**Comment by vinyldarkscratch** [comment]
Re-visiting that statement, I now wonder how I thought 5.5 before...  I've just ran the above code, and found that support was actually added in 14.  /)_-

**Comment by Elchi3** [comment]
That makes more sense to me.
This doesn't fix #4940 though as that page takes data from here:
https://github.com/mdn/browser-compat-data/blob/master/javascript/grammar.json#L948

**Comment by vinyldarkscratch** [comment]
Gotcha -- removed the fix statement so that issue will remain open!

**Pull request merged**
