### PR TITLE
Hack the diff script to compare old.json to new.json

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by saschanaz** [comment]
Why not just do `npm run diff origin/main other-branch`? 👀

**Comment by foolip** [comment]
Because the diff script doesn't use the *code* from the other branch, just the data. When changing how mirroring works, the diff script doesn't tell you what's changes.

**Comment by foolip** [comment]
Also, the diff script seems to be broken right now:

```
TSError: ⨯ Unable to compile TypeScript:
scripts/diff.ts:86:3 - error TS7027: Unreachable code detected.

86   throw new Error(`Unexpected kind ${(diffItem as any).kind}.`);
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by queengooborg** [comment]
In the current diff script, we're checking out branches/commits in subfolders.  Why don't we `cd` into said subfolders to run the build script and extract the build output file?

I'd like to retain the convenience of simply running the diff script without performing any checkouts and extra steps myself!

**Comment by saschanaz** [comment]
If `git checkout` during the node run is safe then that may work. (Not sure it's gauranteed though, I can imagine that module imports break)

**Comment by Elchi3** [comment]
I think this can be closed. Feel free to reopen if this is still relevant.

**Pull request closed without merging**
