### PR TITLE
Add notes for never-supported CSS types

### PR DESCRIPTION
**Pull request by saschanaz**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any: #6854, #6768

### CODE REVIEW

**Comment by ddbeck** [comment]
Hi @rachelandrew, I'm going to start tagging you for review of CSS features proposed for removal, as we discussed in https://github.com/mdn/browser-compat-data/pull/6962#issuecomment-717947251. You don't need to do a full-review of these—I just need to whether they're not part of an active specification. Thank you!

**Comment by rachelandrew** [comment]
@ddbeck no problem, I'll go through them.

All of the ones listed here are currently in Values and Units, or images and are legit. Some are quite new but I don't think are likely to vanish again.

**Review by rachelandrew — COMMENTED** [review]
These are all part of an active spec - either Values and Units, or Images.

**Review by ddbeck — APPROVED** [review]
Thank you! 🎉

**Pull request merged**
