### PR TITLE
Add searchengines api compat data (WebExtensions)

### PR DESCRIPTION
**Pull request by Smile4ever**
https://bugzilla.mozilla.org/show_bug.cgi?id=1352598

@wbamberg If something else is needed, please let me know. I didn't do the chrome_settings_overrides part because I didn't know how.

### CODE REVIEW

**Comment by Smile4ever** [comment]
api/search.json
  JSON schema – OK 
  File : /home/travis/build/mdn/browser-compat-data/api/search.json
  Style – Error on line #1
    Actual:   {
    Expected: {
  Browser versions – OK 

I don't understand what's wrong, can someone look at it?

**Comment by Elchi3** [comment]
Hey, the error looks weird indeed. Not sure what's up there. 
You've put the file under `api/search.json`, but this belongs into `webextensions/api/search.json`. Can you move it?

**Comment by Smile4ever** [comment]
@Elchi3 I moved it.

**Comment by Elchi3** [comment]
So, it looks like the file is not formatted according to our [editorconfig](https://github.com/mdn/browser-compat-data/blob/master/.editorconfig) file. Your file uses CRLF, but we expect LF. Can you set your editor to respect the .editorconfig file?
Consistent formatting in this repo helps us to do mass-data changes more easily. 
Thank you! :)

**Comment by Smile4ever** [comment]
The merge request has been updated with the requested changes.

**Pull request merged**
