### PR TITLE
Remove never-supported HTTP headers

### PR DESCRIPTION
**Pull request by saschanaz**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any: #6854, #6768

### CODE REVIEW

**Comment by Mouvedia** [comment]
Do not remove `set-cookie2` and `cookie2`; it was supported by Opera.

> [Disable Cookie2 by default, with an option to enable it again](https://web.archive.org/web/20120121154633/http://my.opera.com/desktopteam/blog/2011/02/17/a-first-glimpse-at-barracuda)

**Comment by Elchi3** [comment]
> Do not remove `set-cookie2` and `cookie2`; it was supported by Opera.

https://github.com/mdn/browser-compat-data/pull/15405 removed them already and I agree to not have them anymore. We have a policy for when we consider features as irrelevant: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features. The headers were last supported in 2011, so data removal is okay.

**Comment by Elchi3** [comment]
Seems like some of these features are removed already. I think the feature-policy layout-animations might be one left to remove. A rebase could reveal more.

**Comment by Mouvedia** [comment]
> We have a policy for when we consider features as irrelevant: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#removal-of-irrelevant-features.

@Elchi3 you single handedly proposed that guideline the 21/04/2020 and it was merged the next day.
No one had the time to voice their concerns. Only 2 persons were involved in the PR.
This is wrong.

It is obvious that something called _browser-compat-data_ ought to be exhaustive or at least it should be the goal.
A lot of tooling use that data, it should be complete. There are millions of old codebases to maintain.

**Comment by queengooborg** [comment]
Hi @Mouvedia, all of our data guidelines reflect project convention and consensus, and the reason the PR adding the guideline was merged so quickly was because it was already settled across various other issues/PRs and offline discussion (that is, meetings/chats through Matrix, Zoom, etc.).  We'll take your comments into consideration should we ever revisit the guideline!

**Pull request closed without merging**
