### PR TITLE
Update versions for Animation APIs

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR updates various versions for the Animation APIs based upon manual testing.  There were a few APIs defined as supported in Chromium (AnimationPlaybackEvent and AnimationTimeline), however I could not find support in _any_ version of Chrome.  Data is as follows:

```
api.Animation.Animation
	- Opera - Blink
api.AnimationEffect
	- Chrome - 75
	- Edge - Blink
	- IE - false
	- Opera - Blink
	- Safari - 13.1
api.AnimationEffect.getComputedTiming
	- Chrome - 75
	- Edge - Blink
	- IE - false
	- Opera - Blink
	- Safari - 13.1
api.AnimationEffect.getTiming
	- Chrome - 75
	- Edge - Blink
	- IE - false
	- Opera - Blink
	- Safari - 13.1
api.AnimationEffect.updateTiming
	- Chrome - 75
	- Edge - Blink
	- IE - false
	- Opera - Blink
	- Safari - 13.1
api.AnimationEvent
	- Chrome - 43 (1 to 70 w/ WebKit prefix)
	- Opera - incorrect data: 12.1-15, 30, 15-57 w/ WebKit prefix, 12-15 w/ o prefix
	- Safari - incorrect capitalization for WebKit prefix, fixed
api.AnimationEvent.animationName
	- Opera - Blink
api.AnimationEvent.elapsedTime
	- Opera - Blink
api.AnimationEvent.initAnimationEvent
	- Chrome - 1 to 18 as initWebKitAnimationEvent
	- Safari - 4 to 6 as initWebKitAnimationEvent
api.AnimationPlaybackEvent
	- Chrome - false
api.AnimationPlaybackEvent.AnimationPlaybackEvent
	- Chrome - false
api.AnimationPlaybackEvent.currentTime
	- Chrome - false
api.AnimationPlaybackEvent.timelineTime
	- Chrome - false
api.AnimationTimeline
	- Chrome - false
	- Opera - false
```

### CODE REVIEW

**Comment by Elchi3** [comment]
@lpd-au you might be a good reviewer here

**Comment by Elchi3** [comment]
Should this be merged then? Did you two agree on how to deal with conflicts with https://github.com/mdn/browser-compat-data/pull/5963?

**Comment by vinyldarkscratch** [comment]
Apologies, I've been busy the past few weeks with work to try and earn as much money as I can to survive the COVID19 pandemic (as well as quarantining one of my family members who's showing signs).  I've been relatively inactive on BCD as a result, just doing some minimal things here and there, and we haven't really talked yet.

I'll take a look at these PRs shortly!

**Comment by Elchi3** [comment]
No worries, Vinyl! Thanks for checking in with us and be safe!

**Comment by vinyldarkscratch** [comment]
I did a little bit of testing for the AnimationTimeline API in Chrome 81 and 83, and unfortunately it doesn't look like there's support for it just yet.  My guess is that maybe it's enabled in Canary builds, but not the beta or stable just yet?

**Comment by danwilson** [comment]
Through 83, several features (like Timeline) have been behind the "Experimental Web Platform Features" flag... but it appears in Canary 84 it is enabled for the first time without the flag (based on a check this morning).

**Comment by lpd-au** [comment]
> Through 83, several features (like Timeline) have been behind the "Experimental Web Platform Features" flag... but it appears in Canary 84 it is enabled for the first time without the flag (based on a check this morning).

This won't be able to be input until https://github.com/mdn/browser-compat-data/issues/6056 is finished, but in the meantime you may find these links useful:
- https://bugs.chromium.org/p/chromium/issues/detail?id=978551
- https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/Wu4yPMznUw0
- https://chromestatus.com/feature/5126405660606464

**Comment by porsager** [comment]
I got confused by Safari 13.1 not showing support for the Animations API, so it would be nice to get this merged soon so others won't be confused as well 🙂

**Comment by Elchi3** [comment]
@vinyldarkscratch @chrisdavidmills should we merge this one and then sort out https://github.com/mdn/browser-compat-data/pull/5963 later? Did you two coordinate?

**Comment by lpd-au** [comment]
Personally I chose to only review the other PR so far because it was the smaller of the two and easier to follow. I was hoping this one would be more approachable once the overlap was rebased out...

**Comment by chrisdavidmills** [comment]
@Elchi3 I didn't coordinate here, I'm afraid. I'm happy to proceed in whatever way is best for @vinyldarkscratch 's work. Just let me know what you want me to do ;-)

**Comment by Elchi3** [comment]
@vinyldarkscratch any preferences from your side on how to proceed?

If not, I would say, @chrisdavidmills addresses the review comments by @lpd-au on https://github.com/mdn/browser-compat-data/pull/5963, we merge that one, and then sort out this PR.

**Comment by vinyldarkscratch** [comment]
Sounds good to me!  The other PR is much smaller, and thus will be much easier to review and merge.

**Comment by chrisdavidmills** [comment]
OK, thanks folks! I've responded to the review comments on the other one.

**Comment by lpd-au** [comment]
@vinyldarkscratch I believe the other PR is now ready to be merged and this one rebased onto it :)

**Pull request merged**
