### PR TITLE
Fix Chromium versions for font-size-adjust

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR is created based upon https://github.com/mdn/browser-compat-data/pull/4738#discussion_r320303396.

### CODE REVIEW

**Comment by 36degrees** [comment]
@jpmedley @vinyldarkscratch is this change definitely correct? I'm seeing this feature as being behind a flag on [Chrome Platform Status](https://www.chromestatus.com/features/5720910061371392) (deep linking doesn't seem to work, unfortunately, but you can search for font-size-adjust). According to [Chromium #451346](https://bugs.chromium.org/p/chromium/issues/detail?id=451346), it's blocked because of a [Chromium #666674](https://bugs.chromium.org/p/chromium/issues/detail?id=666674).

Can I Use is also [still marking this as behind a flag in Chrome](https://caniuse.com/#search=font-size-adjust).

**Comment by vinyldarkscratch** [comment]
Good catch!  You're right, it doesn't actually seem to be supported (just did a quick test in the latest Chrome (80)).  Can you open up an issue or PR for this?

**Comment by 36degrees** [comment]
Sure thing 👍

**Comment by 36degrees** [comment]
@vinyldarkscratch I'm presuming the Opera change was just based on the fact that Opera uses Chromium? Is there any part of this PR that shouldn't just be reverted?

**Comment by vinyldarkscratch** [comment]
Yeah, Opera, Samsung Internet, and WebView data are all based upon Chrome.

**Comment by 36degrees** [comment]
@vinyldarkscratch PR raised over at https://github.com/mdn/browser-compat-data/pull/5755 🙂

**Pull request merged**
