### PR TITLE
Add BCD for the Attribution Reporting API

### PR DESCRIPTION
**Pull request by chrisdavidmills**
#### Summary

[The Attribution Reporting API](https://wicg.github.io/attribution-reporting-api/) is an integral part of Google's [privacy sandbox](https://developer.chrome.com/docs/privacy-sandbox/) technologies. Many parts of this set are being made available by default in Chrome 115 (depending on a gradual ramp-up to 100% of userbase over the 115 release period).

This PR provides BCD for the Attribution Reporting API and its related HTTP headers and other features.

See my [research document](https://docs.google.com/document/d/1OFOjwVyEjTsyZdM9cfGikG3jMKck08g8pcpRmeSsf9M/edit) for more details of exactly what changes are expected in the PR.

### CODE REVIEW

**Comment by queengooborg** [comment]
Looks like these have actually landed in Chrome 117, may we update the data accordingly?

**Comment by chrisdavidmills** [comment]
> Looks like these have actually landed in Chrome 117, may we update the data accordingly?

@queengooborg Done.

**Review by queengooborg — APPROVED** [review]

**Comment by queengooborg** [comment]
So interestingly enough, it appears that BrowserStack's browsers don't have support for this API.  I had based Chrome 117 off of the fact that my local Chrome has support, but Chrome 115 and 116 on BrowserStack did not.  However, upon further inspection, even Chrome 118 on BrowserStack does not have support for this API.  (Note: I do not have any flags enabled, and I've tested both Windows and macOS in BrowserStack.  I also tested for support in a guest profile on my local machine, not incognito mode.)

You mentioned that the release of this feature set would be performed gradually for the 115 user base.  Is it possible that the gradual rollout stopped for some reason, so now it is stuck at some partial percentage?  Or is something else going on?

**Comment by chrisdavidmills** [comment]
> You mentioned that the release of this feature set would be performed gradually for the 115 user base. Is it possible that the gradual rollout stopped for some reason, so now it is stuck at some partial percentage? Or is something else going on?

Hrm, this is really quite weird. I'll ask the Chrome engineers what is going on.

**Pull request merged**
