### PR TITLE
updates Chromium size-adjust descriptor support

### PR DESCRIPTION
**Pull request by argyleink**
Chromium [intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/1PVr94hZHjU/m/J0xT8-rlAQAJ) `size-adjust` in 92

### CODE REVIEW

**Review by ddbeck — CHANGES_REQUESTED** [review]
Thanks for this PR, @argyleink. A couple things here:

According to [the Chrome Platform Status entry](https://chromestatus.com/feature/5662073285509120), this looks very likely appear on all the other Chromium-derived. Would you mind setting Chrome for Android, Edge, and WebView Android to the same number too?

Also, a minor warning. On Google's recommendation, we wait to merge Canary changes like this until a feature hits beta (or we've been advised that the feature change is set in stone). That appears to be a couple of weeks off right now, so this will likely go unmerged for a little while.

**Comment by argyleink** [comment]
I've added the requested changes, great suggestion thank you! 👍🏻 

totally fine for this to merge later 👍🏻

**Comment by ddbeck** [comment]
Thanks, @argyleink! Looks great. I don't expect any more changes needed, but I'll double check this in June. 🔜

**Comment by jpmedley** [comment]
This feature [merged to 92 last week](https://storage.googleapis.com/chromium-find-releases-static/891.html#89163c9f2a12c74842e19b7c76abb335d5472fc0). It's safe to merge to BCD.

**Review by ddbeck — APPROVED** [review]
@jpmedley thanks for the confirmation.

And thank you for the PR, @argyleink! 🎉

**Pull request merged**
