### PR TITLE
Update IE compatibility for History API

### PR DESCRIPTION
**Pull request by kcak11**
back, forward, go & length are all supported by Internet Explorer

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
   Updated the compatibility data for IE for the back, forward, go & length
- [x] Data: if you tested something, describe how you tested with details like browser and version
   I have tested back, forward, go & length on my machine with IE11 and they all work fine.

### CODE REVIEW

**Comment by kcak11** [comment]
> Hey there, thanks for your PR, and welcome to BCD! This is looking good to me -- I can confirm that support is in IE since IE 10. I think we should add that version number, if you're up for it?

Have updated the version now. Thanks.

**Comment by kcak11** [comment]
@vinyldarkscratch I believe that although this pull-request got merged 4 days ago, the changes are not yet reflected in the online pages i.e.
https://developer.mozilla.org/en-US/docs/Web/API/History#Browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/History_API#Browser_compatibility

image

The page still displays '?' for these 4 values **back, forward, go & length** in the IE column.
Earlier I thought that the changes would automatically reflect after the November 21st Release, but that doesn't seem to be the case.

Did I missing something in my pull-request ?

Request you to please advise.
Thanks in advance.

**Comment by vinyldarkscratch** [comment]
The changes are included in the BCD release, but it takes a while for Kumascript to update.  You can also probably force a regeneration of the compat table using Shift+Cmd/Ctrl+R in your browser!

**Comment by kcak11** [comment]
Hmm I logged into the MDN Website and hit Shift+Cmd+Refresh, but still the old data.

**Comment by ddbeck** [comment]
Because of changes in the MDN frontend, you have to click "Edit in wiki" _then_ force the refresh (i.e., you have to force the refresh on `wiki.developer.mozilla.org` pages, not `developer.mozilla.org`). Then you'll typically see a red box at the top of the page noting that the update is in progress. When the update is done, you should see the latest released compat data in the table.

This worked for me on both of the history pages you linked to, though it took a couple of minutes for the regular `developer.mozilla.org` pages to show the updated tables.

**Comment by vinyldarkscratch** [comment]
Ah, thanks for the information, @ddbeck, I’ll keep that in mind!

**Comment by kcak11** [comment]
Thanks @ddbeck & @vinyldarkscratch :)

**Pull request merged**
