### PR TITLE
Remove `@@notation` from all user-visible strings

### PR DESCRIPTION
**Pull request by Josh-Cena**
Part of https://github.com/mdn/mdn/issues/562. I did not touch the BCD keys in this PR, because we have two options:

1. `Array.symbol_iterator`
2. `Array.%iterator%`

I'm leaning to the first option, but I also want to get BCD maintainers' opinions in this PR. Whatever decision we reach, adding `description` is necessary because we can't reuse the key as the description.

This should be merged after https://github.com/mdn/content/pull/34824 because it's changing the MDN URLs.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
I personally prefer option 1

**Comment by Elchi3** [comment]
+1 for option 1.

Tagging other BCD owners/peers to give input: @queengooborg, @foolip, @ddbeck, @Rumyra

**Comment by ExE-Boss** [comment]
<https://github.com/mdn/content/pull/34824> has now been merged, so the CI can now be re‑ran.

**Comment by ddbeck** [comment]
Was `iterator_symbol` considered? If so, why was it rejected? Type suffixes are widely used too (e.g., `_event`).

What concern is, there if any, for inconsistency with other `@@` keys (e.g., `@@species` but especially `@@asyncIterator`)? Are you going to change those too? Putting on my consumer hat for a moment, I'd _really_ rather deal with a convention change once.

**Comment by Josh-Cena** [comment]
In case it isn't clear: I'm removing every single occurrence of `@@` across MDN. So yes, other keys would be updated too.

`iterator_symbol` is fine, but the description is `[Symbol.iterator]`, and the page slug is `/Symbol.iterator`, so serializing it as `symbol_iterator` seems most reasonable, for the unfortunate fact that BCD keys cannot contain `.`. My qualm about `iterator_symbol` is that for things like `click_event`, we are saying that "click is an event", but here it's not that "iterator is a symbol", but "the property key called symbol.iterator, with . replaced with _".

This PR is intended to start the discussion, and you are welcome to propose more alternatives either here or in https://github.com/mdn/mdn/issues/562.

**Comment by ddbeck** [comment]
Having slept on this, I'm 👎 on changing the keys, but I'm happy with the change to the description. The keys themselves aren't really reader-facing (at least in the presence of a `description`); they're slightly arbitrary identifiers no matter what, so why change them?

**Comment by queengooborg** [comment]
I also think that we should leave the feature identifiers as they are, particularly for BCD's consumers.  Many consumers rely on the current feature identifiers for BCD, including the collector.  Renamed features aren't covered as a breaking change under BCD's semantic versioning policy, but this is a feature I would feel bizarre about renaming in a patch update.  Personally, I don't feel that the effort to change the identifiers (especially for consumers) outweighs the benefits.

The descriptions, on the other hand, we should definitely update!

**Comment by Elchi3** [comment]
In today's BCD call we decided to merge the description change and to defer the key change to an issue where we can discuss the change further and assess effects on consumers like web-features or https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/src/build/bcd/mapper.ts#L94 and other packages. If we change this, it would be probably a breaking change, so let's do that if we feel like it is worth it and get the descriptions sorted here first.

**Comment by Josh-Cena** [comment]
I also agreed to defer the key changes so let's do that.

The problem is that BCD would be using a notation that is nonstandard and likely confusing—which is fine, if y'all all don't want to change it.

**Pull request merged**
