### PR TITLE
Add Navigation API

### PR DESCRIPTION
**Pull request by lukewarlow**
#### Summary

Add data and entries for Navigation API

#### Test results and supporting details

https://wicg.github.io/navigation-api

https://chromestatus.com/feature/6232287446302720

### CODE REVIEW

**Comment by lukewarlow** [comment]
I believe I'm correct in thinking that Wicg APIs are no longer marked as "standard_track" but if I've misunderstood happy to switch them all to true

**Comment by queengooborg** [comment]
We've actually been marking WICG as "standard track" here in BCD, especially since they're included in w3c/browser-specs!

**Comment by lukewarlow** [comment]
Just corrected that, good to know for future reference.

**Review by queengooborg — APPROVED** [review]
LGTM, thank you!

**Comment by Elchi3** [comment]
This added on-* event handler properties which is against the data guidelines. 
https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#dom-events-eventname_event

**Comment by queengooborg** [comment]
Ack, didn't notice that -- fix coming right up!

**Comment by Elchi3** [comment]
Not sure if it is lintable. If it is, we should probably lint for it.

**Comment by lukewarlow** [comment]
Apologies, didn't know about that.

**Pull request merged**
