### PR TITLE
Add Intl Locale info properties

### PR DESCRIPTION
**Pull request by romulocintra**
#### Summary
Add browser compat data for Intl.Locale Info

- [x] Intl.Locale.prototype.weekInfo
- [x] Intl.Locale.prototype.timeZones
- [x] Intl.Locale.prototype.collations
- [x] Intl.Locale.prototype.hourCycles
- [x] Intl.Locale.prototype.numberingSystems
- [x] Intl.Locale.prototype.calendars
- [x] Intl.Locale.prototype.textInfo

#### Test results and supporting details

- https://chromestatus.com/features/5566859262820352
- https://github.com/tc39/proposal-intl-locale-info

#### Related issues

https://github.com/mdn/content/pull/8768

### CODE REVIEW

**Comment by romulocintra** [comment]
Find out this validation is not passing :

```
      AssertionError [ERR_ASSERTION]: Invalid specification host(s) found. Try a more current specification URL and/or
      check if the specification URL is listed in https://github.com/w3c/browser-specs.
      + expected - actual

      -[
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.calendars"
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.collations"
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.hourcycles"
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.numberingSystems"
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.textInfo"
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.timezones"
      -  "https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.weekInfo"
      -]
      +[]
```

How should I proceed when spec is still "draft"  just ignore the spec_url ?

**Comment by ddbeck** [comment]
Hi @romulocintra and thanks for this PR! We use [w3c/browser-specs](https://github.com/w3c/browser-specs) to validate spec URLs. Ideally, you could contribute that spec URL upstream to browser-specs, then it'll validate when we upgrade in BCD (this tends to happen pretty quickly).

That said, if you'd like to see the test results beforehand, you can add a temporary exception in [`test/spec-urls.test.js`](https://github.com/mdn/browser-compat-data/blob/main/test/spec-urls.test.js#L27).

**Comment by romulocintra** [comment]
> Hi @romulocintra and thanks for this PR! We use [w3c/browser-specs](https://github.com/w3c/browser-specs) to validate spec URLs. Ideally, you could contribute that spec URL upstream to browser-specs, then it'll validate when we upgrade in BCD (this tends to happen pretty quickly).
> 
> That said, if you'd like to see the test results beforehand, you can add a temporary exception in [`test/spec-urls.test.js`](https://github.com/mdn/browser-compat-data/blob/main/test/spec-urls.test.js#L27).

Thanks, and is already merged https://github.com/w3c/browser-specs/pull/378 waiting to CI. to work as expected :)

**Comment by lukewarlow** [comment]
Safari also has these in preview now.

https://webkit.org/blog/11971/release-notes-for-safari-technology-preview-132/#:~:text=Implemented%20Intl%20Locale%20Info%20extension

**Comment by romulocintra** [comment]
> Safari also has these in preview now.
> 
> https://webkit.org/blog/11971/release-notes-for-safari-technology-preview-132/#:~:text=Implemented%20Intl%20Locale%20Info%20extension

Safari has already been updated to "preview"

**Comment by romulocintra** [comment]
@Elchi3  there is any way of re-run this PR without commit?

**Comment by Elchi3** [comment]
> @Elchi3 there is any way of re-run this PR without commit?

I did re-run it but you probably need to rebase against latest `main`, so that this branch includes the latest browser-spec package (merged in https://github.com/mdn/browser-compat-data/pull/12621)

**Comment by romulocintra** [comment]
> > @Elchi3 there is any way of re-run this PR without commit?
> 
> I did re-run it but you probably need to rebase against latest `main`, so that this branch includes the latest browser-spec package (merged in #12621)

Thank you , on my way to do it :)

**Comment by romulocintra** [comment]
All good now :) thank you again @Elchi3

**Review by ddbeck — APPROVED** [review]
Looks good. Thank you! 🎉

**Pull request merged**
