### PR TITLE
Require notes if partial_implementation is true

### LINKED ISSUE #4162: Require notes for partial_implementation
The `partial_implementation` data alone isn't very useful. We should consider requiring the `notes` property for any support statement that has `partial_implementation: true`. I started doing [the schema work to do this](https://github.com/mdn/browser-compat-data/compare/master...ddbeck:partial_notes), but it turned out there are more such cases than I would've guessed. At the moment, such support statements appear in the following features:

- [x] `api.CSS.supports`
- [x] `api.Crypto.subtle`
- [x] `api.GeometryUtils`
- [x] `api.SubtleCrypto`
- [x] `api.VisualViewport.onresize`
- [x] `api.VisualViewport.onscroll`
- [x] `api.VisualViewport.resize_event`
- [x] `api.VisualViewport.scroll_event`
- [x] `api.WindowOrWorkerGlobalScope.indexedDB`
- [ ] `css.properties.appearance`
- [ ] `css.properties.appearance.compat`
- [x] `css.properties.filter`
- [ ] `css.properties.font-feature-settings`
- [ ] `css.properties.font-size.rem_values`
- [ ] `css.properties.text-decoration.shorthand`
- [x] `html.elements.input.input-range`
- [x] `html.elements.script.integrity`
- [x] `html.elements.source.sizes`
- [x] `html.elements.source.srcset`
- [ ] `webextensions.api.events.Event`

Note: many of these features have more than support statement with a `partial_implementation` and no note.

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates the schema to require notes when `partial_implementation` is true.  This PR will FAIL for the time being as we have conflicting data.  Fixes #4162.

### CODE REVIEW

**Review by foolip — COMMENTED** [review]
Looks good, but do docs also need updating? And how much data needs updating before this could be landed?

**Comment by queengooborg** [comment]
The docs are good, this linter actually [enforces the existing guideline](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#partial_implementation-requires-a-note)!

**Comment by foolip** [comment]
I think the paragraph starting with "For historical reasons, some support statements have the flag set to true without a note" should  be removed in this PR too.

**Comment by foolip** [comment]
Also, if the lint already enforces this, why doesn't it fail for the cases the schema now fails on?

**Comment by queengooborg** [comment]
Sorry, there's a small detail in the wording (I tweaked it to provide slightly better clarity).  It isn't enforced until this PR lands.

**Comment by foolip** [comment]
Aha. I was thinking of the lint as the manually written rules, not the schema.

**Comment by foolip** [comment]
Alright, this looks good now, just need to make it pass before being able to land :)

**Pull request merged**
