### PR TITLE
add data for Sec-CH-Prefers-Reduced-Motion header

### PR DESCRIPTION
**Pull request by chrisdavidmills**
#### Summary

This PR adds BCD for the `Sec-CH-Prefers-Reduced-Motion` header; see my research document for more details: https://docs.google.com/document/d/1ENCgZ66Jsf40iMK1yatqQLeEHu9NC07Fhd6tKlgj_Bs/edit

#### Test results and supporting details

I tested a demo in multiple browsers; only supported in Chrome at the moment.

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
Non-owner LGTM

(I specified the header, but don't have approval rights here.)

**Comment by chrisdavidmills** [comment]
@hamishwillee have you got the permissions to approve and merge this?

**Review by queengooborg — APPROVED** [review]
I do!  ;P

**Comment by hamishwillee** [comment]
@chrisdavidmills FYI I work MDN Mon, Tues, Friday. I do have rights to merge here - they magically appeared a few days ago. I get most of my reviews from @queengooborg though, and if you want it done right, that's who to ask :-)

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills FYI I work MDN Mon, Tues, Friday. I do have rights to merge here - they magically appeared a few days ago. I get most of my reviews from @queengooborg though, and if you want it done right, that's who to ask :-)

Good to know! I work on MDN Mon-Wed, good to see that we have a decent bit of crossover time.

**Pull request merged**
