### PR TITLE
test(versions): Fix dependency on whole project

### PR DESCRIPTION
**Pull request by ExE-Boss**
Previously, `test-versions` would load the whole project, which would cause issues like https://github.com/mdn/browser-compat-data/issues/2330 when syntax errors were present.

This makes `test-versions` only depend on the `browsers` directory containing syntactically correct JSON.

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
I wanted to look into this a little bit more, however based upon the latest master at the time of this writing, I have not been able to reproduce the issue.  From what I can tell, this issue has already been fixed, particularly by #2338.

I don't want to just flat-out close this PR, though, if it serves an additional purpose aside from fixing #2330.  Can you comment?

**Comment by ExE-Boss** [comment]
It&nbsp;makes loading the&nbsp;tests faster, as&nbsp;currently, all data files and directories are&nbsp;parsed and loaded twice, first by&nbsp;the&nbsp;`index.js` loader and second by&nbsp;the&nbsp;tests.

**Comment by vinyldarkscratch** [comment]
It looks like it does give it a little bit of a performance improvement when running the tests:

```
$ time npm run lint

master: npm run lint  4.64s user 0.49s system 122% cpu 4.201 total
pr:     npm run lint  4.26s user 0.49s system 116% cpu 4.062 total
```

It doesn't seem to be causing issues with accessing the data either, luckily.  So, I think this PR's alright!  Since my level of access prevents me from merging infrastructure updates, I'll leave the final say to @Elchi3.  :wink:

**Comment by Elchi3** [comment]
Not still not quite sure I understand what this fixes instead of performance maybe?

Not a big fan of utils files and also not a big fan of having more files in the root directory. Do we really need this out of the index.js file? If so, should we rather move it to scripts/loader.js?
And then we could test the loader in tests/test-loader.js?

**Comment by ExE-Boss** [comment]
This makes it so that the whole BCD data directory structure is only walked once during testing, which improves performance, especially on HDDs.

**Comment by vinyldarkscratch** [comment]
It's been a little over a year since this PR was opened, and we haven't really progressed with it since about a half a year ago, or even really discussed it.  Although it does slightly improve performance, I'd say that it introduces lots of other changes as well (such as TypeScript/IntelliSense stuff), and the performance increase would only be for contributors during tests, not really for users working with the data.  Especially considering the fact that this introduces a massive infrastructure change, I'd say this is not a route we're interested in exploring at the moment.

I'm going to mark this PR for closure in a week.

**Pull request closed without merging**
