### PR TITLE
Indicate that SharedArrayBuffer was reenabled on Chrome.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by connorshea** [comment]
Source: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/wvV42Hxct3g

Also, should this include Atomics? They were marked as disabled for the same reason in #789, and the blink-dev mailing list message mentions Atomics.

**Comment by jpmedley** [comment]
@connorshea I don't think so, but I'm double-checking with our engineers. I'll get back to you.

**Comment by chicoxyzzy** [comment]
@jpmedley it's better to indicate which versions had features by using ranges in json 
https://github.com/mdn/browser-compat-data/issues/2569#issuecomment-411469480

**Comment by jpmedley** [comment]
@Elchi3 I'm guessing ranges were designed with deprecations and prefix removals in mind. This situation is add > remove > add again. Is this an edge case that the macro will be fail to render properly?

**Comment by Elchi3** [comment]
It should render properly. Firefox is in the same boat here and uses an array in the json data already. See Firefox ranges rendered here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#Browser_compatibility

**Comment by chicoxyzzy** [comment]
Awesome! Thank you @jpmedley

**Pull request merged**
