### PR TITLE
Set deprecated of getCoalescedEvents to false

### PR DESCRIPTION
**Pull request by NavidZ**

### CODE REVIEW

**Comment by NavidZ** [comment]
@chrisdavidmills any reason you changed this feature back to deprecated? I don't think Firefox ever shipped this. Did it? We are still working on standardization of rAF aligning to make this API more clear in terms of the definition.

**Comment by chrisdavidmills** [comment]
I was making a load of changes to PointerEvents docs to try to bring them up to date, and the reference page has it listed as deprecated; see https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents

If this is wrong, I am happy to remove it and merge your PR.

**Comment by chrisdavidmills** [comment]
Ah, the reason I reverted your change is that you had removed the page sidebar at the same time. I didn't realise you were also fixing something. Sorry about that.

So I've now removed the deprecated banner from the page, and merged your PR. Thanks for the contribution!

**Comment by NavidZ** [comment]
I guess I was just copy pasting from some other feature page.
@chrisdavidmills Also can you mark that as experimental. This feature is not yet in the main track of pointerevent spec and FF hasn't shipped it either.

**Comment by chrisdavidmills** [comment]
> Also can you mark that as experimental.

OK, done.

**Pull request merged**
