### PR TITLE
Bug1067769 KeyframeEffect.target on Firefox

### PR DESCRIPTION
**Pull request by a2sheppy**
This was added to Firefox in version 49.

### CODE REVIEW

**Comment by birtles** [comment]
We're not shipping yet though. Probably in 63.

**Comment by a2sheppy** [comment]
@birtles Is it in but preffed off in 62, or has it been removed?

**Comment by birtles** [comment]
Yes, it's preffed off (like most of the API).

We've agreed with Google on a couple of occasions (both with their animation folk and MDN folk) not to mark features in this API as supported if they are preffed off in release, partly because a lot of these features landed in a fairly incomplete state behind a flags and have changed a few times since so it's hard to say when it was supported..

**Comment by a2sheppy** [comment]
Good to know. I had not heard about that agreement, and this issue was on our changelist for Firefox 62, so it got done. I will withdraw this patch.

**Comment by birtles** [comment]
Yes, sorry about that. The animation folk involved in that discussion have since moved on so we can revisit that approach if need be.

**Pull request closed without merging**
