### PR TITLE
Add FileSystem*Handle APIs

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR adds data for three file system handler APIs: FileSystemHandle, FileSystemDirectoryHandle, and FileSystemFileHandle.  Versions were determined using the mdn-bcd-collector project, along with a slight bit of manual testing in Chrome Android, WebView, and Opera.

These are a part of a WICG draft:
https://wicg.github.io/file-system-access/#api-filesystemhandle
https://wicg.github.io/file-system-access/#api-filesystemfilehandle
https://wicg.github.io/file-system-access/#api-filesystemdirectoryhandle

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Ping @jpmedley

**Review by jpmedley — APPROVED** [review]

**Comment by ddbeck** [comment]
@vinyldarkscratch The linked spec has the unofficial watermark and some text about not being "W3C Standards Track". Any chance of a follow-up PR to flip the standard_track values?

**Comment by vinyldarkscratch** [comment]
Sure thing, apologies for that!  Should it be marked as "experimental" as well since it's only supported in Blink?

**Comment by ddbeck** [comment]
Yes, please! Single-implementation should be experimental (unless it's over two years old)—I'm aiming to write up guidelines for that next week.

**Pull request merged**
