### PR TITLE
making some updates to Pointer Events API BCD

### PR DESCRIPTION
**Pull request by chrisdavidmills**
This one was a bit confusing. I had a card to update pointer events information in this sprint (see https://trello.com/c/tOxWV0Jo/48-pointer-events for all the related bugs), but it turned out that we had enabled Pointer Events in Fx59 on desktop, and still haven't on Android. So...I did some testing of my own, and checked what we had against the spec. 

The result was adding a page for [Element.hasPointerCapture()](https://developer.mozilla.org/en-US/docs/Web/API/Element/hasPointerCapture), removing Element.ongotpointercapture and Element.onlostpointercapture because they had been moved to the [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers) interface a long time ago, marking PointerEvent.getCoalescedEvents() as deprecated because it has been removed from the spec and Firefox but I don't know its status in other browsers, and making these updates to the BCD.

### CODE REVIEW

**Comment by Elchi3** [comment]
In addition to all the confusion you outline above, this now also needs a rebase :-) 
I will try to review this, once rebased.

**Comment by chrisdavidmills** [comment]
OK, I fixed the merge conflict. How do I rebase it? I've tried a couple of things, but they only seem to have made things worse. I don't know what I need to do to rebase this successfully.

**Comment by Elchi3** [comment]
All good now :)

**Comment by chrisdavidmills** [comment]
phew ;-)

**Pull request merged**
