### PR TITLE
Update SpeechSynthesis data for Firefox Android

### PR DESCRIPTION
**Pull request by Elchi3**
See
https://bugzilla.mozilla.org/show_bug.cgi?id=1184142
https://bugzilla.mozilla.org/show_bug.cgi?id=1463496

### CODE REVIEW

**Comment by wbamberg** [comment]
This looks great, the only question/suggestion I have is whether we should explicitly "close" version ranges, by doing something like this:

```
"firefox_android": [
  {
    "version_added": "62"
  },
  {
    "version_added": "61",
    "version_removed": "61",
    "flags": [
      {
        "type": "preference",
        "name": "media.webspeech.synth.enabled",
        "value_to_set": "true"
      }
    ]
  }
]
```

This gives us something like this:

screen shot 2018-05-24 at 9 12 58 am

rather than:

screen shot 2018-05-24 at 9 13 08 am

I think the former is clearer, that this condition does not apply any more. What do you think?
(in general I'm starting to feel that explicitly closing version ranges is good practice)

**Comment by Elchi3** [comment]
I think in the past, we've closed the range at the point the preference was removed (now there preference is still there, but enabled by default). So, say Firefox 70 removes the preference entirely, the pref range will be 61 - 70. I'm not sure if that is useful, though. I generally agree with you to close version ranges when possible.

**Comment by wbamberg** [comment]
> I think in the past, we've closed the range at the point the preference was removed (now there preference is still there, but enabled by default).

To me the important consideration for a web developer is not whether there is a pref, but what its default value is. It's important to distinguish the case in 61, where it's effectively unsupported, from 62, where it's effectively supported.

This language:

> From version 61: this feature is behind the media.webspeech.synth.enabled preference (needs to be set to true). To change preferences in Firefox, visit about:config.

...definitely reads to me as if the pref is off by default: *"needs to be set"*, and there is nothing explicit in the table about the pref's default being flipped.

**Comment by Elchi3** [comment]
It would be "version_removed: 62", though, right?

**Comment by wbamberg** [comment]
Yes. Sorry!

**Pull request merged**
