### PR TITLE
Add workflow to catch for potential duplicates

### PR DESCRIPTION
**Pull request by queengooborg**
This PR adds a GitHub Actions workflow to alert for potential duplicate issues.

### CODE REVIEW

**Comment by queengooborg** [comment]
I tested this out and it's working great!  Only notifying the user once when merge conflicts are first found, and accurately adding or removing the label!

**Comment by Rumyra** [comment]
Awesome I'm excited to see what happens with this one & if it ends up being useful we can move it to mdn/workflows. Ping @schalkneethling to take a look 👍

**Comment by schalkneethling** [comment]
Indeed! If this works well, then please open a PR to add it to mdn/workflows @queengooborg. Thanks!

**Comment by Rumyra** [comment]
Are we good to go with merging?

**Comment by schalkneethling** [comment]
> Are we good to go with merging?

I believe so.

**Comment by Rumyra** [comment]
It's done!

**Pull request merged**
