### PR TITLE
Bug 903372: Remove support for xml:base

### PR DESCRIPTION
**Pull request by ExE-Boss**
See [bug&nbsp;903372](https://bugzilla.mozilla.org/show_bug.cgi?id=903372) for details.

review?(@Elchi3)
needinfo?(@jpmedley): In which version of **Google&nbsp;Chrome** was this removed ([Chromium&nbsp;bug&nbsp;341854](https://bugs.chromium.org/p/chromium/issues/detail?id=341854))?

### CODE REVIEW

**Comment by ddbeck** [comment]
I think this needs @Elchi3's review, therefore it's probably going to wait until he returns from holiday in the new year. Thanks for your patience on this one, @ExE-Boss!

**Comment by jpmedley** [comment]
@ExE-Boss It looks like Chrome 45. That's an educated guess meaning the next nearest Chrome dev feature freeze was for Chrome 45. For various reasons I'm unable to locate a commit hash for that change, which would let me look up version number.

**Comment by Elchi3** [comment]
How many more XML features are we expecting to add? Is it really worth it?

**Comment by ExE-Boss** [comment]
There’s a&nbsp;few more attributes in&nbsp;the&nbsp;`xml:`&nbsp;namespace, which we&nbsp;might end&nbsp;up&nbsp;documenting.

**Comment by chrisdavidmills** [comment]
I don't see XML as ever being a priority for the MDN team to invest time in, unless something changes on the web dramatically. Let's not do this.

**Comment by ExE-Boss** [comment]
I went and created https://developer.mozilla.org/en-US/docs/Web/XML and added XML to the missing places, but I see that Chris hasn’t been very keen to do this. 😔

**Comment by Elchi3** [comment]
> There’s a few more attributes in the xml: namespace, which we might end up documenting.

I can understand Chris, also because your answer isn't very detailed and so my impression is as well that XML is just not relevant for MDN and BCD. 
There is xml:lang and xml:space afaik. What other XML features exist that are relevant to web developers and that we should a) document and b) have compat data about? How much are they being used in the wild?

**Pull request closed without merging**
