### PR TITLE
Updates for MediaSession API - Firefox 76

### PR DESCRIPTION
**Pull request by a2sheppy**
Firefox 76 adds support for several new action types;
as part of documenting this, I'm adding the separate
JSON file for the `MediaSessionAction` enum. This
adds the newly-implemented `seekforward` and `seekbackward`
actions for Firefox, and adds the `skipad` and `seekto` actions
that were also missing (but not yet in Firefox).

Also added is the `MediaSessionActionDetails` dictionary,
which is used to provide data about the action.

### Chrome
* `seekto`
  * Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=977375
  * [Commit maps to version 77](https://storage.googleapis.com/chromium-find-releases-static/f23.html#f230e6257d8bd8637314b5dd4d7acb4ae997f604)
* `skipad`
  * Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=910436
  * [Commit maps to version 73](https://storage.googleapis.com/chromium-find-releases-static/b02.html#b0281b1250cdec351658e9bf07dd5f5d3331ef91)

### Firefox
* Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1580623

### CODE REVIEW

**Comment by Elchi3** [comment]
Hey @a2sheppy, this PR has not seen any reviews, because it is super hard to review the different stories here. Overall, the PR adds 1k of new lines, which isn't a problem per se, but it refers to so many bugs and basically munches a lot of MediaSession updates into one big PR. I'm trying to understand all the things that are going on here, but you might have to split this up to make it reviewable.

**Comment by Elchi3** [comment]
The first story seems to be the one about MediaSessionAction that you've described above. The summary is basically:
nexttrack - Fx 71, Chrome 73
pause  - Fx 71, Chrome 73
play  - Fx 71, Chrome 73
previoustrack  - Fx 71, Chrome 73
seekbackward  - Fx 76, Chrome 73
seekforward - Fx 76, Chrome 73
seekto - Fx false, Chrome 77
skipad - Fx false, Chrome 73
stop  - Fx 71, Chrome 73

**Comment by Elchi3** [comment]
The second story is about MediaPositionState. It comes with:
MediaSession.setPositionState - Fx 76 (you didn't mark it behind a pref, but I guess it should be)
MediaPositionState - Fx 76, Chrome 78 (mdn_url is wrong here)
MediaPositionState.duration - Fx 76, Chrome 78
MediaPositionState. playbackRate - Fx 76, Chrome 78
MediaPositionState. position - Fx 76, Chrome 78

The Firefox bug for this stuff seems to be https://bugzilla.mozilla.org/show_bug.cgi?id=1582509

**Comment by Elchi3** [comment]
The third story is about MediaSession.playbackState

It is marked as Fx 76 (and should probably also be marked behind a pref, right?)

The Firefox bug for this is https://bugzilla.mozilla.org/show_bug.cgi?id=1582508

**Comment by Elchi3** [comment]
The forth story is about MediaSessionActionDetails. 

MediaSessionActionDetails - Fx 71
MediaSessionActionDetails.action  - Fx 71
fastSeek- Fx false
seekOffset - Fx 76
seekTime - Fx false 

Unclear where this information is from. I don't see any bug provided for this. Maybe I'm just not seeing it in all the commits.

**Comment by Elchi3** [comment]
So, it seems this could have been 4 PRs instead. I would appreciate splitting this up and also provide more context for the reviewer. Thank you!

**Comment by a2sheppy** [comment]
I did them all as one because trying to do a set of updates that overlap as separate PRs is a pain in the ass with a lot of having to merge and rebase and actually I have no idea how to do that. So I did them all at once. I'll have to do some research to figure out how to bust this up into multiple PRs, but honestly, I'm busy enough it could be several weeks before I get to it.

As for the MDN links that are 404, no, I don't intend to write those pages anytime soon. They're pages that someone needs to write but they are not part of my current workload. It's stuff that should have been done when the API was first documented but was left out for some reason. I added to the data because they should already have been there and they're used in tandem with the stuff I was adding already.

**Comment by Elchi3** [comment]
>  but honestly, I'm busy enough it could be several weeks before I get to it.

Okay, then let's try to further review this in PR. Can you make the changes I requested in my comments above? Have I correctly understood all the stories that make up this PR? Do my suggestions make sense to you?

Thank you for understanding the reviewer's perspective and the time it takes to provide review as well.

> As for the MDN links that are 404, no, I don't intend to write those pages anytime soon. They're pages that someone needs to write but they are not part of my current workload.

Do you intend to write a content issue to capture this work that left to be done?

**Comment by ddbeck** [comment]
It's been nearly a month without action on this PR, so I'm going to close it as abandoned. I've opened #6265 and #6266 to capture some of the information here.

**Comment by a2sheppy** [comment]
I need to go back and try to figure out how to get all this work into place. I had said that it would be several weeks before I got back to this, and the issue then got closed before those several weeks had elapsed, so I lost track of the fact that this needed doing, since it vanished off my list upon being closed. I have new changes I need to make to the files that should have been in place all ready through this issue, too. Good times... good times....

**Comment by a2sheppy** [comment]
FWIW, I don't think it's fair to discard a PR for squeezing too many updates when all I did was add the BCD data for APIs we missed previously. Would a PR be rejected for adding all the data for a new API? If so, I've been doing a lot of things wrong. :)

**Pull request closed without merging**
