### PR TITLE
API: Mirror Chrome Desktop onto Chromium browsers when null

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR is created by a simple script that mirrors the compatibility data of all APIs from Chrome to all other Chromium-based browsers (Chrome Android, Opera, Opera Android, Samsung Internet, and Webview) when they are set to "null".  This should help reduce inconsistencies in the browser data.

### CODE REVIEW

**Comment by ddbeck** [comment]
@Elchi3 any thoughts on this? My hunch is that this sort of mirroring should probably be done explicitly (e.g., with pointer proposals like #1681 and #1799), but I'm not sure if you want to wait for the capability or if you even intend to act on those proposals

**Comment by Elchi3** [comment]
I think this is too gigantic and I haven't looked into it in details yet. Deriving versions from Chrome for other Chromium-based browsers is certainly a valid approach, but I'm unsure how we want to vet this exactly yet. I think we can leave this here for us to look at as we are working on similar mass updates first.  Also, I'd like to get to https://github.com/mdn/browser-compat-data/issues/3264 so that we first have engine versions added to maybe prevent mistakes with this kind of mapping.

The feature imports / json pointer PRs you've mentioned should probably be closed. I think they are adding too much complexity and would likely prevent the scripts and mass-updates that @foolip and @vinyldarkscratch have worked on from being useful.

**Comment by ddbeck** [comment]
> The feature imports / json pointer PRs you've mentioned should probably be closed. I think they are adding too much complexity and would likely prevent the scripts and mass-updates that @foolip and @vinyldarkscratch have worked on from being useful.

That's completely reasonable and I support that position. Given that, would you do the honors of closing #1681, #813, #1799, and #2761? I think it would be good to explicitly say that bulk updates are our preferred approach right now and that we're not currently considering deduplicating version data.

**Comment by Elchi3** [comment]
Thanks Daniel, I went ahead I closed these to no longer set any expectations there.

**Comment by vinyldarkscratch** [comment]
Given that Opera Android versions were merged in as well, this PR needs to be recreated.  I’m going to separate this into smaller PRs for each Chromium browser, making the review process easier.  ;)

**Pull request closed without merging**
