### PR TITLE
Fix descriptions of entries based upon data guidelines

### PR DESCRIPTION
**Pull request by gsouquet**
Hi 👋 ,

I noticed #4725 yesterday and decided to give it a quick go. I read all the [data guidelines](https://github.com/mdn/browser-compat-data/blob/master/docs/data-guidelines.md) and saw that   
 the first 4 items in the list were fairly easily automatable.

This PR is my attempt to create some of those linting rules. They have definitely helped me catch quite a few inconsistencies in the compat data that I have also fixed as part of this pull request.

Keen to hear your thoughts on this.
I was looking on how to unit test those functions I have created but could not see any examples in the repo. Could someone point me on the right direction here?

Thank you

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
Hey @gsouquet, thanks for tackling this!  I briefly skimmed over the changes, and due to the number of files affected, I believe this would classify as a bulk update.  As such, I believe this should follow the [migration](https://github.com/mdn/browser-compat-data/blob/master/docs/migrations.md) process we've recently created.  Step 1 is already taken care of by #4725, leaving steps 2, 3, and 4 for us.

It looks like the data changes may have been manual, so I'm thinking we can skip step 2 and simply separate the changes as step 3.  We would then have the linter as its own PR in step 4, to ensure PRs do not cause any regressions.  Does that sound reasonable?

**Comment by gsouquet** [comment]
The changes were manual indeed. Happy to create a script that will migrate all those entries if needed.

I will remove all the linting code from that PR, keeping only the data changes, and create a separate PR containing the new linting rules in a separate PR. However which branch should that second PR point to? Because at the moment if I point it to `master` it will fail as there are some incorrect data in the repo.

**Comment by vinyldarkscratch** [comment]
Thank you for separating the changes!  The new PR should point to `master` as well -- the linter will fail as stated, but this will show us it's working as expected.  :wink:

**Comment by gsouquet** [comment]
All done, feel free to give this PR and #4791 a review

Thank you very much for your help @vinyldarkscratch , much appreciated 👍

**Pull request merged**
