### PR TITLE
Remove the item* microdata attributes (not supported by browsers)

### PR DESCRIPTION
**Pull request by foolip**
The API reflecting these attributes was removed already:
https://github.com/mdn/browser-compat-data/pull/16226

The attributes have never had any effect beyond the API for accessing
them, so it's fair to say these attributes are not supported.

A search for "itemscope" in the source of Chromium, Gecko and WebKit
finds only old tests and similar, no code handling the attribute.

MDN content update: https://github.com/mdn/content/pull/32926

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Should we remove these completely then? Seems like they meet the criteria: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features

**Comment by foolip** [comment]
@Elchi3 they are documented on MDN and I think that makes sense since they're used by https://schema.org/docs/gs.html and probably other things. Should content be updated to just not have a BCD key then?

**Comment by Elchi3** [comment]
> Should content be updated to just not have a BCD key then?

hm, I guess I would remove the compat tables on MDN and leave a note there saying that browsers do not necessarily need to support this. I mean so that absent a compat table readers are not wondering about the compat story.

**Comment by foolip** [comment]
Just removing the compat tables sounds good to me. Do you want me to do that before we move forward with this PR then?

**Comment by Elchi3** [comment]
That would be great, yes! Thank you!

**Comment by Elchi3** [comment]
Yes, please remove them in this PR.

And as Will says in https://github.com/mdn/content/pull/32926#pullrequestreview-1975208128 use mdn/content's front-matter yaml to provide the spec url for these features in content directly then.

**Comment by foolip** [comment]
https://github.com/mdn/content/pull/32926 is merged now, so this should be good to go too.

**Review by Elchi3 — APPROVED** [review]
Thank you! 👍

**Pull request merged**
