### PR TITLE
Add missing features for appearance CSS property

### PR DESCRIPTION
**Pull request by queengooborg**
This PR adds the missing features of the `appearance` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.9.0).

_Check out the [collector's guide on how to review this PR](https://github.com/openwebdocs/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/appearance

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
This will break references made in https://github.com/web-platform-dx/web-features/pull/634 cc @foolip 

I think we can follow up with a fix to web-features (or we use tags, or we do both).

**Comment by queengooborg** [comment]
The idea of using web-features tags is to eliminate the need for WebDX to define all the BCD keys manually, is that correct?  Tags sounds like the right call here!

**Comment by Elchi3** [comment]
> The idea of using web-features tags is to eliminate the need for WebDX to define all the BCD keys manually, is that correct?

Yes, that was the whole reason I wanted tags! :)

**Comment by foolip** [comment]
> This will break references made in [web-platform-dx/web-features#634](https://github.com/web-platform-dx/web-features/pull/634) cc @foolip
> 
> I think we can follow up with a fix to web-features (or we use tags, or we do both).

Feel free to break web-features references. They'll all come to light when we compute Baseline status from BCD, and I can fix things then. If you _want_ to fix things proactively that's nice, but I don't want web-features to slow down BCD maintenance.

**Comment by queengooborg** [comment]
I've added a tag with the name matching the feature group, so that should help!

**Pull request merged**
