### PR TITLE
Update Edge support data based on MicrosoftEdge-Documentation

### PR DESCRIPTION
**Pull request by mdittmer**
These data constitute all data at
https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/blob/master/EdgeHTML/EdgeHTML.json
for all interface members where BCD *already* contains interface member data.

Data collected using script `edge-bcd.js`:

```js
const fs = require('fs');

const bcd = require('mdn-browser-compat-data');

const apis = JSON.parse(
  fs.readFileSync('MicrosoftEdge-Documentation/EdgeHTML/EdgeHTML.json'));

const ifaces = {};
for (const api of apis) {
  const name = api.api_name;
  const nameParts = api.api_name.split('.');
  const ifaceName = nameParts[0];
  const apiName = nameParts[1];

  let support;
  try {
    support = (
      bcd.javascript.builtins[ifaceName] &&
        bcd.javascript.builtins[ifaceName][apiName] &&
        bcd.javascript.builtins[ifaceName][apiName].__compat.support
    ) || bcd.api[ifaceName][apiName].__compat.support;
    if (!support) {
      console.warn(`No API data for ${name}`);
      continue;
    }
  } catch (err) {
    console.warn(`No API data for ${name}`);
    continue;
  }

  if (!api.version_added) {
    console.warn(`No Edge version_added for ${name}`);
    continue;
  }

  let edgeSupport = support.edge = support.edge || {};
  if (Array.isArray(edgeSupport)) {
    console.warn(`Found unsupported {support: edge: [array]}`);
    continue;
  }
  ifaces[ifaceName] = true;
  edgeSupport.version_added = api.version_added;
}

const ifaceNames = Object.keys(ifaces);
for (const ifaceName of ifaceNames) {
  const builtinPath = `${__dirname}/browser-compat-data/javascript/builtins/${ifaceName}.json`;
  const apiPath = `${__dirname}/browser-compat-data/api/${ifaceName}.json`;
  const isBuiltin = fs.existsSync(builtinPath);
  const isApi = fs.existsSync(apiPath);
  if (!isBuiltin && !isApi) {
    console.warn(`Failed to find interface file for ${ifaceName}`);
    continue;
  }
  const path = isBuiltin ? builtinPath : apiPath;
  let data = isBuiltin ?
        {javascript: {builtins: {[ifaceName]: bcd.javascript.builtins[ifaceName]}}} :
      {api: {[ifaceName]: bcd.api[ifaceName]}};
  fs.writeFileSync(path, JSON.stringify(data, null, 2) + '\n');
}

console.info('DONE!');
```

... with commands:

```bash
git clone https://github.com/mdn/browser-compat-data.git
git clone https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation.git
git init
npm install mdn-browser-compat-data
cd node_modules
rm -rf mdn-browser-compat-data
ln -s ../browser-compat-data mdn-browser-compat-data
cd ..
node edge-bcd.js
```

### CODE REVIEW

**Comment by Elchi3** [comment]
Hey @erikadoyle @mattwojo, can you take a look at this?

**Comment by patrickkettner** [comment]
LGTM!

**Comment by erikadoyle** [comment]
LGTM too. Thanks so much @mdittmer!

**Comment by mattwojo** [comment]
Thank you @mdittmer !

**Pull request merged**
