### PR TITLE
Delete api/DOMHighResTimestamp.json

### PR DESCRIPTION
**Pull request by bershanskiy**
This interface is officially called DOMHighResTimeStamp.

Specification:
https://www.w3.org/TR/hr-time-2/#dom-domhighrestimestamp
Firefox source:
https://github.com/mozilla/gecko-dev/blob/master/dom/webidl/Performance.webidl
WebKit source:
https://github.com/WebKit/WebKit/blob/main/Source/WebCore/page/PerformanceResourceTiming.idl
Chromium:
https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/timing/dom_high_res_time_stamp.idl

Edit: removed unnecessary reference to another bug.

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by foolip** [comment]
This is a curious case. I agree with matching the spec, but I wonder if this should really be in MDN and BCD.

This is a typedef (alias) for double, so it's a bit like saying that JS Number is supported, which it was since before the typedef was conceived of.

@ddbeck @Elchi3 like mixins and partials this is a spec writer convenience, should we remove it?

**Comment by Elchi3** [comment]
Yeah, not sure types need compat data. It seems similar to what we said about constants: usually, there is no compat story to tell. The MDN page seems worthwhile so that people know what this type is, though. However, it could be a glossary page or something more light.

**Comment by foolip** [comment]
Constants are at least visible, `NodeFilter.SHOW_ATTRIBUTE` can be inspected (the value 2) and used as an argument for `document.createNodeIterator()`. By contrast, the string "DOMHighResTimeStamp" would never show up in JavaScript.

But that's all good, if constants were obscure enough to omit then typedefs must be too. I'll file an issue.

**Comment by bershanskiy** [comment]
Given discussion above, deleting this file maks more sense.

**Review by ddbeck — APPROVED** [review]
Thank you! 🎉

**Pull request merged**
