### PR TITLE
feat(css): Update Firefox support for CSS trigonometric functions

### PR DESCRIPTION
**Pull request by ramiy**
#### Summary
Firefox 105 add full support for CSS trigonometric functions.

#### Test results and supporting details
Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1774589#c13

#### Related issues
Related: #17404

### CODE REVIEW

**Comment by queengooborg** [comment]
FYI, we revised our flags policy a while back to simply remove data for flags when the feature has been released in a stable version.  Let's remove the flag data from the statements!

**Comment by ramiy** [comment]
@queengooborg What is the policy for future releases? Firefox 105 scheduled to be released in a month, on September 20, 2022. Firefox 103 was released a month ago, on July 26, 2022. This is why the flag data is still relevant.

**Comment by evilpie** [comment]
These functions will not ship in Firefox 105. They are still Nightly only: https://hg.mozilla.org/integration/autoland/rev/02eccb000404#l1.13

**Comment by queengooborg** [comment]
Ah, thanks for the info @evilpie!  So we should probably avoid making these changes until they will be available in a stable build?

**Comment by ramiy** [comment]
> These functions will not ship in Firefox 105. They are still Nightly only: https://hg.mozilla.org/integration/autoland/rev/02eccb000404#l1.13

@queengooborg @evilpie
see https://github.com/mdn/content/issues/19832#issuecomment-1238175572

**Comment by Rumyra** [comment]
See https://github.com/mdn/content/issues/19832#issuecomment-1239501779 also

**Comment by ramiy** [comment]
Finished testing trig functions with Firefox 105. They did not ship in this release. I've updated the PR to reflect this.

@queengooborg please review and merge.

**Review by queengooborg — APPROVED** [review]

**Pull request merged**
