### PR TITLE
Refactor index.js to allow for better error messages

### PR DESCRIPTION
**Pull request by foolip**
In order to print a useful error message, we need to know both which
file is being loaded, and the JSON path at which the problem occurred.

As a not-strictly-needed improvement, change how directories are
traversed to only create a single result object and extend that with
each file in order, avoiding intermediate result objects in the previous
recursive load() calls.

Fixes https://github.com/mdn/browser-compat-data/issues/10734.

### CODE REVIEW

**Comment by foolip** [comment]
This sort of works if you'd like to review, @vinyldarkscratch, but I'm leaving it as draft.

The big remaining question is that this changes the order of things in the resulting JSON, despite my attempt to traverse directories in the same order. @ddbeck do you think we should be concerned about the key order in the JSON? I'd like to suggest that we actually sort all keys alphabetically, like what `sort_keys=True` does in Python. Then it would be easier to tell that this change doesn't have any impact on the result.

**Comment by ddbeck** [comment]
Oh, interesting! My inclination is to not mess with the order (I know nobody should _rely_ on the order, and yet…), but I don't know that it's a real difference.

I started down a different path to fix this yesterday: https://github.com/ddbeck/browser-compat-data/compare/main...ddbeck:friendlier-extend-errors. My version breaks the tests (I guess because I've created a circular dependency) and I wasn't sure how to fix that just yet.

**Comment by foolip** [comment]
So the challenge in not messing with the order is that it depends on details about how the current implementation traverses, and it's not really a sensible order to my eye. For example, all mixin data will end up appended as the last keys of their target interface.

But I don't feel strongly, I might abandon this PR if the error messages are improved in some other way.

**Comment by q805** [comment]
可拉取請求合併嗎？謝謝

**Pull request closed without merging**
