### PR TITLE
Update Chrome/Firefox support for ReadableStream in Request Body

### PR DESCRIPTION
**Pull request by AnthumChris**
To the best of my knowledge, Chrome and Firefox do not yet support sending `ReadableStream` content in `Request` body during HTTP requests.  I think we should remove the positive indicators until this is fully supported.  Tested with Chrome 67 and FF 59.

```js
// String test - passes
post('hello');

// ReadableStream test - fails
post(new ReadableStream({
  start(controller) {
    controller.enqueue(new TextEncoder().encode('hello'));
    controller.close();
  }
}));

// Server should respond with postBody text value, indicating it was sent and received.
function post(postBody) {
  fetch('https://dev.anthum.com/post-test/', {
    body: postBody,
    headers: {'content-type': 'text/plain'},
    method: 'POST'
  })
  .then(response => response.text())
  .then(data => console.log(data))
  .catch(error => console.error(error));
}
```

### CODE REVIEW

**Comment by evilpie** [comment]
Did you tests with preferences enabled in Firefox?

**Comment by AnthumChris** [comment]
@evilpie Yes, the preferences were enabled.  Firefox sends string "[object ReadableStream]".

**Comment by Elchi3** [comment]
It's not clear to me how the two blocks should look like. @chrisdavidmills can you post the JSON you'd like to see here, so that I can amend this PR? (or open a new PR to get this right and I'll close this one.) Thanks!

**Comment by chrisdavidmills** [comment]
Something like this?

```
"reponse_body_readablestream": {
  "__compat": {
    "description": "Consume response body as a <code>ReadableStream</code>",
    "support": {
      "chrome": {
        "version_added": "43"
      },
      "chrome_android": {
        "version_added": "43"
      },
      "edge": {
        "version_added": null
      },
      "edge_mobile": {
        "version_added": null
      },
      "firefox": {
        "version_added": true,
        "flags": [
          {
            "type": "preference",
            "name": "dom.streams.enabled"
          },
          {
            "type": "preference",
            "name": "javascript.options.streams"
          }
        ]
      },
      "firefox_android": {
        "version_added": true,
        "flags": [
          {
            "type": "preference",
            "name": "dom.streams.enabled"
          },
          {
            "type": "preference",
            "name": "javascript.options.streams"
          }
        ]
      },
      "ie": {
        "version_added": null
      },
      "opera": {
        "version_added": null
      },
      "opera_android": {
        "version_added": null
      },
      "safari": {
        "version_added": false
      },
      "safari_ios": {
        "version_added": "10.3"
      },
      "webview_android": {
        "version_added": "43"
      }
    }
  }
},
"readablestream_request_body": {
  "__compat": {
    "description": "Send <code>ReadableStream</code> in request body",
    "support": {
      "chrome": {
        "version_added": false
      },
      "chrome_android": {
        "version_added": false
      },
      "edge": {
        "version_added": null
      },
      "edge_mobile": {
        "version_added": null
      },
      "firefox": {
        "version_added": false
      },
      "firefox_android": {
        "version_added": false
      },
      "ie": {
        "version_added": null
      },
      "opera": {
        "version_added": null
      },
      "opera_android": {
        "version_added": null
      },
      "safari": {
        "version_added": false
      },
      "safari_ios": {
        "version_added": false
      },
      "webview_android": {
        "version_added": false
      }
    }
  }
}
```

**Comment by guest271314** [comment]
Related https://github.com/whatwg/fetch/pull/425, https://github.com/whatwg/fetch/issues/439.

Technically a workaround is possible using `async/await` and passing `ReadableStream` to `Response` then calling `.text()` which reads the stream to completion.

**Pull request merged**
