### PR TITLE
Scripting api

### PR DESCRIPTION
**Pull request by rebloor**
#### Summary
This is the browser compatibility data for the Scripting API and an update to the Tabs API to indicate that executeScript, insertCSS, and removeCSS are not available in Manifest V3.

Supported versions for Safari to be confirmed.

Find compatibility data in support of  [Scripting API documentation #14725](https://github.com/mdn/content/pull/14725)

### CODE REVIEW

**Comment by queengooborg** [comment]
It looks like you accidentally included changes to `package-lock.json` in your PR, could you revert those real quick?

**Comment by rebloor** [comment]
>  It looks like you accidentally included changes to package-lock.json in your PR, could you revert those real quick?

Done?

**Comment by queengooborg** [comment]
Oops, looks like you deleted the entire file rather than perform a revert?

**Comment by rebloor** [comment]
@queengooborg thought I was deleting it from there commit, obviously not. Probably easier if I just re-create the PR, I'll do that later today.

**Pull request closed without merging**
