### PR TITLE
Add missing features for WebGL2RenderingContext API

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
This PR is a part of a project to add missing interfaces and interface features to BCD that are from an active spec (including WICG specs) and is supported in at least one browser.  This particular PR adds missing features, populating the results using data from the [mdn-bcd-collector](https://mdn-bcd-collector.appspot.com) project (v1.1.7), for the `WebGL2RenderingContext` API.

Spec: https://www.khronos.org/registry/webgl/specs/latest/2.0/

IDL: https://github.com/w3c/webref/blob/master/ed/idl/webgl2.idl

Tests Used: https://mdn-bcd-collector.appspot.com/tests/api/WebGL2RenderingContext

### CODE REVIEW

**Comment by Elchi3** [comment]
This adds all the features from the inherited WebGL 1 context, is that useful?

**Comment by vinyldarkscratch** [comment]
Yikes, I thought that I went through and removed the WebGL1 entries...  Let me revise this PR!

**Comment by Elchi3** [comment]
Can you elaborate what this PR does now?

I see it adds `bufferData` which MDN documents at https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData. Is this part of this PR because the signature changed in WebGL 2?

**Review by sideshowbarker — APPROVED** [review]

**Comment by Elchi3** [comment]
Err, can we still talk about the WebGL 1 features this PR adds to the WebGL 2 context? (I don't see my question answered)

**Comment by sideshowbarker** [comment]
> Err, can we still talk about the WebGL 1 features this PR adds to the WebGL 2 context? (I don't see my question answered)

Sorry, my fault for having merged this prematurely.

**Comment by vinyldarkscratch** [comment]
What this PR does is add all of the missing features that are explicitly defined on this interface.  That includes any methods that have signature changes, such as `bufferData`.

**Comment by Elchi3** [comment]
> What this PR does is add all of the missing features that are explicitly defined on this interface. That includes any methods that have signature changes, such as `bufferData`.

Okay, but it is not added as such to BCD. I mean the data doesn't tell you about signature changes. You just see WebGL 1 methods in the WebGL 2 data without explanation. Further, https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/bufferData#Browser_compatibility already has the info in a separate row called "WebGL 2".

**Comment by vinyldarkscratch** [comment]
Ahhhh, gotcha, I hadn't seen those rows -- alright then, we should probably do a revert of this PR, probably?

**Comment by Elchi3** [comment]
Probably, although I'm not 100% sure what the best data structure is here. 
I just figured that WebGL 1 methods in the WebGL 2 data without explanation is not ideal.

**Pull request merged**
