### PR TITLE
Remove subfeatures for MathML attributes superscriptshift/subscriptshift

### PR DESCRIPTION
**Pull request by fred-wang**
#### Summary

The MathML attributes superscriptshift and subscriptshift
have been removed from Firefox 71 and never been
implemented in any other browser. Remove them
per the guidelines [1].

[1] https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features

#### Test results and supporting details

https://bugzilla.mozilla.org/show_bug.cgi?id=1587570#c13

### CODE REVIEW

**Comment by queengooborg** [comment]
Hey @fred-wang!  Let's actually just remove these features as they meet the [requirements of the irrelevant features removal guideline](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features).

**Comment by fred-wang** [comment]
@queengooborg OK, but the attributes still show up on MDN pages e.g. https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mmultiscripts#attributes. Is agreement that they should be removed from the MDN pages too? Otherwise, I guess it's not clear for developers whether that feature is supported.

**Comment by queengooborg** [comment]
Yes, they should be removed from MDN pages as well -- I'll add a label to this PR to represent this as well!

**Comment by fred-wang** [comment]
@queengooborg ok sounds good, will do that then.

**Comment by fred-wang** [comment]
@queengooborg done

**Comment by fred-wang** [comment]
MDN PR uploaded.

**Review by Elchi3 — APPROVED** [review]

**Comment by fred-wang** [comment]
It looks like I did a mistake here. They were implemented in WebKit in https://commits.webkit.org/139551@main and still present in the source code...

**Pull request merged**
