### PR TITLE
Houdini: Paintworklet

### PR DESCRIPTION
**Pull request by estelle**
Moved PaintWorkletGlobalScope to PaintWorklet, as that is the URL, title of the page, etc.

@jpmedley  I am not 100% sure if this change is correct. Should we instead change the URL and add content to reflect PWGS's global execution context?

https://drafts.css-houdini.org/css-paint-api-1/#paint-worklet
https://developer.mozilla.org/en-US/docs/Web/API/PaintWorklet

### CODE REVIEW

**Comment by jpmedley** [comment]
@estelle I don't believe it is either. The latest spec draft has `PaintWorkletGlobalScope` and that's what Chrome implemented.

**Comment by vinyldarkscratch** [comment]
Based upon the spec you have linked, the attributes are all on a `PaintWorkletGlobalScope` interface.  As such, I believe it is inaccurate to rename the files.  It seems a little odd to have a discrepancy between the MDN articles and the BCD files, though...  Well, since that's what they're under, I would say: let's leave the MDN URL changes, but revert all the renaming changes?

**Comment by vinyldarkscratch** [comment]
Based upon the spec you have linked, the attributes are all on a `PaintWorkletGlobalScope` interface.  As such, I believe it is inaccurate to rename the files.  It seems a little odd to have a discrepancy between the MDN articles and the BCD files, though...  Well, since that's what they're under, I would say: let's leave the MDN URL changes, but revert all the renaming changes?

**Comment by vinyldarkscratch** [comment]
Closing this in favor of the new PR.  (There's some complex merge conflicts that are getting in the way of this PR.)

**Pull request closed without merging**
