### PR TITLE
Update safari and safari_ios support for RTCDataChannel

### PR DESCRIPTION
**Pull request by gorisanson**
A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [x] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

I've experimenting with [RTCDataChannel](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel) and I found some feature that Safari and Safari on iOS supports.

I tested by creating RTCDataChannel by calling the RTCPeerConnection's createDataChannel() method and tested on "send", "onopen", "onmessage", "open event" and "message event" by transferring some data via the created data channel. I tested on Safari with version 13.1,  and Safari on iOS 13.3.1.

### CODE REVIEW

**Comment by Elchi3** [comment]
Thanks for your PR and welcome to BCD @gorisanson :+1: 
I'm not familiar with WebRTC, but hopefully @a2sheppy can provide a review here.

**Comment by gorisanson** [comment]
Here's a link that can be used for testing: https://gorisanson.github.io/pikachu-volleyball-p2p-online/en/. (By opening two windows of the browsers, the test can be done locally.) This toy project I made, i used RTCDataChannel's "send", "open event", "message event". And it works on Safari with version 13.1 and Safari on iOS 13.3.1 as other browsers too.

**Comment by Elchi3** [comment]
@a2sheppy can you review this?

**Comment by Elchi3** [comment]
Sorry for the wait here, @gorisanson. 

From reading https://bugs.webkit.org/show_bug.cgi?id=189503 it seems that some features of RTCDataChannel seem to work iOS Safari. So, I'm going to accept your changes.

**Comment by gorisanson** [comment]
@Elchi3 No problem :) Thank you!

**Pull request merged**
