### PR TITLE
Add Compute Pressure API

### PR DESCRIPTION
**Pull request by Elchi3**
See https://w3c.github.io/compute-pressure/#idl-index for the API surface.

Draft PR given this is not yet stable but it will probably make the Chromium 125 train. (and BCD doesn't have Chrome 125 yet, so the build failure here is expected and this will not matter when we merge this PR later in the process).

cc @arskama @kenchris here you go, draft BCD for compute pressure :)
Question for you: By default we assume that a new web platform features ship on desktop and mobile browsers at the same time (and hence we "mirror" in the data, see the diff). For this API, I'm not sure. If it is shipping soon in 125, on which platforms will it be available? Thanks!

### CODE REVIEW

**Comment by kenchris** [comment]
The feature is only supported on desktop operating systems so far: https://chromestatus.com/feature/5597608644968448

Look at the Intent to Ship part:

image

**Comment by Elchi3** [comment]
Thanks @kenchris! So, "no information provided yet" means no support :)

I've also added the permissions policy bits here, they seem to be implemented as they are marked passing on https://wpt.fyi/results/compute-pressure?label=master&label=experimental&aligned&q=compute-pressure.

All features this PR is adding:

- api.Permissions.permission_compute-pressure
- api.PressureObserver
- api.PressureObserver.PressureObserver
- api.PressureObserver.disconnect
- api.PressureObserver.observe
- api.PressureObserver.supportedSources_static
- api.PressureObserver.takeRecords
- api.PressureObserver.unobserve
- api.PressureRecord
- api.PressureRecord.source
- api.PressureRecord.state
- api.PressureRecord.time
- api.PressureRecord.toJSON
- http.headers.Permissions-Policy.compute-pressure

**Comment by Elchi3** [comment]
@kenchris @arskama This PR is now passing because the Chrome train has moved on to the next milestone :) Can you confirm the API ships as described in https://github.com/mdn/browser-compat-data/pull/22687#issuecomment-2018147584?

**Comment by kenchris** [comment]
@Elchi3 yes, this is shipping. We might remove the supportedSourced static before though, still considering

**Comment by Elchi3** [comment]
Renamed `supportedSources` to `knownSources`. Still waiting for feedback if this will be M125 or M126 before merging.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
I've tested https://mdn-bcd-collector.gooborg.com/tests/api/PressureObserver in Chrome 125 beta and it's supported. I think this is good to go.

**Comment by foolip** [comment]
Yep, `knownSources` should be in Chrome 125:
https://chromiumdash.appspot.com/commit/911bf3b8e88a6eeaa2521f7186fdfcf23f123f70

**Pull request merged**
