### PR TITLE
Data place items

### PR DESCRIPTION
**Pull request by rachelandrew**
Separating the grid and flex place-items data.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
(quoting myself from https://github.com/mdn/browser-compat-data/pull/2519#issuecomment-410538609)
> @rachelandrew To fix your broken master branch, run the following in a command prompt:
> ```pwsh
> git fetch https://github.com/mdn/browser-compat-data.git --tags
> git checkout -fB master FETCH_HEAD
> git push origin master -f --tags
> ```

As for fixing this PR, do this after you have done the above:
```pwsh
git rebase --onto master data-place-items~1 data-place-items
```

**Comment by ExE-Boss** [comment]
Please, do `git checkout -B data-place-self 07bcce7f757c8f70d4ae904cf775712c83d50d5e`.

**Comment by rachelandrew** [comment]
Hi - I followed the instructions you gave me. If that created a "broken git history" then it's probably best I don't continue to follow these instructions.

I'll save the work out, close these PRs and reopen them on a clean cloned copy.

**Comment by ExE-Boss** [comment]
You created the merge commit https://github.com/mdn/browser-compat-data/pull/2520/commits/12b8dee9c25f1ccb599af84a5354c10492c01808 after following my instructions from https://github.com/mdn/browser-compat-data/pull/2520#issuecomment-410538621.

My instructions in https://github.com/mdn/browser-compat-data/pull/2520#issuecomment-410774800 will undo that by checking out to commit https://github.com/mdn/browser-compat-data/pull/2520/commits/05810efef152e040ef582d70bebc5de68389cc6f, which is the correct commit you want to check out to.

**Comment by rachelandrew** [comment]
I can't checkout to that commit at my end, and needed to merge to be able to push the changes. Thanks for the help but it will be easier just to redo these.

(It was an attempt to use a GUI originally that caused the mess, I'll stay at the cli next time)

**Comment by Elchi3** [comment]
If the suggestions above don't work, a new PR would be OK for me, too, in order to move forward.

**Pull request closed without merging**
