### PR TITLE
Add static class fields data

### PR DESCRIPTION
**Pull request by mougrim**
Next code:
```js
class SomeClass {
  static field = 'value';
}
console.log(SomeClass.field);
```
Works well in chrome 76, but throws error 'SyntaxError: bad method definition' in firefox 69.

Non-static fields work ok in both browsers:
```js
class SomeClass {
  field = 'value';
}
const someObject = new SomeClass();
console.log(someObject.field);
```

### CODE REVIEW

**Comment by mougrim** [comment]
Issue for firefox [Implement the Static class features proposal](https://bugzilla.mozilla.org/show_bug.cgi?id=1535804).

**Comment by mougrim** [comment]
Hi @vinyldarkscratch, thanks!
About line 351, there is link [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static), and it's about methods only.

Public static fields are described in [Public class fields](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Classes/Class_elements#Public_fields).

So, I've added `"partial_implementation": true` and link to the issue to public_class_fields.

**Comment by vinyldarkscratch** [comment]
I think that just one data point, `static_class_fields`, should be sufficient to start.  We can expand them later if browsers support them at separate times!

**Comment by mougrim** [comment]
@vinyldarkscratch, as I see public_class_fields and private_class_fields were implemented in different browser versions. For example for chrome public_class_fields were added in v72, private_class_fields were added in v74, how I should describe it in static_class_fields?

**Comment by vinyldarkscratch** [comment]
Before anything else, I think that we should figure out which browsers support this, and when.  I’m going to do some research and get back as soon as possible!

**Comment by vinyldarkscratch** [comment]
After further review, I've found the following:

- Chrome supports static class fields [since it introduced public class fields](https://chromestatus.com/feature/6001727933251584), AKA v72 (I've confirmed this in manual testing)
- Firefox [doesn't support this yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1535804)
- IE/Edge doesn't support it
- Safari doesn't support it

I'd say that we can stick to one data point, rather than separating it by public and private versions (I doubt a browser would have separate support for them), since our private class fields datapoint would imply "private static class fields" already.

**Comment by Elchi3** [comment]
> I'd say that we can stick to one data point, rather than separating it by public and private versions (I doubt a browser would have separate support for them), since our private class fields datapoint would imply "private static class fields" already. 

I think this makes sense to me, too.

**Comment by mougrim** [comment]
Hi, @vinyldarkscratch 

> Chrome supports static class fields since it introduced public class fields, AKA v72 (I've confirmed this in manual testing)

What about private static class fields? Is it introduced from v74 in Chrome?

**Comment by vinyldarkscratch** [comment]
Technically, yes, because private class fields in general are introduced in v74.  Just one data point should be sufficient though — the compatibility data for private class fields and static class fields together will imply private static class fields on its own!

**Comment by mougrim** [comment]
@vinyldarkscratch, I'm not sure, that I understand you correctly, but I hope.
So, please, see last commit.

**Pull request merged**
