### PR TITLE
Remove api.PageRevealEvent.PageRevealEvent from BCD

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the `PageRevealEvent` member of the `PageRevealEvent` API from BCD. Per the [data guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/index.md#removal-of-irrelevant-features), this feature can be considered irrelevant and may be removed from BCD accordingly. Even if the current data suggests that the feature is supported, lack of support has been confirmed by the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.11.0).

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/PageRevealEvent/PageRevealEvent

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
I don't see the constructor in https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/view_transition/page_reveal_event.idl so this seems to be correct.

**Comment by bramus** [comment]
This is a supporting feature for authors to work with cross-document view transitions. It is expected that, today, usage is low.

I'm currently OOO but maybe @noamr can chime in to why the constructor doesn't show up in the IDL?

**Comment by noamr** [comment]
> This

It's an oversight, filed https://issues.chromium.org/issues/354588516

**Comment by bramus** [comment]
This got re-added through https://github.com/mdn/browser-compat-data/pull/23956. Thanks for the fix, @noamr!

**Pull request merged**
