### PR TITLE
Update <iframe sandbox=allow-downloads> for Firefox and Chrome

### LINKED ISSUE #6667: sandbox=allow-downloads
Document `<iframe sandbox=allow-downloads>`. I will open a PR later, but I can't provide accurate data for anything non-Firefox.

https://bugzilla.mozilla.org/show_bug.cgi?id=1558394
https://www.chromestatus.com/feature/5706745674465280

### PR DESCRIPTION
**Pull request by evilpie**
I manually tested in Firefox 82 and Chrome 85, but used the following
references for 81 and 83 respectively.

https://bugzilla.mozilla.org/show_bug.cgi?id=1558394
https://www.chromestatus.com/feature/5706745674465280

Fixes #6667

### CODE REVIEW

**Comment by evilpie** [comment]
Btw. The lint doesn't accept Firefox for Android version 81: html.elements.iframe.sandbox-allow-downloads - version_added: "81" is NOT a valid version number for firefox_android

**Comment by jpmedley** [comment]
LGTM for Chrome part.

**Comment by ddbeck** [comment]
I just retitled this PR, mostly to move the issue link into the body to properly link them. I've also opened #6696 to unblock the Firefox for Android issue.

**Comment by evilpie** [comment]
Rebased on top #6696 and added Firefox for Android. Please merge

**Review by ddbeck — APPROVED** [review]
Thank you, @evilpie! 🎉

**Pull request merged**
