### PR TITLE
Add GlobalEventHandlers.beforexrselect_event

### PR DESCRIPTION
**Pull request by Elchi3**
Companion PR for https://github.com/mdn/content/pull/15376

Discussion: https://github.com/mdn/browser-compat-data/issues/7545#issuecomment-1108500261 and ff.

### CODE REVIEW

**Comment by Elchi3** [comment]
fwiw, the alternative would be to add this under the specific interfaces:

api.Document.beforexrselect_event
api.Window.beforexrselect_event
api.HTMLElement.beforexrselect_event
api.SVGElement.beforexrselect_event
api.MathMLElement.beforexrselect_event

**Comment by Elchi3** [comment]
fwiw, the alternative would be to add this under the specific interfaces:

api.Document.beforexrselect_event
api.Window.beforexrselect_event
api.HTMLElement.beforexrselect_event
api.SVGElement.beforexrselect_event
api.MathMLElement.beforexrselect_event

**Comment by foolip** [comment]
As argued in https://github.com/mdn/content/pull/15376#issuecomment-1117548919, I think this should go under api.Element.beforexselect_event.

**Comment by Elchi3** [comment]
@saschanaz would api.Element.beforexrselect_event work for you even if the IDLs don't install it under Element?

**Comment by Elchi3** [comment]
Also @queengooborg, would this work with the collector? Would you remap this to Element somehow?

**Comment by queengooborg** [comment]
Yes, this would be remapped to the Element API by the collector already, as the collector demixes all mixins before generating tests!

**Comment by saschanaz** [comment]
> Also @queengooborg, would this work with the collector? Would you remap this to Element somehow?

My current logic find two places: The original mixin or each interface. It would be hard to find `Document.onbeforexrselect` when it's in `Element` since it's not an ancestor of `Document`.

**Comment by queengooborg** [comment]
Thanks @Elchi3!  However, we ended up deciding to demix `GlobalEventHandlers` as it's the only mixin left and it's not fully representative of what events fire on what interfaces.

**Comment by Elchi3** [comment]
> Thanks @Elchi3! However, we ended up deciding to demix `GlobalEventHandlers` as it's the only mixin left and it's not fully representative of what events fire on what interfaces.

okay, thanks! How should I add `beforexrselect` to BCD now?

> fwiw, the alternative would be to add this under the specific interfaces:
> 
> api.Document.beforexrselect_event 
> api.Window.beforexrselect_event 
> api.HTMLElement.beforexrselect_event 
> api.SVGElement.beforexrselect_event
> api.MathMLElement.beforexrselect_event

^ like this

**Pull request closed without merging**
