### PR TITLE
Update Firefox data for `EXT_color_buffer_float` API

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects version values for Firefox and Firefox Android for the `EXT_color_buffer_float` API.The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v8.1.2).

_Check out the [collector's guide on how to review this PR](https://github.com/GooborgStudios/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/api/EXT_color_buffer_float

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
I remember documenting this for Firefox 49. https://bugzilla.mozilla.org/show_bug.cgi?id=1129332#c15
Which Firefox did you test this on? Windows? macOS? 
For Android, 80 could make sense. Unsure why it would be so much later for desktop.

**Comment by queengooborg** [comment]
Marking this as a draft as a reminder this needs more research.

**Comment by queengooborg** [comment]
Okay, so, I've run this test on multiple OSes across multiple CIs.  On both BrowserStack and SauceLabs in macOS (Ventura and El Capitan) and Windows (7 and 10), the tests report false in Firefox 50, 78 and 79.  They are reporting false because the WebGL 2 rendering context is apparently not defined.  (Why the collector isn't updating `WebGL2RenderingContext`, I don't know.)  With WebGL 1, I am also getting no support (not that I'd expect it to).

The `WebGL2RenderingContext` API says it was supported since Firefox 51 as well, so "49" doesn't make sense either.  I'm not sure if I trust 51 either, however, as it came from the wiki migration.

**Comment by Elchi3** [comment]
I think Firefox 51 is correct for WebGL 2 support: https://hacks.mozilla.org/2017/01/webgl-2-lands-in-firefox/

**Comment by queengooborg** [comment]
Okay, this is interesting: now BrowserStack is reporting that this interface is supported in Firefox 51.  I haven't changed the tests at all since v8.1.2 and v8.2.0 (the current version)...

Temporary bug?

**Review by Elchi3 — APPROVED** [review]
Thanks! 👍

**Pull request merged**
