### PR TITLE
Remove MediaTrack dictionaries from BCD

### PR DESCRIPTION
**Pull request by queengooborg**
This PR removes the `MediaTrackConstraints`, `MediaTrackSettings`, and `MediaTrackSupportedConstraints` dictionaries from BCD. These are a type (ex. a dictionary, enum, mixin, constant or WebIDL typedef) that we have explicitly stated not to document separately from the feature(s) that depend on it, as they are virtually invisible to the end developer.

Coverage Increase: removes 42 features, increasing collector coverage from 89.48% to 89.75%

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Discussion about dictionary removal is in https://github.com/mdn/browser-compat-data/issues/6810, so I think this is good to go (and might be one of the last work items for this).

Approving but holding off merging so it can be coordinated with the content updates.

**Comment by hamishwillee** [comment]
@queengooborg @Elchi3 SO does this mean that you have merged the compatibility data into the places where this data is used? Such as if you remove `MediaTrackSupportedConstraints` then the data would have to be captured as an update to BCD for [MediaDevices.getSupportedConstraints()]()https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getSupportedConstraints). Similar for the other cases. Otherwise we're throwing away useful support data.

**Comment by queengooborg** [comment]
Content changes have now been merged!

**Review by Elchi3 — APPROVED** [review]
Thanks, merging this so that the compat tables are intact again on pages like https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/aspectRatio etc.

**Pull request merged**
