### PR TITLE
Lint for multiple support statements with only `version_added`

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/mdn/browser-compat-data/issues/3485.

Reviewers! This will fail a few lints, I'm submitting it as-is to show what they are, they need some discussion I think.

### CODE REVIEW

**Comment by foolip** [comment]
Failing lint is:
```
Problems in 2 files:
api/AnimationEvent.json
  Browsers – 6 error(s):
    'api.AnimationEvent.AnimationEvent' has multiple support statement with only `version_added` for chrome
    'api.AnimationEvent.AnimationEvent' has multiple support statement with only `version_added` for chrome_android
    'api.AnimationEvent.AnimationEvent' has multiple support statement with only `version_added` for webview_android
    'api.AnimationEvent.animationName' has multiple support statement with only `version_added` for chrome
    'api.AnimationEvent.animationName' has multiple support statement with only `version_added` for chrome_android
    'api.AnimationEvent.animationName' has multiple support statement with only `version_added` for webview_android
api/PerformanceEntry.json
  Browsers – 1 error(s):
    'api.PerformanceEntry' has multiple support statement with only `version_added` for chrome
```

For `AnimationEvent` I suspect one of the entries was supposed to be for prefixed support, which makes fixing it more complicated.

**Comment by foolip** [comment]
The PerformanceEntry case is messy, I filed https://github.com/mdn/browser-compat-data/issues/3528.

**Comment by vinyldarkscratch** [comment]
Looking at the files, I believe your assumption that one of them is for prefixed support in `AnimationEvent` is correct.  I’d say that the `“version_added”: true` blocks should have a `“prefix”: “webkit”` on them, simply based upon what I’m seeing in the data alone (citation needed, I’m just spewing out thoughts).  Overall though, +1 for this!

(By the way, I think that this check would be better in the `test-consistency.js` file introduced in my PR, #3368, for organization of the checks.  Just another of my little thoughts that may interest someone.  😛)

**Comment by foolip** [comment]
@vinyldarkscratch the `AnimationEvent` data is a bit wrong because, but can be fixed. Just adding `prefix` would still leave it wrong, as `WebKitAnimationEvent` has been removed in Chrome now.

**Comment by vinyldarkscratch** [comment]
Another random thought that just came up: I'm thinking that it might be a nice idea to expand the horizons of this check, and basically test to make sure that each statement is unique (aka linting against `version_added: false` or `version_added: "40", prefix: "webkit` being added twice).  Thoughts?

**Comment by vinyldarkscratch** [comment]
@foolip Got the data updated now, so a quick merge of `master` and the linter should pass!

**Comment by foolip** [comment]
@vinyldarkscratch I've rebased and lint indeed passes now.

**Pull request merged**
