### PR TITLE
Fix browser presence linter

### PR DESCRIPTION
**Pull request by queengooborg**
This PR fixes the messages and behavior of the browser presence linter.

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
What is fixed here exactly? Can you write a test for this change?

**Comment by Elchi3** [comment]
I guess this PR makes it so that you aren't required to provide `ie` anymore. I think the absence of `ie` will mean that support will be `null`. I think we still want to explicitly report `false` for `ie` for a while still? Would be good to discuss this in the BCD call.

**Comment by queengooborg** [comment]
I'm realizing that we didn't already have IE non-required and that I had added that filtering in this PR.  I've reverted those changes, so this only does the fixes of the linter messages.

**Comment by Elchi3** [comment]
OK thanks! What's the reason to remove `path` ?

**Comment by queengooborg** [comment]
It's because the `path` variable was never set, so it always remained blank -- but even if it was set, it'd just be duplicate data the logger outputs, since logger errors for feature scopes always include the path!

image

**Review by Elchi3 — APPROVED** [review]
Got it, thanks for the explanation! 👍

**Pull request merged**
