### PR TITLE
test(style): Improve MDN URL heuristics

### PR DESCRIPTION
**Pull request by ExE-Boss**
See https://github.com/mdn/browser-compat-data/issues/2128#issuecomment-391916855 for details.

I have decided not to implement the descending `mdn_url` check in this PR:
> Another thing that might be a good idea to test is if the `mdn_url`s are descending (eg. sub-features start with the `mdn_url` of the parent) and print a warning if not (not an error, because there are edge‑cases on MDN where this might not necessarily apply).

---

review?(@vinyldarkscratch)

### CODE REVIEW

**Comment by ExE-Boss** [comment]
That wouldn’t allow this&nbsp;PR to&nbsp;be&nbsp;merged, since the&nbsp;build would fail.

But&nbsp;I&nbsp;could split it&nbsp;into separete commits by&nbsp;reverting my&nbsp;force push.

**Comment by vinyldarkscratch** [comment]
That would be great!  (Mostly asking since it's what I had to do with #3368, and I know @Elchi3 would want to review these changes.)  It will indeed cause the build to fail, and for this to depend on the new one, but I plan on merging the data changes pretty quickly.  😛

**Comment by ExE-Boss** [comment]
Actually, the label should be [<kbd>linter :house_with_garden:</kbd>](https://github.com/mdn/browser-compat-data/labels/linter%20%3Ahouse_with_garden%3A).

**Comment by Elchi3** [comment]
I've looked into this and it works as expected. I think it has now become a bit more important as we don't want wiki.developer.mozilla.org domains in the data. Thanks for already taking that into account here!

I think our link testing is quite advanced with this, so it probably deserves to be in its own file? Maybe everything here from line 158 to line 255 should be in a separate file "test-links.js"? I guess we could follow up on that in a separate PR if you prefer, though.

**Comment by ExE-Boss** [comment]
I’ll work on&nbsp;that later today and&nbsp;during the&nbsp;weekend.

**Pull request merged**
