### PR TITLE
Updates CSSStyleSheet() constructor compatability for chromium

### LINKED ISSUE #8822: api.CSSStyleSheet - CSSStyleSheet() constructor enabled by default in Google Chrome as of version 73
#### What information was incorrect, unhelpful, or incomplete?
image

Actually, The full specificaiton is enabled by default in Google Chrome as of version 73.

#### What did you expect to see?
image

#### Did you test this? If so, how?

https://developers.google.com/web/updates/2019/03/nic73#constructable-style-sheets

<details>
<summary>MDN page report details</summary>

* Query: `api.CSSStyleSheet`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/CSSStyleSheet
* Report started: 2021-01-21T08:22:01.733Z

</details>

### PR DESCRIPTION
**Pull request by spiritree**
Fixes #8822

source:
https://blog.chromium.org/2019/02/chrome-73-beta-constructable.html
https://developers.google.com/web/updates/2019/03/nic73#constructable-style-sheets

### CODE REVIEW

**Comment by ddbeck** [comment]
@foolip since you worked on #8041, could review this? It's a funny case: the constructor's there in 66 (the collector test passes in 66 but not 65), but I'm not sure why everything else is written up as if it shipped in 73: [bug 807560](https://bugs.chromium.org/p/chromium/issues/detail?id=807560) and [the Chrome Platform Status entry](https://www.chromestatus.com/feature/5394843094220800) and the ["New in Chrome 73"](https://developers.google.com/web/updates/2019/03/nic73#constructable-style-sheets) page. That seems odd.

**Comment by spiritree** [comment]
In my case,I failed to use `CSSStyleSheet() constructor` in Chromium 69.
image

**Review by ddbeck — APPROVED** [review]
OK, I've decide to move ahead with this. The exception thrown on this constructor in 66-72 seems sufficiently unsupported-like to go with version 73 instead.

Thank you, @spiritree!

**Comment by foolip** [comment]
Oops, sorry I missed or neglected the request for review here!

**Comment by ddbeck** [comment]
@foolip No problem. Giving it some time gave me enough perspective on this issue. And I've been playing with the collector more, so I have a better understanding of how it works than I did a couple of weeks ago, which was helpful here too.

**Pull request merged**
