### PR TITLE
Add WritableStream compat data

### PR DESCRIPTION
**Pull request by Elchi3**
https://developer.mozilla.org/en-US/docs/Web/API/WritableStream
https://www.chromestatus.com/features/5928498656968704
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/streamsapiwritablestream

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Looks OK, except that the WritableStream stuff doesn't work in Firefox yet. Try this demo, for example:

https://mdn.github.io/dom-examples/streams/simple-writer/

**Comment by Elchi3** [comment]
D'oh, we don't have them yet!

**Comment by Elchi3** [comment]
Updated

**Comment by chrisdavidmills** [comment]
Perfect, r+

**Pull request merged**
