### PR TITLE
Clipboard events aren't on Window nor on Element

### PR DESCRIPTION
**Pull request by Elchi3**
Technically clipboard events aren't on `Element` either but I'm not sure what we want to do here. This PR removes them from `Window` for a start and leaves us with: 

- Document (present in BCD, correct per IDL)
- Element (present in BCD, incorrect per IDL)
- HTMLELement (present in BCD, correct per IDL)
- MathMLElement (missing in BCD, correct per IDL)
- SVGElement (missing in BCD, correct per IDL)

```webidl
interface mixin DocumentAndElementEventHandlers {
  attribute EventHandler oncopy;
  attribute EventHandler oncut;
  attributeEventHandler onpaste;
};

Document includes DocumentAndElementEventHandlers;
HTMLElement includes DocumentAndElementEventHandlers;
MathMLElement includes DocumentAndElementEventHandlers;
SVGElement includes DocumentAndElementEventHandlers;
```

Any advise?

### CODE REVIEW

**Comment by queengooborg** [comment]
Can confirm that the events are not present on either Window or Element as per the mdn-bcd-collector project -- we've included custom IDL for the Element interface, and none of the tests are generated for Window.

We should probably perform two different PRs: one to remove the inaccurate data (this one) and one to add the missing data to MathMLElement and SVGElement.  How does that sound?

**Comment by Elchi3** [comment]
Okay. Updated to remove the three clipboard events from `Element` as well.

**Comment by Elchi3** [comment]
@foolip Does this one make sense as is?

**Comment by foolip** [comment]
@Elchi3 from testing in Chrome and https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/clipboard_commands.cc;l=112;drc=e813b3c6b110bce715d55f4ce12746e2c43aedb9 it looks like the event target is always an `Element` and these events bubble.

I'd say we should keep api.Element.*_event in BCD, but testing in more browsers first would be a good idea.

**Comment by foolip** [comment]
And https://github.com/mdn/browser-compat-data/pull/16825 is what I'd suggested instead of this PR.

**Pull request closed without merging**
