### PR TITLE
Fix experimental+deprecated statuses

### PR DESCRIPTION
**Pull request by saschanaz**
#### Summary

Copied from #6813.

### CODE REVIEW

**Comment by foolip** [comment]
All of these change experimental. Was there really no case where the mistake was the other way around?

**Comment by saschanaz** [comment]
> All of these change experimental. Was there really no case where the mistake was the other way around?

I assumed that `deprecated` flags were valid, I didn't reviewed the validity of them 🤔

**Comment by saschanaz** [comment]
Better to merge #15932 first I guess.

**Comment by foolip** [comment]
I'd say this one first, because it's easier to reason about and will probably reduce the number of inheritance fixes needed.

**Comment by foolip** [comment]
Hmm, but fixing https://github.com/mdn/browser-compat-data/pull/11506 before this would also be good, it's mechanical and probably makes many of the same changes.

@queengooborg what do you think of the order of all these status changes?

**Comment by queengooborg** [comment]
My preference would be to perform migration 007 (#11506) first.  It's a change I feel a little more confident about and is just about ready to go, plus it follows the migration steps.

**Comment by foolip** [comment]
@saschanaz I tried to resolve the merge conflict but think I messed it up. Do you want to throw away my merge commit and fix it yourself? I expect a lot fewer changes now that #16285 landed.

**Comment by saschanaz** [comment]
Well, I think the number of changed files are still similar 👀

**Comment by foolip** [comment]
Huh, I thought it would make a big dent, but OK then.

**Review by foolip — APPROVED** [review]
I've look through all of the changes using `npm run diff` and to my surprise couldn't spot any cases where it actually shouldn't be deprecated.

**Pull request merged**
