### PR TITLE
Add border-width CSS property compat data

### PR DESCRIPTION
**Pull request by ddbeck**
This PR adds the [border-width](https://developer.mozilla.org/en-US/docs/Web/CSS/border-width) CSS property.

This is my first PR with compat data, so it's very possible I made some mistakes. Specifically, I wasn't 100% sure how to enter the version numbers that had parentheticals. For example, the table on MDN says it was added to Firefox with version "1.0 (1.7 or earlier)". I'm not sure if that means that "1.0" is a special value (that means it's from some version 1.7 or earlier) or if the entire string was meaningful, so I kept it all. Similar questions came up for Safari and Android.

### CODE REVIEW

**Comment by wbamberg** [comment]
In the case of Firefox, "1.0 (1.7 or earlier)" maps to the table heading "Firefox (Gecko)", so "1.7 or earlier" is the Gecko version.

We've decided to record only Firefox versions in the data, not Gecko versions, so this should be just "1.0" I think. Similarly, where the Safari data says "1.0 (85)", "85" is the WebKit version (the table at https://en.wikipedia.org/wiki/Safari_version_history#Mac seems to confirm this) and I think we are again recording only the Safari version in the data.

There's a very useful comment here: https://github.com/mdn/browser-compat-data/issues/168#issuecomment-300471653 that outlines valid version numbers. We should clean this up and add it to CONTRIBUTING.md :).

**Comment by ddbeck** [comment]
Thanks, @wbamberg! That clears things up a lot. I've dropped the extra numbers accordingly.

> There's a very useful comment here: #168 (comment) that outlines valid version numbers. We should clean this up and add it to CONTRIBUTING.md :).

Sounds like a good idea to me! I've discovered a couple places where the contribution instructions might be expanded, so this is going on my to do list. :smiley:

**Comment by Elchi3** [comment]
Congratulations to your first PR! \o/

Yes, the version numbers are a bit wild all around still and the mentioned issue comment is the best we have agreed on so far. I also think that we should add that info to the contribution docs. Another hope is that we also add a validation script so that `npm test` or travis will complain if version numbers are invalid as per our standards.

Review:
- Instead of "1.0" we agreed that it is just "1", so leave out the ".0" everywhere (see https://github.com/mdn/browser-compat-data/issues/168#issuecomment-300471653).
- If you rebase against master you can now also add an `mdn_url`: 

```
{
  "css": {
    "properties": {
      "border-width": {
        "__compat": {
          "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/border-width",
          "support": {
```

**Comment by ddbeck** [comment]
> - Instead of "1.0" we agreed that it is just "1", so leave out the ".0" everywhere (see #168 (comment)).
> - If you rebase against master you can now also add an mdn_url

Done and done!

**Pull request merged**
