### PR TITLE
api.Node.removeChild is standard and non-deprecated

### PR DESCRIPTION
**Pull request by Konrud**
"deprecated": set to FALSE
"standard_track": set to TRUE

### CODE REVIEW

**Comment by ddbeck** [comment]
It looks like this supersedes #3202 and fixes #3192. I'll review this one and close the other, but for future reference, you can push new commits to an existing PR branch. A new PR is not required.

**Comment by Konrud** [comment]
Thank you, actually, I've tried to commit to an existing PR branch but couldn't as it gave me a message that I should open a new branch or something like that.

**Comment by ddbeck** [comment]
Oh, I've never encountered that before. I'm sorry for assuming that you didn't try to do that first.

**Comment by Konrud** [comment]
I see that update has not been applied yet. The page for `removeChild` still has "deprecated" and "non standard" icons.

**Comment by ddbeck** [comment]
The tables update when a new version of the npm package has been released and it gets picked up by the MDN dev team. That's likely to be later this week, but because of the holidays it maybe somewhat later. Thank you for your patience!

**Pull request merged**
