### PR TITLE
Add WebAuthn latest feature data and make it more descriptive

### PR DESCRIPTION
**Pull request by chrisdavidmills**
#### Summary

There are several features of the [WebAuthn API](https://w3c.github.io/webauthn) that are not covered on MDN, so I've started a project to update these docs, filling in gaps and improving the available information. I've also checked through the available BCD to see what is missing.

This PR does the following:

* Adds data for the `publickey-credentials-create` Permissions-Policy directive
  * For this data, I'm just copying the `publickey-credentials-get` data, assuming they would both be implemented at the same time. I don't see why they'd be implemented at different times — they are both needed together to be useful.
* Adds data for the `publicKey` options of `CredentialsContainer.create()` and `CredentialsContainer.get()` — I thought it important to call these out separately, as well as individual sub-items that were implemented later than the initial implementation. I don't want to create data points for the entire hierarchy of sub-properties, as it would be time-consuming and not very useful (we won't have separate pages for those properties, as they are members of a dictionary, not a class.)
  * for the basic `publicKey` data, I'm just copying the data for the `PublicKeyCredential` interface, as one returned the other, and I don't see that they'd be implemented separately.
  * for `credProps`, `residentKey`, and `requireResidentKey`, see https://chromestatus.com/feature/5701094648840192
  * for `largeBlob`, see https://chromestatus.com/feature/5657899357437952
  * I asked the WebAuthn Chrome engineers about the other extensions that I couldn't find data for, and they said that `credProtect` shipped in Chrome 76, `minPinLength` in 98.

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Where are the version numbers from? It would speed up review if links to chromestatus or similar sites/bugtrackers are provided.

**Comment by chrisdavidmills** [comment]
> Where are the version numbers from? It would speed up review if links to chromestatus or similar sites/bugtrackers are provided.

Oops, sorry — I've added them to the main PR description.

**Comment by Elchi3** [comment]
The data structures here are not trivial. `npm run diff` produces:

```
api.CredentialsContainer.create:
 → api.CredentialsContainer.create.publicKey_option is added
api.CredentialsContainer.get:
 → api.CredentialsContainer.get.publicKey_option is added
http.headers.Permissions-Policy:
 → http.headers.Permissions-Policy.publickey-credentials-create is added
```

For `api.CredentialsContainer.create.publicKey_option` the sub sub features `extensions`, `credProps`, `largeBlob`, `requireResidentKey`, `residentKey` are added.

**Comment by chrisdavidmills** [comment]
> The data structures here are not trivial. `npm run diff` produces:
> 
> ```
> api.CredentialsContainer.create:
>  → api.CredentialsContainer.create.publicKey_option is added
> api.CredentialsContainer.get:
>  → api.CredentialsContainer.get.publicKey_option is added
> http.headers.Permissions-Policy:
>  → http.headers.Permissions-Policy.publickey-credentials-create is added
> ```
> 
> For `api.CredentialsContainer.create.publicKey_option` the sub sub features `extensions`, `credProps`, `largeBlob`, `requireResidentKey`, `residentKey` are added.

Yeah, it's hard to figure out what best to do for this. It is complex because the same API has been reused for a bunch of different credential-related features. The extensions are used by stating the necessary properties inside the `publicKey.extensions` object, in each case. My only other option would be to create a completely new support structure just for WebAuthn extensions, which would be painful too.

I'm still working on this, so I'm going to convert it back to a draft.

**Comment by chrisdavidmills** [comment]
@Elchi3 quick ping on this one. I'm not sure if you've got any thoughts about the best way to structure this weird BCD, but we should maybe have a chat about it soon. I'm aiming to hit a deadline of May 10th for the WebAuthn docs updates, so there is a bit of time to play with.

**Comment by Elchi3** [comment]
So, my comment earlier was not quite correct, there is even another level with everything under the "extensions" object.
So, I think the additions here are:

api.CredentialsContainer.create.publicKey_option
api.CredentialsContainer.create.publicKey_option.extensions
api.CredentialsContainer.create.publicKey_option.extensions.appidExclude
api.CredentialsContainer.create.publicKey_option.extensions.credProps
api.CredentialsContainer.create.publicKey_option.extensions.credProtect
api.CredentialsContainer.create.publicKey_option.extensions.largeBlob
api.CredentialsContainer.create.publicKey_option.extensions.minPinLength

api.CredentialsContainer.get.publicKey_option
api.CredentialsContainer.get.publicKey_option.extensions
api.CredentialsContainer.get.publicKey_option.extensions.appid
api.CredentialsContainer.get.publicKey_option.extensions.largeBlob

I think this is fine. I don't know how and if MDN will render this. I guess we will find out :)

An alternative would be to get rid of one level and have:
api.CredentialsContainer.create.publicKey_option.appidExclude_extension
api.CredentialsContainer.create.publicKey_option.credProps_extension

**Comment by Elchi3** [comment]
Ah wait, that would make no sense, given there is also stuff sitting at the same level as extensions. I see why you have done it this way.

api.CredentialsContainer.create.publicKey_option.requiredResidentKey
api.CredentialsContainer.create.publicKey_option.residentKey

**Comment by Elchi3** [comment]
> * I asked the WebAuthn Chrome engineers about the other extensions that I couldn't find data for, and they said that `credProtect` shipped in Chrome 76, `minPinLength` in 98.

In the data you put 89 for `minPinLength` and not 98. What is correct?

**Comment by chrisdavidmills** [comment]
> Ah wait, that would make no sense, given there is also stuff sitting at the same level as extensions. I see why you have done it this way.
> Ah wait, that would make no sense, given there is also stuff sitting at the same level as extensions. I see why you have done it this way.
> api.CredentialsContainer.create.publicKey_option.requiredResidentKey
> api.CredentialsContainer.create.publicKey_option.residentKey

Yup, it was a hard call on this, but I ended up doing it like this so that I can group the extensions data together on BCD rendering, and plus I can list just extensions support data on the extensions page I wrote in the updated docs.

**Comment by chrisdavidmills** [comment]
> In the data you put 89 for `minPinLength` and not 98. What is correct?

@Elchi3 Darnit, it was supposed to be 98. I've corrected it now.

**Review by Elchi3 — APPROVED** [review]
Alright, thanks for figuring it all out! Let's hope MDN can render something useful with this structure :)

**Pull request merged**
