### PR TITLE
Update Firefox data for css.properties.appearance.compat-auto

### PR DESCRIPTION
**Pull request by queengooborg**
This PR updates and corrects version values for Firefox and Firefox Android for the `compat-auto` member of the `appearance` CSS property. The data comes from the [mdn-bcd-collector](https://mdn-bcd-collector.gooborg.com) project (v10.0.3).

_Check out the [collector's guide on how to review this PR](https://github.com/GooborgStudios/mdn-bcd-collector#reviewing-bcd-changes)._

Tests Used: https://mdn-bcd-collector.gooborg.com/tests/css/properties/appearance/compat-auto

### CODE REVIEW

**Review by Elchi3 — CHANGES_REQUESTED** [review]
It seems the list of `<compat-auto>` values has changed: https://github.com/web-platform-tests/interop/issues/295

"Remove slider-horizontal, square-button, push-button from `<compat-auto>`"

Can we update the test code and the description?

**Comment by queengooborg** [comment]
Sure thing!  Should we create separate entries for those three values as well?

**Comment by Elchi3** [comment]
I think it would be ok to just have them gone from this list

**Comment by queengooborg** [comment]
Opened #20205 to handle that!

**Pull request closed without merging**
