### PR TITLE
First pass of new Animation data

### PR DESCRIPTION
**Pull request by CalmBit**
Hey all,

Submitting this for review barring a few clarity points!

1. The `finished` promise was implemented in [Firefox 40](https://bugzilla.mozilla.org/show_bug.cgi?id=1074630), but given its own separate task in [Firefox 42](https://bugzilla.mozilla.org/show_bug.cgi?id=1178665). Should I stick with version 40 as the date this feature was added? Should a note recognize this as anything but an internal change?

2. In [Firefox 36](https://bugzilla.mozilla.org/show_bug.cgi?id=1037321), `playState` was made visible, but in [Firefox 40](https://bugzilla.mozilla.org/show_bug.cgi?id=1074630) the player finishing behaviour (along with the aforementioned `finished` promise) was brought to bear. I'm not sure if this counts as an effective "this feature works" point or not, so should that feature be shown as 40 or 42?

Thank you!

### CODE REVIEW

**Comment by teoli2003** [comment]
Hi CalmBit,

Thank you very much for your PR.

Here are some answers to your questions:

1. The idea here is to describe what is changing for web developers. So the finished promise was usable since Fx 40, so "40" is the right value. If the "Own separate task" is not user-facing (that improves performance or reliability, but we don't change the overall behaviour), we don't mention it. If it does, we can add it as a note.

2. Set it at "36", but add a note that some values/behaviour only work correctly in Fx 40 and later.

Hope it helps.

**Comment by Elchi3** [comment]
CC'ing @birtles in case he wants to provide additional review comments for the Firefox support of the Web Animation API.

**Comment by birtles** [comment]
Thank you so much for doing this! It looks great!

> The finished promise was implemented in Firefox 40, but given its own separate task in Firefox 42. Should I stick with version 40 as the date this feature was added? Should a note recognize this as anything but an internal change?

I'd only report what we actually ship. We discussed this with the Chrome team and agreed not to report version numbers for features that are pref-ed off in release channels.

We didn't ship `Element.animate` until Firefox 48 so I wouldn't bother with any versions less than that. We haven't shipped either the `ready` or `finished` promise (and neither has Chrome) so I would mark it as unsupported. I'm actually working on that right now so I hope we will ship it in Firefox 60 but for now it's not pref-ed on in release channels.

> In Firefox 36, playState was made visible, but in Firefox 40 the player finishing behaviour (along with the aforementioned finished promise) was brought to bear. I'm not sure if this counts as an effective "this feature works" point or not, so should that feature be shown as 40 or 42?

Again, we shipped `playState` as part of the subset we shipped in 48 so I'd set it as 48.

**Comment by birtles** [comment]
Just a further clarification: basically, everything should either be 48 or unsupported. The only exception I can think of is the `pending` which we implemented in 59 and which will ride the trains to release. `updatePlaybackRate` which I should land tomorrow should ride the trains to 60 but it's not in MDN yet so you don't need to worry about that.

**Comment by Elchi3** [comment]
I would preserve the preference information. The rendered compat tables hide the prior preffed support range and you will have to click the little arrow to expand the cells. This is exactly why we allow to have version ranges in the compat data.
https://developer.mozilla.org/en-US/docs/Web/API/Animation#Browser_compatibility

**Comment by birtles** [comment]
Ok, fair enough. Previously we had all that information in MDN but it was too hard to nail down which version a feature landed in. Often it landed in one version but was incomplete, and then the spec changed, and so often there were 3 or 4 versions to choose from. The same was true of Chrome so we agreed at that time just to report shipping versions and updated MDN accordingly.

Last year at BlinkOn I spoke to the Chrome MDN lead and he agreed we should only report shipping versions. Perhaps reporting flags makes sense for other APIs that have landed more atomically?

**Pull request merged**
