### PR TITLE
Combine selection events under GlobalEventHandlers

### PR DESCRIPTION
**Pull request by Elchi3**
Companion PR for https://github.com/mdn/content/pull/15385

Let me know if this approach makes sense at all.

### CODE REVIEW

**Comment by saschanaz** [comment]
Okay, this is what I was worried about https://github.com/mdn/content/pull/15376#issuecomment-1109594730. `HTMLInputElement` does not include GlobalEventHandlers and there is no machine-readable way to tell the data is in that mixin instead of the interface.

**Comment by Elchi3** [comment]
Okay, so I guess whenever a specific interface's compat data differs from the data we have in `GlobalEventHandlers`, we want to have a compat data entry for that feature on the specific interface.

So, in addition to
api.GlobalEventHandlers.selectionchange_event

we also want
api.HTMLInputElement.selectionchange_event
api.HTMLTextAreaElement.selectionchange_event

**Comment by saschanaz** [comment]
Having them together sounds good, but I think "whenever a specific interface's compat data differs" should be "always" or machines will get no data for those interfaces.

**Comment by Elchi3** [comment]
Okay, but what would "always" imply exactly? The list of interfaces is quite long as `GlobalEventHandlers` is well global... 

As a start it would be all of these:
Document includes GlobalEventHandlers
Window includes GlobalEventHandlers
HTMLElement includes GlobalEventHandlers
MathMLElement includes GlobalEventHandlers
SVGElement includes GlobalEventHandlers

And then the two we identified only through the different compat data:
HTMLInputElement
HTMLTextAreaElement
(but there are of course more elements that inherit from HTMLElement). 

How would I programmatically detect where I need to have compat data entries?

**Comment by saschanaz** [comment]
>How would I programmatically detect where I need to have compat data entries?

Perhaps there should be a script that checks the IDL?

**Comment by saschanaz** [comment]
GlobalEventHandlers itself is not very practical to be fair. As current BCD items are IDL machine readable in some ways, I think it's practical to leave it as is.

**Comment by Elchi3** [comment]
I reverted the changes for HTMLInputElement and HTMLTextAreaElement.

(Not sure this brings me any further to come to a general rule for how to treat events that come from `GlobalEventHandlers`, though. Just having the data on api.GlobalEventHandlers.* is not it apparently. Having it on all specific interfaces isn't either, so it is something in-between that is maybe a case-by-case decision.)

**Comment by Elchi3** [comment]
In https://github.com/mdn/content/pull/15385#issuecomment-1117562379 @foolip proposes yet another way.

> Per https://w3c.github.io/selection-api/#selectionchange-event the "selectionchange" event can be fired at Document, HTMLInputElement and HTMLTextareaElement. I think it'd make sense to have these as 3 pages, and link them together. (I haven't tested if they're actually supported.)

If I understand Philip correctly, the proposal would be to have
api.Document.selectionchange_event
api.HTMLInputElement.selectionchange_event
api.HTMLTextAreaElement.selectionchange_event

(and nothing in api.GlobalEventHandlers)

**Comment by foolip** [comment]
Manual testing with https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=10319 confirms the "selectionchange" event on `<textarea>` is supported in Firefox but not in Chrome/Safari.

**Comment by foolip** [comment]
Hah, this is amusing, none other than @saschanaz implemented this in Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1677253

**Comment by saschanaz** [comment]
Yeah it's weird, Chrome "supports" selectionchange within textarea but fires it at document, not at each element.

**Comment by saschanaz** [comment]
> `HTMLInputElement` does not include GlobalEventHandlers and there is no machine-readable way to tell the data is in that mixin instead of the interface.

Wait, sorry, t does actually (via `HTMLElement includes GlobalEventHandlers`). But https://github.com/mdn/browser-compat-data/pull/16029#issuecomment-1129721909 is still relevant here.

**Comment by queengooborg** [comment]
Thanks @Elchi3!  However, we ended up deciding to demix `GlobalEventHandlers` as it's the only mixin left and it's not fully representative of what events fire on what interfaces.

**Pull request closed without merging**
