### PR TITLE
relnote(116): CSSPropertyRule enabled in Fx nightly by default

### PR DESCRIPTION
**Pull request by bsmth**
The pref `layout.css.properties-and-values.enabled` is set to true (enabled) on Nightly in 116. This allows for using the following APIs:

- [`CSSPropertyRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule)
- [`CSSPropertyRule.inherits`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/inherits)
- [`CSSPropertyRule.initialvalue`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/initialvalue)
- [`CSSPropertyRule.name`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/name)
- [`CSSPropertyRule.syntax`](https://developer.mozilla.org/en-US/docs/Web/API/CSSPropertyRule/syntax)

- [`registerProperty()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/registerProperty_static)

And the following CSS syntax:

```css
@property --item-size {
  syntax: "<percentage>";
  inherits: true;
  initial-value: 40%;
}
```

__pen/demo:__
https://codepen.io/bsmth/pen/xxQpVow?editors=0111

__Related issues and pull requests:__
- [ ] Parent issue https://github.com/mdn/content/issues/27756
- [x] Content (Exp Features): https://github.com/mdn/content/pull/27902

__Bugzilla:__
- [BUG-1840480](https://bugzilla.mozilla.org/show_bug.cgi?id=1840480)

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
LGTM; nice work @bsmth

**Comment by bsmth** [comment]
Thank you

**Comment by ZuBB** [comment]
I spent an hour this morning and found that this does not work(broken?) in the nightly https://bugzilla.mozilla.org/show_bug.cgi?id=1846488

Right now, information about the presence of this feature in v119 is incorrect and may confuse users. Does it make sense to revert it?

**Comment by bsmth** [comment]
> I spent an hour this morning and found that this does not work(broken?)

I'm sorry you wasted time on this! I've amended the entries in the linked PR with a note linking to https://bugzilla.mozilla.org/show_bug.cgi?id=1846516 ("Support interpolating registered custom properties") which you can track for the fixes and improvements.

**Pull request merged**
