### PR TITLE
Update compatibility of Element.getBoundingClientRect

### PR DESCRIPTION
**Pull request by eunsukimme**
I updated browser compatibility data by adding missed properties(`top`, `left`) of `Element.getBoundingClientRect`

Reference: https://caniuse.com/getboundingclientrect

Related PR: https://github.com/mdn/browser-compat-data/pull/5648

A checklist to help your pull request get merged faster:
- [x] Summarize your changes
- [x] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [x] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [x] Link to related issues or pull requests, if any

### CODE REVIEW

**Review by sideshowbarker — COMMENTED** [review]
I think our current policy is that we always try to add specific browser version numbers rather than `"version_added": true` — unless it’s impossible or completely impractical to determine which browser version numbers to add.

**Comment by ddbeck** [comment]
Hi @eunsukimme and thanks for this PR. I see it's your first here too—welcome to BCD!

I agree with @sideshowbarker here that we'd like to have real version numbers for this. I'm happy to help test, but it would be nice to have a test case to work from.

I think the existing data and the information from caniuse lack material to substantiate it (tests, release notes, bugs, etc.), so we may as well treat what we have as suspect and test things to be sure. Happy to help with this, if needed.

**Comment by ddbeck** [comment]
Hi @eunsukimme, do you plan to return to this PR?

**Comment by eunsukimme** [comment]
Hi @ddbeck , Thank you for let me remind this PR. 
But I have not enough time and devices to test compatibilities and specific versions of browsers. So may be I will be able to make updates on this PR slowly, starting with modern browsers such as Chrome and Safari.

Once this PR is open, I hope someone else can contribute.

**Comment by ddbeck** [comment]
@eunsukimme we have access to testing tools and can help with running the tests. But we do need a simple test case to use, whether that's a link to an existing test or something new you've written. Thank you!

**Comment by ddbeck** [comment]
Thanks for your contribution here, @eunsukimme. I've opened #9061 to improve the data (with a different approach), which will close this PR when it merges. Thank you again!

**Comment by sideshowbarker** [comment]
The status of this seems to be stuck on the following checks:

* Active LTS _Expected — Waiting for status to be reported_
* Maintenance LTS Expected — _Waiting for status to be reported_

**Comment by ddbeck** [comment]
@sideshowbarker I've opened #9061 to supersede this PR. If that's merged, then this PR being stuck won't matter.

**Pull request closed without merging**
