### PR TITLE
Linter for data guidelines scripts

### PR DESCRIPTION
**Pull request by gsouquet**
Hi,

This PR follows up on the issue #4725 . It contains the script that helped migrating the data on #4790.

The CI build will fail and this is expected as we want to highlight the impact these new linting rules 
have. This will hopefully help to have a smooth transition.

It is [step 4 of the migration](https://github.com/mdn/browser-compat-data/blob/master/docs/migrations.md#step-4-wrap-up) process

Thank you

### CODE REVIEW

**Comment by gsouquet** [comment]
@vinyldarkscratch thank you very much for your comments, everything has been updated and should be ready to go.
I've tried to make all those rule fail locally to see the yellow/green and it does work beautifully 💯

**Comment by vinyldarkscratch** [comment]
With the actual/expected lines, I was actually hoping we would keep some indentation (about six spaces), so that it's one level lower than the error message itself.  Can we update that accordingly?

Also, another thought: perhaps we should name the file `test-descriptions.js` instead?  I think it would make more sense that way, since it's testing the descriptions within the data, rather than the guidelines themselves!

**Comment by gsouquet** [comment]
Makes sense, I have just updated the PR with the correct indentation for the logs.

In regards to the name I believe `test-guidelines.js` is appropriate. It follows the data guidelines, it just happens that what we can only automate the description rules. But I could see this project introducing a new guideline that would be unrelatable to the description property and I still believe that it should fall under this `test-guidelines.js` file.

Happy to change it if you feel strongly about it, let me know your thoughts

**Comment by Elchi3** [comment]
Hey, sorry for the slow response! I was traveling and attending a conference.

I think, given this only touches descriptions for now, we could as well rename it to test-descriptions. Note that we're thinking about moving things around anyway in #4688. So, maybe this will be renamed or moved again.

**Comment by gsouquet** [comment]
Thank you for the feedback
@vinyldarkscratch can you give it a last review and I believe it will be good to go 👍

**Comment by vinyldarkscratch** [comment]
Actually, the last review should be done by @Elchi3, or another repository owner.  Since I’m a peer (collaborator), I’m allowed to merge data PRs, not linter/infrastructure PRs.  It looks good to me, though, thanks for all your hard work on this!

**Comment by vinyldarkscratch** [comment]
A little update: there is one thing.  Can we revert the package-lock.json changes, as they're out of scope?  (Not that they're inaccurate, just beyond the scope of this PR!)

**Comment by gsouquet** [comment]
You're right, this is defo out of scope.
Fixed and pushed! Ready to go now.

**Pull request merged**
