### PR TITLE
Split webext jsons

### PR DESCRIPTION
**Pull request by wbamberg**
Splits:

* javascript-apis.json into separate files, one for each API
* manifest-keys.json into separate files, one for each key

I tested this by doing something like:
```
$ git checkout master
$ npm run render webextensions.api 100 > test-api-old.html 
$ git checkout split-webext-jsons
$ npm run render webextensions.api 100 > test-api-new.html 
```
```
$ git checkout master
$ npm run render webextensions.manifest 100 > test-manifest-old.html 
$ git checkout split-webext-jsons
$ npm run render webextensions.manifest 100 > test-manifest-new.html 
```
...then comparing the outputs.

One wrinkle there is that javascript-apis.json did not properly alphabetize apis: `browsingData` was placed before `browserSettings`. So the old and new versions have a different ordering there, that you have to account for.

### CODE REVIEW

**Comment by teoli2003** [comment]
Once landed, we will be able to close issue #21.

**Comment by teoli2003** [comment]
Also a question, once this lands, will we need to change someting in the MDN pages before regenerating or is the macro there already smart enough to deal with this change. (Trying to figure out if we have to fix all the pages in a short time once this goes into production.)

**Comment by Elchi3** [comment]
Data access should be the same, file structure doesn't matter.

**Comment by teoli2003** [comment]
LGTM, r+

Before approving and merging, @elchi3 can you confirm that the division in file is at the right level: 1 file/entry_just_below_api ? (I think it is fine).

[I want to merge this quickly as it will block any other change to webextensions, or it would rot quickly]

**Pull request merged**
