### PR TITLE
Corrected Safari 15.4 support for the FileSystem API

### PR DESCRIPTION
**Pull request by jdatapple**
#### Summary
Fixed Safari/Safari Technology Preview support information for FileSystemHandle, FileSystemWritableFileStream and StorageManager.

#### Test results and supporting details
See [Safari 15.4 Beta Release Notes](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes)

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
The commit message is "Added Safari 15.4 support for the FileSystem API" but then you change the values to `false`. So, did you mean to say that Safari no longer supports the FileSystem API or is the change to `false` wrong?

**Comment by gsnedders** [comment]
The commit message seems to be wrong.

Looking at https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/filesystemaccess/FileSystemHandle.idl and its history makes it look like there never was support for those in api/FileSystemHandle.json.

I don't see any evidence for FileSystemWritableFileStream ever being supported.

https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/storage/StorageManager.idl has estimate commented out.

So this commit seems accurate aside from the commit message.

**Comment by jdatapple** [comment]
I've corrected the commit message.

**Review by Elchi3 — APPROVED** [review]
Thanks for the clarification! 👍

**Pull request merged**
