### PR TITLE
Firefox 59 allows browserAction set* methods to accept null

### PR DESCRIPTION
**Pull request by Loirooriol**
See [Bug 1419940](https://bugzilla.mozilla.org/show_bug.cgi?id=1419940).

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for this, and sorry to be slow reviewing.

I think this is good, but it needs a [`description`](https://github.com/mdn/browser-compat-data/blob/master/compat-data-schema.md#the-__compat-object) field: just `null` as a subfeature doesn't explain properly what the thing is.

The `description` could be something like (for example, for `setTitle()`:

"The \<code\>title\</code\> property of the \<code\>details\</code\> parameter can be set to \<code\>null\</code\>."

**Comment by Loirooriol** [comment]
Done! You can squash the commits into a single one, right?

**Comment by Loirooriol** [comment]
Will MDN be updated automatically or should I do something?

**Comment by wbamberg** [comment]
> Will MDN be updated automatically or should I do something?

Short answer: you don't have to do anything.

Long answer: after you update compat data, several things need to happen before the pages display the new data:

1. the MDN team needs to make a new release of the npm package containing the data
2. the MDN team needs to make a new production deployment that contains the new npm package
3. someone needs to shift-refresh the page while logged into MDN, so the macros that build the table are regenerated.

(1) and (2) happen each week, usually Monday. So your change was actually deployed already. I just did (3), so the tables are now updated.

In 2018 we're planning to make this process simpler and faster.

**Pull request merged**
