### PR TITLE
Updates for Firefox 128 beta

### PR DESCRIPTION
**Pull request by Elchi3**
The @openwebdocs [BCD collector project](https://github.com/openwebdocs/mdn-bcd-collector) v10.10.7 found new features shipping in Firefox 128 beta which was released yesterday. Currently, the collector covers about 90% of BCD, so the following list might not be exhaustive. Also, if a feature is in Firefox Nightly only, it is not considered here.

With this PR, BCD considers the following 37 features as shipping in Firefox 128:

- api.Blob.bytes
- api.CSS.registerProperty_static
- api.CSSPropertyRule
- api.CSSPropertyRule.inherits
- api.CSSPropertyRule.initialValue
- api.CSSPropertyRule.name
- api.CSSPropertyRule.syntax
- api.Element.getHTML
- api.HTMLMediaElement.seekToNextFrame (removal)
- api.HTMLTemplateElement.shadowRootSerializable
- api.MediaKeys.getStatusForPolicy
- api.PushMessageData.bytes
- api.RTCRtpReceiver.getParameters
- api.RTCRtpReceiver.getParameters.return_object_property_codecs
- api.RTCRtpSender.getParameters.return_object_property_codecs
- api.RTCRtpSender.setParameters.parameters_codecs_parameter
- api.RTCRtpTransceiver.setCodecPreferences
- api.Request.bytes
- api.Response.bytes
- api.ShadowRoot.getHTML
- api.ShadowRoot.serializable
- css.at-rules.property
- css.at-rules.property.inherits
- css.at-rules.property.initial-value
- css.at-rules.property.syntax
- css.properties.content.alt_text
- css.types.calc.color_component
- javascript.builtins.ArrayBuffer.ArrayBuffer.maxByteLength_option
- javascript.builtins.ArrayBuffer.maxByteLength
- javascript.builtins.ArrayBuffer.resizable
- javascript.builtins.ArrayBuffer.resize
- javascript.builtins.SharedArrayBuffer.SharedArrayBuffer.maxByteLength_option
- javascript.builtins.SharedArrayBuffer.grow
- javascript.builtins.SharedArrayBuffer.growable
- javascript.builtins.SharedArrayBuffer.maxByteLength
- webextensions.api.declarativeNetRequest.getDisabledRuleIds
- webextensions.api.declarativeNetRequest.updateStaticRules

See also https://github.com/mdn/mdn/issues/553 and https://www.mozilla.org/en-US/firefox/128.0beta/releasenotes/

### CODE REVIEW

**Comment by hamishwillee** [comment]
FWIW:
- all the `javascript.builtins.xxx` changes are good. Docs work for that in https://github.com/mdn/content/issues/33983

**Review by hamishwillee — APPROVED** [review]
This all looks sane. Thanks very much @Elchi3

**Comment by Elchi3** [comment]
Thanks Hamish! 🎉

**Comment by Elchi3** [comment]
> Dont know about these:
> 
> ```
> css.at-rules.property
> css.at-rules.property.inherits
> css.at-rules.property.initial-value
> css.at-rules.property.syntax
> ```

This is part of https://github.com/mdn/content/issues/33993

**Pull request merged**
