### PR TITLE
Remove progress event from GlobalEventHandlers

### PR DESCRIPTION
**Pull request by queengooborg**
This PR demixes the `progress` event from the GlobalEventHandlers mixin.

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@queengooborg can you resolve conflicts?

**Comment by foolip** [comment]
@queengooborg sorry, I wasn't paying attention to labels on my phone. Are you keeping track of what was already merged and needs content changes?

**Comment by queengooborg** [comment]
No worries!  Basically what I've been doing is awaiting approval of the BCD PRs, and then once I know that we've got the story mapped out in BCD, I'm heading over to `mdn/content` to open a PR containing similar changes.  That way, everything is kept in sync as much as possible!

**Comment by queengooborg** [comment]
And I'm now realizing that there are some events that don't actually need any updates since there are no GlobalEventHandlers pages for the particular events -- I'm going through now to find them and remove the label, and apparently this is one of them!

**Review by foolip — APPROVED** [review]

**Pull request merged**
