### PR TITLE
Add Safari support for javascript.functions.method_definitions

### PR DESCRIPTION
**Pull request by julienetie**
A checklist to help your pull request get merged faster:
- [ ] Summarize your changes
- [ ] Data: link to resources that verify support information (such as browser's docs, changelogs, source control, bug trackers, and tests)
- [ ] Data: if you tested something, describe how you tested with details like browser and version
- [ ] Review the results of the linter and fix problems reported (If you need help, please ask in a comment!)
- [ ] Link to related issues or pull requests, if any

### CODE REVIEW

**Comment by ddbeck** [comment]
Hi @julienetie and welcome to BCD!

Do you have any background for this change, such as a link to release notes or a test? Before we can merge this, we'll need to substantiate the change and that Safari 9.1 was the first version to have this feature.

**Comment by vinyldarkscratch** [comment]
I used the test from the MDN docs in SauceLabs.  I got a success in Safari 9.1, but not in 8.  (I'm not able to test it in Safari 9.0.)  Will have to check against 9.0 vs. 9.1!

**Comment by ddbeck** [comment]
Hi @julienetie, do you plan to revisit this PR soon?

**Comment by ddbeck** [comment]
We've added this data in another PR. Thanks for your help on this, @julienetie!

**Pull request closed without merging**
