### PR TITLE
Remove redundant testing on test/*

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
I noticed that while running the linter, a "Browsers - Unknown category" kept on showing up, and I was wondering why, so I looked it up and found out that it was regarding the `test/` folder.  This seemed like a redundant, and possibly misleading (since it looks like it's related to the above file), message.  This PR intends to disable the message by silently ignoring the `test/` category from double-checking the browsers.

### CODE REVIEW

**Comment by ddbeck** [comment]
> I noticed that while running the linter, a "Browsers - Unknown category" kept on showing up

@vinyldarkscratch could you link to a Travis CI build or a gist with your logs demonstrating this? It'd help to have an illustration of the problem (I don't recall noticing this myself)

**Comment by vinyldarkscratch** [comment]
Just grabbed a random log from another PR: https://travis-ci.org/mdn/browser-compat-data/builds/522266021#L2413

**Comment by ddbeck** [comment]
I fell down a rabbit hole trying to figure out why the code was written the way it was in the first place, to see if we could avoid this odd special case. And it looks like the only reason [we load the `test` directory](https://github.com/mdn/browser-compat-data/blob/master/test/lint.js#L105) is to test the seemingly-pointless [`sample-data.json`](https://github.com/mdn/browser-compat-data/blob/master/test/sample-data.json).

Maybe the right thing to do here is to stop loading `test`, delete `sample-data.json` (which seems to serve no particular purpose in light of our JSON schema) and rewrite this part of the check as:

```js
  if (!category) {  // from (!category || category === "test")
    console.warn('\x1b[1;30m  Browsers – Unknown category \x1b[0m');
    return false;
  }
```

**Comment by vinyldarkscratch** [comment]
That sounds like a plan to me!  Let me make the appropriate changes, in that case.  :wink:

**Comment by vinyldarkscratch** [comment]
Done!

**Pull request merged**
