### PR TITLE
WebXR API files, part II.

### PR DESCRIPTION
**Pull request by jpmedley**
These match what's in the current editor's draft spec. The spec author expects few changes between now and the shipping of WebXR in the fall. I'd link to Chromium code, but it hasn't caught up.

https://immersive-web.github.io/webxr

### CODE REVIEW

**Comment by jpmedley** [comment]
@a2sheppy I'm catching up to you. Any chance you can get to these soon?

**Comment by jpmedley** [comment]
@a2sheppy Pinging you again. These will very shortly be blocking me.

**Comment by a2sheppy** [comment]
I am working on these now and hope to start having feedback and/or OKs tomorrow morning.

**Comment by vinyldarkscratch** [comment]
Merging as per @a2sheppy's r+, thanks for your hard work, you two!

**Pull request merged**
