### PR TITLE
Enforce alphabetical order of browsers in the `support` block

### LINKED ISSUE #398: lint.js should check browser order
It came up recently (e.g., on #387) that we ought to use a consistent order for browsers, for each features. So, for example, `chrome` should precede `chrome_android` in a support array. Rather than have PR reviewers check these by hand, `lint.js` should check the order and warn if it's inconsistent.

### PR DESCRIPTION
**Pull request by ExE-Boss**
Depends on #2889
Fixes #398
Closes #1474; Closes #2890

### CODE REVIEW

**Comment by ExE-Boss** [comment]
@Elchi3 If you’re gonna merge this, you should do it now when I just rebased this to master (before all the merge conflicts pile up again)

**Comment by Elchi3** [comment]
Thanks for working on this!
I don't think it's useful to merge this at this point as it will add rebasing work and additional fixing work to all currently opened PRs. I would rather like to spend my time on getting the PR backlog down now and merge this later. This change can be done programmatically at any time, lets rebase it again (or re-run an alphabetization script again) when we're ready to merge.

**Comment by connorshea** [comment]
@ExE-Boss @Elchi3 how about now? :D

**Comment by ExE-Boss** [comment]
Yes, I still have the script I used for this.

**Comment by Elchi3** [comment]
Yes, we can do this soon. There are other PRs that affect many files, though. Trying to get in https://github.com/mdn/browser-compat-data/pull/1356 for example, so maybe wait a bit before rebasing.

**Comment by connorshea** [comment]
577 files left to go! :D

**Comment by Elchi3** [comment]
The backlog is relatively small now. I would review a PR that sorts `api/*`. Anyone interested? @ExE-Boss @vinyldarkscratch @connorshea ?

**Comment by vinyldarkscratch** [comment]
@Elchi3 Ask and ye shall receive.  :wink:

**Comment by Elchi3** [comment]
This needs to be rebased now and then we might be able to finally enforce this :) 
Thanks to everyone involved so far! :+1:

**Comment by connorshea** [comment]
😱🥳

**Comment by Elchi3** [comment]
Sorry, I didn't see that you pushed a merge here. Latest master has two new issues now unfortunately:

```
Problems in 2 files:
api/Element.json
  File : api/Element.json
  Style – Error on line #2125
    Actual:               "webview_android": {
    Expected:             "chrome": {
css/properties/justify-content.json
  File : css/properties/justify-content.json
  Style – Error on line #545
    Actual:                 "opera": {
    Expected:               "ie": {
```

Seeing these messages, I wonder if we should have a better error message. Especially to new contributors it might not be obvious what we want here.

**Comment by Elchi3** [comment]
I've resolved the conflict here and added a (naive) special case to see how this could look like. It now outputs this against master for me:

```
Problems in 3 files:
api/Element.json
  File : api/Element.json
  Browser name sorting – Error on line #2128
    Actual:               "webview_android": {
    Expected:             "chrome": {
css/properties/justify-content.json
  File : css/properties/justify-content.json
  Browser name sorting – Error on line #545
    Actual:                 "opera": {
    Expected:               "ie": {
test/sample-data.json
  File : test/sample-data.json
  Browser name sorting – Error on line #8
    Actual:               "webview_android": {
    Expected:             "chrome": {
```

I think this looks like a better error message. What do you think about this, @ExE-Boss? Do you want to rebase and land this then?

**Comment by ExE-Boss** [comment]
Let’s finally land this.

**Pull request merged**
