### PR TITLE
Include render-blocking status browser compat data

### PR DESCRIPTION
**Pull request by abinpaul1**
#### Summary

`renderBlockingStatus` in PerfomanceResourceTiming to indicate the render-blocking nature of a resource. The attribute takes away the burden of having to rely on complex heurestics to determine which resources were actually render-blocking and provides a direct signal from the browser.

#### Related issues

https://github.com/mdn/content/pull/19325

### CODE REVIEW

**Review by bsmth — APPROVED** [review]
Thanks 👍🏻

**Comment by bsmth** [comment]
Hi @abinpaul1 is this correct for Edge and Opera? I think it's only in Chrome 107, right:

See: 
https://pr19325.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/PerformanceResourceTiming/renderBlockingStatus

---

image

**Comment by abinpaul1** [comment]
Hey @bsmth , apologies for delay in responding. I think its accurate, because all three of them share the same rendering engine Blink and the feature is available from blink 107 onwards. I have confirmed the field is present in Opera 93 and Edge 107.

**Comment by bsmth** [comment]
> I have confirmed the field is present in Opera 93 and Edge 107

OK very good, tnx

**Pull request merged**
