### PR TITLE
Remove onvisibilitychange notes from webkitvisibilitychange

### PR DESCRIPTION
**Pull request by foolip**
The prefixed event shouldn't be assoicated with the unprefixed event
handler property.

### CODE REVIEW

**Comment by queengooborg** [comment]
Are we sure that the notes are irrelevant though?  Based upon the delay in a lack of support for the event handler property, shouldn't the notes be changed to reference the prefixed event handler?

**Review by lucalves — APPROVED** [review]

**Comment by foolip** [comment]
> Are we sure that the notes are irrelevant though? Based upon the delay in a lack of support for the event handler property, shouldn't the notes be changed to reference the prefixed event handler?

My perspective is that with non-standard APIs, we can't say that something is partially implemented because there's nothing to compare it to. We could have a note, but not `partial_implementation`. Would that work?

**Comment by queengooborg** [comment]
This isn't non-standard though, it's just prefixed.  But even if it was non-standard, we should still retain a `partial_implementation` statement per our [guidelines](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/api.md#dom-events-eventname_event), as part of the feature (the event handler) is known to be unsupported.

**Comment by foolip** [comment]
At the time it was implemented it might have been non-standard, but I guess that doesn't matter now. OK, so I'll have to research whether the event handler properties were supported or not.

**Pull request closed without merging**
